(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Freeer160x600.jpg?1504143936360", id:"Freeer160x600"},
		{src:"images/HTML5rastershad.png?1504143936360", id:"HTML5rastershad"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.Freeer160x600 = function() {
	this.initialize(img.Freeer160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,267,177);


(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuastackai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdAlIADgFQACABAFABQAGAAADgJIgVgsIAHAAIARAkIAOgkIAHAAIgSAuQgFANgKAAQgFAAgFgDgAFDAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAFIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAEOATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAEsAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAC0AVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAB/ATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgAh8AXQgGgFAAgHQAAgHAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAEABAKIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAh7ALQABAJALAAQAHABAFgEQAEgDAAgGIAAgFQgHgCgGAAQgOAAgBAKgAjRATQgHgGAAgLQAAgIAGgIQAHgGAJAAQAKAAAGAGQAGAIAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEADQgIAJgLAAQgKAAgGgHgAizAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAkNAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAkIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAlCATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIAAADIglAAQACAPAOAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAkkAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgADnAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgABtAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAA1AZIAAgsIAHAAIAAAsgAgyAZIAAg/IAIAAIAAA/gAhJAZIAAg/IAHAAIAAA/gAigAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIAAAAQgIAAgGAFQgFAGAAAJIAAASgAlkAZIAAgnIgGAAIAAgFIAGAAIAAgFQAAgHAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAFIgPAAIAAAngAA0gdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhwAlIACgFIAHACQAGAAAEgJIgVgsIAHAAIARAkIAPgkIAIAAIgUAtQgFANgKAAQgGAAgEgCgACFAXQgGgFAAgHQAAgNAUAAQAGAAAIACIAAgBQAAgNgNAAQgHAAgIAEIgCgGQAJgEAIAAQALAAAEAFQAFAEAAAKIAAAaIgHAAIAAgHQgFAIgLAAQgHAAgFgDgACGALQAAAJAMAAQAHABAEgEQAEgDAAgGIAAgFQgGgCgHAAQgOAAAAAKgABPAVQgEgFAAgIIAAgbIAHAAIAAAZQAAAOAMAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgFAJgLAAQgIAAgFgFgAAcATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgHgHgHAAQgHABgFAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAHgHIAEAEQgIAJgLAAQgKAAgHgHgAigAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAJgBAGAHQAHAHAAAIIAAABQAAALgHAGQgGAHgJAAQgMAAgGgKgAibgJQgGAFAAAFIAAABQAAAHAGAGQAFAFAGAAQAHAAAFgFQAFgFAAgIQAAgGgFgFQgFgFgHAAQgGAAgFAFgAACAZIAAgZQAAgOgLAAQgGAAgEAEQgEAEAAAGIAAAZIgGAAIAAgsIAGAAIAAAIQAHgJAJAAQAHAAAFAEQAEAFAAAJIAAAbg");
	this.shape_1.setTransform(0,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.3,0,72.7,18.9);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape.setTransform(30.9,146.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgHgHgFgKIgDgKIAAgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIADALQADAKAAAJIAAAHIhLAAQAAAGADAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgFACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_1.setTransform(22.2,142.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_2.setTransform(12.5,142.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgGgFgDgGQgCgFAAgIIAAgBQAAgJACgGQAEgGAFgDQAGgEAIgCQAIgCAJAAQALgBARAFIAAgCQAAgGgCgDQgCgFgDgDQgEgDgEgBQgFgCgEAAQgJAAgIACQgGABgIAEIgGgUIASgGQAKgCAKAAQAMAAAIADQAJADAGAFQAGAGACAJQADAIAAAKIAAA9IgXAAIAAgNQgGAHgJAEQgKAEgIAAQgHAAgHgCgAgIAFIgIADIgFAFQgCADAAAEIAAAAQABAIAFAEQAGAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgEAAgFIAAgGQgPgFgJABIgIABg");
	this.shape_3.setTransform(1.8,142.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgDgEQgEgEgEgCQgGgCgFAAQgDAAgGACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_4.setTransform(-15.8,142.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAXA1IgXhHIgXBHIgVAAIgihpIAYAAIAWBHIAXhHIATAAIAXBHIAWhHIAYAAIgjBpg");
	this.shape_5.setTransform(-30.4,142.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgPASQAJgCAEgFQADgFgBgGIgIAAIAAgbIAYAAIAAAYQAAAGgCAGQgCAGgEAEQgDAEgFACQgFACgHABg");
	this.shape_6.setTransform(18.1,128.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgCgGgBgIIAAg2IgMAAIAAgVIAMAAIAAgdIAXAAIAAAdIAcAAIAAAVIgcAAIAAAyQAAAHADADQADADAHAAQAHAAAIgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_7.setTransform(11.6,121.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgKBIIAAhoIAWAAIAABogAgLgwIAAgXIAYAAIAAAXg");
	this.shape_8.setTransform(4.7,120.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgFgFgDgFQgDgHgBgIIAAAAQABgIADgHQADgGAGgDQAFgEAIgCQAIgCAJgBQALAAAQAFIAAgCQAAgFgBgEQgCgFgDgDQgEgDgEgBQgFgBgEgBQgJABgHABQgHABgIAEIgHgTIASgHQALgCAKAAQAMAAAIADQAJADAGAFQAGAHADAIQACAIAAALIAAA8IgYAAIAAgNQgGAHgHAEQgLAEgIAAQgHAAgHgCgAgIAEIgIAEIgFAFQgBADgBAEIAAAAQAAAIAHAEQAFAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgEAAgFIAAgGQgPgFgJAAIgIABg");
	this.shape_9.setTransform(-4.2,122.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAiBGIgihiIghBiIgVAAIgxiLIAbAAIAhBmIAjhmIASAAIAjBmIAhhmIAaAAIgxCLg");
	this.shape_10.setTransform(-19,121);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape_11.setTransform(15.9,96.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgYAzQgIgDgEgGQgFgFgCgHQgDgIAAgJIAAhBIAYAAIAAA6QAAAGABAFQACAEADAEQADADAEACQAEABAFAAQAEAAAFgBQAEgCADgEQADgDACgFQABgFAAgGIAAg5IAZAAIAABnIgZAAIAAgQQgFAIgHAFQgEADgFABQgDABgGAAQgJAAgHgCg");
	this.shape_12.setTransform(7,92.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAFQAFAEAGADQAGADAFAAQAHAAAGgDQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_13.setTransform(-5.7,92.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgjBDQgFgCgGgDIAIgSQAIAEAGAAQAGAAADgDQAEgDACgGIgshnIAaAAIAcBMIAchMIAZAAIgqBqQgDAIgEAFQgDAHgCADQgEADgGACQgEABgHABQgHgBgHgBg");
	this.shape_14.setTransform(-18.2,94.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgaBCQgMgDgKgGIAJgSQAJAFAIADQAKADAKAAQAGAAAHgCQAGgCAEgEQAFgEACgGQACgGAAgIIAAgJQgJALgHADQgEADgGABQgEACgFAAQgKAAgIgDQgJgEgHgGQgGgHgEgJQgEgHAAgMQAAgIAEgNQAEgJAGgGQAIgHAIgDQAIgEAKAAQAFAAAFACIAKAEQAIAEAHAIIAAgPIAYAAIAABSQAAANgEAKQgDAKgHAGQgDAEgFADIgKAEQgPAEgIAAQgNAAgMgEgAgLguQgFACgEAEQgEAEgCAFQgDAGAAAGIAAAAQAAAHADAFQACAFAEACQAEAEAFACQAGACAFAAQAGAAAFgCQAFgCAFgEQAFgCACgFQACgFAAgHQAAgGgCgGQgCgFgFgEIgKgGQgFgCgGAAQgFAAgGACg");
	this.shape_15.setTransform(38.5,74.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAXA2IAAg6QAAgGgCgFQgBgFgDgDQgDgEgEgCQgEgCgGAAQgDAAgEACQgFACgDAEQgDADgCAFQgBAFgBAGIAAA6IgYAAIAAhoIAYAAIAAARQAGgJAIgFQADgDAFAAQADgCAHAAQAJAAAHADQAGACAFAGQAFAFADAHQACAIAAAJIAABCg");
	this.shape_16.setTransform(25.9,72.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgLBIIAAhoIAXAAIAABogAgMgwIAAgXIAYAAIAAAXg");
	this.shape_17.setTransform(16.8,70.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgjBDQgFgBgGgEIAIgSQAIAEAGAAQAGAAADgDQAEgDACgGIgshoIAaAAIAcBNIAchNIAZAAIgqBrQgDAIgEAGQgDAFgCAEQgEAEgGABQgEABgHABQgHgBgHgBg");
	this.shape_18.setTransform(8,74.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgGgEgDgHQgCgGAAgHIAAgBQAAgIACgHQAEgGAFgDQAGgEAIgDQAIgBAJAAQALAAARAEIAAgCQAAgGgCgEQgCgEgDgDQgEgDgFgBQgEgBgEAAQgJAAgIABQgGABgIAEIgGgUIASgGQAKgCAKAAQAMAAAIADQAJACAGAHQAGAGACAHQADAJAAAKIAAA9IgXAAIAAgNQgHAHgIAEQgKAEgIAAQgIAAgGgCgAgIAFIgIADIgFAFQgCADAAAEIAAABQABAGAFAFQAGAEAJAAQAEAAAFgCQAFgBAEgDQAEgDACgEQACgEAAgFIAAgGQgPgFgJABIgIABg");
	this.shape_19.setTransform(-4,72.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag1BFIAAiHIAYAAIAAASQAHgJAIgGQAEgDAFAAQAFgCAFAAQAJAAAJADQAJAEAHAHQAHAHAEAKQAEAPAAAJIAAAAIgBAMIgDAJQgEAKgHAHQgHAIgJADQgIADgKABQgFgBgFgBQgFgBgFgDQgIgFgGgIIAAAwgAgKgtQgGACgEAFQgFAFgCAFQgCAHAAAIIAAAAQAAAHACAGQACAFAFAFQAEAEAGACQAFACAFABQAGgBAFgCQAGgCAEgEQAEgFACgFQADgGAAgHIAAAAQAAgIgDgHQgCgFgEgFQgFgFgFgCQgGgCgFgBQgFABgFACg");
	this.shape_20.setTransform(-16.1,74.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgDgKIAAgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgGACQgEACgDAEIgGAJQgDAFAAAGIA0AAIAAAAg");
	this.shape_21.setTransform(-35,72.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgFBIQgFgBgFgDQgIgFgGgIIAAARIgYAAIAAiRIAYAAIAAA7QAHgJAIgGQAEgDAFAAQAFgCAFAAQAJAAAJADQAJAEAHAHQAHAHAEAKQAEANAAAJIAAAAIgBAMIgDALQgEAKgHAHQgHAIgJADQgIADgKABQgFgBgFgBgAgKgLQgGACgEAFQgFAEgCAEQgCAHAAAIIAAAAQAAAHACAHQACAGAFAFQAEAEAGACQAFACAFABQAGgBAFgCQAGgCAEgEQAEgFACgGQADgHAAgHIAAAAQAAgIgDgHQgCgEgEgEQgFgFgFgCQgGgCgFgBQgFABgFACg");
	this.shape_22.setTransform(-47.5,70.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXBGQgIgDgHgIQgHgHgEgKIgDgKIgBgNIAAAAQAAgJAEgNQAEgJAHgIQAHgHAIgDQAJgEAKgBQAEABAGACQAFABAFACQAHAFAHAJIAAg6IAYAAIAACQIgYAAIAAgRQgHAJgHAFIgKAEQgGACgEAAQgKAAgJgEgAgKgLQgFADgFAEQgEAEgCAEQgDAHAAAIIAAAAQAAAIADAGQACAGAFAEQAEAFAFACQAGACAEAAQAFAAAGgCQAFgCAFgFQAEgEACgHQADgFAAgIIAAAAQAAgIgDgHQgCgEgEgEQgFgEgFgDQgGgDgFABQgEgBgGADg");
	this.shape_23.setTransform(34.3,50.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgPASQAJgCAFgFQABgFAAgGIgJAAIAAgbIAZAAIAAAYQAAAGgBAGQgCAGgFAEQgDAEgFACQgFACgHABg");
	this.shape_24.setTransform(25,46.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgIgHgEgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIAEALQACAKABAJIgBAHIhMAAQABAGADAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgEgCQgGgCgFAAQgEAAgFACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_25.setTransform(16.5,52.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAXA1IgXhHIgXBHIgVAAIgihpIAYAAIAWBHIAXhHIATAAIAXBHIAWhHIAYAAIgjBpg");
	this.shape_26.setTransform(1.9,52.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgXBGQgIgDgHgIQgHgHgEgKIgDgKIgBgNIAAAAQAAgJAEgNQAEgJAHgIQAHgHAIgDQAJgEAKgBQAEABAGACQAFABAFACQAHAFAHAJIAAg6IAYAAIAACQIgYAAIAAgRQgHAJgHAFIgKAEQgGACgEAAQgKAAgJgEgAgKgLQgFADgFAEQgEAEgDAEQgCAHAAAIIAAAAQAAAIACAGQADAGAFAEQAEAFAFACQAGACAEAAQAFAAAGgCQAFgCAFgFQAEgEACgHQADgFAAgIIAAAAQAAgIgDgHQgCgEgEgEQgFgEgFgDQgGgDgFABQgEgBgGADg");
	this.shape_27.setTransform(-19.7,50.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAXA1IAAg5QAAgHgBgEQgCgFgDgDQgDgEgEgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFQgBAFAAAGIAAA5IgZAAIAAhnIAZAAIAAARQAFgKAHgEQAFgCAEgBQADgCAGgBQAJABAHADQAHADAFAFQAFAFACAHQADAIAAAJIAABBg");
	this.shape_28.setTransform(-32.3,52.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgFgFgDgGQgDgFAAgIIAAgBQAAgJADgGQADgGAGgDQAFgEAIgCQAIgCAJAAQALgBARAFIAAgCQAAgGgCgDQgCgFgDgDQgEgDgEgBQgFgCgEAAQgJAAgHACQgHABgIAEIgGgUIASgGQAKgCAKAAQALAAAJADQAJADAGAFQAGAHADAIQACAIAAAKIAAA9IgXAAIAAgNQgGAHgJAEQgKAEgIAAQgHAAgHgCgAgIAFIgIADIgFAFQgBADgBAEIAAAAQAAAIAHAEQAFAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgEAAgFIAAgGQgPgFgJABIgIABg");
	this.shape_29.setTransform(-44.6,52.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_30.setTransform(26,32.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgIgHgDgKIgDgKIgCgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACQgEACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_31.setTransform(15.4,32.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgcALIAAgVIA5AAIAAAVg");
	this.shape_32.setTransform(5.3,31.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgHgHgFgKIgDgKIgBgMIAAAAQABgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhLAAQAAAGADAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgFACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_33.setTransform(-4.8,32.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgEgKIgEgKIgBgMIAAAAQABgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIADALQADAKAAAJIAAAHIhLAAQAAAGADAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgFgCQgEgCgGAAQgDAAgFACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_34.setTransform(-16.8,32.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAXQACgGADgEQADgFAEgEQAFgDAFgCQAGgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_35.setTransform(-26.5,32.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgSBJIAAhTIgNAAIAAgUIANAAIAAgIQAAgIADgHQACgGAEgFQAEgEAFgCQAFgCAIAAQAKAAAJADIAAAUQgHgCgHAAQgHgBgDAEQgEAFAAAHIAAAGIAcAAIAAAUIgbAAIAABTg");
	this.shape_36.setTransform(-34.7,30.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgjBDQgFgCgGgDIAIgSQAIAEAGAAQAGAAADgCQAEgEACgGIgshnIAaAAIAcBMIAchMIAZAAIgqBqQgDAIgEAFQgDAHgCADQgEADgGACQgEACgHgBQgHABgHgCg");
	this.shape_37.setTransform(9.6,14.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAXA2IAAg7QAAgGgBgFQgCgEgDgEQgDgDgEgBQgEgCgGgBQgDABgFACQgEACgDACQgDAEgCAFQgBAFAAAGIAAA6IgZAAIAAhoIAZAAIAAAQQAFgJAHgDQAEgEAFgBQADgBAGgBQAKAAAGADQAHAEAFAFQAFAFACAIQADAHAAAKIAABBg");
	this.shape_38.setTransform(-2.5,12.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAuBGIgNgiIhBAAIgOAiIgZAAIA9iLIAVAAIA9CLgAAYAOIgYg2IgXA2IAvAAg");
	this.shape_39.setTransform(-16.6,11);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59,0,109,154);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("EgMfAsOMAAAhYbIY/AAMAAABYbg");
	this.shape.setTransform(80,262,1,0.926);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgQArQgNgGgFgEIAJgOQAHAFAIADQAHADAFAAQAHAAAEgDQADgDAAgEQAAgFgGgDIgMgFQgNgEgGgDQgEgCgCgEQgDgFAAgGIAAAAQAAgHADgFQACgFAFgEQAEgDAGgCQAGgCAEAAQAJAAAIADQAJADAHAFIgIAOQgHgEgGgCQgHgDgFAAQgEAAgEADQgDACAAAEIAAABQAAAEAGADIAMAGIAKADIAJADQAFADACAFQACAEAAAGIAAAAQAAAHgCAFQgDAFgEAEQgFAEgGACQgGABgHAAQgIAAgKgDg");
	this.shape.setTransform(22.1,78.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgUArQgGgDgEgEQgFgFgCgGQgCgHAAgHIAAg3IAVAAIAAAwQAAAGABAEQABAEADADIAGAEQADABAEAAQADAAAEgBIAGgEQADgDACgEQABgFAAgFIAAgwIAVAAIAABXIgVAAIAAgOQgFAIgGADQgDADgEABQgDABgFAAQgHAAgGgCg");
	this.shape_1.setTransform(12.7,78.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_2.setTransform(2.3,78);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgJAtIgJgCQgIgEgHgGQgGgHgEgIIgCgJIgBgJQAAgFADgMQAEgIAGgHQAHgGAJgEIAJgCIAIgBQAHAAAMADQAIAEAHAGQAGAHAEAIQADAMAAAFIAAAAIAAAJIgDAJQgEAIgGAGQgHAHgIAEQgNADgGAAgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQAFACAEAAQAGAAAFgCQAFgCAEgEQADgEACgFQACgFAAgGQAAgEgCgGQgCgFgEgEQgEgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_3.setTransform(-8.6,78.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AgwA7IAAh1IAzAAQALAAAHACQAIAEAFAEQAFAFACAEQABAGAAAFIgBAKIgEAHQgEAGgIAEIAKADQAEACADAEQADADACAEQACAFAAAGIAAABQAAAHgEAGQgDAHgFADQgGAFgIACQgIACgKAAgAgcAoIAhAAIAJgBIAIgCQADgCABgEQACgDAAgEQAAgEgCgDQgBgDgDgCQgDgCgFgBIgKgBIggAAgAgcgIIAcAAIAIgBQAEgBADgCQADgCACgDQACgDAAgEIAAAAQgBgEgBgDIgEgEQgDgDgEgBIgJgBIgcAAg");
	this.shape_4.setTransform(-19.9,76.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AAAA4QgFgBgDgDQgEgEgCgEQgCgGAAgHIAAgtIgKAAIAAgSIAKAAIAAgZIATAAIAAAZIAYAAIAAASIgYAAIAAAqQAAAGADACQADADAGAAQAGAAAGgDIAAARIgJADIgKABQgFAAgDgBg");
	this.shape_5.setTransform(32.4,58);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_6.setTransform(23.8,59);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AgUArQgGgDgEgEQgFgFgCgGQgCgHAAgHIAAg3IAVAAIAAAwQAAAGABAEQABAEADADIAGAEQADABAEAAQADAAAEgBIAGgEQADgDACgEQABgFAAgFIAAgwIAVAAIAABXIgVAAIAAgOQgFAIgGADQgDADgEABQgDABgFAAQgHAAgGgCg");
	this.shape_7.setTransform(13.2,59.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgJAtIgJgCQgIgEgHgGQgGgHgEgIIgCgJIgBgJQAAgFADgMQAEgIAGgHQAHgGAJgEIAJgCIAIgBQAHAAAMADQAIAEAHAGQAGAHAEAIQADAMAAAFIAAAAIAAAJIgDAJQgEAIgGAGQgHAHgIAEQgNADgGAAgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQAFACAEAAQAGAAAFgCQAFgCAEgEQADgEACgFQACgFAAgGQAAgEgCgGQgCgFgEgEQgEgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_8.setTransform(2.4,59.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgDAtIgJgCQgIgEgHgGQgGgHgEgIQgDgJAAgJQAAgIADgJQAEgIAGgGQAHgHAIgEIAJgCIAIgBIALABIAKADQAFADAKAIIgOAOQgEgGgGgCQgGgDgGAAQgFAAgEACQgFACgDAEQgEAEgCAFQgBAFAAAFIAAAAQAAAFABAGQACAFAEAEQADAEAGACQADACAGAAQAGAAAGgDQAGgCAEgGIANAMQgJAKgGADIgKADIgLABg");
	this.shape_9.setTransform(-7.9,59.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgDAtIgJgCQgJgEgGgGQgGgHgEgIQgDgJAAgJQAAgIADgJQAEgIAGgGQAGgHAJgEIAJgCIAHgBIAMABIAKADQAFADAJAIIgMAOQgGgGgFgCQgFgDgIAAQgEAAgEACQgEACgEAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQADACAFAAQAIAAAGgDQAEgCAGgGIAMAMQgJAKgGADIgKADIgMABg");
	this.shape_10.setTransform(-17.6,59.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AAnA8IgMgdIg1AAIgNAdIgWAAIA1h3IARAAIA1B3gAAUAMIgUguIgTAuIAnAAg");
	this.shape_11.setTransform(-29.2,57.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AATAtIgTg7IgTA7IgSAAIgdhYIAVAAIASA7IAUg8IAPAAIAUA8IATg7IAUAAIgdBYg");
	this.shape_12.setTransform(35.5,40.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgOArQgJgDgFgHQgHgGgDgIIgDgJIgBgKIAAAAQAAgIADgJQADgIAHgHQAFgGAIgEIAIgCIAIgBIAKABIAIADQAGACAIAIQAGAHACAIQADAJAAAIIAAAGIhAAAIADAJQACAFAEADIAHAEQAEABADAAQAHAAAHgCQAFgDAFgFIANAKIgHAHQgEAEgEACIgKADIgMABQgHAAgJgDgAAXgFQgBgFgCgEQgBgFgDgDIgHgFQgFgCgEAAQgDAAgEACQgEACgDADIgFAHQgCAFAAAFIAsAAIAAAAg");
	this.shape_13.setTransform(23.1,40.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AAiA7IhAhSIAABSIgUAAIAAh1IATAAIA+BRIAAhRIAUAAIAAB1g");
	this.shape_14.setTransform(11.2,38.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgKA8IgKgDIgIgHQgFgDgDgEIgGgJIgEgLIgEgKIgBgNIAAAAIABgLIAEgLIAEgLIAGgJIAIgHQADgEAGgCIAKgEIAJgBIALABIAKADIAIAHQAFADADAEIAHAJIADAKQAFAPAAAIIAAAAIgBAMIgEALQgBAGgDAFIgGAJIgIAHQgDAEgGACIgKAEIgKABIgKgBgAgLgmQgFADgEAGQgFAGgBAIQgCAHAAAIIAAAAQAAAIACAIQABAIAFAGQAEAFAFAEQAGADAFAAQAGAAAGgDQAFgDAEgGQAFgGABgIQADgHAAgJIAAAAQAAgHgDgIQgBgIgFgGQgEgFgFgEQgGgDgGAAQgFAAgGADg");
	this.shape_15.setTransform(-6.7,38.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgKA8IgKgDIgJgHQgEgDgDgEIgGgJIgFgLIgCgKIgBgNIAAAAIABgLIACgLIAFgLIAGgJIAHgHQAFgEAEgCIAKgEIAKgBIALABIAKADIAJAHQAEADADAEIAGAJIAFAKQADAPAAAIIAAAAIgBAMIgCALQgCAGgDAFIgGAJIgHAHQgFAEgEACIgKAEIgLABIgKgBgAgLgmQgGADgDAGQgEAGgDAIQgCAHAAAIIAAAAQAAAIACAIQADAIAEAGQADAFAGAEQAGADAFAAQAHAAAFgDQAFgDAFgGQADgGACgIQADgHAAgJIAAAAQAAgHgDgIQgCgIgDgGQgFgFgFgEQgGgDgGAAQgFAAgGADg");
	this.shape_16.setTransform(-19,38.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AACA8IAAhhIgTAGIgFgRIAegLIAPAAIAAB3g");
	this.shape_17.setTransform(-29.1,38.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgEBIIAAgRQgOgCgIgDQgJgEgJgHIALgQIAOAKQAHADAJACIAAgiIgRgEQgGgCgFgEQgFgEgCgGQgBgFAAgHIAAgBQgBgHADgFQADgGAEgEQAFgEAGgDQAHgDAIAAIAAgKIANAAIAAAKQAJABAIAEQAHADAHAFIgJAQQgFgEgGgDQgGgDgGgBIAAAgQAKADAGADQAIADAEADQAEAEADAFQACAGAAAGIAAABQAAAHgDAFQgCAGgFAEQgFAFgHACQgGADgIABIAAAQgAAIAmQAIAAAFgEQAEgEAAgGQAAgGgDgEQgEgDgKgDgAgPgoQgFAEAAAGQAAAGADADQAFAEAJADIAAgeQgIABgEADg");
	this.shape_18.setTransform(-37.4,39);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgIApIAAggIghAAIAAgRIAhAAIAAggIARAAIAAAgIAhAAIAAARIghAAIAAAgg");
	this.shape_19.setTransform(0,19.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AgWA4QgKgCgIgGIAHgPQAIAEAHADQAIADAJAAQAFgBAFgCQAGgBADgDQAEgEACgFQACgGAAgGIAAgHQgIAJgGADQgDACgFABQgEACgEAAQgIgBgHgDQgIgDgFgFQgGgGgEgHQgDgGAAgJIAAgBQAAgGAEgLQADgJAGgFQAFgGAIgCQAHgDAIAAIAIABQAFABAEADQAGADAGAHIAAgNIAVAAIAABFQAAALgDAJQgDAJgGAFIgGAGIgJADQgNADgGAAQgLAAgLgDgAgJgnQgEACgEADQgDAEgCAEQgCAFAAAFQAAAGACAFQACAEADABQAEAEAEABQAFACAEAAQAFAAAEgCQAFgBAEgEQAEgCACgDQACgFAAgFIAAgBQAAgFgCgFQgCgEgEgEQgEgDgFgCQgEgCgFAAQgEAAgFACg");
	this.shape_20.setTransform(33.9,3.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_21.setTransform(23.2,2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgJA9IAAhXIASAAIAABXgAgKgpIAAgTIAUAAIAAATg");
	this.shape_22.setTransform(15.5,0.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AASA9IgZgmIgNANIAAAZIgUAAIAAh5IAUAAIAABIIAjgmIAZAAIgkAiIAlA1g");
	this.shape_23.setTransform(8.7,0.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AgEAtIgIgCQgIgEgHgGQgGgHgDgIQgEgJAAgJQAAgIAEgJQADgIAGgGQAHgHAIgEIAJgCIAHgBIAMABIAKADQAGADAIAIIgMAOQgFgGgFgCQgHgDgHAAQgEAAgEACQgFACgDAEQgDAEgCAFQgCAFgBAFIAAAAQABAFACAGQACAFADAEQAEAEAEACQAEACAFAAQAHAAAHgDQAFgCAFgGIAMAMQgJAKgGADIgKADIgMABg");
	this.shape_24.setTransform(-1.5,2.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgOArQgJgDgFgHQgHgGgDgIIgDgJIgBgKIAAAAQAAgIADgJQADgIAHgHQAFgGAIgEIAIgCIAIgBIAKABIAIADQAGACAIAIQAGAHACAIQADAJAAAIIAAAGIhAAAIADAJQACAFAEADIAHAEQAEABADAAQAHAAAHgCQAFgDAFgFIANAKIgHAHQgEAEgEACIgKADIgMABQgHAAgJgDgAAXgFQgBgFgCgEQgBgFgDgDIgHgFQgFgCgEAAQgDAAgEACQgEACgDADIgFAHQgCAFAAAFIAsAAIAAAAg");
	this.shape_25.setTransform(-11.6,2.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AATA9IAAgyQAAgGgBgEQgBgCgDgCQgCgDgEgCQgDgBgFgBIgGACQgEACgDADIgEAFQgBAEAAAFIAAAyIgVAAIAAh5IAVAAIAAAwQAFgIAGgDIAHgEIAIgBQAHAAAGACQAGADAEAEQAEAFADAGQACAGAAAGIAAA5g");
	this.shape_26.setTransform(-21.9,0.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AgFA8IgMgDIgKgGIgIgIQgFgEgDgFIgGgKIgDgLIgBgNIAAAAIABgLIADgLIAGgLIAHgJIAJgHQAFgEAFgCIAMgEIAMgBQAHAAAHACQAHABAGACQAHAEAMAJIgOAQQgHgHgHgEIgJgDIgKgBQgGAAgIAEQgGACgGAHQgFAFgDAIQgDAHAAAIIAAAAQAAAIADAIQADAHAFAHQAGAFAGAEQAIADAGAAQAGAAAFgBIAIgEQAHgDAJgIIANAOIgKAJIgKAGIgOAFQgHABgHAAIgLgBg");
	this.shape_27.setTransform(-33.3,0.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgOArQgIgDgHgHQgGgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQAEgIAFgHQAGgGAIgEIAJgCIAHgBIAKABIAJADQAFACAIAIQAFAHADAIQADAJAAAIIAAAGIhBAAIAEAJQACAFADADIAIAEQAFABACAAQAIAAAGgCQAFgDAGgFIAMAKIgHAHQgEAEgFACIgKADIgLABQgIAAgIgDgAAWgFQAAgFgCgEQgCgFgCgDIgHgFQgFgCgEAAQgDAAgEACQgEACgDADIgFAHQgCAFgBAFIAsAAIAAAAg");
	this.shape_28.setTransform(14.2,-16.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("AgOArQgJgDgFgHQgHgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQADgIAGgHQAGgGAIgEIAJgCIAHgBIAKABIAIADQAGACAIAIQAFAHADAIQADAJAAAIIAAAGIhBAAIAEAJQACAFADADIAIAEQAFABACAAQAHAAAHgCQAFgDAGgFIAMAKIgHAHQgEAEgEACIgLADIgLABQgIAAgIgDgAAWgFQAAgFgCgEQgBgFgDgDIgHgFQgFgCgEAAQgDAAgEACQgEACgDADIgFAHQgCAFgBAFIAsAAIAAAAg");
	this.shape_29.setTransform(4,-16.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgZAtIAAhXIAVAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAFAAIAAAWIgBAAQgGAAgGACQgFACgEAEQgDAFgBAHQgDAEAAAJIAAAig");
	this.shape_30.setTransform(-4.3,-17);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AgrA7IAAh1IBXAAIAAATIhCAAIAAAgIA6AAIAAARIg6AAIAAAxg");
	this.shape_31.setTransform(-13.4,-18.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.5,-28,117,116);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgJSguyISlAAMAAABdlIylAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-300.5,121,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Freeer160x600();
	this.instance.parent = this;
	this.instance.setTransform(46,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(168,187,1,1,0,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,197);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201708_Freeer_120x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(101,448,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.357,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(60,586.2,0.683,0.683,0,0,0,0,0.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuastackai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(60,558.7,1.153,1.153,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border120x600();
	this.instance_2.parent = this;
	this.instance_2.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},164).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(34,57,1,1,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},164).wait(1));

	// CTA
	this.instance_4 = new lib.CTA();
	this.instance_4.parent = this;
	this.instance_4.setTransform(719.5,683,5,5,0,0,0,119.5,40);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(71).to({_off:false},0).to({scaleX:1,scaleY:1,x:179.5,y:414},4).to({_off:true},89).wait(1));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(754.5,384,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleX:1,scaleY:1,x:183.5,y:214},4).to({_off:true},160).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({_off:true},164).wait(1));

	// tag
	this.instance_7 = new lib._2016TAGvert();
	this.instance_7.parent = this;
	this.instance_7.setTransform(60.1,526.2,1.014,1.014,0,0,0,0,2.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(204.9,528.5,0.673,0.673,0,0,0,215.2,63.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.parent = this;
	this.instance_9.setTransform(116.8,517.3,0.696,0.696,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_10 = new lib.HTML5rastershad_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_10.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},164).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},164).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(17.1,232.1,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78,300,545,1019);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;