(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 468,
	height: 60,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Freeer336x280.jpg?1504144232721", id:"Freeer336x280"},
		{src:"images/HTML5rastershad.png?1504144232721", id:"HTML5rastershad"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.Freeer336x280 = function() {
	this.initialize(img.Freeer336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,409,165);


(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACPAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgFAAgFgCgAAwAXQgFgFAAgGQAAgIAFgEQAGgCAJAAQAFAAAKACIAAgBQAAgNgPAAQgGAAgHAEIgDgGQAJgEAIAAQAKAAAGAFQAEAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgFgDgAAyALQAAAKAMAAQAGAAAFgEQAFgDAAgGIAAgEQgIgCgGAAQgOAAAAAJgAgjAUQgHgHAAgLQABgIAGgHQAGgHAKAAQAJAAAHAHQADAHAAAIIAAADIgjAAQABAHAFAEQAEAEAHAAQAIAAAGgGIAEAEQgHAIgLAAQgKAAgHgGgAgFAAQgBgOgNAAQgHAAgDAEQgFAEgBAGIAeAAIAAAAgAhfAUQgGgHAAgLQAAgJAGgHQAHgGAJAAQAKAAAIAKIAAgcIAHAAIAAA/IgHAAIAAgJQgHAKgLAAQgJAAgHgGgAhZgJQgFAFAAAGIAAAAQAAAIAFAFQAFAFAGAAQAHAAAFgFQAFgFAAgIIAAAAQAAgGgFgFQgFgFgHAAQgHAAgEAFgAiUAUQgHgHABgLQAAgIAFgHQAHgHAJAAQALAAAGAHQAGAHAAAIIgBADIglAAQACAPAOAAQAJAAAHgGIADAEQgHAIgMAAQgKAAgGgGgAh1AAQgCgOgOAAQgFAAgFAEQgDAEgCAGIAfAAIAAAAgAB7AZIAAg/IAHAAIAAA/gABjAZIAAg/IAIAAIAAA/gAAMAZIAAgsIAHAAIAAAMQAHgNAMAAIAAAHIAAAAQgIAAgFAGQgFAGgBAIIAAASgAi1AZIAAgmIgHAAIAAgGIAHAAIAAgEQAAgIADgEQAFgEAFAAIAIABIAAAGIgHgBQgHAAgBAKIAAAEIAPAAIAAAGIgPAAIAAAmg");
	this.shape.setTransform(-36.4,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA+AlIADgFQADABAEABQAGAAADgJIgUgsIAHAAIARAkIAPgkIAHAAIgTAtQgFANgLAAQgGAAgEgCgAE2AXQgGgFAAgHQAAgNAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAEAAAKIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAE3ALQAAAJAMAAQAGABAFgEQAEgDABgGIAAgFQgIgCgGAAQgOAAAAAKgAD7AIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgADNATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgIgHgGAAQgIABgEAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgAAPAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAIgBAGAHQAIAHgBAIIAAABQABALgIAGQgGAHgIAAQgMAAgGgKgAATgJQgEAFAAAFIAAABQAAAHAEAGQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgAhJATQgHgGAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgHgAhEgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAh+ATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAhgAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAjYAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAkNATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgACzAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAilAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgAkfAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAlXAZIAAgsIAHAAIAAAsgAlYgdIAAgIIAIAAIAAAIg");
	this.shape_1.setTransform(20.8,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAKIAAgTIATAAIAAATg");
	this.shape.setTransform(32.4,21.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgCgJIgBgJIAAAAQAAgIADgIQACgIAGgGQAFgGAIgDIAIgDIAHAAIAJAAIAIADQAGACAHAIQAFAGACAJQAEAHAAAIIgBAFIg8AAQAAAFADAEIAFAHQADADAFABQAEABACABQAHgBAGgCQAFgCAFgFIALAKIgGAGIgIAFIgJADIgLACQgHgBgIgDgAAVgFIgCgIQgBgFgDgDQgDgDgEgBQgEgCgEAAQgCAAgFACQgDABgDADIgFAIIgCAIIApAAIAAAAg");
	this.shape_1.setTransform(25.4,18.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_2.setTransform(17.6,18.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSApQgGgBgEgDQgEgEgCgEQgDgFAAgHQAAgHADgGQACgEAFgCQAEgDAHgCQAGgCAHAAQAJAAANAEIAAgCQAAgEgCgDQgBgEgDgDIgGgDIgHgBQgHAAgGACIgLADIgFgPIAOgGQAIgBAIAAQAJgBAHADQAHADAFAEQAEAFADAGQACAHAAAJIAAAvIgTAAIAAgKQgFAFgGAEQgIAEgHAAQgGgBgFgCgAgGADQgEABgDACQgCACgBADQgCACAAADQAAAGAFAEQAFADAHAAIAHgBIAHgEQADgDABgDQACgDAAgEIAAgFQgMgDgHAAIgGAAg");
	this.shape_3.setTransform(9.1,18.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgDgJIAAgJIAAAAQAAgIACgIQADgIAGgGQAGgGAHgDIAIgDIAHAAIAKAAIAHADQAGACAHAIQAFAGADAJQACAHAAAIIAAAFIg8AAQABAFACAEIAFAHQADADAFABQAEABACABQAHgBAFgCQAGgCAFgFIAMAKIgHAGIgIAFIgJADIgLACQgHgBgIgDgAAVgFIgCgIQgCgFgDgDQgCgDgEgBQgDgCgFAAQgDAAgDACQgEABgDADIgFAIIgDAIIAqAAIAAAAg");
	this.shape_4.setTransform(-5,18.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AASAqIgSg3IgRA3IgSAAIgbhTIAUAAIARA4IASg4IAPAAIATA4IARg4IATAAIgbBTg");
	this.shape_5.setTransform(-16.7,18.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAOQAIgBADgEQABgEAAgFIgGAAIAAgVIATAAIAAASQAAAGgCAEQgBAFgDADQgDADgEACIgKACg");
	this.shape_6.setTransform(-30.8,22.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAAA0QgEgBgDgCQgEgDgBgFQgCgFAAgHIAAgqIgLAAIAAgRIALAAIAAgXIARAAIAAAXIAXAAIAAARIgXAAIAAAnQAAAFADADQADADAFAAQAGAAAGgDIAAAQIgIADIgKABQgFAAgDgCg");
	this.shape_7.setTransform(-36.1,17.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgIA5IAAhSIARAAIAABSgAgJgmIAAgTIATAAIAAATg");
	this.shape_8.setTransform(-41.5,17);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSApQgGgBgEgDQgEgEgCgEQgDgFAAgHQAAgHADgGQACgEAFgCQAEgDAHgCQAGgCAHAAQAJAAANAEIAAgCQAAgEgCgDQgBgEgDgDIgGgDIgHgBQgHAAgGACIgLADIgFgPIAOgGQAIgBAIAAQAJgBAHADQAHADAFAEQAEAFADAGQACAHAAAJIAAAvIgTAAIAAgKQgFAFgGAEQgIAEgHAAQgGgBgFgCgAgGADQgEABgDACQgCACgBADQgCACAAADQAAAGAFAEQAFADAHAAIAHgBIAHgEQADgDABgDQACgDAAgEIAAgFQgMgDgHAAIgGAAg");
	this.shape_9.setTransform(-48.7,18.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAbA4IgbhOIgaBOIgRAAIgnhvIAVAAIAbBRIAbhRIAPAAIAbBRIAbhRIAVAAIgnBvg");
	this.shape_10.setTransform(-60.5,17.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgJALIAAgVIATAAIAAAVg");
	this.shape_11.setTransform(126.9,7.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTAoQgFgCgEgEQgFgFgCgGQgBgGAAgHIAAg0IATAAIAAAuQAAAFABAEQACAEACADQACACADACIAHABQAEAAADgCQAEgBACgDQACgCACgEIABgJIAAguIATAAIAABTIgTAAIAAgNQgFAHgFADIgIADQgBACgFAAQgHAAgGgDg");
	this.shape_12.setTransform(119.7,4.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgIArIgJgDQgHgDgHgGQgGgGgDgJIgDgIIgBgIQABgEADgMQADgHAHgGQAGgHAHgDIAJgDIAIgBQAGAAALAEQAJADAGAGQAGAGADAIQAEALgBAFIAAAAIgBAIIgCAIQgDAJgGAGQgGAGgJADQgLADgGABgAgJgYQgFACgDAEQgEAEgBAFQgCAEAAAFIAAAAQAAAFACAFQABAFAEADQAEAFAEACQAFABAEAAQAGAAAEgBQAFgCADgFQAEgDACgFQABgFAAgFQAAgEgBgFQgCgFgEgDQgDgFgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_13.setTransform(109.6,4.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgbA1IgJgDIAGgPQAGAEAGAAQADAAADgDQADgCACgFIgjhTIAVAAIAWA9IAWg9IAUAAIgiBVIgFALIgEAHQgEADgEACIgJABQgFAAgFgCg");
	this.shape_14.setTransform(99.6,5.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUA1QgKgCgIgFIAHgPIAOAHQAIACAIAAQAFgBAFgBQAFgCADgDQADgDACgFQACgFAAgGIAAgHQgIAIgEAEIgIADQgEABgDAAQgIAAgHgDQgHgDgFgEQgGgGgDgHQgDgGAAgIIAAgBQAAgGADgLQADgHAGgGQAFgFAHgCQAHgCAIgBIAHABIAIAEQAGADAGAHIAAgNIATAAIAABBQAAALgCAIQgDAHgFAGIgHAFIgIADQgNAEgFAAQgLAAgJgDgAgIglQgFACgDADQgDADgCAFQgBAEAAAFQAAAFABAFQACAEADABQADADAFABQAEACAEAAQAFAAAEgCQAFgBADgDQADgBACgEQACgFAAgEIAAgBQAAgFgCgEQgCgFgDgDQgDgDgFgCQgEgBgFgBQgEABgEABg");
	this.shape_15.setTransform(84.5,5.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AASArIAAgvIgBgJQgBgDgDgCIgFgFIgIgBQgCAAgDABQgEACgDADQgCACgBAEQgCAEAAAFIAAAuIgUAAIAAhTIAUAAIAAANQAEgGAHgEIAGgEIAIgBQAGAAAGACQAGADAEAEQAEAFACAFQACAHAAAHIAAA0g");
	this.shape_16.setTransform(74.4,4.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgIA6IAAhTIARAAIAABTgAgJgmIAAgSIATAAIAAASg");
	this.shape_17.setTransform(67.2,3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgbA1IgJgDIAGgPQAGAEAGAAQAEAAACgDQADgCADgFIgkhTIAVAAIAWA9IAVg9IAVAAIghBVIgGALIgEAHQgDADgEACIgJABQgHAAgEgCg");
	this.shape_18.setTransform(60.1,5.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgSAqQgGgCgEgEQgEgDgCgFQgDgFAAgGQAAgHADgFQACgFAFgCQAEgDAHgCQAGgCAHAAQAJAAANADIAAgBQAAgEgCgEQgBgDgDgCIgGgEIgHgBQgHAAgGABIgLAFIgFgQIAOgGQAIgCAIAAQAJABAHACQAHACAFAFQAEAEADAIQACAGAAAIIAAAxIgTAAIAAgLQgFAGgGADQgIADgHABQgGAAgFgCgAgGAEQgEABgDACQgCABgBACQgCADAAADQAAAGAFADQAFADAHAAIAHgBIAHgDQADgDABgDQACgDAAgEIAAgFQgMgDgHAAIgGABg");
	this.shape_19.setTransform(50.5,4.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgqA3IAAhsIATAAIAAAOQAFgHAHgEQADgCAFgBIAHgBQAHAAAIACQAHADAFAGQAGAGADAIQADALAAAHIAAABIgBAKIgCAGQgDAIgGAGQgFAGgHADQgHADgIAAQgEAAgEgCIgHgDQgHgEgFgGIAAAmgAgIgkQgEACgEAEQgDADgCAFQgCAFAAAGIAAABQAAAGACAEQACAEADADQAEAEAEACQAFACADAAQAEAAAFgCQAEgCADgEQAEgDACgEQACgEAAgGIAAgBQAAgGgCgFQgCgFgEgDQgDgEgEgCQgFgCgEAAQgDAAgFACg");
	this.shape_20.setTransform(40.9,5.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgNApQgIgEgGgFQgGgHgDgIIgDgIIAAgJIAAAAQgBgIADgIQAEgIAFgGQAGgGAHgDIAIgDIAHgBIAKABIAIADQAFADAHAHQAFAGADAIQACAJAAAGIAAAGIg8AAQABAFACAFIAFAGQAEADAEABQADACADgBQAHABAFgDQAGgDAFgFIAMAKIgHAHIgIAFIgKAEIgKABQgHAAgIgDgAAVgFIgCgJQgCgDgDgDQgCgEgEgBQgDgCgFAAQgDAAgDACQgEABgDAEIgFAGIgDAJIAqAAIAAAAg");
	this.shape_21.setTransform(25.7,4.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgEA5IgHgCQgHgEgFgHIAAANIgTAAIAAhzIATAAIAAAuQAFgGAHgFQADgCAFgBIAHgBQAHAAAIACQAHADAFAGQAGAGADAIQADAJAAAIIAAAAIgBAKIgCAJQgDAHgGAGQgFAGgHADQgHADgIAAQgEAAgEgCgAgIgIQgEACgEADQgDADgCADQgCAGAAAGIAAAAQAAAGACAFQACAFADAEQAEADAEACQAFACADAAQAEAAAFgCQAEgCADgDQAEgEACgFQACgFAAgGIAAAAQAAgGgCgGQgCgDgEgDQgDgDgEgCQgFgCgEAAQgDAAgFACg");
	this.shape_22.setTransform(15.7,3.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgRA4QgIgDgFgGQgGgGgDgHIgDgJIAAgKIAAAAQAAgIADgJQADgIAGgGQAFgGAIgDQAGgCAIAAIAHABIAIADQAHAEAFAGIAAgtIATAAIAABzIgTAAIAAgOQgFAIgHADIgIADQgEACgDAAQgIAAgGgDgAgHgIQgFACgDADQgEADgCADQgCAGAAAGIAAAAQAAAGACAFQACAFAEAEQADADAFACQAEACADAAQAEAAAFgCQAFgCADgDQADgEACgFQACgFAAgGIAAAAQAAgGgCgGQgCgDgDgDQgDgDgFgCQgFgCgEAAQgEAAgDACg");
	this.shape_23.setTransform(-0.2,3.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgMAOQAHgCAEgDQABgEAAgFIgHAAIAAgVIAUAAIAAASQAAAFgCAFQgBAFgEADQgDADgDACQgEACgGAAg");
	this.shape_24.setTransform(-7.7,-0.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgNApQgIgEgGgFQgGgHgDgIIgDgIIAAgJIAAAAQAAgIACgIQADgIAGgGQAGgGAHgDIAIgDIAHgBIAKABIAHADQAGADAHAHQAFAGADAIQACAJAAAGIAAAGIg8AAQABAFACAFIAFAGQADADAFABQAEACACgBQAHABAFgDQAGgDAFgFIAMAKIgHAHIgIAFIgJAEIgLABQgHAAgIgDgAAVgFIgCgJQgCgDgDgDQgCgEgEgBQgDgCgFAAQgDAAgDACQgEABgDAEIgFAGIgDAJIAqAAIAAAAg");
	this.shape_25.setTransform(-14.4,4.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AASAqIgSg3IgRA3IgSAAIgbhTIAUAAIARA4IASg4IAPAAIATA4IARg4IATAAIgbBTg");
	this.shape_26.setTransform(-26.2,4.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgRA4QgIgDgFgGQgGgGgDgHIgDgJIAAgKIAAAAQAAgIADgJQADgIAGgGQAFgGAIgDQAGgCAIAAIAHABIAIADQAHAEAFAGIAAgtIATAAIAABzIgTAAIAAgOQgFAIgHADIgIADQgEACgDAAQgIAAgGgDgAgHgIQgFACgDADQgEADgCADQgCAGAAAGIAAAAQAAAGACAFQACAFAEAEQADADAFACQAEACADAAQAEAAAFgCQAFgCADgDQADgEACgFQACgFAAgGIAAAAQAAgGgCgGQgCgDgDgDQgDgDgFgCQgFgCgEAAQgEAAgDACg");
	this.shape_27.setTransform(-43.4,3.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AASArIAAgvIgBgJQgBgDgCgCIgGgFIgIgBQgCAAgEABQgDACgCADQgDACgCAEQgBAEAAAFIAAAuIgTAAIAAhTIATAAIAAANQAFgGAFgEIAHgEIAHgBQAHAAAGACQAFADAEAEQAFAFABAFQACAHAAAHIAAA0g");
	this.shape_28.setTransform(-53.4,4.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgSAqQgGgCgEgEQgEgDgCgFQgDgFAAgGQAAgHADgFQACgFAFgCQAEgDAHgCQAGgCAHAAQAJAAANADIAAgBQAAgEgCgEQgBgDgDgCIgGgEIgHgBQgHAAgGABIgLAFIgFgQIAOgGQAIgCAIAAQAJABAHACQAHACAFAFQAEAEADAIQACAGAAAIIAAAxIgTAAIAAgLQgFAGgGADQgIADgHABQgGAAgFgCgAgGAEQgEABgDACQgCABgBACQgCADAAADQAAAGAFADQAFADAHAAIAHgBIAHgDQADgDABgDQACgDAAgEIAAgFQgMgDgHAAIgGABg");
	this.shape_29.setTransform(-63.3,4.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_30.setTransform(-75.5,4.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgNApQgIgEgGgFQgGgHgDgIIgDgIIgBgJIAAAAQAAgIADgIQADgIAGgGQAFgGAIgDIAIgDIAHgBIAKABIAIADQAEADAIAHQAFAGADAIQACAJAAAGIAAAGIg8AAQABAFACAFIAFAGQAEADADABQAEACADgBQAHABAFgDQAGgDAFgFIAMAKIgHAHIgIAFIgKAEIgKABQgHAAgIgDgAAVgFIgCgJQgBgDgEgDQgCgEgEgBQgDgCgFAAQgDAAgDACQgEABgDAEIgFAGIgDAJIAqAAIAAAAg");
	this.shape_31.setTransform(-84,4.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgWAJIAAgRIAtAAIAAARg");
	this.shape_32.setTransform(-92.1,3.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgNApQgIgEgGgFQgGgHgDgIIgCgIIgBgJIAAAAQAAgIACgIQADgIAGgGQAFgGAIgDIAIgDIAHgBIAJABIAIADQAGADAHAHQAFAGACAIQAEAJAAAGIgBAGIg8AAQAAAFADAFIAFAGQADADAFABQAEACACgBQAHABAGgDQAFgDAFgFIALAKIgGAHIgIAFIgJAEIgLABQgHAAgIgDgAAVgFIgCgJQgBgDgDgDQgDgEgEgBQgEgCgEAAQgCAAgFACQgDABgDAEIgFAGIgCAJIApAAIAAAAg");
	this.shape_33.setTransform(-100.1,4.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgNApQgIgEgGgFQgGgHgDgIIgCgIIgCgJIAAAAQABgIADgIQADgIAFgGQAGgGAHgDIAIgDIAHgBIAJABIAIADQAFADAIAHQAFAGACAIQADAJABAGIgBAGIg8AAQAAAFADAFIAFAGQADADAEABQAEACADgBQAHABAGgDQAFgDAFgFIALAKIgGAHIgIAFIgKAEIgKABQgHAAgIgDgAAVgFIgCgJQgBgDgDgDQgDgEgEgBQgEgCgEAAQgDAAgEACQgDABgDAEIgFAGIgCAJIApAAIAAAAg");
	this.shape_34.setTransform(-109.8,4.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_35.setTransform(-117.6,4.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgOA6IAAhCIgKAAIAAgQIAKAAIAAgGQAAgHABgFQACgFAEgEQADgDAEgCQADgBAHAAQAIAAAIACIAAAQQgHgCgFAAQgGAAgCADQgDADAAAHIAAAEIAXAAIAAAQIgXAAIAABCg");
	this.shape_36.setTransform(-124,2.9);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgbA1IgJgDIAGgPQAGAEAGAAQAEAAACgDQADgCACgFIgjhTIAVAAIAWA9IAWg9IAUAAIgiBVIgFALIgEAHQgEADgEACIgJABQgFAAgFgCg");
	this.shape_37.setTransform(-136.8,5.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AASArIAAgvIgBgJQgBgDgDgCIgFgFIgIgBQgCAAgEABQgDACgDADQgCACgBAEQgCAEAAAFIAAAuIgTAAIAAhTIATAAIAAANQAFgGAGgEIAGgEIAIgBQAGAAAGACQAGADADAEQAEAFADAFQABAHAAAHIAAA0g");
	this.shape_38.setTransform(-146.4,4.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAlA4IgLgbIgzAAIgMAbIgUAAIAxhvIARAAIAxBvgAATALIgTgrIgSArIAlAAg");
	this.shape_39.setTransform(-157.7,3.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-177,-6,319,34);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("A8lFJIAAqSMA5LAAAIAAKSg");
	this.shape.setTransform(238,33,1.3,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,476,66);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgMAgQgKgEgEgDIAHgLQAGAEAFACQAGADAEAAQAFAAACgCQADgCAAgEIAAAAQAAgEgEgCIgJgEQgLgDgEgCIgFgFQgCgDAAgFIAAAAQAAgFACgEQACgEAEgCQADgDAEgCQAFgBADAAQAGAAAHACQAHACAFAEIgGALIgKgFQgFgCgEAAQgDAAgDACQgCACAAADIAAABQAAADAFACIAIAEIAIADIAHACQADACACADQACAEAAAEIAAABQAAAFgCAEQgCAEgEADIgIAEQgEABgGAAQgFAAgIgDg");
	this.shape.setTransform(134.1,14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgPAhQgFgCgDgEQgDgDgCgFQgBgFAAgGIAAgqIAQAAIAAAmIABAGIACAGQACACADABIAFABIAGgBIAEgDIAEgGIABgHIAAglIAPAAIAABDIgPAAIAAgKQgEAFgFADIgFADIgGAAQgFABgFgCg");
	this.shape_1.setTransform(126.9,14.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AAPAiIAAgkIgBgIIgDgFIgFgDQgDgBgDgBQgCABgCABQgDABgCADIgEAEIgBAIIAAAkIgPAAIAAhCIAPAAIAAALQAEgGAFgDIAFgCIAGgBQAGAAAEACQAFABADADQADAEACAFQABAFAAAGIAAApg");
	this.shape_2.setTransform(118.9,13.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgGAjIgHgDQgHgCgFgFQgFgFgCgGIgCgHIgBgHQAAgDADgJQACgHAFgFQAFgFAHgCIAHgDIAGAAQAFAAAJACQAHADAFAFQAFAFACAGQADAJAAAEIAAAAIgBAHIgCAGQgCAHgFAFQgFAFgHACQgJADgFAAgAgHgTQgEACgDADIgEAHQgBAEAAADIAAAAIABAIIAEAHQADADAEACQAEACADAAQAEAAAEgCQAEgCADgDIAEgHQABgEAAgEQAAgDgBgEQgCgEgDgDQgCgDgEgCQgEgCgEAAQgDAAgEACg");
	this.shape_3.setTransform(110.6,14);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AgkAtIAAhZIAmAAQAJAAAGACQAFACAFAEQADADABAEQABADAAAFIAAAAIgBAHIgDAHQgDADgGAEIAIABIAFAEQADADABADQABAEAAAFQAAAGgCAFQgCAEgFADQgEAEgGACQgHABgHAAgAgVAfIAZAAIAHgBQADAAADgCIADgFIABgEIAAgBIgBgFIgDgEIgGgCIgJgBIgXAAgAgVgGIAVAAIAHAAIAEgCIAEgFQACgCAAgDIAAAAIgBgFIgEgDIgEgDIgHgBIgWAAg");
	this.shape_4.setTransform(102,12.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AAAArQgEgBgCgCQgCgDgCgEQgBgEgBgFIAAgiIgIAAIAAgOIAIAAIAAgTIAPAAIAAATIASAAIAAAOIgSAAIAAAfQAAAFACACQACACAEAAQAFAAAFgCIAAAMIgHADIgIABIgGgBg");
	this.shape_5.setTransform(90.4,13.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AAPAiIAAgkIgBgIIgDgFIgFgDQgDgBgDgBQgCABgCABQgDABgCADIgEAEIgBAIIAAAkIgPAAIAAhCIAPAAIAAALQAEgGAFgDIAFgCIAGgBQAGAAAEACQAFABADADQADAEACAFQABAFAAAGIAAApg");
	this.shape_6.setTransform(83.8,13.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AgPAhQgFgCgDgEQgDgDgCgFQgBgFAAgGIAAgqIAQAAIAAAmIABAGIACAGQACACADABIAFABIAGgBIAEgDIAEgGIABgHIAAglIAPAAIAABDIgPAAIAAgKQgEAFgFADIgFADIgGAAQgFABgFgCg");
	this.shape_7.setTransform(75.7,14.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgGAjIgHgDQgHgCgFgFQgFgFgCgGIgCgHIgBgHQAAgDADgJQACgHAFgFQAFgFAHgCIAHgDIAGAAQAFAAAJACQAHADAFAFQAFAFACAGQADAJAAAEIAAAAIgBAHIgCAGQgCAHgFAFQgFAFgHACQgJADgFAAgAgHgTQgEACgDADIgEAHQgBAEAAADIAAAAIABAIIAEAHQADADAEACQAEACADAAQAEAAAEgCQAEgCADgDIAEgHQABgEAAgEQAAgDgBgEQgCgEgDgDQgCgDgEgCQgEgCgEAAQgDAAgEACg");
	this.shape_8.setTransform(67.5,14);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgCAjIgHgDQgGgCgFgFQgFgFgCgGQgDgHAAgHQAAgGADgGQACgHAFgFQAFgFAGgCIAHgDIAFAAIAJABIAIACQAEACAHAHIgKAKQgEgEgEgCQgEgDgGAAQgDAAgDACQgDACgDADIgEAHQgBAEAAADIAAAAQAAAEABAEIAEAHQADADAEACQACACAEAAQAFAAAFgDQAEgCAEgEIAJAJQgHAHgEADIgIACIgJABg");
	this.shape_9.setTransform(59.6,14);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgCAjIgHgDQgGgCgFgFQgFgFgCgGQgDgHAAgHQAAgGADgGQACgHAFgFQAFgFAGgCIAHgDIAFAAIAJABIAIACQAEACAHAHIgKAKQgEgEgEgCQgEgDgGAAQgDAAgDACQgDACgDADIgEAHQgBAEAAADIAAAAQAAAEABAEIAEAHQADADAEACQACACAEAAQAFAAAFgDQAEgCAEgEIAJAJQgHAHgEADIgIACIgJABg");
	this.shape_10.setTransform(52.2,14);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AAeAtIgKgWIgoAAIgKAWIgQAAIAohZIANAAIAoBZgAAPAJIgPgiIgPAiIAeAAg");
	this.shape_11.setTransform(43.3,12.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AAPAiIgPgtIgOAtIgOAAIgXhDIARAAIANAtIAQgtIALAAIAPAtIAPgtIAQAAIgYBDg");
	this.shape_12.setTransform(28.7,14);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgKAhQgHgDgEgFQgFgEgDgHIgCgHIgBgHIAAAAQAAgGADgGQACgHAFgFQAEgFAGgCIAHgDIAFAAIAIAAIAGADQAEACAHAGQAEAFACAHQACAGAAAGIAAAEIgxAAIACAHIAFAGQACACAEABIAFABQAFAAAFgCQAEgCAEgEIAKAIIgGAGIgGAEIgIACIgIABQgGAAgGgCgAARgDIgCgHQgBgEgCgCIgFgEIgHgBIgFABIgFAEQgDACgBADIgCAIIAhAAIAAAAg");
	this.shape_13.setTransform(19.2,14);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AAaAtIgwg+IAAA+IgQAAIAAhZIAPAAIAvA9IAAg9IAPAAIAABZg");
	this.shape_14.setTransform(10.1,12.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgHAuIgIgDIgHgFIgFgFIgFgHIgDgIIgCgIIgBgKIABgIIACgJIADgIIAFgHIAFgGIAHgEIAIgCIAHgBIAIABIAIACIAHAEIAFAGIAFAHIADAIQADAMAAAFIAAAAIgBAJIgCAJIgDAIIgFAGIgFAGIgHAFIgIADIgIAAIgHAAgAgIgdQgEADgEAEQgDAFgBAFQgCAHAAAFIAAAAQAAAGACAGQABAGADAEQAEAFAEACQAFADADAAQAFAAAEgDQAFgCADgFQADgDABgHQACgGAAgGQAAgFgCgGQgBgGgDgFQgEgEgEgDQgFgCgEAAQgDAAgFACg");
	this.shape_15.setTransform(-3.6,12.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgHAuIgIgDIgHgFIgGgFIgEgHIgEgIIgCgIIAAgKIAAgIIADgJIADgIIAFgHIAFgGIAIgEIAHgCIAHgBIAIABIAIACIAGAEIAHAGIAEAHIAEAIQACAMAAAFIAAAAIAAAJIgCAJIgEAIIgEAGIgHAGIgHAFIgHADIgIAAIgHAAgAgIgdQgEADgDAEQgEAFgBAFQgBAHgBAFIAAAAQABAGABAGQABAGAEAEQADAFAEACQAEADAEAAQAFAAAEgDQAEgCADgFQAEgDABgHQACgGgBgGQABgFgCgGQgBgGgEgFQgDgEgEgDQgEgCgFAAQgEAAgEACg");
	this.shape_16.setTransform(-13,12.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AABAtIAAhJIgOAEIgDgNIAWgHIALAAIAABZg");
	this.shape_17.setTransform(-20.7,12.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgDA3IAAgNIgQgEQgIgEgGgFIAIgMQAGAFAFADQAGADAGAAIAAgZIgNgDIgIgFQgEgDgBgEQgCgEAAgGQAAgFACgFQACgEAEgDQADgDAFgCQAFgCAGgBIAAgHIAKAAIAAAIQAHAAAGADQAGACAFAEIgHANQgEgEgFgCIgJgDIAAAZQAIACAFACQAFADAEABIAFAHQABAFAAAFIAAAAQAAAFgCAFQgCAEgDADQgEAEgFACQgFACgGAAIAAANgAAGAdQAGgBAEgCQADgDAAgFQAAgFgDgCQgDgDgHgDgAgMgeQgDADAAAEQAAAFADACQADADAHACIAAgXQgGABgEADg");
	this.shape_18.setTransform(-27,13.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgGAgIAAgZIgZAAIAAgNIAZAAIAAgYIANAAIAAAYIAZAAIAAANIgZAAIAAAZg");
	this.shape_19.setTransform(-39.1,12.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AgQArQgIgCgHgEIAGgMIAMAGQAGACAGAAQAEgBAEgBQAEgBACgDQADgDACgEQABgEABgFIAAgFQgHAHgEACQgCACgEAAIgGABQgGAAgFgCQgHgCgDgEQgFgEgCgGQgDgEAAgHIAAgBQAAgFADgJQACgFAFgEQAEgEAGgDQAFgCAGAAIAGABQADABAEABQAFADAEAFIAAgKIAQAAIAAA1QAAAIgDAHQgCAGgEAFIgFAEIgHADIgOACQgJAAgHgCgAgGgdIgHADQgCADgCAEQgCADAAAEIAAABQAAAEACADQACADACABIAHAEQADABADABQADgBAEgBIAGgEIAFgEQACgDAAgEIAAgBQAAgEgCgDIgFgHIgGgDQgEgCgDAAQgDAAgDACg");
	this.shape_20.setTransform(-51.7,15);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AAPAiIAAgkIgBgIIgDgFIgFgDQgDgBgDgBQgCABgCABQgDABgCADIgEAEIgBAIIAAAkIgPAAIAAhCIAPAAIAAALQAEgGAFgDIAFgCIAGgBQAGAAAEACQAFABADADQADAEACAFQABAFAAAGIAAApg");
	this.shape_21.setTransform(-59.9,13.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgGAuIAAhCIAOAAIAABCgAgHgeIAAgPIAPAAIAAAPg");
	this.shape_22.setTransform(-65.8,12.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AAOAvIgUgdIgJAKIAAATIgPAAIAAhdIAPAAIAAA3IAagdIAUAAIgbAaIAcApg");
	this.shape_23.setTransform(-71,12.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AgCAjIgHgDQgGgCgFgFQgFgFgCgGQgDgHAAgHQAAgGADgGQACgHAFgFQAFgFAGgCIAHgDIAFAAIAJABIAIACQAEACAHAHIgKAKQgEgEgEgCQgEgDgGAAQgDAAgDACQgDACgDADIgEAHQgBAEAAADIAAAAQAAAEABAEIAEAHQADADAEACQACACAEAAQAFAAAFgDQAEgCAEgEIAJAJQgHAHgEADIgIACIgJABg");
	this.shape_24.setTransform(-78.8,14);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgKAhQgHgDgEgFQgFgEgDgHIgCgHIgBgHIAAAAQAAgGADgGQACgHAFgFQAEgFAGgCIAHgDIAFAAIAIAAIAGADQAEACAHAGQAEAFACAHQACAGAAAGIAAAEIgxAAIACAHIAFAGQACACAEABIAFABQAFAAAFgCQAEgCAEgEIAKAIIgGAGIgGAEIgIACIgIABQgGAAgGgCgAARgDIgCgHQgBgEgCgCIgFgEIgHgBIgFABIgFAEQgDACgBADIgCAIIAhAAIAAAAg");
	this.shape_25.setTransform(-86.5,14);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AAPAvIAAgnIgBgHIgDgEIgFgCQgDgCgDAAQgCAAgCACQgDAAgCADIgEADIgBAIIAAAmIgPAAIAAhdIAPAAIAAAlQAEgGAFgDIAFgCIAGgBQAGAAAEACQAFACADADQADAEACAFQABAFAAAEIAAArg");
	this.shape_26.setTransform(-94.4,12.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AgDAuIgJgDIgIgFIgHgFIgFgHIgFgIIgCgIIgBgKIABgIIACgJIAEgHIAGgIIAHgGIAIgEIAJgCIAIgBIALABIAKADQAFACAJAHIgKAMQgGgFgFgDIgHgCIgHgBQgFAAgFACQgGADgEAEQgEAFgCAFQgCAHAAAFIAAAAQAAAGACAGQACAGAEAEQAEAFAGACQAFADAFAAIAHgBIAHgDQAFgCAHgGIAKAKIgHAHIgJAFQgEACgFACIgMAAIgHAAg");
	this.shape_27.setTransform(-103.1,12.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgKAhQgHgDgEgFQgFgEgDgHIgCgHIgBgHIAAAAQAAgGADgGQACgHAFgFQAEgFAGgCIAHgDIAFAAIAIAAIAGADQAEACAHAGQAEAFACAHQACAGAAAGIAAAEIgxAAIACAHIAFAGQACACAEABIAFABQAFAAAFgCQAEgCAEgEIAKAIIgGAGIgGAEIgIACIgIABQgGAAgGgCgAARgDIgCgHQgBgEgCgCIgFgEIgHgBIgFABIgFAEQgDACgBADIgCAIIAhAAIAAAAg");
	this.shape_28.setTransform(-115.9,14);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("AgKAhQgHgDgEgFQgFgEgDgHIgCgHIgBgHIAAAAQAAgGADgGQACgHAFgFQAEgFAGgCIAHgDIAFAAIAIAAIAGADQAEACAHAGQAEAFACAHQACAGAAAGIAAAEIgxAAIACAHIAFAGQACACAEABIAFABQAFAAAFgCQAEgCAEgEIAKAIIgGAGIgGAEIgIACIgIABQgGAAgGgCgAARgDIgCgHQgBgEgCgCIgFgEIgHgBIgFABIgFAEQgDACgBADIgCAIIAhAAIAAAAg");
	this.shape_29.setTransform(-123.7,14);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgTAiIAAhCIAQAAIAAAPIADgGIAEgGQADgDAEAAIAJgBIAAAQIgBAAQgGAAgEACQgEABgDAEQgCAEgBAEQgCADAAAHIAAAag");
	this.shape_30.setTransform(-130,13.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AggAtIAAhZIBBAAIAAAOIgyAAIAAAZIAsAAIAAANIgsAAIAAAlg");
	this.shape_31.setTransform(-136.9,12.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-161.5,5,319,17);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border468x60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgkegEmMBI9AAAIAAJNMhI9AAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-234.5,-30.5,469,61);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AByHMIAAq/IQyAAIAAK/g");
	mask.setTransform(118.9,46.1);

	// pic
	this.instance = new lib.Freeer336x280();
	this.instance.parent = this;
	this.instance.setTransform(102,17,0.473,0.473);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(247.6,75.8,1,1,-90,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(130.3,-92.2,127.3,336);


// stage content:
(lib.SCU201708_Freeer_468x60_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_179 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(179).call(this.frame_179).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(451,41,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,1.393,0.214);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},180).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(385,53.9,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(220,51.2,1.11,1.11,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border468x60();
	this.instance_2.parent = this;
	this.instance_2.setTransform(234,30);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},180).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(16.7,30,0.851,0.851,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({x:-76.3},9).to({_off:true},1).wait(91));

	// HEAD
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(390.5,34,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({x:296.5},9).wait(80).to({x:442.5},9).to({_off:true},2).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(280.5,67,1,1,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90).to({_off:false},0).wait(79).to({x:426.6},9).to({_off:true},2).wait(1));

	// shad
	this.instance_6 = new lib.HTML5rastershad_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(155,45,1,1,-90,0,0,0,10);
	this.instance_6.alpha = 0.199;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(146.5,124.8,0.872,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(80).to({regX:167.9,scaleX:0.68,x:112.6},9).wait(80).to({x:258.6},9).to({_off:true},2).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(71.7,51,0.716,0.716,0,0,0,0,2.6);

	this.instance_9 = new lib._2016TAG();
	this.instance_9.parent = this;
	this.instance_9.setTransform(394.1,51.2,0.716,0.716,0,0,0,0,2.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_9},{t:this.instance_8}]},81).to({state:[]},99).wait(1));

	// logo
	this.instance_10 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(237.4,55.6,0.771,0.771,0,0,0,215.2,63.1);

	this.instance_11 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_11.parent = this;
	this.instance_11.setTransform(559.8,55.8,0.771,0.771,0,0,0,215.2,63.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_11},{t:this.instance_10}]},81).to({state:[]},99).wait(1));

	// logo rule
	this.instance_12 = new lib._2016_SCU_logoruleai();
	this.instance_12.parent = this;
	this.instance_12.setTransform(136.4,42.8,0.797,0.797,0,0,0,81.4,0.5);

	this.instance_13 = new lib._2016_SCU_logoruleai();
	this.instance_13.parent = this;
	this.instance_13.setTransform(458.8,43,0.797,0.797,0,0,0,81.4,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_13},{t:this.instance_12}]},81).to({state:[]},99).wait(1));

	// shad
	this.instance_14 = new lib.HTML5rastershad_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(425.2,71,1,1,-90,0,0,0,10);
	this.instance_14.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(80).to({x:331},9).to({_off:true},91).wait(1));

	// logo box
	this.instance_15 = new lib.box1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(209,19.8,1.393,0.429,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({_off:true},180).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(209.8,-67,492.2,336.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;