(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497567330515", id:"HTML5rastershad"},
		{src:"images/YourPlace160x600.jpg?1497567330515", id:"YourPlace160x600"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.YourPlace160x600 = function() {
	this.initialize(img.YourPlace160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,177);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZBxIAAgsIApAAIAAAsgAgQAqIgGgyIABgBQAPgBAKgDQALgCAHgFQAHgEAEgHQADgGAAgIIAAAAQAAgIgCgFQgDgGgEgEQgFgDgHgDQgHgCgIAAQgNAAgNAHQgNAGgMAMIgYgaIAPgOQAJgGAJgFQAKgFALgDQALgCALAAQAQAAAOAFQAOAEAKAIQAKAJAFAMQAGANAAAOIAAABQAAAOgFAMQgFALgJAIQgJAGgMAFQgLAEgOADIgDAZg");
	this.shape.setTransform(-54,99.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfBRQgYgKgLgJIASgbQANALAPAFQAOAGALgBQAMAAAHgEQAHgGAAgIIAAgBQAAgIgLgGIgZgJQgZgIgKgGQgIgGgFgHQgEgJAAgMIAAgBQAAgLAEgKQAFgJAIgHQAIgGALgEQALgEALAAQAPAAARAGQAQAFAOAIIgPAcQgNgIgMgEQgNgEgKAAQgJAAgHAEQgGAFAAAIIAAAAQAAAJAMAFQAGADASAHIATAHQAKAEAHADQAIAHAEAHQAFAJAAALIAAAAQAAANgFAKQgFAKgIAHQgJAGgLAEQgMADgNAAQgQAAgTgGg");
	this.shape_1.setTransform(-69.5,102.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgwBWIAAinIAnAAIAAAmQAEgKAFgHQAEgIAIgGQAHgFAJgDQAKgDALABIAAApIgDAAQgMAAgLAEQgLAEgHAIQgGAJgEAMQgEALAAAQIAABBg");
	this.shape_2.setTransform(-83.1,102);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgoBRQgLgEgIgJQgIgIgDgMQgEgMgBgPIAAhqIAnAAIAABeQAAAKACAIQADAHAFAGQAEAFAHADQAHACAIAAQAGAAAHgDQAHgCAGgGQAFgFADgIQACgIAAgJIAAheIAnAAIAACnIgnAAIAAgaQgJAOgLAHQgHAEgIACQgGADgKAAQgNAAgMgFg");
	this.shape_3.setTransform(-100.4,102.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRBWIgRgFQgQgHgNgMQgMgMgHgQIgFgQIgBgSIAAAAQgBgKAIgXQAGgPANgNQAMgMAQgHIARgFIARgCQANAAAXAHQAQAHAMAMQAMAMAHAQQAGAWABALIAAAAIgCARIgFARQgHAPgMANQgMAMgQAHQgYAHgMAAgAgUgxQgJAEgHAIQgGAHgEAKQgDAKgBAKIAAAAQABAKADAKQAEAKAHAIQAHAHAJAEQAJAFAKAAQALAAAKgFQAJgEAHgHQAHgHADgKQAEgKAAgLIAAAAQAAgJgEgKQgEgKgGgIQgIgHgJgEQgKgFgKAAQgKAAgKAEg");
	this.shape_4.setTransform(-120.8,102.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgwBWIAAinIAnAAIAAAmQAEgKAFgHQAEgIAIgGQAHgFAJgDQAKgDALABIAAApIgDAAQgMAAgLAEQgLAEgHAIQgGAJgEAMQgEALAAAQIAABBg");
	this.shape_5.setTransform(-30.7,68);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgRBWIgSgFQgPgHgNgMQgMgMgHgQIgFgQIgCgSIAAAAQAAgKAIgXQAGgPANgNQALgMARgHIARgFIARgCQANAAAXAHQAQAHAMAMQAMAMAHAQQAGAWAAALIAAAAIgBARIgFARQgHAPgMANQgNAMgQAHQgXAHgMAAgAgUgxQgJAEgHAIQgHAHgDAKQgEAKAAAKIAAAAQAAAKAEAKQAEAKAHAIQAHAHAJAEQAKAFAJAAQALAAAKgFQAKgEAGgHQAHgHADgKQAEgKAAgLIAAAAQAAgJgEgKQgDgKgIgIQgHgHgJgEQgKgFgKAAQgKAAgKAEg");
	this.shape_6.setTransform(-48.6,68.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgcBRQgPgGgMgMQgMgLgHgQIgFgRIgBgTIAAAAQAAgRAGgQQAGgQALgMQALgMAPgHIAQgFIAPgCQAKAAAJACQAJACAIAEQAKAEAPAPQAKANAFARQAFAQAAAQIAAALIh6AAQABAKAEAIQAFAIAGAGQAGAFAJADQAIADAHAAQAOAAALgFQAKgFALgKIAXAUQgHAHgHAGQgHAGgIAEQgJAEgKACQgKADgMAAQgQAAgQgHgAArgKQgBgKgDgIQgEgIgFgGQgFgGgIgEQgIgDgJAAQgHAAgHADQgIADgFAGQgGAGgEAIQgEAJgBAKIBVAAIAAAAg");
	this.shape_7.setTransform(-78.3,68.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgIBWIgQgFQgQgHgMgMQgMgMgGgQQgHgQAAgSIAAAAQAAgQAHgRQAGgPAMgMQAMgNAQgHIARgFQAHgCAJAAQAMAAAKACQAJACAJAEQALAGARAPIgYAaQgKgKgKgFQgKgGgOAAQgJAAgJAEQgIAFgHAHQgHAHgDAKQgEAKAAAKIAAAAQAAALAEAKQADAJAHAIQAHAHAJAEQAIAFALAAQANAAALgGQAKgFAJgKIAYAXQgSARgLAGQgIAEgKACQgKADgMAAg");
	this.shape_8.setTransform(-96.4,68.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglBTQgLgDgJgHQgJgGgEgKQgFgKAAgMIAAgBQAAgNAFgLQAFgKAKgFQAIgHANgDQANgDAQAAQAQAAAbAHIAAgFQAAgJgDgGQgCgHgGgFQgFgFgHgCQgIgCgIAAQgOAAgMADQgKACgNAFIgKgeQAPgHANgDQARgEAQAAQAUAAANAFQAOAFAKAJQAIAJAFANQAFANAAARIAABiIgmAAIAAgVQgKALgMAHQgSAHgNAAQgMAAgKgEgAgOAGQgIACgFAEQgEADgEAGQgCAFAAAGIAAABQAAAMAKAHQAJAHAOAAQAIAAAHgDQAJgDAGgEQAGgFADgHQAEgHAAgIIAAgLQgXgHgQAAQgGAAgIACg");
	this.shape_9.setTransform(-115.5,68.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSB0IAAjnIAlAAIAADng");
	this.shape_10.setTransform(-129,64.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhWBvIAAjaIAnAAIAAAcQAKgPANgIQAHgEAIgCQAJgDAIAAQAPABAOAFQAPAGAKALQAMAMAGAQQAHAXAAAOIAAABIgCATIgFAQQgGAQgLALQgLAMgPAFQgNAHgQgBQgIAAgJgCQgIgCgHgFQgNgHgKgNIAABNgAgShJQgIAEgHAHQgHAIgEAJQgEALAAALIAAABQAAALAEALQAEAIAHAHQAHAHAIAEQAJAEAJAAQAJAAAJgEQAJgEAGgGQAHgIAEgIQADgKAAgMIAAgBQAAgLgDgLQgEgKgHgHQgGgHgJgEQgJgEgJAAQgJAAgJAEg");
	this.shape_11.setTransform(-143.9,70.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgwBWIAAinIAnAAIAAAmQAEgKAFgHQAEgIAIgGQAHgFAJgDQAKgDALABIAAApIgDAAQgMAAgLAEQgLAEgHAIQgGAJgEAMQgEALAAAQIAABBg");
	this.shape_12.setTransform(-59.7,34);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgoBRQgLgEgIgJQgHgIgFgMQgEgMAAgPIAAhqIAnAAIAABeQAAAKADAIQACAHAEAGQAFAFAHADQAHACAIAAQAGAAAHgDQAIgCAEgGQAGgFACgIQADgIABgJIAAheIAnAAIAACnIgnAAIAAgaQgKAOgMAHQgGAEgHACQgHADgJAAQgOAAgMgFg");
	this.shape_13.setTransform(-77,34.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgSBWIgRgFQgPgHgNgMQgMgMgHgQIgFgQIgCgSIAAAAQABgKAGgXQAHgPAMgNQANgMAQgHIARgFIARgCQANAAAXAHQAQAHAMAMQANAMAGAQQAHAWgBALIAAAAIgBARIgFARQgHAPgMANQgMAMgRAHQgXAHgMAAgAgUgxQgJAEgHAIQgHAHgDAKQgEAKABAKIAAAAQgBAKAEAKQAEAKAHAIQAHAHAJAEQAJAFAKAAQALAAAKgFQAKgEAGgHQAHgHAEgKQADgKAAgLIAAAAQAAgJgEgKQgDgKgIgIQgGgHgKgEQgKgFgKAAQgKAAgKAEg");
	this.shape_14.setTransform(-97.3,34.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTBvIAAhYIhYiGIAuAAIA9BjIA/hjIAtAAIhZCFIAABZg");
	this.shape_15.setTransform(-114.7,31.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,15,160,104);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("EgMfAo7MAAAhR2IY/AAMAAABR2g");
	this.shape.setTransform(80,262);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgTAyQgPgGgGgGIAKgQQAJAGAJAEQAJADAGAAQAIAAAEgDQAFgDAAgFIAAgBQAAgFgIgEIgOgGQgRgEgFgEQgGgDgCgFQgDgFAAgIQAAgHADgGQADgGAFgFQAFgEAHgCQAGgCAHAAQAJAAALADQAKADAIAGIgJARQgIgFgIgCQgIgDgGAAQgFAAgEADQgEADAAAEIAAABQAAAFAHAEIAPAGIAMAEIAKAEQAFAEADAFQACAFAAAHIAAAAQAAAIgCAHQgDAGgFAEQgGAEgHACQgHACgIAAQgKAAgMgEg");
	this.shape.setTransform(40.9,78.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgRAzQgJgEgIgIQgHgHgEgKIgEgKIgBgMIAAAAQABgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIADALQADAKABAJIgBAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgFgCQgEgCgGAAQgEAAgEACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_1.setTransform(30.1,78.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AAXBIIAAg7QAAgHgBgFQgCgCgDgDQgDgEgEgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCADQgCAFABAGIAAA7IgZAAIAAiQIAZAAIAAA5QAFgJAHgEQAFgCAEgCQAEgCAFAAQAKAAAGAEQAHACAFAGQAFAFACAHQADAIAAAHIAABDg");
	this.shape_2.setTransform(17.9,76.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgEA2IgLgEQgJgEgIgHQgHgIgEgKQgEgKAAgLIAAAAQAAgKAEgKQAEgKAHgHQAIgIAKgEIAKgDQAEgCAGAAQAHAAAGACIALAEQAHADALAKIgPAQQgGgHgGgDQgHgDgJAAQgFAAgFACQgFADgEAFQgFAEgCAGQgCAGAAAGIAAAAQAAAHACAGQACAGAFAFQAEAEAGADQAEACAGAAQAJAAAHgDQAGgDAGgHIAOAPQgKALgHADIgMAEQgGACgIAAg");
	this.shape_3.setTransform(6,78.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AAXA1IAAg5QAAgHgCgFQgBgEgDgDQgDgEgEgCQgFgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFQgCAFAAAGIAAA5IgYAAIAAhnIAYAAIAAAQQAGgJAIgEQADgCAFgCQAEgCAFAAQAJAAAIAEQAGACAFAGQAFAFADAHQACAIAAAJIAABBg");
	this.shape_4.setTransform(-5.9,78.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AgXA0QgHgCgFgEQgFgFgDgGQgDgFAAgJIAAAAQAAgIADgGQADgHAGgCQAGgFAIgBQAIgDAKAAQAJAAARAEIAAgCQAAgFgCgFQgBgEgEgDQgDgDgFgCQgFgBgEAAQgJAAgHACIgOAEIgHgSQAKgEAIgDQAKgCAKAAQAMAAAJADQAIADAGAGQAGAGADAIQACAIAAALIAAA8IgXAAIAAgNQgGAHgIAEQgLAEgIAAQgHAAgHgCgAgIAEQgFABgDADQgDACgCADQgBADAAAEIAAAAQAAAIAGAFQAFADAJAAQAEABAFgCQAFgBAEgEQAEgDACgEQACgEAAgFIAAgHQgOgFgKAAQgDAAgFACg");
	this.shape_5.setTransform(-18.3,78.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AgeA1IAAhnIAZAAIAAAXQACgGADgEQACgFAFgEQAFgDAFgCQAGgCAIABIAAAZIgCAAQgIAAgHADQgGACgFAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_6.setTransform(-27,78.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("Ag5BFIAAiJIA9AAQAMAAAJACQAKAEAGAGQAEAFADAFQACAGAAAHIAAABQAAAGgCAEQgBAFgDAEQgFAHgJAEIALAEIAJAHQAEAEACAFQACAGAAAGIAAABQAAAJgEAIQgDAHgHAEQgHAFgKADQgJACgMAAgAghAwIAnAAIAMgBQAFgBADgDQAEgDABgDQACgEAAgEIAAgBQAAgEgCgEQgBgEgEgCIgJgDIgNgBIglAAgAghgKIAhAAIAKgBIAIgDQAEgDACgDQABgEAAgFIAAAAQAAgEgBgEIgFgFIgIgEIgKgBIgiAAg");
	this.shape_7.setTransform(-38.4,77);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgDgKIAAgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCQAGAAAGACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgGACQgEACgDAEIgGAJQgDAFAAAGIA0AAIAAAAg");
	this.shape_8.setTransform(69.4,56.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgEA2IgLgEQgJgEgIgHQgHgIgEgKQgEgKAAgLIAAAAQAAgKAEgKQAEgKAHgHQAIgIAKgEIAKgDQAEgCAGAAQAHAAAGACIALAEQAHADALAKIgPAQQgGgHgGgDQgHgDgJAAQgFAAgFACQgFADgEAFQgFAEgCAGQgCAGAAAGIAAAAQAAAHACAGQACAGAFAFQAEAEAGADQAEACAGAAQAJAAAHgDQAGgDAGgHIAOAPQgKALgHADIgMAEQgGACgIAAg");
	this.shape_9.setTransform(58,56.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgLBIIAAhnIAXAAIAABngAgLgwIAAgXIAYAAIAAAXg");
	this.shape_10.setTransform(49.4,54.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AgJA1IgshpIAaAAIAbBMIAchMIAaAAIgrBpg");
	this.shape_11.setTransform(40.5,56.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_12.setTransform(31,56.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgRAzQgKgEgHgIQgIgHgDgKIgDgKIgCgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCQAGAAAGACIAKADQAHADAJAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_13.setTransform(20.4,56.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AgKBGIgPgEIgOgHIgOgKIAPgRQAHAFAOAIQAFACAGACIAKABIALgBIAHgEQAEgDABgDQACgDAAgEIAAAAQAAgEgBgDIgFgGQgDgCgHgCIgNgFIgUgFQgJgEgGgCQgGgGgDgGQgDgHAAgJIAAgBQAAgJAEgHQADgIAGgFQAHgGAJgDQAIgDAKAAIANABIANAEQAJADAPAKIgOASQgJgGgKgEQgJgDgIAAIgJABIgHADQgGAFAAAHIAAAAIABAHIAFAGQAEADAGABIAPAGQALACAIAEQAJADAFADQAGAFADAGQADAHAAAIQAAALgEAHQgDAIgHAGQgHAFgJADQgJACgLAAQgGABgIgCg");
	this.shape_14.setTransform(7.8,55);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgcALIAAgVIA5AAIAAAVg");
	this.shape_15.setTransform(-2.6,55.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgLBJIAAiQIAXAAIAACQg");
	this.shape_16.setTransform(-9.5,54.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AgLBJIAAiQIAXAAIAACQg");
	this.shape_17.setTransform(-15.2,54.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgZAzQgGgDgFgGQgFgFgDgHQgCgIAAgJIAAhBIAYAAIAAA6QAAAGACAFQABAEADAEIAHAFQAFABAEAAQAEAAAEgCQAFgBADgEIAFgIQACgFAAgGIAAg5IAYAAIAABnIgYAAIAAgQQgGAIgIAFQgEADgFABQgDABgFAAQgJAAgIgCg");
	this.shape_18.setTransform(-24.3,56.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgzBGIAAiLIBnAAIAAAXIhOAAIAAAmIBFAAIAAAVIhFAAIAAA5g");
	this.shape_19.setTransform(-36.5,55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AAPBGIAAgfIhEAAIgFgSIBMhaIAVAAIAABYIAUAAIAAAUIgUAAIAAAfgAgcATIArAAIAAg2g");
	this.shape_20.setTransform(-56.5,55);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AgxBHIAAgUIAwgpQAIgIAKgKQAEgEABgFIABgIQAAgFgBgFQgCgEgEgDIgGgEQgFgBgEAAIgHABQgFABgDADQgHAEgJAMIgRgPIAKgLQAFgGAGgEQAGgEAIgCQAHgCAIAAQAKAAAIADQAJADAGAGQAGAFAEAIQADAIAAAKQAAAIgCAGQgCAHgFAGQgEAEgHAHIgRAOIgaAYIBAAAIAAAWg");
	this.shape_21.setTransform(-69.3,54.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgKAxIAAgnIgmAAIAAgUIAmAAIAAgmIAVAAIAAAmIAmAAIAAAUIgmAAIAAAng");
	this.shape_22.setTransform(0,33);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AgaBCQgMgDgKgGIAJgSQAJAFAJADQAJADALAAQAFAAAHgCQAGgCAFgEQAEgEACgGQACgGAAgIIAAgJQgKALgFADQgFADgFABQgFACgFAAQgJAAgJgDQgJgEgGgGQgIgHgDgJQgEgHAAgMQAAgIAEgNQADgJAIgGQAGgHAJgDQAJgEAJAAQAFAAAFACIAKAEQAIAEAHAIIAAgPIAYAAIAABSQAAANgDAKQgEAKgGAGQgEAEgEADIgKAEQgRAEgHAAQgNAAgMgEgAgKguQgGACgEAEQgEAEgDAFQgCAGAAAGIAAAAQAAAHACAFQADAFAEACQAEAEAGACQAFACAFAAQAFAAAGgCQAFgCAFgEQAEgCACgFQADgFAAgHIAAAAQAAgGgDgGQgCgFgEgEIgKgGQgGgCgFAAQgFAAgFACg");
	this.shape_23.setTransform(33.9,14.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AAXA2IAAg7QAAgGgBgFQgCgEgDgEQgDgDgEgBQgFgCgFgBQgDABgFACQgEACgDACQgDAEgCAFQgBAFAAAGIAAA6IgZAAIAAhoIAZAAIAAAQQAFgJAHgDQAFgEAEgBQADgBAGgBQAJAAAIADQAGAEAFAEQAFAGACAIQADAHAAAJIAABCg");
	this.shape_24.setTransform(21.3,12.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgKBIIAAhnIAWAAIAABngAgLgwIAAgXIAXAAIAAAXg");
	this.shape_25.setTransform(12.2,10.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AAUBJIgdguIgPAQIAAAeIgYAAIAAiQIAYAAIAABUIAqgsIAdAAIgpApIArA/g");
	this.shape_26.setTransform(4.2,10.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AAXA2IAAg7QAAgGgBgFQgCgEgDgEQgDgDgEgBQgFgCgFgBQgDABgFACQgEACgDACQgDAEgCAFQgBAFAAAGIAAA6IgZAAIAAhoIAZAAIAAAQQAFgJAHgDQAFgEAEgBQADgBAGgBQAJAAAHADQAHAEAFAEQAFAGACAIQADAHAAAJIAABCg");
	this.shape_27.setTransform(-8.4,12.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgXA0QgHgCgFgEQgFgFgDgFQgDgHAAgIIAAAAQAAgIADgHQADgGAGgDQAGgDAIgCQAIgDAKAAQAJAAARAFIAAgDQAAgFgCgFQgBgEgEgDQgDgDgFgCQgFgBgEAAQgJAAgHACIgOAFIgHgTQAKgFAIgBQAKgDAKAAQAMAAAJADQAIADAGAGQAGAFADAJQACAIAAALIAAA8IgXAAIAAgNQgGAHgIAEQgLAEgIAAQgHAAgHgCgAgIAEQgFABgDADQgDABgCAEQgBADAAAEIAAAAQAAAIAGAEQAFAFAJAAQAEgBAFgBQAFgCAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgKAAQgDAAgFABg");
	this.shape_28.setTransform(-20.8,12.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("Ag5BGIAAiLIA9AAQAMABAJADQAKADAGAGQAEAFADAFQACAGAAAHIAAAAQAAAGgCAGQgBAEgDAFQgFAGgJAFIALACIAJAHQAEAFACAFQACAGAAAHIAAAAQAAAJgEAIQgDAHgHAFQgHAEgKADQgJACgMABgAghAwIAnAAIAMgCQAFgBADgCQAEgDABgDQACgEAAgFIAAAAQAAgEgCgEQgBgDgEgCIgJgFIgNgBIglAAgAghgKIAhAAIAKAAIAIgEQAEgCACgEQABgEAAgEIAAgBQAAgEgBgEIgFgFIgIgEIgKAAIgiAAg");
	this.shape_29.setTransform(-33.2,11);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgRAzQgKgEgHgIQgHgHgFgKIgDgKIgBgMIAAAAQABgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIADALQADAKAAAJIAAAHIhLAAQAAAGADAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgFACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_30.setTransform(62.7,-9.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AgLBJIAAiRIAXAAIAACRg");
	this.shape_31.setTransform(53.8,-11.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#002663").s().p("AgLBIIAAhoIAXAAIAABogAgMgwIAAgXIAZAAIAAAXg");
	this.shape_32.setTransform(48.1,-11.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#002663").s().p("AgFBIQgFgBgFgDQgHgFgHgIIAAARIgYAAIAAiRIAYAAIAAA7QAHgJAIgGQAEgCAFgBQAFgCAFAAQAKAAAIADQAJAEAHAHQAHAHAEAKQAEANAAAJIAAAAIgBAMIgDALQgEAKgHAHQgHAIgJADQgIADgKABQgFgBgFgBgAgKgLQgGADgEAEQgFAEgCAEQgCAHAAAIIAAAAQAAAIACAFQACAHAFAEQAEAFAGACQAFACAFAAQAGAAAFgCQAGgCAEgFQAEgEACgGQADgHAAgHIAAAAQAAgIgDgHQgCgEgEgEQgFgEgFgDQgGgDgFABQgFgBgFADg");
	this.shape_33.setTransform(38.8,-11.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#002663").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAEQAFAFAGADQAGACAFAAQAHAAAGgCQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_34.setTransform(25.3,-9.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#002663").s().p("AAsBGIAAhjIgsBAIAAAAIgrhAIAABjIgYAAIAAiLIAaAAIApBCIAqhCIAaAAIAACLg");
	this.shape_35.setTransform(10.1,-11);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#002663").s().p("AgXBGQgIgDgHgIQgHgHgEgKIgDgLIgBgMIAAAAQAAgJAEgNQAEgKAHgHQAGgHAJgEQAJgDAKAAQAEAAAFACQAGABAEACQAIAFAHAJIAAg6IAYAAIAACRIgYAAIAAgSQgHAJgIAFIgKAEQgFABgEABQgJgBgKgDgAgKgLQgGADgEAEQgEAEgCAEQgDAHAAAIIAAAAQAAAHADAHQACAGAEAEQAEAFAGACQAFACAFAAQAFAAAGgCQAFgCAFgFQAFgEACgHQACgFAAgIIAAAAQAAgIgCgHQgCgEgFgEQgFgEgFgDQgGgDgFABQgFgBgFADg");
	this.shape_36.setTransform(-11.5,-11.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#002663").s().p("AAXA2IAAg6QAAgHgCgEQgBgFgDgDQgDgEgEgCQgEgCgGAAQgDAAgEACQgFADgDADQgDADgCAFQgBAFgBAGIAAA6IgYAAIAAhoIAYAAIAAAQQAGgIAIgFQADgDAFgBQADgBAHAAQAIAAAIADQAGACAFAGQAFAFADAHQACAIAAAJIAABCg");
	this.shape_37.setTransform(-24.1,-9.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#002663").s().p("AgYAzQgIgDgEgGQgFgFgCgHQgDgIAAgJIAAhBIAYAAIAAA6QAAAGABAFQACAEADAEIAHAFQAEABAFAAQAEAAAFgCQAEgBADgEIAFgIQABgFAAgGIAAg5IAZAAIAABnIgZAAIAAgQQgFAIgHAFQgEADgFABQgDABgGAAQgJAAgHgCg");
	this.shape_38.setTransform(-36.6,-9.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#002663").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAEQAFAFAGADQAGACAFAAQAHAAAGgCQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_39.setTransform(-49.3,-9.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#002663").s().p("AgKBGIgPgEIgOgHIgOgKIAPgSQAHAHAOAHQAFADAGAAIAKABIALgBIAHgDQAEgDABgDQACgDAAgEIAAgBQAAgEgBgCIgFgGQgDgCgHgCIgNgFIgUgGQgJgDgGgDQgGgFgDgGQgDgHAAgKIAAAAQAAgJAEgIQADgHAGgFQAHgGAJgDQAIgCAKAAIANABIANADQAJADAPAKIgOATQgJgIgKgDQgJgDgIgBIgJABIgHAEQgGAFAAAHIAAAAIABAIIAFAFQAEACAGACIAPAGQALACAIADQAJAEAFADQAGAEADAHQADAGAAAJQAAALgEAHQgDAIgHAGQgHAFgJACQgJAEgLAAIgOgCg");
	this.shape_40.setTransform(-62.4,-11);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79.5,-22,159,112);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.5,-300.5,161,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.YourPlace160x600();
	this.instance.parent = this;
	this.instance.setTransform(-80,-11);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,176,1,1,0,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,-11,336,197);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201706_YourPlace_160x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(142,448,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.476,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.parent = this;
	this.instance.setTransform(80,586.9,1.35,1.35,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border160x600();
	this.instance_1.parent = this;
	this.instance_1.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},164).wait(1));

	// PIC
	this.instance_2 = new lib.pic();
	this.instance_2.parent = this;
	this.instance_2.setTransform(230,57,1,1,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},164).wait(1));

	// CTA
	this.instance_3 = new lib.CTA();
	this.instance_3.parent = this;
	this.instance_3.setTransform(963.5,628,5,5,0,0,0,119.5,40);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(71).to({_off:false},0).to({scaleX:1,scaleY:1,x:199.5,y:394},4).to({_off:true},89).wait(1));

	// HEAD
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(1223.5,335,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1,scaleY:1,x:288.5,y:211},4).to({_off:true},160).wait(1));

	// head bkgd
	this.instance_5 = new lib.headbkgd();
	this.instance_5.parent = this;
	this.instance_5.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({_off:true},164).wait(1));

	// tag
	this.instance_6 = new lib._2016TAGvert();
	this.instance_6.parent = this;
	this.instance_6.setTransform(80.1,546.9,1.35,1.35,0,0,0,0,2.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_7 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(272.9,550.1,0.897,0.897,0,0,0,215.2,63.1);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_8 = new lib._2016_SCU_logoruleai();
	this.instance_8.parent = this;
	this.instance_8.setTransform(155.6,535.1,0.927,0.927,0,0,0,81.5,0.5);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_9 = new lib.HTML5rastershad_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_9.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:true},164).wait(1));

	// logo box
	this.instance_10 = new lib.box1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},164).wait(1));

	// com
	this.instance_11 = new lib.comhoriz();
	this.instance_11.parent = this;
	this.instance_11.setTransform(80.1,585.7,0.8,0.8,0,0,0,0.1,0.9);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(17.1,232.1,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-144,289,800,806);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;