(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497568986004", id:"HTML5rastershad"},
		{src:"images/Teensy336x280.jpg?1497568986004", id:"Teensy336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Teensy336x280 = function() {
	this.initialize(img.Teensy336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACPAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgFAAgFgCgAAwAXQgFgFAAgGQAAgIAFgEQAGgCAJAAQAFAAAKACIAAgBQAAgNgPAAQgGAAgHAEIgDgGQAJgEAIAAQAKAAAGAFQAEAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgFgDgAAyALQAAAKAMAAQAGAAAFgEQAFgDAAgGIAAgEQgIgCgGAAQgOAAAAAJgAgjAUQgHgHAAgLQABgIAGgHQAGgHAKAAQAJAAAHAHQADAHAAAIIAAADIgjAAQABAHAFAEQAEAEAHAAQAIAAAGgGIAEAEQgHAIgLAAQgKAAgHgGgAgFAAQgBgOgNAAQgHAAgDAEQgFAEgBAGIAeAAIAAAAgAhfAUQgGgHAAgLQAAgJAGgHQAHgGAJAAQAKAAAIAKIAAgcIAHAAIAAA/IgHAAIAAgJQgHAKgLAAQgJAAgHgGgAhZgJQgFAFAAAGIAAAAQAAAIAFAFQAFAFAGAAQAHAAAFgFQAFgFAAgIIAAAAQAAgGgFgFQgFgFgHAAQgHAAgEAFgAiUAUQgHgHABgLQAAgIAFgHQAHgHAJAAQALAAAGAHQAGAHAAAIIgBADIglAAQACAPAOAAQAJAAAHgGIADAEQgHAIgMAAQgKAAgGgGgAh1AAQgCgOgOAAQgFAAgFAEQgDAEgCAGIAfAAIAAAAgAB7AZIAAg/IAHAAIAAA/gABjAZIAAg/IAIAAIAAA/gAAMAZIAAgsIAHAAIAAAMQAHgNAMAAIAAAHIAAAAQgIAAgFAGQgFAGgBAIIAAASgAi1AZIAAgmIgHAAIAAgGIAHAAIAAgEQAAgIADgEQAFgEAFAAIAIABIAAAGIgHgBQgHAAgBAKIAAAEIAPAAIAAAGIgPAAIAAAmg");
	this.shape.setTransform(-36.4,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA+AlIADgFQADABAEABQAGAAADgJIgUgsIAHAAIARAkIAPgkIAHAAIgTAtQgFANgLAAQgGAAgEgCgAE2AXQgGgFAAgHQAAgNAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAEAAAKIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAE3ALQAAAJAMAAQAGABAFgEQAEgDABgGIAAgFQgIgCgGAAQgOAAAAAKgAD7AIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgADNATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgIgHgGAAQgIABgEAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgAAPAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAIgBAGAHQAIAHgBAIIAAABQABALgIAGQgGAHgIAAQgMAAgGgKgAATgJQgEAFAAAFIAAABQAAAHAEAGQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgAhJATQgHgGAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgHgAhEgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAh+ATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAhgAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAjYAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAkNATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgACzAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAilAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgAkfAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAlXAZIAAgsIAHAAIAAAsgAlYgdIAAgIIAIAAIAAAIg");
	this.shape_1.setTransform(20.8,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAPIAAgdIAdAAIAAAdg");
	this.shape.setTransform(227,15.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADAMQAEALAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgGgEgEQgEgEgFgCQgGgDgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_1.setTransform(217.2,11.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBTIAAilIAbAAIAAClg");
	this.shape_2.setTransform(207,9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA8QgHgDgGgEQgGgFgEgHQgDgHAAgJIAAgBQAAgJADgIQAEgHAHgDQAGgFAJgCQAKgDALAAQALAAATAFIAAgDQAAgGgBgFQgCgFgEgDQgEgEgGgBQgFgCgGAAQgJAAgJACIgQAFIgIgVQALgFAKgDQALgCAMAAQAOAAAKADQAKAEAGAGQAHAHADAJQADAKAAAMIAABGIgbAAIAAgPQgHAIgJAEQgMAFgJAAQgJAAgIgCgAgKAEIgJAEQgDADgCAEQgCADAAAFIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAFgDQAEgEACgEQADgFAAgGIAAgIQgRgFgLAAQgEAAgGABg");
	this.shape_3.setTransform(196.6,11.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAKAHAKAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEADAAAGIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_4.setTransform(184.3,11.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAaA9IAAhCQAAgIgCgFQgCgFgCgFQgEgDgEgCQgFgCgHAAQgEAAgFACQgFACgEAEQgDAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAHgKAHgFIALgFQAEgBAHAAQAKAAAIADQAIADAFAGQAGAGADAJQADAIAAALIAABLg");
	this.shape_5.setTransform(164.8,11.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMA9IgNgDQgLgFgJgJQgJgJgFgKIgDgMIgBgNIAAAAQAAgHAEgQQAFgMAJgIQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFALQAFARAAAHIAAAAIgBAMIgEAMQgFALgIAJQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAHADAIQADAGAFAGQAFAFAHADQAGADAHAAQAIAAAHgDQAGgDAFgFQAFgFADgHQACgHAAgIIAAAAQAAgGgDgIQgCgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgHACg");
	this.shape_6.setTransform(150,11.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABMQgHgBgEgFQgFgEgCgGQgDgIAAgKIAAg9IgPAAIAAgZIAPAAIAAghIAaAAIAAAhIAgAAIAAAZIggAAIAAA5QAAAIAEAEQADADAIAAQAJAAAIgEIAAAXQgFADgGACQgGABgIAAQgIAAgEgCg");
	this.shape_7.setTransform(130.7,9.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBTIAAh4IAbAAIAAB4gAgOg3IAAgbIAdAAIAAAbg");
	this.shape_8.setTransform(122.9,9.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGBTIgLgFQgJgFgHgKIAAATIgcAAIAAimIAcAAIAABDQAHgKAJgGIALgFQAGgCAGAAQALAAAKAEQAKAFAIAIQAIAIAEALQAFAPAAAKIAAABIgBAOIgEANQgEALgIAIQgIAIgKAFQgKAEgLAAQgGAAgGgCgAgMgNQgHADgEAFQgGAFgCAFQgDAIAAAIIAAABQAAAIADAIQACAHAGAFQAEAFAHADQAGADAGAAQAGAAAHgDQAGgDAFgFQAFgFACgHQADgIAAgIIAAgBQAAgIgDgIQgCgFgFgFQgFgFgGgDQgHgDgGAAQgGAAgGADg");
	this.shape_9.setTransform(112.2,9.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgoBNQgGgBgHgEIAJgVQAJAEAIABQAGAAADgDQAEgEAEgIIgzh3IAeAAIAgBYIAghYIAdAAIgwB7IgIAPQgEAHgDAFQgEAEgGABQgGACgHAAQgJAAgHgCg");
	this.shape_10.setTransform(90.4,13.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAKAHAKAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEADAAAGIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_11.setTransform(78,11.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAaA9IAAhCQAAgIgBgFQgCgFgEgFQgDgDgFgCQgFgCgGAAQgEAAgFACQgFACgDAEQgEAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAGgKAJgFIAKgFQAEgBAGAAQALAAAIADQAIADAGAGQAFAGADAJQADAIAAALIAABLg");
	this.shape_12.setTransform(65.4,11.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADAMQAEALAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgGgEgEQgEgEgFgCQgGgDgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_13.setTransform(51.3,11.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADAMQAEALAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgGgEgEQgEgEgFgCQgGgDgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_14.setTransform(37.4,11.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAABMQgHgBgEgFQgFgEgCgGQgDgIAAgKIAAg9IgPAAIAAgZIAPAAIAAghIAaAAIAAAhIAgAAIAAAZIggAAIAAA5QAAAIAEAEQADADAIAAQAJAAAIgEIAAAXQgFADgGACQgGABgIAAQgIAAgEgCg");
	this.shape_15.setTransform(25.9,9.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgbA8QgHgDgGgEQgGgFgEgHQgDgHAAgJIAAgBQAAgJADgIQAEgHAHgDQAGgFAJgCQAKgDALAAQALAAATAFIAAgDQAAgGgBgFQgCgFgEgDQgEgEgGgBQgFgCgGAAQgJAAgJACIgQAFIgIgVQALgFAKgDQALgCAMAAQAOAAAKADQAKAEAGAGQAHAHADAJQADAKAAAMIAABGIgbAAIAAgPQgHAIgJAEQgMAFgJAAQgJAAgIgCgAgKAEIgJAEQgDADgCAEQgCADAAAFIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAFgDQAEgEACgEQADgFAAgGIAAgIQgRgFgLAAQgEAAgGABg");
	this.shape_16.setTransform(7.4,11.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgdBMQgOgDgMgHIAKgVQAKAGAKADQAMADAMAAQAGAAAIgCQAHgCAFgFQAFgFACgHQADgHAAgJIAAgJQgLAMgHAEQgFADgGABQgGACgGAAQgLAAgJgEQgLgEgHgHQgJgHgDgLQgGgJAAgNIAAAAQAAgJAGgPQAEgLAIgHQAHgHALgEQAKgEAKAAQAGAAAGABQAGACAFADQAJAFAJAJIAAgSIAbAAIAABfQAAAPgDAMQgFALgHAIQgEAEgGADQgEADgHACQgSAEgJAAQgPAAgNgEgAgMg1QgGACgFAEQgFAFgDAGQgCAGAAAIIAAAAQAAAHACAHQADAGAFACQAFAFAGACQAGACAGAAQAHAAAGgCQAGgCAGgFQAEgCADgGQADgHAAgHIAAAAQAAgIgDgGQgDgGgEgFQgGgEgGgCQgGgDgHAAQgGAAgGADg");
	this.shape_17.setTransform(-13.9,13.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAaA9IAAhCQAAgIgCgFQgCgFgCgFQgEgDgEgCQgGgCgGAAQgEAAgFACQgFACgEAEQgDAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAHgKAHgFIALgFQAEgBAHAAQAKAAAIADQAIADAFAGQAGAGADAJQADAIAAALIAABLg");
	this.shape_18.setTransform(-28.4,11.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgMBTIAAh4IAaAAIAAB4gAgNg3IAAgbIAbAAIAAAbg");
	this.shape_19.setTransform(-38.8,9.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAaBTIAAhEQAAgIgCgFQgBgDgDgFQgEgDgEgCQgGgCgGAAQgEAAgFACQgFACgEAEQgDAEgCADQgCAGAAAHIAABEIgcAAIAAilIAcAAIAABBQAGgKAIgFIALgFQAEgBAHAAQAKAAAIADQAIADAFAGQAGAGADAJQADAIAAAJIAABNg");
	this.shape_20.setTransform(-49.2,9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAABMQgHgBgEgFQgFgEgCgGQgDgIAAgKIAAg9IgPAAIAAgZIAPAAIAAghIAaAAIAAAhIAgAAIAAAZIggAAIAAA5QAAAIAEAEQADADAIAAQAJAAAIgEIAAAXQgFADgGACQgGABgIAAQgIAAgEgCg");
	this.shape_21.setTransform(-61.3,9.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgoBNQgGgBgHgEIAJgVQAJAEAIABQAGAAADgDQAEgEAEgIIgzh3IAeAAIAgBYIAghYIAdAAIgwB7IgIAPQgEAHgDAFQgEAEgGABQgGACgHAAQgJAAgHgCg");
	this.shape_22.setTransform(-72.7,13.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgiA9IAAh3IAcAAIAAAcQADgIADgFIAIgKQAFgEAHgBQAHgCAIAAIAAAdIgCAAQgJAAgHADQgIADgGAGQgDAGgDAJQgDAIAAALIAAAug");
	this.shape_23.setTransform(-83.7,11.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADAMQAEALAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgGgEgEQgEgEgFgCQgGgDgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_24.setTransform(-95.9,11.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgLA9Igyh5IAeAAIAfBYIAhhYIAdAAIgyB5g");
	this.shape_25.setTransform(-109,11.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADAMQAEALAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgGgEgEQgEgEgFgCQgGgDgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_26.setTransform(-122.1,11.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgWA6QgRgIgIgGIANgSQAKAHAKAEQAKADAHAAQAJAAAFgDQAFgEAAgGIAAAAQAAgGgIgFIgRgGQgSgGgHgEQgGgDgDgGQgEgGAAgJIAAAAQAAgJAEgHQADgGAGgFQAGgFAIgDQAHgCAIAAQALAAAMADQALAEAKAHIgLATQgJgFgJgDQgJgDgHAAQgGAAgFADQgEADAAAGIAAAAQAAAGAIAFIARAGIAOAFQAHADAFACQAGAEACAGQAEAGAAAIIAAAAQAAAKgEAHQgDAHgGAFQgGAFgIACQgJACgJAAQgLAAgOgEg");
	this.shape_27.setTransform(-141.9,11.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADAMQAEALAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgGgEgEQgEgEgFgCQgGgDgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_28.setTransform(-154.4,11.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAYBTIgig0IgRASIAAAiIgcAAIAAilIAcAAIAABiIAwg0IAiAAIgxAvIAyBIg");
	this.shape_29.setTransform(-166.7,9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgbA8QgHgDgGgEQgGgFgEgHQgDgHAAgJIAAgBQAAgJADgIQAEgHAHgDQAGgFAJgCQAKgDALAAQALAAATAFIAAgDQAAgGgBgFQgCgFgEgDQgEgEgGgBQgFgCgGAAQgJAAgJACIgQAFIgIgVQALgFAKgDQALgCAMAAQAOAAAKADQAKAEAGAGQAHAHADAJQADAKAAAMIAABGIgbAAIAAgPQgHAIgJAEQgMAFgJAAQgJAAgIgCgAgKAEIgJAEQgDADgCAEQgCADAAAFIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAFgDQAEgEACgEQADgFAAgGIAAgIQgRgFgLAAQgEAAgGABg");
	this.shape_30.setTransform(-181.2,11.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABAA9IAAhCQAAgHgCgHQgBgFgDgEQgDgEgFgBQgFgCgGAAQgFAAgFACQgFABgDAEQgEAFgCAFQgBAGAAAHIAABCIgaAAIAAhCQAAgIgCgGQgCgFgDgEQgDgEgFgBQgEgCgGAAQgGAAgEACQgFACgEAEQgDAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAHgKAHgFIAKgEQAGgCAHAAQAHAAAFABQAGABAEADQAEADADAEIAFAJQAIgKAKgGQAFgDAGgBQAGgBAGAAQAKAAAIADQAIACAGAHQAFAFADAJQADAJAAALIAABLg");
	this.shape_31.setTransform(-198.5,11.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAABMQgHgBgEgFQgFgEgCgGQgDgIAAgKIAAg9IgPAAIAAgZIAPAAIAAghIAaAAIAAAhIAgAAIAAAZIggAAIAAA5QAAAIAEAEQADADAIAAQAJAAAIgEIAAAXQgFADgGACQgGABgIAAQgIAAgEgCg");
	this.shape_32.setTransform(-221.3,9.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgNBQIAAifIAaAAIAACfg");
	this.shape_33.setTransform(-229.4,9.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-264,-3,525,27);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("EgoTAHzIAAvmMBQnAAAIAAPmg");
	this.shape.setTransform(432,50);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(174,0,516,100);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E7E").s().p("AgJALIAAgVIATAAIAAAVg");
	this.shape.setTransform(228.4,8.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E7E").s().p("AgNApQgIgEgGgFQgGgHgDgIIgCgIIgBgJIAAAAQAAgIADgIQACgIAGgGQAFgGAIgDIAIgDIAHgBIAJABIAIADQAGADAHAHQAFAGACAIQAEAJAAAGIgBAGIg8AAQAAAFADAEIAFAHQADADAFABQAEABACAAQAHAAAGgCQAFgDAFgFIALAKIgGAHIgIAFIgJADIgLABQgHAAgIgCgAAVgEIgCgJQgBgFgDgCQgDgDgEgCQgEgCgEAAQgCAAgFACQgDACgDADIgFAHIgCAJIApAAIAAAAg");
	this.shape_1.setTransform(221.6,5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E7E").s().p("AgPAoQgMgFgFgEIAIgNQAIAFAHACQAGADAFAAQAGAAAEgCQADgDAAgEQAAgFgFgDIgMgEQgNgEgFgDQgDgCgCgEQgDgEAAgGQAAgGADgFQACgFADgDQAFgEAFgBQAFgCAFAAQAIAAAIACQAIADAHAEIgIAOQgGgEgGgCQgHgCgEAAQgEAAgDADQgEACAAADIAAABQABAEAFADQADACAJADIAJADIAJADQADADACAEQADAEAAAFIAAABQAAAGgDAFQgCAFgEAEQgFADgFACQgGABgHAAQgHAAgJgDg");
	this.shape_2.setTransform(212.7,5.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E7E").s().p("AgSApQgGgBgEgEQgEgDgCgFQgDgFAAgGQAAgHADgFQACgFAFgCQAFgDAGgCQAGgCAIAAQAIAAANAEIAAgCIgBgIQgCgEgCgCQgDgCgEgBQgEgCgDAAQgHAAgGACIgLAEIgFgPQAHgEAHgBQAIgCAIAAQAJAAAHACQAHACAFAFQAEAFACAGQADAHAAAIIAAAwIgTAAIAAgKQgFAFgGADQgIAEgHAAQgGAAgFgCgAgGADIgHACIgDAFIgCAGIAAAAQAAAGAFAEQAFADAHAAIAHgBIAHgEIAEgGQACgDAAgEIAAgGQgLgDgIAAIgGABg");
	this.shape_3.setTransform(203.9,5.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E7E").s().p("AASA6IAAgwIgBgJQgBgCgCgCIgGgEIgIgBQgCgBgEACQgDABgCADQgDADgCABQgBAEAAAFIAAAwIgTAAIAAhzIATAAIAAAtQAFgGAFgEIAHgDIAIgBQAGAAAGACQAFACAEAFQAFAEABAGQACAGAAAFIAAA2g");
	this.shape_4.setTransform(194.5,4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E7E").s().p("AgDAqIgIgCQgIgEgGgFQgGgGgDgJQgEgHAAgJQAAgHAEgJQADgHAGgGQAGgHAIgDIAIgDIAHgBIALABIAJAEQAGACAIAIIgMANQgFgGgFgCQgFgDgHAAQgEAAgEACQgEADgDADQgEAEgBAFQgCAEAAAFIAAAAQAAAFACAFQABAFAEADQADAFAFABQADACAFAAQAGAAAGgCQAFgDAFgFIAMALQgJAJgGADIgJADIgLABg");
	this.shape_5.setTransform(185.1,5.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E7E").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_6.setTransform(177.8,5.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E7E").s().p("AgTAoQgFgCgEgEQgFgFgBgGQgCgGAAgHIAAg0IATAAIAAAuQAAAFABAEQACAEACACQACADAEABQADACADAAQAEAAADgCIAGgEQACgCACgEIABgJIAAguIATAAIAABTIgTAAIAAgNQgEAHgGADIgIADQgBACgFAAQgHAAgGgDg");
	this.shape_7.setTransform(169.1,5.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E7E").s().p("AgqA3IAAhsIATAAIAAAOQAFgHAHgEIAIgDIAHgBQAIAAAHACQAHADAFAGQAGAGADAIQADALAAAHIAAABIgBAKIgCAGQgDAIgGAGQgFAGgHADQgHADgIAAQgEAAgEgCIgHgDQgHgEgFgGIAAAmgAgIgkQgEACgEAEQgDADgCAFQgCAFAAAGIAAABQAAAGACAEQACAEADADQAEAEAEACQAFACADAAQAEAAAFgCQAEgCADgEQAEgDACgEQACgEAAgGIAAgBQAAgGgCgFQgCgFgEgDQgDgEgEgCQgFgCgEAAQgDAAgFACg");
	this.shape_8.setTransform(159.1,6.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E7E").s().p("AgcA1IgJgDIAHgPQAGAEAFAAQAFAAACgDQADgCADgFIgkhTIAVAAIAWA9IAWg9IAUAAIghBVIgGALIgEAHQgDADgFACIgJABQgFAAgGgCg");
	this.shape_9.setTransform(144,6.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E7E").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_10.setTransform(136.3,5.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E7E").s().p("AgNApQgIgEgGgFQgGgHgDgIIgCgIIgCgJIAAAAQABgIADgIQADgIAFgGQAGgGAHgDIAIgDIAHgBIAJABIAIADQAFADAIAHQAFAGACAIQADAJABAGIgBAGIg8AAQAAAFADAEIAFAHQADADAEABQAEABADAAQAHAAAGgCQAFgDAFgFIALAKIgGAHIgIAFIgKADIgKABQgHAAgIgCgAAVgEIgCgJQgBgFgDgCQgDgDgEgCQgEgCgEAAQgDAAgEACQgDACgDADIgFAHIgCAJIApAAIAAAAg");
	this.shape_11.setTransform(127.8,5.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E7E").s().p("AgHAqIgjhTIAVAAIAVA8IAWg8IAVAAIgiBTg");
	this.shape_12.setTransform(118.7,5.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E7E").s().p("AgNApQgIgEgGgFQgGgHgDgIIgCgIIgBgJIAAAAQAAgIACgIQADgIAGgGQAFgGAIgDIAIgDIAHgBIAJABIAIADQAGADAHAHQAFAGACAIQAEAJAAAGIgBAGIg8AAQAAAFADAEIAFAHQADADAFABQAEABACAAQAHAAAGgCQAFgDAFgFIALAKIgGAHIgIAFIgJADIgLABQgHAAgIgCgAAVgEIgCgJQgBgFgDgCQgDgDgEgCQgEgCgEAAQgCAAgFACQgDACgDADIgFAHIgCAJIApAAIAAAAg");
	this.shape_13.setTransform(109.6,5.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E7E").s().p("AASArIAAguIgBgJQgBgEgDgCIgFgFIgIgBQgCAAgDABQgEACgDADQgCACgBAEQgCAEAAAFIAAAuIgUAAIAAhTIAUAAIAAANQAEgHAHgDIAGgEIAHgBQAIAAAFADQAGACAEAEQADAEADAGQACAGAAAIIAAA0g");
	this.shape_14.setTransform(95,5.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E7E").s().p("AgIAqIgIgCQgJgEgGgFQgGgGgDgJIgCgIIgBgIQgBgEAEgMQADgHAGgGQAHgHAIgDIAJgDIAHgBQAGAAAMAEQAHADAHAGQAGAGADAIQAEALAAAFIAAAAIgBAIIgDAIQgDAJgGAGQgHAFgHAEQgMADgGAAgAgJgYQgFADgDADQgDAEgDAFQgBAEAAAFIAAAAQAAAFACAFQACAEADAEQADAFAGABQAEACAEAAQAGAAAFgCQAEgBAEgFQACgDACgFQACgFAAgFQAAgEgCgFQgCgFgDgEQgDgDgFgDQgFgCgFAAQgFAAgEACg");
	this.shape_15.setTransform(84.8,5.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E7E").s().p("AAXA3QgFgDgEgEQgDgEgCgFQgCgFAAgFIAAgBQAAgFACgGQACgFADgEQAEgEAFgCQAFgCAGAAQAFAAAFACQAFACAEAEQADAEACAFQACAFAAAGQAAAGgCAFQgCAGgDADQgEAEgFADQgFACgGAAQgFAAgFgCgAAZARQgEAEAAAHQAAAHAEAEQADAFAGABQAFgBADgFQAEgEAAgGIAAgBQAAgGgEgFQgDgFgGAAQgFAAgDAFgAgvA4IAsg6IAkg1IAQAAIgtA6IgjA1gAgrgBQgFgCgDgEQgEgEgCgFQgCgFAAgGQAAgGACgFQACgFAEgFQADgDAFgCQAFgDAGAAQAGAAAFADQAFACADADIAFAJQACAGAAAFIAAABQAAAFgCAGQgCAFgDAEQgEAEgEACQgFABgGAAQgGAAgFgBgAgpgnQgDAFAAAGIAAABQAAAHADAFQAEAEAFAAQAFAAAEgEQADgFAAgHQAAgHgDgFQgEgEgFAAQgGAAgDAEg");
	this.shape_16.setTransform(67.9,4.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E7E").s().p("AgLA3IgLgDIgJgFIgJgIIAMgOQAHAHAHADQAIADAGAAQAEABAEgCQAEgBADgDQADgCACgEQABgDAAgFQAAgEgBgEQgCgDgDgDIgHgDIgIgBIgLABIgJADIgMgFIADg4IBBAAIAAASIgwAAIgCAaIAIgCIAIgBQAIAAAHACQAHADAGAEQAFAEADAEQADAIAAAIIAAABQAAAIgDAHQgDAHgFAFQgGAFgIADQgHACgJAAQgFABgGgCg");
	this.shape_17.setTransform(56.1,4.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E7E").s().p("AgJALIAAgVIATAAIAAAVg");
	this.shape_18.setTransform(49.1,8.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E7E").s().p("AACA4IAAhbIgSAGIgEgQIAcgKIANAAIAABvg");
	this.shape_19.setTransform(43.2,4.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E7E").s().p("AASArIAAguIgBgJQgBgEgCgCIgGgFIgIgBQgCAAgDABQgEACgCADQgDACgCAEQgBAEAAAFIAAAuIgUAAIAAhTIAUAAIAAANQAEgHAGgDIAHgEIAHgBQAIAAAFADQAGACAEAEQADAEACAGQACAGABAIIAAA0g");
	this.shape_20.setTransform(30.9,5.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E7E").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_21.setTransform(23,5.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E7E").s().p("AgSApQgGgBgEgEQgEgDgCgFQgDgFAAgGQAAgHADgFQACgFAFgCQAFgDAGgCQAGgCAIAAQAIAAANAEIAAgCIgBgIQgCgEgCgCQgDgCgEgBQgEgCgDAAQgHAAgGACIgLAEIgFgPQAHgEAHgBQAIgCAIAAQAJAAAHACQAHACAFAFQAEAFACAGQADAHAAAIIAAAwIgTAAIAAgKQgFAFgGADQgIAEgHAAQgGAAgFgCgAgGADIgHACIgDAFIgCAGIAAAAQAAAGAFAEQAFADAHAAIAHgBIAHgEIAEgGQACgDAAgEIAAgGQgLgDgIAAIgGABg");
	this.shape_22.setTransform(14.4,5.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E7E").s().p("AgoA4IAAhvIBRAAIAAASIg+AAIAAAdIA2AAIAAAQIg2AAIAAAeIA+AAIAAASg");
	this.shape_23.setTransform(4.9,4.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E7E").s().p("AgJALIAAgVIATAAIAAAVg");
	this.shape_24.setTransform(-7.7,8.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E7E").s().p("AgRA4QgIgDgFgGQgGgGgDgHIgDgJIAAgKIAAAAQAAgIADgJQADgIAGgGQAFgGAIgDQAGgCAIAAIAHABIAIADQAHAEAFAGIAAgtIATAAIAABzIgTAAIAAgOQgFAHgHAEIgIADQgEACgDAAQgIAAgGgDgAgHgIQgFACgEADQgDADgCADQgCAFAAAHIAAAAQAAAGACAFQACAFADAEQAEADAFACQAEACADAAQAEAAAFgCQAFgCADgDQAEgEABgFQACgFAAgGIAAAAQAAgHgCgFQgBgDgEgDQgDgDgFgCQgFgCgEAAQgDAAgEACg");
	this.shape_25.setTransform(-15.4,4.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E7E").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_26.setTransform(-23.2,5.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E7E").s().p("AgSApQgGgBgEgEQgEgDgCgFQgDgFAAgGQAAgHADgFQACgFAFgCQAFgDAGgCQAGgCAIAAQAIAAANAEIAAgCIgBgIQgCgEgCgCQgDgCgEgBQgEgCgDAAQgHAAgGACIgLAEIgFgPQAHgEAHgBQAIgCAIAAQAJAAAHACQAHACAFAFQAEAFACAGQADAHAAAIIAAAwIgTAAIAAgKQgFAFgGADQgIAEgHAAQgGAAgFgCgAgGADIgHACIgDAFIgCAGIAAAAQAAAGAFAEQAFADAHAAIAHgBIAHgEIAEgGQACgDAAgEIAAgGQgLgDgIAAIgGABg");
	this.shape_27.setTransform(-31.8,5.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003E7E").s().p("AgFA4IgKgDQgGgCgEgDIgJgIIgGgIIgFgKIgEgKIgBgMIAAAAIABgKIADgLIAGgKIAGgJIAJgHIAKgFIALgDIAKgCQAHABAHABQAGABAGADQAHACALAKIgNAPQgHgHgHgDIgIgEIgJgBQgGABgHADQgHADgFAFQgFAFgCAIQgDAHAAAHIAAAAQAAAHADAIQACAHAFAGQAFAFAHADQAHADAGAAIAJgBIAIgCQAHgEAIgHIANANIgKAIIgKAGIgMAEQgGACgIgBIgKgBg");
	this.shape_28.setTransform(-42,4.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003E7E").s().p("AARA6IgXglIgNANIAAAYIgTAAIAAhzIATAAIAABEIAhgjIAYAAIgiAgIAjAyg");
	this.shape_29.setTransform(-57,4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003E7E").s().p("AgDAqIgIgCQgIgEgGgFQgGgGgDgJQgEgHAAgJQAAgHAEgJQADgHAGgGQAGgHAIgDIAIgDIAHgBIALABIAJAEQAGACAIAIIgMANQgFgGgFgCQgFgDgHAAQgEAAgEACQgEADgDADQgEAEgBAFQgCAEAAAFIAAAAQAAAFACAFQABAFAEADQADAFAFABQADACAFAAQAGAAAGgCQAFgDAFgFIAMALQgJAJgGADIgJADIgLABg");
	this.shape_30.setTransform(-66.6,5.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003E7E").s().p("AgSApQgGgBgEgEQgEgDgCgFQgDgFAAgGQAAgHADgFQACgFAFgCQAFgDAGgCQAGgCAIAAQAIAAANAEIAAgCIgBgIQgCgEgCgCQgDgCgEgBQgEgCgDAAQgHAAgGACIgLAEIgFgPQAHgEAHgBQAIgCAIAAQAJAAAHACQAHACAFAFQAEAFACAGQADAHAAAIIAAAwIgTAAIAAgKQgFAFgGADQgIAEgHAAQgGAAgFgCgAgGADIgHACIgDAFIgCAGIAAAAQAAAGAFAEQAFADAHAAIAHgBIAHgEIAEgGQACgDAAgEIAAgGQgLgDgIAAIgGABg");
	this.shape_31.setTransform(-76.1,5.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003E7E").s().p("AgtA4IAAhvIAwAAQAJAAAIADQAHACAGAGQADADACAFQACAEAAAGIAAABIgCAJQAAADgDADQgEAFgHAEIAJADQAEACADADQADADACAEQABAFAAAFIAAABQAAAHgDAGQgCAGgGAEQgGAEgHACQgIACgJAAgAgZAmIAeAAIAJgBIAHgDIAEgFQABgCABgFQgBgDgBgDQgCgDgCgBIgIgDIgKgBIgcAAgAgZgHIAZAAIAIgBIAHgDQADgCAAgDQACgDAAgEIAAAAQABgDgCgDQgCgDgCgBIgGgDIgJgBIgZAAg");
	this.shape_32.setTransform(-86,4.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003E7E").s().p("AASA6IAAgwIgBgJQgBgCgCgCIgGgEIgIgBQgCgBgDACQgEABgCADQgDADgCABQgBAEAAAFIAAAwIgUAAIAAhzIAUAAIAAAtQAEgGAGgEIAHgDIAHgBQAIAAAFACQAGACAEAFQADAEACAGQACAGABAFIAAA2g");
	this.shape_33.setTransform(-101.8,4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003E7E").s().p("AgPAoQgMgFgFgEIAIgNQAHAFAHACQAIADAEAAQAGAAAEgCQADgDAAgEQAAgFgGgDIgKgEQgOgEgEgDQgEgCgDgEQgCgEAAgGQAAgGACgFQADgFAEgDQAEgEAFgBQAFgCAFAAQAIAAAIACQAIADAHAEIgHAOQgHgEgGgCQgGgCgFAAQgEAAgDADQgDACAAADIAAABQgBAEAHADQADACAIADIAJADIAIADQAFADACAEQACAEAAAFIAAABQAAAGgCAFQgDAFgEAEQgEADgGACQgFABgIAAQgGAAgKgDg");
	this.shape_34.setTransform(-110.9,5.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003E7E").s().p("AgSApQgGgBgEgEQgEgDgCgFQgDgFAAgGQAAgHADgFQACgFAFgCQAFgDAGgCQAGgCAIAAQAIAAANAEIAAgCIgBgIQgCgEgCgCQgDgCgEgBQgEgCgDAAQgHAAgGACIgLAEIgFgPQAHgEAHgBQAIgCAIAAQAJAAAHACQAHACAFAFQAEAFACAGQADAHAAAIIAAAwIgTAAIAAgKQgFAFgGADQgIAEgHAAQgGAAgFgCgAgGADIgHACIgDAFIgCAGIAAAAQAAAGAFAEQAFADAHAAIAHgBIAHgEIAEgGQACgDAAgEIAAgGQgLgDgIAAIgGABg");
	this.shape_35.setTransform(-119.7,5.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003E7E").s().p("AgFA4IgKgDQgGgCgEgDIgJgIIgGgIIgFgKIgEgKIgBgMIAAAAIABgKIADgLIAGgKIAGgJIAJgHIAKgFIALgDIAKgCQAHABAHABQAGABAGADQAHACALAKIgNAPQgHgHgHgDIgIgEIgJgBQgGABgHADQgHADgFAFQgFAFgCAIQgDAHAAAHIAAAAQAAAHADAIQACAHAFAGQAFAFAHADQAHADAGAAIAJgBIAIgCQAHgEAIgHIANANIgKAIIgKAGIgMAEQgGACgIgBIgKgBg");
	this.shape_36.setTransform(-129.9,4.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003E7E").s().p("AgRA4QgIgDgFgGQgGgGgDgHIgDgJIAAgKIAAAAQAAgIADgJQADgIAGgGQAFgGAIgDQAGgCAIAAIAHABIAIADQAHAEAFAGIAAgtIATAAIAABzIgTAAIAAgOQgFAHgHAEIgIADQgEACgDAAQgIAAgGgDgAgHgIQgFACgEADQgDADgCADQgCAFAAAHIAAAAQAAAGACAFQACAFADAEQAEADAFACQAEACADAAQAEAAAFgCQAFgCADgDQAEgEABgFQACgFAAgGIAAAAQAAgHgCgFQgBgDgEgDQgDgDgFgCQgFgCgEAAQgDAAgEACg");
	this.shape_37.setTransform(-146.3,4.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003E7E").s().p("AASArIAAguIgBgJQgBgEgCgCIgGgFIgIgBQgCAAgEABQgDACgCADQgDACgCAEQgBAEAAAFIAAAuIgUAAIAAhTIAUAAIAAANQAFgHAFgDIAHgEIAHgBQAIAAAFADQAFACAFAEQADAEACAGQACAGAAAIIAAA0g");
	this.shape_38.setTransform(-156.4,5.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003E7E").s().p("AgTAoQgFgCgEgEQgFgFgCgGQgBgGAAgHIAAg0IATAAIAAAuQAAAFABAEQABAEADACQACADADABQAEACADAAQADAAAEgCIAGgEQACgCACgEIABgJIAAguIATAAIAABTIgTAAIAAgNQgFAHgFADIgIADQgCACgEAAQgHAAgGgDg");
	this.shape_39.setTransform(-166.4,5.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003E7E").s().p("AgIAqIgJgCQgHgEgHgFQgGgGgDgJIgDgIIgBgIQAAgEAEgMQADgHAHgGQAGgHAHgDIAJgDIAIgBQAGAAALAEQAJADAGAGQAGAGADAIQAEALgBAFIAAAAIgBAIIgCAIQgDAJgGAGQgGAFgJAEQgLADgGAAgAgJgYQgFADgDADQgDAEgCAFQgCAEAAAFIAAAAQAAAFACAFQACAEADAEQAEAFAEABQAFACAEAAQAFAAAGgCQAEgBADgFQAEgDABgFQACgFAAgFQAAgEgCgFQgCgFgDgEQgEgDgEgDQgFgCgFAAQgEAAgFACg");
	this.shape_40.setTransform(-176.5,5.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003E7E").s().p("AgIA4IgMgDQgGgDgFgDIgLgIIAMgOQAFAEALAHIAJACIAIABIAJgBIAGgCIAEgFIABgFIgBgGIgEgFQgCgBgFgCIgLgEIgQgFQgHgDgFgBQgFgEgCgFQgCgGAAgHQAAgIACgGQADgGAFgEQAGgFAGgBQAIgDAHAAIALABIAKADQAHACALAIIgKAPQgIgGgHgCQgIgEgGAAIgHABIgGADQgFAEAAAGIAAAAIABAFIAFAFIAIAEIALAEIAQAEIALAFQAEAEADAFQACAGAAAGQAAAJgDAGQgDAGgFAEQgGAEgHADQgHACgJAAIgLgBg");
	this.shape_41.setTransform(-187,4.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#003E7E").s().p("AgNApQgIgEgGgFQgGgHgDgIIgCgIIgCgJIAAAAQABgIADgIQADgIAFgGQAGgGAHgDIAIgDIAHgBIAJABIAIADQAFADAIAHQAFAGACAIQADAJABAGIgBAGIg8AAQAAAFADAEIAFAHQADADAEABQAEABADAAQAHAAAGgCQAFgDAFgFIALAKIgGAHIgIAFIgKADIgKABQgHAAgIgCgAAVgEIgCgJQgBgFgDgCQgDgDgEgCQgEgCgEAAQgDAAgEACQgDACgDADIgFAHIgCAJIApAAIAAAAg");
	this.shape_42.setTransform(-201.6,5.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#003E7E").s().p("AASA6IAAgwIgBgJQgBgCgDgCIgFgEIgIgBQgCgBgDACQgEABgDADQgCADgBABQgCAEAAAFIAAAwIgUAAIAAhzIAUAAIAAAtQAEgGAHgEIAGgDIAIgBQAGAAAGACQAGACADAFQAFAEACAGQACAGAAAFIAAA2g");
	this.shape_43.setTransform(-211.3,4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#003E7E").s().p("AgJA4IAAhcIgjAAIAAgTIBZAAIAAATIgjAAIAABcg");
	this.shape_44.setTransform(-221.3,4.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-256,-5,516,20);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364.5,-45.5,729,91);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Teensy336x280();
	this.instance.parent = this;
	this.instance.setTransform(-16,5,0.756,0.756);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(247.6,75.8,1,1,-90,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16,-92.2,273.6,336);


// stage content:
(lib.SCU201706_Teensy_728x90_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_179 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(179).call(this.frame_179).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(707,69,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,2.167,0.321);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},180).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(640,82.7,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(288,80,1.11,1.11,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border728x90();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},180).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(122,38,0.851,0.851,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({x:-76.3},9).to({_off:true},1).wait(91));

	// HEAD
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(564.5,44,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({x:367.5},9).wait(80).to({x:588.5},9).to({_off:true},2).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(367.5,90,1,1,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90).to({_off:false},0).wait(79).to({x:584.5},9).to({_off:true},2).wait(1));

	// shad
	this.instance_6 = new lib.HTML5rastershad_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(221,45,1,1,-90,0,0,0,10);
	this.instance_6.alpha = 0.199;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(80).to({x:-24},9).wait(80).to({x:205},9).to({_off:true},2).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(612.3,77,1.037,1.037,0,0,0,0,2.7);

	this.instance_9 = new lib._2016TAG();
	this.instance_9.parent = this;
	this.instance_9.setTransform(612.3,76.4,1.037,1.037,0,0,0,0,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_8,p:{x:612.3,y:77}}]},81).to({state:[{t:this.instance_9},{t:this.instance_8,p:{x:105.5,y:76.4}}]},88).to({state:[]},11).wait(1));

	// logo
	this.instance_10 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(852.4,83.5,1.116,1.116,0,0,0,215.3,63.1);

	this.instance_11 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_11.parent = this;
	this.instance_11.setTransform(852.4,83,1.116,1.116,0,0,0,215.3,63.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_10,p:{x:852.4,y:83.5}}]},81).to({state:[{t:this.instance_11},{t:this.instance_10,p:{x:345.6,y:83}}]},88).to({state:[]},11).wait(1));

	// logo rule
	this.instance_12 = new lib._2016_SCU_logoruleai();
	this.instance_12.parent = this;
	this.instance_12.setTransform(706,65,1.154,1.154,0,0,0,81.4,0.5);

	this.instance_13 = new lib._2016_SCU_logoruleai();
	this.instance_13.parent = this;
	this.instance_13.setTransform(706,64.5,1.154,1.154,0,0,0,81.4,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_12,p:{x:706,y:65}}]},81).to({state:[{t:this.instance_13},{t:this.instance_12,p:{x:199.3,y:64.5}}]},88).to({state:[]},11).wait(1));

	// shad
	this.instance_14 = new lib.HTML5rastershad_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(700,92,1,1,-90,0,0,0,10);
	this.instance_14.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(80).to({x:508,y:79.1},9).to({_off:true},91).wait(1));

	// logo box
	this.instance_15 = new lib.box1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(324.8,29.5,2.165,0.639,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({_off:true},180).wait(1));

	// EHO
	this.instance_16 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_16.parent = this;
	this.instance_16.setTransform(466.5,75,0.07,0.07,0,0,0,135,145);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(344.8,-44,747.3,349.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;