(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1499363086588", id:"HTML5rastershad"},
		{src:"images/Takeout160x600.jpg?1499363086588", id:"Takeout160x600"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Takeout160x600 = function() {
	this.initialize(img.Takeout160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,210);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAQIAAgfIAdAAIAAAfg");
	this.shape.setTransform(21,126.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgqBQQgHgBgHgEIAKgWQAJAFAIAAQAGAAAFgDQAEgEADgIIg1h8IAgAAIAhBcIAhhcIAfAAIgzCAQgEAKgEAGQgEAHgDAEQgFAFgGACQgGABgIAAQgIAAgIgCg");
	this.shape_1.setTransform(12.6,123.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgcA+QgIgCgGgFQgHgFgDgHQgEgHAAgKIAAgBQAAgJAEgJQAEgHAHgDQAHgFAJgDQAKgCALAAQANgBATAGIAAgDQAAgHgCgFQgCgFgEgDQgEgEgFgCQgGgBgGAAQgKgBgJACQgIACgJAEIgIgXQAMgFAKgCQAMgDAMAAQAOAAALAEQAKAEAHAGQAHAHADAKQAEAKAAAMIAABJIgdAAIAAgPQgHAIgJAFQgNAFgKAAQgJAAgIgDgAgKAFQgGABgEADQgEACgCAEQgCAFAAAEIAAABQAAAJAIAFQAGAFALAAQAFAAAHgCQAGgCAEgDQAFgEACgFQADgFAAgGIAAgJQgRgFgMAAQgFAAgFACg");
	this.shape_2.setTransform(-1.4,121.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbBUQgLgEgIgJQgIgIgFgMIgEgOIgBgOIAAgBQAAgKAFgQQAFgMAIgJQAIgIALgEQAKgFAMAAQAFAAAHACQAGACAGADQAJAGAIAKIAAhEIAdAAIAACtIgdAAIAAgVQgIALgJAFQgGAEgGACQgHABgFAAQgLAAgLgEgAgMgOQgHADgFAFQgFAGgDAFQgDAIAAAJIAAABQAAAJADAHQADAIAFAFQAFAFAHADQAGADAGAAQAHAAAHgDQAGgDAFgFQAGgGACgHQAEgIAAgIIAAgBQAAgJgEgIQgCgFgGgFQgFgGgGgCQgHgDgHAAQgGAAgGACg");
	this.shape_3.setTransform(-16.5,119.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfBQQgPgEgMgHIALgWQALAGAKAEQAMADAMAAQAIAAAHgCQAIgDAFgFQAFgFADgHQACgHAAgKIAAgKQgLANgHAEQgGADgGACQgGACgGAAQgMAAgKgEQgKgEgIgIQgJgIgEgLQgFgJAAgOIAAAAQAAgJAFgQQAEgLAJgIQAIgIAKgEQAKgEAMAAQAGAAAGACIAMAFQAKAFAIAKIAAgTIAdAAIAABjQAAAQgEAMQgEAMgIAIIgKAHIgMAFQgTAFgJAAQgQAAgOgEgAgNg4QgGADgFAEQgFAFgDAGQgDAHAAAIIAAAAQAAAIADAGQADAHAFACQAFAFAGACQAHADAGAAQAHAAAHgDQAGgCAFgFQAGgCACgHQAEgGAAgIIAAAAQAAgIgEgHQgCgGgGgFQgFgEgGgDQgHgCgHAAQgGAAgHACg");
	this.shape_4.setTransform(55.4,97.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAIQADAJAAALIAABPg");
	this.shape_5.setTransform(40.4,95.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBXIAAh9IAbAAIAAB9gAgOg6IAAgcIAdAAIAAAcg");
	this.shape_6.setTransform(29.5,93.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLA/Ig1h9IAgAAIAgBbIAihbIAfAAIg0B9g");
	this.shape_7.setTransform(18.9,95.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAJgJANgFIAMgEIANgCQAJAAASAGQAMAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgBANIgEAMQgFAMgKAJQgJAJgMAFQgRAGgJAAgAgPgkQgHADgFAGQgFAFgCAIQgDAHAAAHIAAAAQAAAIADAHQACAIAGAFQAFAGAHADQAHADAHAAQAIAAAHgDQAHgDAGgGQAEgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgFgGgIgDQgGgDgIAAQgIAAgHADg");
	this.shape_8.setTransform(4.7,95.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABDBAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFACgDAEQgEAEgCAGQgCAGAAAIIAABFIgbAAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFADgDAEQgEAEgCAGQgCAGAAAHIAABFIgdAAIAAh8IAdAAIAAATQAHgKAIgFQAFgEAGgBQAGgCAHAAQAGAAAGACIALAEQAEADACAEQAEAEADAFQAIgLAKgFIALgEQAGgCAHAAQALAAAIADQAIADAGAHQAGAGADAJQADAJAAALIAABPg");
	this.shape_9.setTransform(-14.6,95.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAIQADAJAAALIAABPg");
	this.shape_10.setTransform(-40.6,95.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAJgJAMgFIAOgEIAMgCQAJAAARAGQANAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgBANIgEAMQgFAMgJAJQgJAJgNAFQgSAGgIAAgAgPgkQgGADgGAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAHQAEAIAEAFQAGAGAHADQAHADAHAAQAIAAAHgDQAIgDAEgGQAGgFACgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgHgDQgHgDgHAAQgHAAgIADg");
	this.shape_11.setTransform(-55.9,95.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_12.setTransform(41,68.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeA9QgIgEgGgGQgGgHgDgIQgDgKAAgKIAAhPIAdAAIAABGQAAAHACAGQACAGADADQAEAEAFADQAFABAGAAQAFAAAFgBQAGgDADgEQAEgEACgFQACgGAAgHIAAhGIAeAAIAAB9IgeAAIAAgUQgHAKgIAFIgLAGQgEABgIAAQgKAAgJgDg");
	this.shape_13.setTransform(28.8,70);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAKgJAMgFIAMgEIANgCQAJAAARAGQAMAFAKAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgIAJgNAFQgSAGgIAAgAgPgkQgGADgGAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAHQAEAIAFAFQAFAGAHADQAHADAHAAQAIAAAIgDQAGgDAFgGQAFgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgGgDQgIgDgHAAQgHAAgIADg");
	this.shape_14.setTransform(13.5,69.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_15.setTransform(-1.6,69.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAZBXIgkg3IgSATIAAAkIgdAAIAAitIAdAAIAABmIAzg2IAjAAIgzAyIA1BLg");
	this.shape_16.setTransform(-14.4,67.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcA/QgIgDgGgFQgHgFgDgHQgEgIAAgJIAAAAQAAgLAEgHQAEgIAHgDQAHgFAJgDQAKgCALAAQANAAATAFIAAgDQAAgHgCgFQgCgFgEgEQgEgDgFgCQgGgBgGgBQgKAAgJACQgIACgJAEIgIgWQAMgGAKgCQAMgDAMAAQAOAAALAEQAKAEAHAGQAHAHADAKQAEAJAAANIAABKIgdAAIAAgQQgHAIgJAFQgNAFgKAAQgJAAgIgCgAgKAEQgGACgEADQgEACgCAEQgCAFAAAEIAAABQAAAJAIAFQAGAFALAAQAFAAAHgCQAGgCAEgDQAFgEACgFQADgFAAgGIAAgJQgRgFgMAAQgFAAgFABg");
	this.shape_17.setTransform(-29.5,69.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_18.setTransform(-41.3,68.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbBUQgLgEgIgJQgIgIgFgMIgEgOIgBgOIAAgBQAAgKAFgQQAFgMAIgJQAIgIALgEQAKgFAMAAQAFAAAHACQAGACAGADQAJAGAIAKIAAhEIAdAAIAACtIgdAAIAAgVQgIALgJAFQgGAEgGACQgHABgFAAQgLAAgLgEgAgMgOQgHADgFAFQgFAGgDAFQgDAIAAAJIAAABQAAAJADAHQADAIAFAFQAFAFAHADQAGADAGAAQAHAAAHgDQAGgDAFgFQAGgGACgHQAEgIAAgIIAAgBQAAgJgEgIQgCgFgGgFQgFgGgGgCQgHgDgHAAQgGAAgGACg");
	this.shape_19.setTransform(60,41.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAKgJAMgFIAMgEIANgCQAJAAASAGQAMAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgIAJgNAFQgRAGgJAAgAgPgkQgGADgGAGQgFAFgCAIQgDAHAAAHIAAAAQAAAIADAHQACAIAGAFQAFAGAHADQAHADAHAAQAIAAAIgDQAHgDAEgGQAFgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgGgDQgIgDgHAAQgHAAgIADg");
	this.shape_20.setTransform(44.5,43.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAKgJAMgFIAMgEIANgCQAJAAASAGQAMAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgIAJgNAFQgRAGgJAAgAgPgkQgGADgGAGQgFAFgCAIQgDAHAAAHIAAAAQAAAIADAHQACAIAGAFQAFAGAHADQAHADAHAAQAIAAAIgDQAHgDAEgGQAFgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgGgDQgIgDgHAAQgHAAgIADg");
	this.shape_21.setTransform(28.7,43.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgfBQQgPgEgMgHIALgWQALAGAKAEQAMADAMAAQAIAAAHgCQAIgDAFgFQAFgFADgHQACgHAAgKIAAgKQgLANgHAEQgGADgGACQgGACgGAAQgMAAgKgEQgKgEgIgIQgJgIgEgLQgFgJAAgOIAAAAQAAgJAFgQQAEgLAJgIQAIgIAKgEQAKgEAMAAQAGAAAGACIAMAFQAKAFAIAKIAAgTIAdAAIAABjQAAAQgEAMQgEAMgIAIIgKAHIgMAFQgTAFgJAAQgQAAgOgEgAgNg4QgGADgFAEQgFAFgDAGQgDAHAAAIIAAAAQAAAIADAGQADAHAFACQAFAFAGACQAHADAGAAQAHAAAHgDQAGgCAFgFQAGgCACgHQAEgGAAgIIAAAAQAAgIgEgHQgCgGgGgFQgFgEgGgDQgHgCgHAAQgGAAgHACg");
	this.shape_22.setTransform(12.4,45.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgqBQQgHgBgHgEIAKgWQAJAFAIAAQAGAAAFgDQAEgEADgIIg1h8IAgAAIAhBcIAhhcIAfAAIgzCAQgEAKgEAGQgEAHgDAEQgFAFgGACQgGABgIAAQgIAAgIgCg");
	this.shape_23.setTransform(-9.7,45.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgNBXIAAitIAbAAIAACtg");
	this.shape_24.setTransform(-20.2,41.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgNBXIAAitIAbAAIAACtg");
	this.shape_25.setTransform(-27,41.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgcA/QgIgDgGgFQgHgFgDgHQgEgHAAgKIAAAAQAAgLAEgHQAEgIAHgDQAHgFAJgDQAKgDALAAQANABATAFIAAgDQAAgHgCgFQgCgFgEgEQgEgDgFgCQgGgCgGAAQgKAAgJADQgIABgJAEIgIgWQAMgFAKgDQAMgDAMAAQAOAAALAEQAKAEAHAGQAHAHADAKQAEAJAAANIAABKIgdAAIAAgRQgHAJgJAFQgNAFgKAAQgJAAgIgCgAgKAEQgGACgEADQgEADgCAEQgCADAAAGIAAAAQAAAJAIAFQAGAFALAAQAFAAAHgCQAGgCAEgDQAFgEACgFQADgFAAgGIAAgJQgRgFgMAAQgFAAgFABg");
	this.shape_26.setTransform(-37.8,43.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_27.setTransform(-51.7,43.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_28.setTransform(-62.9,43.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_29.setTransform(30.8,17.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_30.setTransform(18.1,17.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgbBUQgLgEgIgJQgIgIgFgMIgEgOIgBgOIAAgBQAAgKAFgQQAFgMAIgJQAIgIALgEQAKgFAMAAQAFAAAHACQAGACAGADQAJAGAIAKIAAhEIAdAAIAACtIgdAAIAAgVQgIALgJAFQgGAEgGACQgHABgFAAQgLAAgLgEgAgMgOQgHADgFAFQgFAGgDAFQgDAIAAAJIAAABQAAAJADAHQADAIAFAFQAFAFAHADQAGADAGAAQAHAAAHgDQAGgDAFgFQAGgGACgHQAEgIAAgIIAAgBQAAgJgEgIQgCgFgGgFQgFgGgGgCQgHgDgHAAQgGAAgGACg");
	this.shape_31.setTransform(2.5,15.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_32.setTransform(-9.3,17.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgSBUQgIgBgIgEIgPgHQgHgFgGgGIgLgNQgEgHgDgIIgEgPQgCgJgBgJIAAAAQABgIACgHQABgJADgIIAIgPIAKgMIANgLIAPgIQAIgEAJgCQAJgBAIAAQAKAAAIABQAJACAIAEQAIACAHAGQAHAEAGAGIAKANIAIAPQADAHACAJQABAIAAAIIAAAAQAAAIgBAJIgFAQIgIAPQgEAHgHAFQgFAGgHAGIgPAHQgJAEgIABQgJACgJAAQgIAAgKgCgAgVg2QgLAFgHAIQgIAJgEAKQgEALAAALIAAAAQAAALAEALQAEAMAIAHQAHAJALAFQAKAEALAAQAMAAALgEQAKgFAIgIQAHgJAEgKQAFgLAAgMIAAAAQAAgKgFgMQgEgLgHgHQgIgJgKgFQgLgEgMAAQgLAAgKAEg");
	this.shape_33.setTransform(-25,15.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78,3,156,132);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("EgMfAsOMAAAhYbIY/AAMAAABYbg");
	this.shape.setTransform(80,262,1,0.926);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgNAPIAAgdIAbAAIAAAdg");
	this.shape.setTransform(30.6,114.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgVA3QgQgHgIgFIAMgSQAKAGAKAEQAJAEAHgBQAJABAEgEQAFgDAAgGIAAAAQAAgHgIgDIgPgHQgSgFgIgEQgFgDgDgFQgDgHAAgIQAAgIADgHQADgGAGgFQAGgEAHgDQAIgDAHAAQAKAAALAEQAMADAJAHIgLATQgIgFgJgEQgIgCgHAAQgGAAgFACQgDAEAAAFIAAAAQAAAGAIAEQAEADAMAEIAMAEQAHAEAFABQAFAEADAFQADAHABAHIAAAAQgBAJgDAHQgDAHgGAFQgGAEgHACQgJADgIAAQgLAAgNgFg");
	this.shape_1.setTransform(22,109.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AAABIQgGgBgFgEQgEgEgDgGQgCgHAAgJIAAg8IgPAAIAAgWIAPAAIAAghIAZAAIAAAhIAfAAIAAAWIgfAAIAAA3QAAAHADAFQAEADAHAAQAJAAAHgEIAAAVQgFADgFACQgGACgIAAQgHAAgEgDg");
	this.shape_2.setTransform(12,108.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgVA3QgQgHgIgFIAMgSQAKAGAKAEQAJAEAHgBQAJABAEgEQAFgDAAgGIAAAAQAAgHgIgDIgQgHQgRgFgIgEQgFgDgDgFQgDgHAAgIQAAgIADgHQADgGAGgFQAGgEAHgDQAIgDAHAAQAKAAAMAEQALADAJAHIgLATQgIgFgJgEQgIgCgHAAQgGAAgFACQgDAEAAAFIAAAAQAAAGAIAEQAEADAMAEIANAEQAGAEAFABQAFAEADAFQADAHABAHIAAAAQgBAJgDAHQgDAHgGAFQgGAEgHACQgJADgIAAQgLAAgNgFg");
	this.shape_3.setTransform(2.2,109.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgMA7IgLgEQgLgEgJgIQgIgJgFgKIgDgMIgBgMIAAAAQAAgHAEgPQAFgLAIgIQAJgJALgEIAMgEIALgBQAJAAAPAFQALAFAJAHQAIAJAFALQAEAPAAAHIAAAAIgBALIgDAMQgFALgIAIQgJAJgLAEQgQAFgIAAgAgNghQgHADgEAFQgFAFgCAHQgDAGAAAHIAAAAQAAAHADAHQACAHAFAFQAFAFAGADQAHADAGAAQAHAAAHgDQAHgDAEgFQAFgFACgGQADgIAAgHIAAAAQAAgGgDgHQgCgHgFgFQgFgFgGgDQgHgDgHAAQgHAAgGADg");
	this.shape_4.setTransform(-10.4,109.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgHBOIgPgFIgNgHQgHgFgFgFIgJgLIgHgOQgDgHgBgIIgCgQIAAAAIACgPQABgHADgIQACgGAFgHQAEgGAFgFIALgKQAHgFAIgDQAGgDAJgCIAOgBQAKAAAKABIAPAGQALAEAOANIgRAUQgKgJgKgFIgKgEQgHgCgGABQgJgBgJAFQgKAEgGAIQgHAHgEAKQgEAKABAKIAAAAQgBAKAEAKQAEAKAHAIQAGAIAKAEQAJAEAJAAQAHAAAGgBQAGgBAFgDQAKgEAKgKIASARIgMALQgIAGgHADQgHADgJADQgJABgLAAQgHAAgHgBg");
	this.shape_5.setTransform(-25.2,107.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgcBJQgOgDgLgHIAKgVQAKAHAKADQAKADAMAAQAGAAAHgCQAHgCAFgFQAEgEADgHQACgHAAgIIAAgJQgKALgHAEQgFADgGABQgFACgGAAQgKAAgJgEQgKgEgHgGQgIgIgEgJQgFgJAAgNIAAAAQAAgJAFgOQAEgKAIgHQAHgHAKgEQAJgDAKgBQAGABAGABIALAFQAIAEAIAJIAAgRIAbAAIAABbQAAAOgEALQgEAKgHAIQgEAEgFADIgLAFQgRAEgJgBQgOABgNgEgAgMgzQgGADgEAEQgFAEgCAGQgDAGAAAHQAAAHADAGQACAGAFADQAFADAGACQAGADAFAAQAGAAAHgDQAGgCAEgDQAFgDADgGQACgGAAgHQAAgHgCgGQgDgGgFgEQgEgEgGgDQgHgCgGAAQgGAAgGACg");
	this.shape_6.setTransform(33.6,87.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AAZA7IAAhAQAAgHgCgFQgCgGgDgDQgDgEgFgCQgEgCgGAAQgEAAgEACQgFACgEAEQgEAEgCAFQgBAGAAAGIAABAIgbAAIAAhyIAbAAIAAARQAGgJAIgFQAFgDAFgBQAEgCAGAAQAKAAAHADQAIADAGAGQAFAGACAIQAEAJAAAKIAABIg");
	this.shape_7.setTransform(19.8,85.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgMBPIAAhyIAZAAIAABygAgNg1IAAgZIAbAAIAAAZg");
	this.shape_8.setTransform(9.8,83.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgVA4QgQgIgIgGIAMgSQAJAIAKADQAKAEAHAAQAJAAAFgEQAEgDAAgGIAAgBQAAgGgHgEIgQgGQgTgFgGgEQgGgDgDgGQgDgGAAgIQAAgJADgGQADgGAGgFQAFgEAIgDQAIgCAGAAQALgBAMAEQAKAEAKAFIgKATQgJgEgIgEQgJgCgHAAQgGAAgEACQgFAEAAAFIAAAAQABAGAHAEQAFACALAFIAOAFQAGADAFABQAGAEADAFQACAGAAAIIAAAAQAAAJgCAHQgEAHgGAFQgFAEgJADQgHABgKAAQgKAAgNgDg");
	this.shape_9.setTransform(1,85.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgMA7IgLgDQgLgFgJgJQgIgIgFgLIgDgLIgBgMIAAAAQAAgGAEgQQAFgLAIgIQAJgJALgFIAMgDIALgBQAJAAAPAEQALAFAJAJQAIAIAFALQAEAPAAAHIAAAAIgBAMIgDALQgFALgIAIQgJAIgLAGQgQAEgIAAgAgNghQgHADgEAFQgFAFgCAHQgDAHAAAGIAAAAQAAAHADAHQACAGAFAGQAFAFAGADQAHADAGAAQAHAAAHgDQAHgDAEgFQAFgFACgHQADgHAAgHIAAAAQAAgGgDgHQgCgGgFgGQgFgFgGgDQgHgDgHAAQgHAAgGADg");
	this.shape_10.setTransform(-11.6,85.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgMBQIAAifIAZAAIAACfg");
	this.shape_11.setTransform(-21.9,83.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AgHBOIgPgFIgNgHQgHgFgFgFIgJgMIgHgNQgDgHgBgIIgCgQIAAAAIACgPQABgIADgGQACgIAFgGQAEgHAFgFIALgJQAHgFAIgDQAGgDAJgBQAGgCAIAAQAKAAAKACIAPAEQALAFAOANIgRAUQgKgJgKgFIgKgEQgHgBgGgBQgJABgJAEQgKAEgGAIQgHAHgEAKQgEAKABAKIAAAAQgBALAEAKQAEAJAHAIQAGAIAKAEQAJAEAJAAQAHAAAGgCQAGgBAFgCQAKgEAKgLIASASIgMALQgIAGgHADQgHAEgJACQgJABgLAAQgHAAgHgBg");
	this.shape_12.setTransform(-32.9,83.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgTA4QgLgFgIgHQgIgJgEgLIgEgMIgBgMIAAAAQAAgLAEgLQAEgLAIgIQAIgIAKgGIALgDIAKgBIANABIALAEQAHADALAKQAGAJAEALQAEAMAAALIgBAHIhTAAQABAHADAFQADAGAEAEQAEAEAGACQAGABAEAAQAKAAAHgDQAHgDAIgIIAPAOIgJAJQgFAEgGADQgGADgGABQgHACgIAAQgLAAgLgEgAAdgGIgDgNQgCgFgEgFQgDgEgGgCQgFgDgGAAQgEAAgGADQgFACgEAEQgEAEgCAGQgDAFgBAIIA6AAIAAAAg");
	this.shape_13.setTransform(46.9,61.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgcBJQgOgEgLgGIAKgUQAKAGAKADQAKADAMAAQAGAAAHgCQAHgDAFgEQAEgFADgGQACgHAAgJIAAgJQgKAMgHAEQgFADgGABQgFACgGAAQgKAAgJgEQgKgEgHgHQgIgHgEgKQgFgIAAgMIAAgBQAAgIAFgPQAEgKAIgHQAHgHAKgEQAJgEAKAAQAGAAAGACIALAEQAIAFAIAJIAAgRIAbAAIAABaQAAAPgEALQgEALgHAHQgEAEgFADIgLAFQgRAEgJAAQgOAAgNgEgAgMgzQgGADgEAEQgFAEgCAFQgDAHAAAHQAAAHADAGQACAGAFACQAFAEAGADQAGACAFAAQAGAAAHgCQAGgDAEgEQAFgCADgGQACgGAAgHQAAgHgCgGQgDgGgFgEQgEgEgGgDQgHgCgGAAQgGAAgGACg");
	this.shape_14.setTransform(32.5,63.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgZA5QgIgCgGgFQgFgEgEgHQgDgHAAgIIAAgBQAAgJADgIQAEgGAGgDQAGgEAJgDQAJgCALAAQALAAASAEIAAgCQAAgGgBgFQgDgFgDgDQgEgDgFgCQgGgBgEgBQgJAAgJACIgQAGIgHgVQAKgFAKgCQALgCALAAQANAAAJADQALADAFAGQAHAGADAKQADAJAAALIAABDIgaAAIAAgOQgHAHgIAEQgMAGgJAAQgIgBgHgCgAgJAEIgJAEQgDADgCADQgCAEAAAEIAAABQAAAHAHAFQAGAFAJAAQAFAAAGgCQAFgBAFgEQAEgDADgFQACgEAAgGIAAgIQgQgEgKAAQgFAAgFABg");
	this.shape_15.setTransform(18.7,61.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgcBJQgOgEgLgGIAKgUQAKAGAKADQAKADAMAAQAGAAAHgCQAHgDAFgEQAEgFADgGQACgHAAgJIAAgJQgKAMgHAEQgFADgGABQgFACgGAAQgKAAgJgEQgKgEgHgHQgIgHgEgKQgFgIAAgMIAAgBQAAgIAFgPQAEgKAIgHQAHgHAKgEQAJgEAKAAQAGAAAGACIALAEQAIAFAIAJIAAgRIAbAAIAABaQAAAPgEALQgEALgHAHQgEAEgFADIgLAFQgRAEgJAAQgOAAgNgEgAgMgzQgGADgEAEQgFAEgCAFQgDAHAAAHQAAAHADAGQACAGAFACQAFAEAGADQAGACAFAAQAGAAAHgCQAGgDAEgEQAFgCADgGQACgGAAgHQAAgHgCgGQgDgGgFgEQgEgEgGgDQgHgCgGAAQgGAAgGACg");
	this.shape_16.setTransform(4.9,63.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AAABIQgGgBgFgEQgEgEgDgHQgCgHAAgIIAAg7IgPAAIAAgYIAPAAIAAgfIAZAAIAAAfIAfAAIAAAYIgfAAIAAA2QAAAHADAEQAEAEAHAAQAJAAAHgFIAAAXQgFADgFABQgGABgIAAQgHAAgEgCg");
	this.shape_17.setTransform(-6.5,60.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AggA7IAAhyIAaAAIAAAaQADgHADgFQADgGAFgDQAFgEAGgCQAHgCAHAAIAAAdIgBAAQgJAAgHACQgIADgFAGQgDAGgDAIQgDAHAAALIAAAtg");
	this.shape_18.setTransform(-14.9,61.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgMA7IgLgDQgLgFgJgJQgIgIgFgLIgDgLIgBgMIAAAAQAAgHAEgPQAFgLAIgIQAJgIALgGIAMgDIALgBQAJAAAPAEQALAGAJAIQAIAIAFALQAEAPAAAHIAAAAIgBAMIgDALQgFALgIAIQgJAJgLAFQgQAEgIAAgAgNghQgHADgEAFQgFAFgCAHQgDAHAAAGIAAAAQAAAHADAHQACAGAFAGQAFAFAGADQAHADAGAAQAHAAAHgDQAHgDAEgFQAFgFACgHQADgGAAgIIAAAAQAAgGgDgHQgCgHgFgEQgFgGgGgDQgHgDgHAAQgHAAgGADg");
	this.shape_19.setTransform(-27.2,61.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AAwBMIAAhsIgwBHIAAAAIgvhGIAABrIgbAAIAAiXIAcAAIAuBIIAuhIIAdAAIAACXg");
	this.shape_20.setTransform(-43.9,59.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AAABIQgGgBgFgEQgEgEgDgGQgCgHAAgJIAAg8IgPAAIAAgWIAPAAIAAghIAZAAIAAAhIAfAAIAAAWIgfAAIAAA3QAAAHADAFQAEACAHAAQAJAAAHgDIAAAWQgFACgFACQgGACgIAAQgHAAgEgDg");
	this.shape_21.setTransform(20.1,36.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgVA3QgQgHgIgFIAMgSQAKAGAKAEQAJAEAHgBQAJABAEgEQAFgDAAgGIAAAAQAAgHgIgDIgQgHQgRgFgIgEQgFgDgDgFQgDgHAAgIQAAgIADgHQADgGAGgFQAGgEAHgDQAIgDAHAAQAKAAALAEQAMADAJAHIgLATQgIgFgJgDQgIgDgHAAQgGAAgFADQgDADAAAFIAAAAQAAAGAIAEQAEADAMAEIAMAEQAHAEAFABQAFAEADAFQADAHABAHIAAAAQgBAJgDAHQgDAHgGAFQgGAEgHACQgJADgIAAQgLAAgNgFg");
	this.shape_22.setTransform(10.3,37.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AggA7IAAhyIAaAAIAAAaQADgHADgFQADgGAFgDQAFgEAGgCQAHgCAHAAIAAAdIgBAAQgJAAgHACQgIADgFAGQgDAGgDAIQgDAHAAALIAAAtg");
	this.shape_23.setTransform(1,37.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgLBPIAAhyIAYAAIAABygAgNg1IAAgZIAbAAIAAAZg");
	this.shape_24.setTransform(-7.2,35.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("Ag4BMIAAiYIBxAAIAAAZIhWAAIAAAqIBMAAIAAAXIhMAAIAAA+g");
	this.shape_25.setTransform(-17,35.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgUBRIAAhcIgOAAIAAgWIAOAAIAAgJQAAgJACgIQADgGAEgFQAFgFAGgCQAFgDAJABQALAAALACIAAAXQgJgDgHAAQgIAAgEAFQgDAEgBAJIAAAGIAfAAIAAAWIgeAAIAABcg");
	this.shape_26.setTransform(46.9,11.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AgUBRIAAhcIgOAAIAAgWIAOAAIAAgJQAAgJADgIQACgGAFgFQAEgFAGgCQAFgDAJABQALAAALACIAAAXQgJgDgIAAQgHAAgEAFQgEAEAAAJIAAAGIAfAAIAAAWIgeAAIAABcg");
	this.shape_27.setTransform(38.6,11.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AgQBOQgIgCgHgDQgIgDgGgEIgLgKQgGgFgEgHQgEgHgDgGQgDgIgCgHIgBgQIAAAAIABgPQACgHADgHIAHgOIAKgMIALgJQAHgFAHgDQAIgDAHgBQAJgCAHAAQAJAAAIACQAIABAHADQAHADAHAFIAMAJQAFAFAEAHIAHAOQADAGACAIQABAIAAAHIAAAAIgBAPQgCAIgDAHQgDAIgEAFIgJAMIgNALIgNAGQgHAEgJACQgIABgIAAQgHAAgJgBgAgTgxQgKAEgHAIQgHAHgEAKQgEAKAAAKIAAAAQAAALAEAKQAEAJAHAIQAHAIAKAEQAKAEAJAAQALAAAJgEQAKgEAHgHQAHgIAEgKQADgKABgLIAAAAQgBgJgDgKQgEgLgHgHQgHgIgKgEQgKgEgKgBQgKABgJAEg");
	this.shape_28.setTransform(24.9,11.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgNBOQgHgCgGgDQgGgDgGgEQgFgFgEgFIgIgMIgFgNIgEgPIgCgQIAAAAIACgPIAEgOIAFgOIAIgMQAEgGAGgDQAFgFAHgDQAFgDAHgBQAIgCAFAAQAIAAAGACIAOAEQAGADAFAFQAFADAEAGQAFAGADAFIAGAOQAEAUABAKIAAAAIgBAPIgEAQIgGANIgIAMIgJAKQgGAEgGADQgGADgHACQgHABgHAAQgGAAgHgBgAgOgxQgIAEgFAHQgFAIgDAKQgCAKgBAKIAAAAQAAALAEAKQACAKAFAIQAFAHAIAFQAHADAHAAQAIAAAIgDQAHgEAGgIQAEgIADgKQADgKAAgLIAAAAQAAgKgDgKQgDgKgFgHQgFgIgIgEQgHgFgIAAQgIAAgGAFg");
	this.shape_29.setTransform(1,11.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgNBOQgHgCgGgDQgGgDgFgEQgGgFgEgFIgIgMIgGgNIgDgPIgCgQIAAAAIACgPIADgOIAGgOIAIgMQAEgGAGgDQAFgFAHgDQAFgDAHgBQAIgCAFAAQAHAAAIACIAMAEQAGADAFAFQAGADAEAGQAFAGADAFIAGAOQAFAUgBAKIAAAAIgBAPIgDAQIgGANIgIAMIgKAKQgFAEgGADQgGADgHACQgHABgHAAQgGAAgHgBgAgPgxQgGAEgGAHQgFAIgDAKQgCAKAAAKIAAAAQAAALADAKQACAKAFAIQAGAHAGAFQAIADAHAAQAJAAAHgDQAHgEAFgIQAFgIADgKQADgKAAgLIAAAAQAAgKgDgKQgDgKgFgHQgGgIgGgEQgIgFgIAAQgHAAgIAFg");
	this.shape_30.setTransform(-14.9,11.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgQBMQgHgBgIgEIgNgHIgLgKIAQgTQAKAJAJAEQALAFAJAAQAGAAAGgCQAFgCAEgDQAEgEACgEQACgFAAgGIAAgBQAAgGgCgEQgCgFgEgDQgFgEgGgCQgFgBgFAAQgIAAgIACIgNAEIgQgIIAEhMIBbAAIAAAYIhDAAIgDAkIALgDQAGgBAGAAQALAAAKADQAKADAHAGQAHAGAEAHQAEAJAAAMIAAABQAAALgEAKQgEAKgHAHQgIAHgLADQgKAEgMAAQgIAAgIgCg");
	this.shape_31.setTransform(-29.9,12);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F78E1E").s().p("AgGBeIAAgXQgSgDgJgEQgNgFgMgJIAPgUQAJAHAJAFQAKAFAKACIAAgrQgMgEgIgCQgKgDgFgGQgGgFgDgHQgDgHAAgJIAAgBQABgIADgIQADgHAGgGQAHgFAIgDQAIgEAKgBIAAgMIASAAIAAAMQALACALAEQAKAFAJAGIgMAVQgIgGgHgDQgIgEgHgBIAAAqQANADAJAEQAIAEAGADQAGAGADAHQACAHAAAJIAAABQAAAIgDAHQgDAIgHAGQgFAFgJAEQgIADgLABIAAAWgAALAyQAKgCAGgFQAGgEAAgIIAAAAQAAgIgFgFQgFgEgMgFgAgVg0QgEAFAAAIQAAAHADAEQAGAFALAEIAAgnQgKABgGAFg");
	this.shape_32.setTransform(-43.7,12.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76,0,152,122);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.5,-300.5,161,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AvmOsIAA9XIfNAAIAAdXg");
	mask.setTransform(162,67);

	// Layer 1
	this.instance = new lib.Takeout160x600();
	this.instance.parent = this;
	this.instance.setTransform(82,0);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(168,171,1,1,0,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,181);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201706_Takeout_160x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(142,426,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.476,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(80,563.8,0.68,0.68,0,0,0,0.1,1.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(80,550.9,1.13,1.13,0,0,0,0.1,3.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// EHO
	this.instance_2 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,586.2,0.07,0.07,0,0,0,135,145);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_3 = new lib.border160x600();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},164).wait(1));

	// PIC
	this.instance_4 = new lib.pic();
	this.instance_4.parent = this;
	this.instance_4.setTransform(68,57,1,1,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({_off:true},164).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(866.5,509,5,5,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(71).to({_off:false},0).to({scaleX:1,scaleY:1,x:199.5,y:354},4).to({_off:true},89).wait(1));

	// HEAD
	this.instance_6 = new lib.HEAD1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(792.5,393,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:1,scaleY:1,x:199.5,y:197},4).to({_off:true},160).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(168,119.7,1,0.847,0,0,0,168,140.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},164).wait(1));

	// tag
	this.instance_8 = new lib._2016TAGvert();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80.1,514.9,1.35,1.35,0,0,0,0,2.6);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(272.9,518.1,0.897,0.897,0,0,0,215.2,63.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.parent = this;
	this.instance_10.setTransform(155.6,503.1,0.927,0.927,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_11 = new lib.HTML5rastershad_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(61.1,454.9,1,1,0,0,0,0,10);
	this.instance_11.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},164).wait(1));

	// logo box
	this.instance_12 = new lib.box1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({_off:true},164).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115,273,780,960);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;