(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497891313113", id:"HTML5rastershad"},
		{src:"images/Wheels160x600.jpg?1497891313113", id:"Wheels160x600"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Wheels160x600 = function() {
	this.initialize(img.Wheels160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,177);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuastackai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdAlIADgFQACABAFABQAGAAADgJIgVgsIAHAAIARAkIAOgkIAHAAIgSAuQgFANgKAAQgFAAgFgDgAFDAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAFIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAEOATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAEsAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAC0AVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAB/ATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgAh8AXQgGgFAAgHQAAgHAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAEABAKIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAh7ALQABAJALAAQAHABAFgEQAEgDAAgGIAAgFQgHgCgGAAQgOAAgBAKgAjRATQgHgGAAgLQAAgIAGgIQAHgGAJAAQAKAAAGAGQAGAIAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEADQgIAJgLAAQgKAAgGgHgAizAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAkNAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAkIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAlCATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIAAADIglAAQACAPAOAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAkkAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgADnAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgABtAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAA1AZIAAgsIAHAAIAAAsgAgyAZIAAg/IAIAAIAAA/gAhJAZIAAg/IAHAAIAAA/gAigAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIAAAAQgIAAgGAFQgFAGAAAJIAAASgAlkAZIAAgnIgGAAIAAgFIAGAAIAAgFQAAgHAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAFIgPAAIAAAngAA0gdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhwAlIACgFIAHACQAGAAAEgJIgVgsIAHAAIARAkIAPgkIAIAAIgUAtQgFANgKAAQgGAAgEgCgACFAXQgGgFAAgHQAAgNAUAAQAGAAAIACIAAgBQAAgNgNAAQgHAAgIAEIgCgGQAJgEAIAAQALAAAEAFQAFAEAAAKIAAAaIgHAAIAAgHQgFAIgLAAQgHAAgFgDgACGALQAAAJAMAAQAHABAEgEQAEgDAAgGIAAgFQgGgCgHAAQgOAAAAAKgABPAVQgEgFAAgIIAAgbIAHAAIAAAZQAAAOAMAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgFAJgLAAQgIAAgFgFgAAcATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgHgHgHAAQgHABgFAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAHgHIAEAEQgIAJgLAAQgKAAgHgHgAigAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAJgBAGAHQAHAHAAAIIAAABQAAALgHAGQgGAHgJAAQgMAAgGgKgAibgJQgGAFAAAFIAAABQAAAHAGAGQAFAFAGAAQAHAAAFgFQAFgFAAgIQAAgGgFgFQgFgFgHAAQgGAAgFAFgAACAZIAAgZQAAgOgLAAQgGAAgEAEQgEAEAAAGIAAAZIgGAAIAAgsIAGAAIAAAIQAHgJAJAAQAHAAAFAEQAEAFAAAJIAAAbg");
	this.shape_1.setTransform(0,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.3,0,72.7,18.9);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSAUIAAgnIAlAAIAAAng");
	this.shape.setTransform(51.7,147.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBJQgWgJgJgIIAPgYQANAKANAEQAMAFAKAAQALAAAHgFQAGgEAAgHIAAgBQAAgIgKgFQgFgDgRgGQgYgGgIgGQgIgFgEgHQgEgIAAgLIAAAAQAAgKAEgKQAFgIAHgHQAIgFAKgEQAJgDAKAAQAOAAAPAFQAPAEAMAJIgOAZQgMgHgLgEQgLgEgJAAQgIAAgGAFQgGAEAAAGIAAABQAAAHALAFQAGADAQAGIAQAHQAKADAGADQAHAGAEAGQAFAJAAAJIAAABQAAALgFAKQgEAIgIAHQgHAGgLADQgLADgMAAQgOAAgRgGg");
	this.shape_1.setTransform(40.3,141.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQBpIAAjRIAhAAIAADRg");
	this.shape_2.setTransform(29.2,138.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZBJQgOgFgLgLQgLgKgGgPIgEgPIgCgRIAAAAQAAgPAGgPQAFgOAKgLQAKgLAOgGIAOgFIAOgBQAJAAAIABQAIACAHAEQAJAEAOAOQAJAKAFAQQAFAOAAAPIgBAKIhvAAQACAJAEAHQAEAIAFAEQAGAFAIADQAHADAGAAQANAAAKgFQAKgEAJgKIAVATIgMAMQgHAFgIAEQgHADgJACQgKADgKAAQgOgBgPgGgAAngJQgBgJgDgHQgDgIgFgFQgFgGgHgDQgHgDgIAAQgGAAgHADQgHADgFAFQgFAGgDAIQgEAHgBAJIBNAAIAAAAg");
	this.shape_3.setTransform(16.3,141.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZBJQgOgFgLgLQgLgKgGgPIgEgPIgCgRIAAAAQAAgPAGgPQAFgOAKgLQAKgLAOgGIAOgFIAOgBQAJAAAIABQAIACAHAEQAJAEAOAOQAJAKAFAQQAFAOAAAPIgBAKIhvAAQACAJAEAHQAEAIAFAEQAGAFAIADQAHADAGAAQANAAAKgFQAKgEAJgKIAVATIgMAMQgHAFgIAEQgHADgJACQgKADgKAAQgOgBgPgGgAAngJQgBgJgDgHQgDgIgFgFQgFgGgHgDQgHgDgIAAQgGAAgHADQgHADgFAFQgFAGgDAIQgEAHgBAJIBNAAIAAAAg");
	this.shape_4.setTransform(-1.2,141.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAhBpIAAhXQAAgJgCgHQgCgEgEgFQgFgFgGgDQgGgCgIAAQgFAAgHACQgGADgEAFQgFAFgDAFQgCAHAAAJIAABWIgjAAIAAjRIAjAAIAABSQAIgNALgGQAGgEAHgCQAFgCAJAAQANAAAKAEQAKAEAHAIQAHAIAEAKQADALAAAMIAABhg");
	this.shape_5.setTransform(-18.9,138.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAiBNIgihnIgiBnIgeAAIgyiYIAjAAIAgBnIAhhoIAdAAIAiBoIAfhnIAjAAIgyCYg");
	this.shape_6.setTransform(-40.4,141.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrBOIAAiXIAjAAIAAAiQADgJAFgGQAEgIAGgFQAHgFAJgCQAIgDAKABIAAAlIgCAAQgMAAgJAEQgKADgHAIQgFAIgDALQgEAKAAAOIAAA7g");
	this.shape_7.setTransform(30.2,110.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgkBJQgKgEgHgIQgHgHgDgLQgEgLgBgNIAAhgIAkAAIAABVQAAAJACAHQACAHAEAFQAFAEAFADQAHACAHAAQAGAAAHgCQAGgDAFgFQAEgFADgHQACgHAAgIIAAhVIAkAAIAACXIgkAAIAAgYQgIANgKAGQgHAEgHACQgFADgIAAQgNAAgLgFg");
	this.shape_8.setTransform(14.5,110.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgQBOIgPgFQgPgGgLgLQgLgLgGgOIgFgPIgBgQIAAAAQAAgJAGgUQAGgPALgLQALgLAPgGIAQgEIAPgDQALAAAVAHQAPAGALALQALALAGAOQAGAUAAAKIAAAAIgBAPIgFAQQgGAOgLALQgLALgPAGQgVAGgLAAgAgSgsQgIAEgHAHQgGAHgDAIQgDAJAAAJIAAAAQAAAKAEAIQADAJAGAHQAHAHAIAEQAJADAIABQAKgBAJgDQAIgEAHgHQAGgGADgJQADgJAAgKIAAAAQAAgIgDgKQgEgIgGgHQgHgHgIgEQgJgDgJAAQgJAAgJADg");
	this.shape_9.setTransform(-3.9,110.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgzBhQgIgCgJgFIANgaQAKAGAKAAQAIAAAEgEQAGgEAEgJIhAiYIAlAAIAqBwIAohwIAkAAIg9CcQgEAMgFAHQgFAJgEAFQgGAFgIACQgHADgJAAQgKAAgKgDg");
	this.shape_10.setTransform(-20.2,112.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaBqIAAh5IgUAAIAAgdIAUAAIAAgLQAAgNADgJQADgKAGgGQAGgGAIgDQAHgDAMAAQAOAAAOAEIAAAdQgLgDgKAAQgKAAgFAFQgFAGAAAMIAAAIIApAAIAAAdIgoAAIAAB5g");
	this.shape_11.setTransform(37.6,76.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgQBOIgPgFQgPgGgLgLQgLgLgGgOIgFgPIgBgQIAAAAQAAgJAGgUQAGgPALgKQALgMAPgGIAQgFIAPgCQALABAVAGQAPAGALALQALALAGAOQAGAUAAAKIAAAAIgBAQIgFAOQgGAPgLALQgLALgPAGQgVAGgLABgAgSgsQgIAEgHAHQgGAGgDAKQgDAIAAAJIAAAAQAAAJAEAJQADAKAGAGQAHAHAIAEQAJAEAIgBQAKABAJgEQAIgEAHgGQAGgHADgJQADgJAAgKIAAAAQAAgIgDgJQgEgJgGgHQgHgHgIgDQgJgEgJgBQgJAAgJAEg");
	this.shape_12.setTransform(22.3,79.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgBBgQgIgCgGgFQgGgGgDgIQgDgJAAgNIAAhOIgTAAIAAgeIATAAIAAgqIAhAAIAAAqIApAAIAAAeIgpAAIAABJQAAAKAFAFQAFAEAJAAQALAAALgFIAAAdIgOAFQgIACgKAAQgKAAgGgCg");
	this.shape_13.setTransform(-2,77.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgkBJQgKgEgHgIQgHgHgDgLQgFgLAAgNIAAhgIAkAAIAABVQAAAJACAHQADAHADAFQAFAEAFADQAHACAHAAQAGAAAGgCQAHgDAEgFQAFgFACgHQADgHAAgIIAAhVIAjAAIAACXIgjAAIAAgYQgIANgLAGQgFAEgIACQgFADgJAAQgNAAgKgFg");
	this.shape_14.setTransform(-16.8,79.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgQBOIgPgFQgPgGgLgLQgLgLgGgOIgFgPIgBgQIAAAAQAAgJAGgUQAGgPALgKQALgMAPgGIAQgFIAPgCQALABAVAGQAPAGALALQALALAGAOQAGAUAAAKIAAAAIgBAQIgFAOQgGAPgLALQgLALgPAGQgVAGgLABgAgSgsQgIAEgHAHQgGAGgDAKQgDAIAAAJIAAAAQAAAJAEAJQADAKAGAGQAHAHAIAEQAJAEAIgBQAKABAJgEQAIgEAHgGQAGgHADgJQADgJAAgKIAAAAQAAgIgDgJQgEgJgGgHQgHgHgIgDQgJgEgJgBQgJAAgJAEg");
	this.shape_15.setTransform(-35.3,79.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZBKQgOgGgLgKQgLgLgGgPIgEgPIgCgRIAAAAQAAgPAGgOQAFgPAKgLQAKgLAOgGIAOgEIAOgCQAJAAAIACQAIABAHADQAJAFAOANQAJALAFAPQAFAPAAAPIgBAKIhvAAQACAJAEAIQAEAHAFAEQAGAFAIADQAHADAGAAQANAAAKgFQAKgEAJgKIAVATIgMALQgHAGgIADQgHAFgJABQgKACgKAAQgOAAgPgFgAAngJQgBgJgDgHQgDgIgFgFQgFgGgHgDQgHgCgIAAQgGAAgHACQgHADgFAFQgFAGgDAHQgEAIgBAJIBNAAIAAAAg");
	this.shape_16.setTransform(28,48.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgrBOIAAiXIAjAAIAAAiQADgJAFgGQAEgIAGgFQAHgFAJgCQAIgDAKABIAAAlIgCAAQgMAAgJAEQgKADgHAIQgFAIgDALQgEAKAAAOIAAA7g");
	this.shape_17.setTransform(14.5,48.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgQBOIgPgFQgPgGgLgLQgLgKgGgPIgFgPIgBgQIAAAAQAAgJAGgUQAGgPALgLQALgLAPgGIAQgEIAPgCQALgBAVAHQAPAGALALQALALAGAOQAGAUAAAKIAAAAIgBAPIgFAQQgGAOgLALQgLALgPAGQgVAHgLgBgAgSgsQgIAEgHAHQgGAHgDAIQgDAJAAAJIAAAAQAAAJAEAKQADAIAGAHQAHAHAIAEQAJADAIABQAKgBAJgDQAIgEAHgHQAGgGADgJQADgJAAgKIAAAAQAAgIgDgKQgEgIgGgHQgHgHgIgEQgJgEgJAAQgJABgJADg");
	this.shape_18.setTransform(-1.7,48.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ABRBOIAAhVQAAgJgCgHQgDgHgDgFQgEgFgGgCQgGgDgHAAQgIAAgFADQgGACgFAFQgEAFgDAHQgCAHAAAJIAABVIghAAIAAhVQAAgJgCgHQgDgHgDgFQgEgFgGgCQgGgDgHAAQgIAAgFADQgHADgDAEQgFAGgDAHQgCAHAAAIIAABVIgjAAIAAiXIAjAAIAAAXQAJgMAKgHQAFgDAHgCQAHgDAJAAQAIAAAHACQAHACAGAEQAFADADAFQAFAFACAGQALgNALgGQAHgEAHgCQAIgCAIAAQAMAAAKAEQALAEAGAIQAIAHADALQAEALAAAOIAABgg");
	this.shape_19.setTransform(-24.9,48.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgBBgQgIgCgGgFQgGgGgDgIQgDgJAAgNIAAhOIgTAAIAAgeIATAAIAAgqIAhAAIAAAqIApAAIAAAeIgpAAIAABJQAAAKAFAFQAFAEAJAAQALAAALgFIAAAdIgOAFQgIACgKAAQgKAAgGgCg");
	this.shape_20.setTransform(18.9,15.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgZBJQgOgFgLgLQgLgKgGgOIgEgQIgCgRIAAAAQAAgPAGgOQAFgPAKgLQAKgLAOgGIAOgFIAOgCQAJAAAIACQAIACAHAEQAJADAOAPQAJALAFAPQAFAOAAAPIgBAKIhvAAQACAJAEAHQAEAHAFAGQAGAFAIACQAHADAGAAQANAAAKgFQAKgFAJgIIAVASIgMAMQgHAFgIAEQgHAEgJACQgKACgKAAQgOAAgPgHgAAngJQgBgJgDgHQgDgHgFgGQgFgFgHgDQgHgEgIAAQgGAAgHAEQgHACgFAGQgFAFgDAHQgEAIgBAJIBNAAIAAAAg");
	this.shape_21.setTransform(4.4,17.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLBnQgLgCgKgEQgJgEgJgGQgHgGgHgGQgIgIgFgIIgJgRQgEgKgBgKQgDgLAAgLIAAAAQAAgJADgKQACgLADgJQAEgJAFgIQAGgJAHgHQAHgHAIgGQAIgGAKgEIAUgGQALgCAJAAQAOAAALACQAKABAKADQAMAGAWAPIgYAbQgMgLgMgFQgUgFgMgBQgMABgMAFQgMAGgJAKQgJAJgFANQgFAOAAANIAAAAQAAAPAFANQAFANAJAKQAJAKANAGQAMAFAOAAQAOAAANgEQAMgEAKgHIAAgnIg0AAIAAgcIBWAAIAABTQgVARgPAFQgLAFgLACQgNACgNABQgKAAgLgCg");
	this.shape_22.setTransform(-15.8,15.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64,0,126,157);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AD34AD").s().p("EgMfAo7MAAAhR2IY/AAMAAABR2g");
	this.shape.setTransform(80,262);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgLANIAAgZIAXAAIAAAZg");
	this.shape.setTransform(49.7,99.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AATBFIgbgsIgPAPIAAAdIgWAAIAAiJIAWAAIAABRIAogrIAcAAIgoAnIApA8g");
	this.shape_1.setTransform(42.2,94.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgEAzIgKgEQgJgDgHgHQgIgIgDgJQgEgKAAgKIAAAAQAAgJAEgJQAEgKAHgHQAHgIAKgDIAKgEIAIgBQAHAAAGABQAFABAFADQAHADAKAJIgOAQQgGgHgGgCQgGgEgIAAQgFAAgEADQgGACgEAEQgDAFgDAGQgCAFAAAGIAAAAQAAAGACAGQADAGAEAEQAEAFAFACQAEACAGAAQAHAAAIgDQAFgCAGgHIAOAOQgLAKgGADIgLAFQgGABgHAAg");
	this.shape_2.setTransform(30.8,96.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgWAxQgGgCgFgEQgFgEgDgFQgDgGAAgIQAAgIADgGQADgGAGgCQAFgEAIgCQAHgCAJAAQAKAAAPAEIAAgDQAAgFgBgEQgCgEgDgDQgDgDgFgBQgEgBgEAAQgIAAgIABIgNAFIgGgSQAJgEAIgCQAJgCAKAAQALAAAIADQAJACAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAGgIAEQgKAEgHAAQgIAAgGgCgAgIADIgHAEQgDACgCADQgCADAAAEQAAAIAGAEQAGAEAIAAQAEAAAFgCQAEgBAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgJAAIgIABg");
	this.shape_3.setTransform(19.4,96.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgFBEIgJgDQgHgFgGgIIAAAQIgXAAIAAiJIAXAAIAAA3QAGgJAHgEIAKgEQAEgCAFAAQAJAAAIAEQAJADAGAHQAHAHADAJQAEAMAAAIIAAABIgBAMIgDAKQgDAJgHAHQgGAHgJADQgIAEgJAAQgFAAgFgCgAgKgKQgFACgEAEQgEAEgDAEQgCAGAAAHIAAABQAAAHACAGQADAGAEAEQAEAEAFADQAGACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQACgGAAgHIAAgBQAAgHgCgGQgCgEgEgEQgEgEgGgCQgFgDgFAAQgEAAgGADg");
	this.shape_4.setTransform(8,94.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AAVBFIAAg5QABgGgCgFQgCgCgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgEADgBADQgCAEAAAGIAAA5IgWAAIAAiJIAWAAIAAA2QAGgIAHgEIAIgEQADgCAGAAQAIAAAHADQAGADAFAFQAFAFACAHQACAHABAHIAABAg");
	this.shape_5.setTransform(-10.1,94.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgSAvQgOgGgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgCAAgGIAAAAQAAgFgHgEQgDgBgKgEQgPgFgGgDQgFgDgDgEQgDgFAAgHIAAgBQAAgHADgGQADgFAFgFQAFgEAGgCQAHgCAFAAQAJAAAKADQAKADAIAGIgJAQQgHgFgIgCQgHgCgGgBQgFAAgEADQgDADAAAEIAAABQAAAFAGADIAOAGIALAEQAGACAEACQAFAEACAEQADAFAAAGIAAABQAAAHgDAHQgCAFgFAFQgFADgHACQgHADgIAAQgJAAgLgFg");
	this.shape_6.setTransform(-20.9,96.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgWAxQgGgCgFgEQgFgEgDgFQgDgGAAgIQAAgIADgGQADgGAGgCQAFgEAIgCQAHgCAJAAQAKAAAPAEIAAgDQAAgFgBgEQgCgEgDgDQgDgDgFgBQgEgBgEAAQgIAAgIABIgNAFIgGgSQAJgEAIgCQAJgCAKAAQALAAAIADQAJACAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAGgIAEQgKAEgHAAQgIAAgGgCgAgIADIgHAEQgDACgCADQgCADAAAEQAAAIAGAEQAGAEAIAAQAEAAAFgCQAEgBAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgJAAIgIABg");
	this.shape_7.setTransform(-31.4,96.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgEAzIgKgEQgJgDgIgHQgGgIgEgJQgEgKAAgKIAAAAQAAgJAEgJQADgKAIgHQAHgIAJgDIAKgEIAJgBQAHAAAGABQAGABAEADQAHADAKAJIgOAQQgGgHgGgCQgGgEgIAAQgFAAgFADQgFACgEAEQgEAFgCAGQgCAFAAAGIAAAAQAAAGACAGQACAGAEAEQAFAFAFACQAEACAGAAQAIAAAGgDQAGgCAGgHIAOAOQgLAKgGADIgLAFQgGABgHAAg");
	this.shape_8.setTransform(-41.9,96.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AAbBBQgGgCgEgFQgEgFgCgGQgDgGAAgHIAAgBQAAgHADgFQACgHAEgFQAEgEAGgDQAGgCAHAAQAHAAAGACQAFADAEAEQAEAFADAGQACAGAAAHIAAAAQAAAIgCAFQgDAGgEAGQgDAEgHADQgGACgGABQgHgBgGgCgAAdAUQgDAFgBAIIAAAAQAAAJAFAGQAEAFAGAAQAHAAADgFQAEgGAAgIIAAgBQABgIgFgFQgEgGgGAAQgHAAgEAGgAg4BCIA0hEIArg/IATAAIg1BFIgrA+gAg0gBQgFgDgFgFQgDgEgCgGQgDgHAAgGIAAgBQAAgHADgGQACgGAEgEQAEgFAGgDQAGgCAHAAQAGAAAGACQAGADAEAFQAFAEABAGQADAGAAAHIAAAAQAAAHgDAHQgCAFgEAFQgEAFgGADQgGABgGAAQgIAAgGgBgAgxguQgEAFAAAIIAAAAQAAAJAEAFQAFAGAGAAQAGAAAEgGQAEgFAAgIIAAgBQAAgHgEgGQgFgGgFAAQgHAAgEAGg");
	this.shape_9.setTransform(24.6,73.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AguBDIAAgSIAtgoQAHgHALgKQACgEABgEQACgEAAgFQAAgEgCgEQgBgEgDgCIgHgFQgEgBgEAAQgDAAgEABQgEACgEACQgGAEgIALIgRgNIAKgMQAFgGAFgDQAGgEAHgBQAIgCAGAAQAKAAAIADQAIADAGAFQAGAGADAGQADAIAAAJQAAAIgCAHQgCAGgFAFIgKAKIgQAOIgZAWIA9AAIAAAVg");
	this.shape_10.setTransform(10.7,73.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_11.setTransform(-4.8,73.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgKAEgJQADgJAHgIQAGgHAJgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAHAIIAJAEQAEACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgMADIgNACQgJAAgJgEgAAZgFQgBgHgCgEQgBgFgDgDQgEgEgEgCQgEgCgGAAQgEAAgEACQgEACgDADIgHAJIgCALIAxAAIAAAAg");
	this.shape_12.setTransform(-14.2,75.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgYA/QgMgDgJgGIAIgRQAJAFAIADQAJACAKAAQAFAAAGgCQAGgBAEgEQAEgEACgGQADgGAAgHIAAgIQgJAKgGADQgEADgGABQgEABgFAAQgJAAgIgDQgIgDgGgGQgHgGgEgJQgDgHAAgLIAAAAQAAgHADgNQAEgIAHgHQAGgGAIgDQAIgDAJAAQAFAAAFABQAFABAEADQAIAEAGAIIAAgPIAXAAIAABOQAAAMgDAKQgDAJgGAHIgIAGIgKAEQgPADgHAAQgMAAgLgDgAgKgsQgFACgEAEIgGAIQgCAGAAAGIAAAAQAAAGACAFQACAFAEACQAEAEAFACQAFACAFAAQAFAAAGgCQAFgCAEgEQAEgCACgFQADgFAAgGIAAAAQAAgGgDgFQgCgFgEgEQgEgEgFgCQgGgCgFAAQgFAAgFACg");
	this.shape_13.setTransform(-26.6,76.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgOARQAIgCAFgEQACgFgBgGIgIAAIAAgaIAXAAIAAAXQAAAGgBAFQgCAHgEADQgEAEgEACQgFACgHAAg");
	this.shape_14.setTransform(44.3,59.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AAWAzIAAg3QgBgGgBgFQgBgEgDgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCAFQgCAEABAGIAAA3IgYAAIAAhjIAYAAIAAAQQAFgIAGgEIAJgEQADgCAFAAQAJAAAHADQAGADAFAFQAEAFADAHQACAHAAAJIAAA+g");
	this.shape_15.setTransform(36.3,54.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgWAxQgGgCgFgEQgFgEgDgFQgDgGAAgIQAAgIADgGQADgGAGgCQAFgEAIgCQAHgCAJAAQAKAAAPAEIAAgDQAAgFgBgEQgCgEgDgDQgDgDgFgBQgEgBgEAAQgIAAgIABIgNAFIgGgSQAJgEAIgCQAJgCAKAAQALAAAIADQAJACAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAGgIAEQgKAEgHAAQgIAAgGgCgAgIADIgHAEQgDACgCADQgCADAAAEQAAAIAGAEQAGAEAIAAQAEAAAFgCQAEgBAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgJAAIgIABg");
	this.shape_16.setTransform(24.5,54.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgKAzIgKgDQgKgFgHgHQgHgGgEgKIgDgKIgBgKIAAAAQAAgFAEgNQAEgKAHgIQAHgHAKgDIAKgEIAKgBQAHAAAOAEQAKAEAHAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAJQgEAKgHAHQgIAHgJAFQgOAEgHAAgAgMgcQgFACgEAFQgEAEgCAGQgCAGAAAFIAAAAQAAAGACAGQADAGAEAEQADAFAGACQAGACAFABQAHgBAFgCQAGgCAEgFQADgEADgGQACgGAAgGIAAAAQAAgFgCgGQgDgGgDgEQgFgFgFgCQgHgDgFAAQgGAAgGADg");
	this.shape_17.setTransform(13,54.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgKBFIAAiJIAVAAIAACJg");
	this.shape_18.setTransform(4.1,52.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgKAzIgKgDQgJgFgIgHQgHgGgEgKIgDgKIgBgKIAAAAQAAgFAEgNQAEgKAHgIQAIgHAJgDIALgEIAJgBQAHAAAOAEQAJAEAIAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAJQgEAKgIAHQgHAHgKAFQgNAEgHAAgAgMgcQgFACgEAFQgEAEgCAGQgCAGAAAFIAAAAQAAAGACAGQACAGAEAEQAEAFAGACQAGACAFABQAGgBAGgCQAFgCAEgFQAFgEACgGQACgGAAgGIAAAAQAAgFgCgGQgCgGgFgEQgEgFgGgCQgFgDgGAAQgFAAgHADg");
	this.shape_19.setTransform(-10.5,54.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_20.setTransform(-20.5,52.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AgXAwQgGgDgGgFQgEgFgCgHQgCgHgBgJIAAg+IAXAAIAAA3QABAGABAFQABAEADADQACAEAEABQAEACAFAAIAIgCIAHgFQADgDACgFQACgEAAgGIAAg3IAWAAIAABjIgWAAIAAgQQgGAIgHAFQgEACgEABQgEACgFAAQgIAAgHgDg");
	this.shape_21.setTransform(-30.2,54.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgWAxQgGgCgFgEQgFgEgDgFQgDgGAAgIQAAgIADgGQADgGAGgCQAFgEAIgCQAHgCAJAAQAKAAAPAEIAAgDQAAgFgBgEQgCgEgDgDQgDgDgFgBQgEgBgEAAQgIAAgIABIgNAFIgGgSQAJgEAIgCQAJgCAKAAQALAAAIADQAJACAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAGgIAEQgKAEgHAAQgIAAgGgCgAgIADIgHAEQgDACgCADQgCADAAAEQAAAIAGAEQAGAEAIAAQAEAAAFgCQAEgBAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgJAAIgIABg");
	this.shape_22.setTransform(-41.9,54.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_23.setTransform(31.4,33.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgXAwQgHgDgFgFQgEgFgDgHQgCgHAAgJIAAg+IAYAAIAAA3QAAAGABAFQABAEADADQADAEAEABQADACAFAAIAIgCIAHgFQADgDABgFQACgEAAgGIAAg3IAXAAIAABjIgXAAIAAgQQgFAIgHAFQgEACgFABQgCACgGAAQgJAAgGgDg");
	this.shape_24.setTransform(21.2,33.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgKAzIgKgEQgJgDgIgIQgHgHgEgJIgDgKIgBgKIAAAAQAAgGAEgMQAEgKAHgHQAIgIAJgDIALgEIAJgBQAHAAAOAEQAJAEAIAIQAHAGAEAKQAEANAAAGIAAAAIgBAKIgDAJQgEAKgIAHQgHAIgKADQgNAFgHAAgAgLgcQgGACgEAEQgEAFgCAGQgCAFAAAGIAAAAQAAAGACAGQADAGAEAEQAEAEAFADQAGACAFAAQAHAAAFgCQAFgDAFgEQAEgEABgGQADgGAAgGIAAAAQAAgFgDgGQgBgGgEgEQgFgFgGgCQgGgDgFAAQgGAAgFADg");
	this.shape_25.setTransform(9.1,33.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AghBAIgLgFIAIgRQAHAEAGAAQAGAAACgDQAEgCADgHIgqhiIAYAAIAbBIIAahIIAYAAIgoBlIgGANQgDAGgCADQgFADgEACQgFABgGAAQgHAAgGgBg");
	this.shape_26.setTransform(-2.2,34.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AgSAvQgOgGgGgFIAKgPQAIAGAIADQAJADAGAAQAHAAAEgDQAEgCAAgGIAAAAQAAgFgHgEQgDgBgKgEQgPgFgGgDQgFgDgDgEQgDgFAAgHIAAgBQAAgHADgGQADgFAFgFQAFgEAGgCQAHgCAFAAQAJAAAKADQAKADAIAGIgJAQQgHgFgIgCQgHgCgGgBQgFAAgEADQgDADAAAEIAAABQAAAFAGADIAOAGIALAEQAGACAEACQAFAEACAEQADAFAAAGIAAABQAAAHgDAHQgCAFgFAFQgFADgHACQgHADgIAAQgJAAgLgFg");
	this.shape_27.setTransform(-18.5,33.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AgXAwQgHgDgEgFQgFgFgDgHQgBgHAAgJIAAg+IAWAAIAAA3QAAAGACAFQABAEADADQADAEAEABQAEACAEAAIAIgCIAHgFQADgDABgFQACgEAAgGIAAg3IAYAAIAABjIgYAAIAAgQQgFAIgHAFQgEACgEABQgDACgGAAQgIAAgHgDg");
	this.shape_28.setTransform(-29,33.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgYA/QgMgDgJgGIAIgRQAJAFAIADQAJACAKAAQAFAAAGgCQAGgBAEgEQAEgEACgGQADgGAAgHIAAgIQgJAKgGADQgEADgGABQgEABgFAAQgJAAgIgDQgIgDgGgGQgHgGgEgJQgDgHAAgLIAAAAQAAgHADgNQAEgIAHgHQAGgGAIgDQAIgDAJAAQAFAAAFABQAFABAEADQAIAEAGAIIAAgPIAXAAIAABOQAAAMgDAKQgDAJgGAHIgIAGIgKAEQgPADgHAAQgMAAgLgDgAgKgsQgFACgEAEIgGAIQgCAGAAAGIAAAAQAAAGACAFQACAFAEACQAEAEAFACQAFACAFAAQAFAAAGgCQAFgCAEgEQAEgCACgFQADgFAAgGIAAAAQAAgGgDgFQgCgFgEgEQgEgEgFgCQgGgCgFAAQgFAAgFACg");
	this.shape_29.setTransform(19.1,13.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AAWAzIAAg3QgBgGgBgFQgCgEgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCAFQgBAEgBAGIAAA3IgXAAIAAhjIAXAAIAAAQQAGgIAGgEIAJgEQADgCAFAAQAJAAAHADQAHADAEAFQAEAFADAHQACAHAAAJIAAA+g");
	this.shape_30.setTransform(7.2,12.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_31.setTransform(-1.5,10.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_32.setTransform(-7.6,12.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F78E1E").s().p("Ag2BCIAAiDIA5AAQAMAAAJADQAJADAFAFQAFAFACAFQACAGAAAHQAAAGgBAFQgBAFgDADQgFAHgJAEIALACIAIAHQAEAEACAFQACAGAAAGIAAABQAAAIgDAHQgEAHgGAFQgHAEgJACQgJADgLAAgAgfAtIAlAAQAGAAAFgBQAFgBADgCQADgCABgEQACgEABgEIAAgBQAAgEgCgDIgFgFQgDgDgGgBIgMgBIgjAAgAgfgJIAfAAIAJgBQAFgBADgCQADgDADgDQABgEAAgEIAAAAQAAgFgBgDQgCgCgDgCQgDgDgFgBQgEgBgFgBIggAAg");
	this.shape_33.setTransform(-18.4,10.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.5,0,115,107);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgJSguyISlAAMAAABdlIylAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-300.5,121,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AD34AD").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AqiHuIAAvbIVEAAIAAPbg");
	mask.setTransform(76.5,50.6);

	// pic
	this.instance = new lib.Wheels160x600();
	this.instance.parent = this;
	this.instance.setTransform(14,0,0.75,0.75);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(168,110.1,1,1,0,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,1.2,336,118.9);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201706_Wheels_120x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(101,448,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.357,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(60,586.2,0.683,0.683,0,0,0,0,0.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuastackai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(60,558.7,1.153,1.153,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border120x600();
	this.instance_2.parent = this;
	this.instance_2.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},164).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(136,56,1,1,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},164).wait(1));

	// CTA
	this.instance_4 = new lib.CTA();
	this.instance_4.parent = this;
	this.instance_4.setTransform(749.5,517,5,5,0,0,0,119.5,40);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(71).to({_off:false},0).to({scaleX:1,scaleY:1,x:179.5,y:357},4).to({_off:true},89).wait(1));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(729.5,330,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleX:1,scaleY:1,x:179.5,y:159},4).to({_off:true},160).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({_off:true},164).wait(1));

	// tag
	this.instance_7 = new lib._2016TAGvert();
	this.instance_7.parent = this;
	this.instance_7.setTransform(60.1,526.2,1.014,1.014,0,0,0,0,2.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(204.9,528.5,0.673,0.673,0,0,0,215.2,63.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.parent = this;
	this.instance_9.setTransform(116.8,517.3,0.696,0.696,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_10 = new lib.HTML5rastershad_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_10.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},164).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},164).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(17.1,232.1,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128,299,630,981);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;