(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497572146829", id:"HTML5rastershad"},
		{src:"images/Reasons336x280.jpg?1497572146829", id:"Reasons336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Reasons336x280 = function() {
	this.initialize(img.Reasons336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,166);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Reasons336x280();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,166);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAOIAAgbIAZAAIAAAbg");
	this.shape.setTransform(100.4,38.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgSA1QgKgEgHgIQgJgHgDgLIgEgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIANABIALADQAGADAKAKQAHAIADALQADALAAAKIAAAHIhPAAQABAHACAFQADAGAEADQAFAEAEACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQAAgHgDgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgFACgEADQgEAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_1.setTransform(91.5,34.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSA1QgKgEgIgIQgIgHgEgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAHgJAKgEIAKgDIAKgBIAMABIALADQAHADAKAKQAGAIAEALQADALAAAKIAAAHIhQAAQACAHACAFQADAGAEADQAEAEAGACQAFABAEAAQAJAAAIgDQAGgDAHgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgLgEgAAcgGQgBgHgCgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgEAAgFADQgEACgFADQgEAEgBAGQgDAFgBAHIA3AAIAAAAg");
	this.shape_2.setTransform(78.8,34.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfA4IAAhtIAaAAIAAAZQACgGADgFQADgFAFgEQAFgDAGgCQAGgCAHAAIAAAbIgCAAQgIAAgHADQgHADgFAFQgDAGgDAIQgCAGAAALIAAAqg");
	this.shape_3.setTransform(69,34.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgTBNIAAhXIgOAAIAAgVIAOAAIAAgJQAAgJADgHQACgHAEgEQAFgEAFgDQAFgCAIAAQALAAAKADIAAAWQgIgDgHAAQgHAAgEAEQgEAEAAAJIAAAGIAeAAIAAAVIgdAAIAABXg");
	this.shape_4.setTransform(60.5,32.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAYA4IAAg9QAAgGgCgGQgBgFgDgDQgDgDgFgCQgEgCgGAAQgDAAgFACQgFACgDAEQgDADgCAFQgCAFAAAHIAAA8IgZAAIAAhtIAZAAIAAARQAGgJAIgEIAJgFQAEgBAGAAQAJAAAHADQAIACAFAGQAFAGADAIQACAIAAAJIAABFg");
	this.shape_5.setTransform(43.6,34.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYA2QgHgCgGgEQgFgEgDgHQgEgHAAgHIAAgBQAAgJAEgGQADgHAGgCQAGgFAJgCQAIgCAKAAQALgBARAFIAAgCQAAgGgCgFQgCgEgDgDQgEgDgFgCQgFgCgFAAQgIAAgIACIgPAFIgHgUQAKgEAJgDQAKgCALAAQAMAAAJADQAKAEAGAFQAGAHADAIQADAJAAALIAAA/IgZAAIAAgNQgGAHgJAEQgLAFgIAAQgIAAgHgDgAgJAEQgFABgDACQgDADgCAEQgCADAAAEIAAABQAAAHAGAFQAGAFAKgBQAEAAAGgCQAFgBAEgDQAEgEACgDQACgFAAgFIAAgIQgPgFgKAAQgEAAgFACg");
	this.shape_6.setTransform(30.6,34.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAYBMIAAg/QAAgGgCgFQgBgDgDgEQgDgDgFgCQgEgCgGAAQgDAAgFACQgFACgDAEQgDADgCADQgCAFAAAHIAAA+IgZAAIAAiXIAZAAIAAA7QAGgIAIgFIAJgEQAEgCAGAAQAJAAAHADQAIADAFAGQAFAFADAIQACAIAAAHIAABHg");
	this.shape_7.setTransform(18.3,32.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAABFQgGgBgEgEQgEgEgDgGQgCgGAAgJIAAg5IgOAAIAAgWIAOAAIAAgeIAXAAIAAAeIAeAAIAAAWIgeAAIAAA1QAAAHAEADQADADAHAAQAIAAAIgDIAAAUIgKAFQgGABgHAAQgHAAgEgCg");
	this.shape_8.setTransform(7.3,32.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfA4IAAhtIAaAAIAAAZQACgGADgFQADgFAFgEQAFgDAGgCQAGgCAHAAIAAAbIgCAAQgIAAgHADQgHADgFAFQgDAGgDAIQgCAGAAALIAAAqg");
	this.shape_9.setTransform(-7,34.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgRA1QgLgEgHgIQgIgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIAMABIAMADQAGADAKAKQAGAIAEALQADALAAAKIAAAHIhPAAQAAAHADAFQADAGAEADQAFAEAEACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgKgEgAAcgGQgBgHgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgEACgEADQgFAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_10.setTransform(-18.1,34.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAABFQgGgBgEgEQgEgEgDgGQgCgGAAgJIAAg5IgOAAIAAgWIAOAAIAAgeIAXAAIAAAeIAeAAIAAAWIgeAAIAAA1QAAAHAEADQADADAHAAQAIAAAIgDIAAAUIgKAFQgGABgHAAQgHAAgEgCg");
	this.shape_11.setTransform(-28.6,32.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAABFQgGgBgEgEQgEgEgDgGQgCgGAAgJIAAg5IgOAAIAAgWIAOAAIAAgeIAXAAIAAAeIAeAAIAAAWIgeAAIAAA1QAAAHAEADQADADAHAAQAIAAAIgDIAAAUIgKAFQgGABgHAAQgHAAgEgCg");
	this.shape_12.setTransform(-37.2,32.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgSA1QgKgEgIgIQgIgHgEgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAHgJAKgEIAKgDIAKgBIAMABIALADQAHADAKAKQAGAIAEALQADALAAAKIAAAHIhQAAQACAHACAFQADAGAEADQAEAEAGACQAFABAEAAQAJAAAIgDQAGgDAHgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgLgEgAAcgGQgBgHgCgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgEAAgFADQgEACgFADQgEAEgBAGQgDAFgBAHIA3AAIAAAAg");
	this.shape_13.setTransform(-47.6,34.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgFBMQgGgBgEgEQgJgEgGgJIAAARIgaAAIAAiXIAaAAIAAA8QAGgJAJgFQAFgDAFgCQAFgBAFAAQAKAAAJAEQAKAEAHAHQAHAIAEAKQAFANAAAKIgBANIgEALQgEALgHAHQgHAHgKAFQgJADgKAAQgFAAgFgBgAgLgLQgGACgEAFQgFAEgCAFQgDAHAAAIQAAAIADAGQACAHAFAEQAEAFAGACQAGADAFAAQAGAAAGgDQAFgBAFgGQAEgEADgHQACgGAAgIQAAgIgDgHQgCgFgEgEQgFgFgFgCQgGgDgGAAQgFAAgGADg");
	this.shape_14.setTransform(-60.7,32.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUA1QgPgHgIgGIAMgRQAJAHAJADQAJAEAHAAQAIAAAFgEQAFgDgBgFIAAgBQAAgFgHgEIgQgGQgQgFgHgEQgFgDgDgFQgDgGAAgHIAAgBQAAgIADgGQADgHAGgEQAEgEAIgDQAHgCAGAAQALAAAKAEQALADAJAGIgKASQgIgFgIgDQgJgDgGAAQgFABgEADQgFACAAAGQAAAFAIAEIAPAGIAMAFQAHADAFABQAFAEACAFQAEAGAAAHIAAAAQAAAJgEAHQgDAGgFAEQgGAEgIADQgHACgJAAQgKAAgMgEg");
	this.shape_15.setTransform(-79.7,34.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQASQAKgBAEgFQADgFgBgHIgJAAIAAgcIAaAAIAAAYQAAAHgCAGQgCAHgEAEQgEAEgFACQgFADgIAAg");
	this.shape_16.setTransform(-87.9,28.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAABFQgGgBgEgEQgEgEgDgGQgCgGAAgJIAAg5IgOAAIAAgWIAOAAIAAgeIAXAAIAAAeIAeAAIAAAWIgeAAIAAA1QAAAHAEADQADADAHAAQAIAAAIgDIAAAUIgKAFQgGABgHAAQgHAAgEgCg");
	this.shape_17.setTransform(-95,32.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLBLIAAhsIAYAAIAABsgAgMgzIAAgYIAZAAIAAAYg");
	this.shape_18.setTransform(-102.2,32.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgUA1QgPgHgHgFIALgRQAJAGAJADQAKAEAGAAQAJAAAEgEQAEgCABgGIAAAAQgBgGgHgEIgQgGQgRgFgGgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAGgFQAFgEAHgDQAHgCAHAAQAJAAALADQALAEAJAGIgKASQgIgFgIgDQgIgCgHgBQgFAAgFADQgEAEAAAEQAAAGAIAEIAPAGIAMAFQAHADAEABQAGAEACAFQADAGAAAHIAAABQAAAIgDAGQgDAHgFAFQgGAEgHACQgHACgJAAQgKAAgNgEg");
	this.shape_19.setTransform(133.3,13.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAJIAABFg");
	this.shape_20.setTransform(121.7,13.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgLA4IgLgDQgLgFgIgIQgIgIgEgKIgDgLIgBgLIAAAAQgBgGAFgPQAEgKAJgIQAHgIALgFIALgDIALgBQAIAAAPAEQALAEAIAIQAIAIAEALQAEAOABAHIgBALIgEALQgEAKgIAIQgJAIgKAFQgQAEgHAAgAgMgfQgHACgEAFQgEAFgDAGQgCAHAAAGQAAAHADAGQACAHAFAFQAEAFAGACQAHADAFAAQAHAAAHgDQAFgCAFgFQAEgFADgGQACgHAAgHIAAAAQAAgGgCgGQgDgHgFgFQgEgFgGgCQgHgDgGAAQgHAAgFADg");
	this.shape_21.setTransform(108.3,13.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUA1QgQgHgGgFIALgRQAJAGAJADQAJAEAHAAQAIAAAFgEQAEgCAAgGIAAAAQAAgGgHgEIgQgGQgQgFgHgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAGgFQAEgEAIgDQAHgCAHAAQAKAAAKADQALAEAJAGIgKASQgIgFgIgDQgIgCgHgBQgFAAgFADQgEAEAAAEQAAAGAIAEIAPAGIAMAFQAHADAEABQAGAEACAFQADAGABAHIAAABQgBAIgDAGQgDAHgFAFQgGAEgHACQgIACgJAAQgJAAgNgEg");
	this.shape_22.setTransform(96,13.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgYA3QgHgCgGgFQgFgFgDgFQgEgIAAgIIAAAAQAAgJAEgGQADgHAGgDQAGgEAJgCQAIgDAKAAQALAAARAFIAAgCQAAgHgCgEQgCgEgDgDQgEgEgFgBQgFgCgFAAQgIAAgIACIgPAFIgHgUQAKgEAJgCQAKgDALAAQAMAAAJAEQAKACAGAHQAGAFADAJQADAJAAALIAABAIgZAAIAAgPQgGAIgJAEQgLAFgIAAQgIAAgHgCgAgJAEQgFABgDADQgDACgCADQgCAEAAAEIAAAAQAAAJAGAEQAGAEAKAAQAEAAAGgBQAFgCAEgEQAEgDACgDQACgFAAgGIAAgHQgPgEgKgBQgEABgFABg");
	this.shape_23.setTransform(84.5,13.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgSA1QgKgEgIgIQgHgHgEgLIgEgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIAKgDIAKgBIANABIAKADQAHADAKAKQAHAIADALQADALAAAKIAAAHIhQAAQABAHADAFQADAGAEADQAEAEAFACQAGABAEAAQAJAAAIgDQAGgDAHgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQAAgHgDgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgEAAgFADQgEACgFADQgDAEgCAGQgDAFgBAHIA3AAIAAAAg");
	this.shape_24.setTransform(72.3,13.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgfA4IAAhtIAaAAIAAAZQACgGADgFQADgFAFgEQAFgDAGgCQAGgCAHAAIAAAbIgCAAQgIAAgHADQgHADgFAFQgDAGgDAIQgCAGAAALIAAAqg");
	this.shape_25.setTransform(62.5,13.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgNBKQgGgCgGgDIgLgHIgJgJQgEgFgDgGIgGgMIgDgOIgBgQIAAAAIABgOIADgOIAGgNIAHgMIAKgJIALgHQAFgCAHgCQAGgCAGABQAHgBAGACQAHACAGACQAGADAFAEIAJAJIAIALIAFAOQAEASABAKIAAAAIgBAPIgEAOIgFANIgIALIgJAJIgLAHQgHADgGACQgHACgGAAQgGAAgHgCgAgOgvQgHAEgFAHQgEAHgDAKQgDAJAAAKIAAAAQAAAKADAKQADAKAFAGQAFAIAGAEQAHAEAHAAQAIAAAHgEQAHgEAFgHQAFgIADgJQACgJAAgLIAAAAQAAgKgDgJQgCgJgFgIQgGgHgGgEQgIgEgHAAQgHAAgHAEg");
	this.shape_26.setTransform(43.8,11.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgNBKQgGgCgGgDIgLgHIgJgJQgEgFgDgGIgGgMIgDgOIgBgQIAAAAIABgOIADgOIAGgNIAHgMIAKgJIALgHQAFgCAHgCQAGgCAGABQAHgBAGACQAHACAGACQAGADAFAEIAJAJIAIALIAFAOQAEASABAKIAAAAIgBAPIgEAOIgFANIgIALIgJAJIgLAHQgHADgGACQgHACgGAAQgGAAgHgCgAgOgvQgHAEgFAHQgEAHgDAKQgDAJAAAKIAAAAQAAAKADAKQADAKAFAGQAEAIAHAEQAHAEAHAAQAIAAAHgEQAHgEAFgHQAEgIAEgJQACgJAAgLIAAAAQAAgKgDgJQgDgJgEgIQgGgHgGgEQgIgEgHAAQgHAAgHAEg");
	this.shape_27.setTransform(28.6,11.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AADBKIAAh5IgZAIIgFgVIAlgNIASAAIAACTg");
	this.shape_28.setTransform(16.1,11.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgaA1QgHgDgFgGQgFgFgDgIQgCgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQABAFADAEQAEADADACQAFACAFAAQAFAAAEgCQAFgCADgDIAFgJQACgFAAgHIAAg8IAaAAIAABtIgaAAIAAgRQgHAJgGAEQgFADgFABQgDACgHAAQgJAAgIgDg");
	this.shape_29.setTransform(-0.1,13.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgLA4IgLgDQgLgFgIgIQgIgIgEgKIgEgLIgBgLIAAAAQABgGAEgPQAEgKAJgIQAHgIALgFIALgDIALgBQAIAAAPAEQALAEAIAIQAIAIAEALQAEAOAAAHIgBALIgDALQgEAKgIAIQgJAIgKAFQgPAEgIAAgAgNgfQgFACgFAFQgEAFgDAGQgCAHAAAGQAAAHACAGQADAHAFAFQAEAFAGACQAGADAGAAQAHAAAGgDQAGgCAFgFQAEgFADgGQACgHAAgHIAAAAQAAgGgDgGQgCgHgFgFQgEgFgGgCQgGgDgHAAQgHAAgGADg");
	this.shape_30.setTransform(-13.4,13.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AglBGQgFgBgHgEIAJgTQAIAFAHAAQAGAAADgDQADgDADgHIguhtIAbAAIAeBQIAdhQIAaAAIgsBwQgDAJgEAFQgDAHgDADQgEAEgGABQgEACgIAAQgHAAgHgCg");
	this.shape_31.setTransform(-25.9,15);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgSA1QgKgEgIgIQgHgHgEgLIgEgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIAKgDIAKgBIANABIALADQAGADAKAKQAHAIADALQADALAAAKIAAAHIhQAAQACAHACAFQADAGAEADQAEAEAFACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQAAgHgDgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgFACgEADQgDAEgDAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_32.setTransform(-44.8,13.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgKA3IguhtIAbAAIAdBPIAehPIAbAAIguBtg");
	this.shape_33.setTransform(-56.7,13.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgLBMIAAhtIAXAAIAABtgAgMgyIAAgZIAZAAIAAAZg");
	this.shape_34.setTransform(-66,11.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgbBGQgNgDgKgHIAJgTQAJAFAKAEQAJADALAAQAHAAAHgCQAGgDAEgEQAFgEACgHQADgGAAgJIAAgIQgKALgHAEQgEACgGABQgFACgGAAQgJAAgJgEQgKgDgHgGQgHgIgEgJQgEgIAAgLIAAgBQAAgJAEgNQAEgJAIgIQAHgGAJgEQAJgDAJAAQAGAAAFACQAGAAAFADQAIAFAHAJIAAgRIAaAAIAABXQAAAOgEAKQgDAKgHAHIgJAGIgKAGQgRADgIAAQgOAAgMgDgAgLgxQgGADgEADQgFAEgCAGQgCAGAAAHIAAAAQAAAHACAFQACAGAFACQAEAEAGADQAGACAFAAQAGAAAGgCQAGgDAEgEQAFgCACgGQADgFAAgHIAAAAQAAgHgDgGQgCgFgFgFQgEgDgGgDQgGgCgGAAQgFAAgGACg");
	this.shape_35.setTransform(-76.3,14.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgLBMIAAiXIAXAAIAACXg");
	this.shape_36.setTransform(-92.3,11.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgLBMIAAiXIAXAAIAACXg");
	this.shape_37.setTransform(-98.3,11.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgQASQAKgBAEgFQADgFgBgHIgJAAIAAgcIAaAAIAAAYQAAAHgCAGQgCAHgEAEQgEAEgFACQgFADgIAAg");
	this.shape_38.setTransform(-104.4,7.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgRA1QgLgEgHgIQgIgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAHgJAKgEIAKgDIAKgBIAMABIALADQAHADAKAKQAHAIADALQADALAAAKIAAAHIhPAAQABAHACAFQADAGAEADQAFAEAFACQAFABAEAAQAJAAAIgDQAGgDAHgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgKgEgAAcgGQgBgHgCgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgEAAgFADQgEACgEADQgFAEgBAGQgDAFgBAHIA3AAIAAAAg");
	this.shape_39.setTransform(-113.2,13.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAkBKIgkhoIgjBoIgWAAIgziSIAcAAIAjBrIAkhsIAUAAIAkBsIAjhrIAbAAIgzCSg");
	this.shape_40.setTransform(-128.9,11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-149.5,0,297,46);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape.setTransform(111.4,20.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgWAuQgGgDgEgFQgFgFgCgGQgCgIAAgHIAAg7IAWAAIAAA0QAAAFABAFQABAEADADQADADADACQAEABAEAAQAEAAAEgBQAEgCACgDQADgDACgFQABgEAAgGIAAgzIAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIAEQgDABgFAAQgIAAgHgCg");
	this.shape_1.setTransform(101.4,20.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAJIAAA6g");
	this.shape_2.setTransform(90.4,20.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEANAAAFIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAEAFADQAFACAFAAQAGAAAFgCQAGgDADgEQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_3.setTransform(78.9,20.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AgzA+IAAh8IA2AAQALAAAJAEQAIADAGAEQAEAFACAFQACAFAAAHIAAAAQAAAGgBAEQgCAEgDAEQgEAGgIAEIALACQAEADADADQAEAEABAFQACAFAAAGIAAABQAAAIgDAHQgDAGgHAEQgGAFgIACQgJACgLAAgAgdArIAiAAIALgBIAHgDQAEgDACgDQABgDAAgFIAAAAQAAgEgBgDQgCgDgEgCQgDgDgEgBIgMgBIghAAgAgdgJIAdAAIAJgBIAIgCIAEgGQACgDAAgFIAAAAQAAgEgCgDQgBgDgDgBIgHgEIgJgBIgeAAg");
	this.shape_4.setTransform(66.9,19.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_5.setTransform(50.8,19.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAJIAAA6g");
	this.shape_6.setTransform(41.7,20.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AgWAuQgGgDgEgFQgFgFgCgGQgCgIAAgHIAAg7IAWAAIAAA0QAAAFABAFQABAEADADQADADADACQAEABAEAAQAEAAAEgBQAEgCACgDQADgDACgFQABgEAAgGIAAgzIAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIAEQgDABgFAAQgIAAgHgCg");
	this.shape_7.setTransform(30.5,20.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEANAAAFIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAEAFADQAFACAFAAQAGAAAFgCQAGgDADgEQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_8.setTransform(19.1,20.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgDAwIgKgDQgJgDgGgIQgHgGgEgJQgEgJAAgKIAAAAQAAgIAEgKQAEgIAHgHQAHgIAIgDIAKgDIAIgBIAMABIAKADQAGAEAKAJIgNAOQgHgGgFgDQgGgDgHAAQgFAAgEACQgFADgEAEQgEAEgCAFQgCAGAAAFQAAAGACAGQACAFAEAEQAEAEAFADQAEACAFAAQAIAAAHgDQAFgDAGgFIAMANQgKAJgGADIgKAEIgMABg");
	this.shape_9.setTransform(8.4,20.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgDAwIgKgDQgJgDgGgIQgHgGgEgJQgEgJAAgKIAAAAQAAgIAEgKQAEgIAHgHQAGgIAJgDIAKgDIAIgBIAMABIAKADQAGAEAKAJIgNAOQgGgGgGgDQgGgDgHAAQgFAAgEACQgFADgEAEQgDAEgDAFQgCAGAAAFQAAAGACAGQADAFADAEQAEAEAFADQAEACAGAAQAHAAAGgDQAGgDAGgFIAMANQgKAJgGADIgKAEIgMABg");
	this.shape_10.setTransform(-1.6,20.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AAqA/IgNgfIg6AAIgNAfIgWAAIA3h9IATAAIA3B9gAAVANIgVgwIgVAwIAqAAg");
	this.shape_11.setTransform(-13.5,19.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AAUAwIgUg/IgUA/IgUAAIgeheIAWAAIATA/IAVhAIARAAIAVBAIATg/IAWAAIgfBeg");
	this.shape_12.setTransform(-33.7,20.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQAAgIAEgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAJQADAJABAJIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAIACQAHgBAGgCQAGgEAHgFIAMAMIgIAHIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQAAgGgCgEIgGgIQgDgEgDgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_13.setTransform(-46.4,20.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AAkA+IhEhXIAABXIgVAAIAAh8IAUAAIBCBWIAAhWIAVAAIAAB8g");
	this.shape_14.setTransform(-58.9,19.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgLA/IgKgDIgKgHIgIgHIgGgKIgFgLIgCgMIgBgNIAAAAIABgLIACgNIAFgLIAHgKIAIgIIAJgFIALgFIAKgBIALABIALAFIAJAFIAIAIIAHAKIAEALQAEAQAAAIIAAAAIgBANIgDAMIgEALIgHAJIgIAIIgJAHIgLADIgLABIgLgBgAgMgoQgGADgEAHQgEAGgCAHQgDAJAAAIIAAAAQAAAJADAIQACAIAEAHQAEAFAGAEQAGAEAGgBQAHABAGgEQAGgDAEgGQAEgHACgIQACgIAAgJIAAAAQAAgHgCgJQgCgJgEgFQgFgHgGgDQgGgDgGgBQgGABgGADg");
	this.shape_15.setTransform(-77.9,19.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgLA/IgKgDIgKgHIgIgHIgGgKIgFgLIgCgMIgBgNIAAAAIABgLIACgNIAFgLIAHgKIAIgIIAJgFIALgFIAKgBIALABIALAFIAJAFIAIAIIAHAKIAEALQAEAQAAAIIAAAAIgBANIgDAMIgEALIgHAJIgIAIIgJAHIgLADIgLABIgLgBgAgMgoQgGADgEAHQgEAGgCAHQgDAJAAAIIAAAAQAAAJADAIQACAIAEAHQAEAFAGAEQAGAEAGgBQAHABAGgEQAGgDAEgGQAEgHACgIQACgIAAgJIAAAAQAAgHgCgJQgCgJgEgFQgFgHgGgDQgGgDgGgBQgGABgGADg");
	this.shape_16.setTransform(-90.9,19.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AACA/IAAhnIgUAHIgFgSIAggLIAPAAIAAB9g");
	this.shape_17.setTransform(-101.6,19.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgEBNIAAgSQgQgEgHgCQgLgFgJgHIAMgQQAIAGAHADQAIAEAIACIAAgjIgRgFQgHgDgFgEQgFgEgCgGQgCgFAAgIIAAAAQAAgIADgGQACgGAFgEQAFgFAHgDQAHgCAJgBIAAgKIANAAIAAALQAKABAIADQAIADAIAGIgKARIgMgIQgGgDgGAAIAAAiIARAFQAIAEAEACQAFAFACAFQADAHAAAHQAAAIgDAFQgDAHgFAEQgFAEgHADQgHADgJABIAAASgAAJApQAIgBAFgEQAEgEAAgHIAAAAQAAgGgDgEQgEgEgKgDgAgRgqQgEAEAAAGIAAAAQAAAHADADQAEAEAKADIAAggQgIABgFAEg");
	this.shape_18.setTransform(-110.4,19.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgJAsIAAgjIgjAAIAAgSIAjAAIAAgiIATAAIAAAiIAiAAIAAASIgiAAIAAAjg");
	this.shape_19.setTransform(67.8,-0.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AgXA8QgLgDgJgGIAIgQQAIAFAIACQAIADAKAAQAFAAAGgCQAFgCAFgEQADgDACgGQACgFAAgHIAAgIQgJAKgFADQgEACgFABIgIACQgJAAgIgDQgHgDgGgGQgHgGgDgIQgDgHgBgKIAAAAQABgHADgMQADgIAHgGQAGgFAHgDQAIgEAJAAQAEABAEABIAJAEQAIADAGAHIAAgOIAVAAIAABKQAAAMgCAJQgEAJgFAGIgIAFIgJAFQgOACgHAAQgLABgLgDgAgKgqQgEADgEADQgDAEgCAEQgCAFAAAGIAAAAQAAAGACAFQACAFADABQAEAEAFACQAFABAEAAQAFAAAFgBQAFgCAEgEQAEgBACgFQACgFAAgGIAAAAQAAgGgCgFQgCgEgEgEQgEgEgFgBQgFgCgFAAQgEAAgGABg");
	this.shape_20.setTransform(50.5,2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AAVAwIAAg0QAAgFgCgFIgEgHQgCgDgEgCQgEgBgFAAQgDAAgDABQgEACgDADQgDADgCAEQgBAFAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgDIAIgCQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAJIAAA6g");
	this.shape_21.setTransform(39.1,0.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_22.setTransform(31,-1.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AASBBIgZgpIgOAOIAAAbIgWAAIAAiBIAWAAIAABMIAmgoIAaAAIgmAlIAnA4g");
	this.shape_23.setTransform(23.8,-1.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AgEAwIgJgDQgJgDgGgIQgHgGgEgJQgDgJAAgKIAAAAQAAgJADgJQAEgJAHgHQAGgGAJgEIAJgDIAJgBIAMABIAKADQAHADAJAKIgOAOQgGgGgFgDQgFgDgJAAQgEAAgEACQgFADgEAEQgDAEgCAGQgDAFAAAFQAAAGADAGQACAFADAEQAEAEAFACQAEADAGAAQAHAAAGgDQAGgDAFgGIAOAOQgLAJgGADIgKAEIgNABg");
	this.shape_24.setTransform(13,0.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgPAtQgJgDgHgHQgGgGgEgJIgCgKIgCgKIAAAAQAAgJAEgJQAEgJAGgHQAGgGAIgEIAJgDIAIgBIALABIAJADQAGADAIAIQAFAHADAJQAEAKAAAIIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAIACQAHAAAGgEQAGgDAHgFIAMAMIgIAHIgIAFIgLAEIgMABQgIAAgJgEgAAYgFQAAgFgDgFIgFgIQgDgDgDgCQgFgCgFAAQgDAAgEACQgFACgDADQgDADgCAEIgDALIAvAAIAAAAg");
	this.shape_25.setTransform(2.3,0.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AAVBBIAAg2QAAgFgCgFIgEgFQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCADQgBAEAAAGIAAA1IgWAAIAAiBIAWAAIAAAzQAFgIAGgEIAIgDIAIgCQAIAAAHADQAGACAEAFQAFAFACAHQACAGAAAHIAAA8g");
	this.shape_26.setTransform(-8.7,-1.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AgFA/IgNgDIgKgGIgKgIIgIgKIgFgLQgDgGgBgGIgBgNIAAAAIABgLQABgHADgGIAFgLIAIgJIAJgJIAMgGIAMgDIAMgBQAIgBAIACQAHABAGADQAIAEAMAKIgOARQgIgJgIgDIgJgDIgKgCQgHABgIADQgHADgGAGQgGAHgDAIQgDAIAAAIIAAAAQAAAJADAIQADAIAGAGQAFAGAIAEQAIADAHAAIAKgBIAKgDQAHgEAJgIIAOAPIgKAJQgGAEgGADQgGACgHACQgHACgJgBIgLgBg");
	this.shape_27.setTransform(-20.7,-0.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgPAtQgJgDgHgHQgGgGgEgJIgCgKIgBgKIAAAAQgBgJAEgJQAEgJAFgHQAHgGAIgEIAJgDIAIgBIAKABIAKADQAGADAIAIQAFAHAEAJQACAKAAAIIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIACQAIAAAHgEQAGgDAFgFIANAMIgHAHIgJAFIgKAEIgNABQgIAAgJgEgAAYgFQgBgFgCgFIgEgIQgDgDgFgCQgEgCgFAAQgDAAgEACQgEACgEADQgDADgCAEIgDALIAvAAIAAAAg");
	this.shape_28.setTransform(-38.3,0.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("AgPAtQgJgDgGgHQgHgGgEgJIgDgKIgBgKIAAAAQABgJADgJQADgJAHgHQAGgGAIgEIAJgDIAIgBIALABIAJADQAGADAIAIQAFAHADAJQADAKAAAIIAAAGIhEAAQABAGACAEQADAFAEADIAIAFIAIACQAHAAAGgEQAHgDAGgFIAMAMIgIAHIgIAFIgLAEIgMABQgIAAgJgEgAAYgFQAAgFgCgFIgGgIQgCgDgFgCQgEgCgFAAQgDAAgFACQgEACgDADQgDADgCAEIgDALIAvAAIAAAAg");
	this.shape_29.setTransform(-49.2,0.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgaAwIAAhdIAWAAIAAAVQACgFACgFQACgEAFgDQAEgDAFgBQAFgCAGAAIAAAXIgBAAQgHAAgGADQgGACgEAEQgDAGgCAHQgCAEAAAKIAAAkg");
	this.shape_30.setTransform(-57.6,0.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AgtA/IAAh9IBbAAIAAAUIhFAAIAAAjIA9AAIAAASIg9AAIAAA0g");
	this.shape_31.setTransform(-67.2,-0.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139,-11,278,42);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A3WzcMAutAAAMAAAAm5MgutAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.5,-125.5,301,251);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.parent = this;
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201706_Reasons_300x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(280,141,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.893,0.893);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(67,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(233,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border300x250();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A3TMGIAA4MMAunAAAIAAYMg");
	var mask_graphics_80 = new cjs.Graphics().p("A3TMGIAA4MMAunAAAIAAYMg");
	var mask_graphics_81 = new cjs.Graphics().p("A3QLwIAA3fMAumAAAIAAXfg");
	var mask_graphics_82 = new cjs.Graphics().p("A3QLaIAA2zMAumAAAIAAWzg");
	var mask_graphics_83 = new cjs.Graphics().p("A3QLEIAA2HMAumAAAIAAWHg");
	var mask_graphics_84 = new cjs.Graphics().p("A3QKuIAA1bMAumAAAIAAVbg");
	var mask_graphics_85 = new cjs.Graphics().p("A3QKXIAA0tMAumAAAIAAUtg");
	var mask_graphics_86 = new cjs.Graphics().p("A3QKBIAA0BMAumAAAIAAUBg");
	var mask_graphics_87 = new cjs.Graphics().p("A3QJrIAAzVMAumAAAIAATVg");
	var mask_graphics_88 = new cjs.Graphics().p("A3QJVIAAypMAumAAAIAASpg");
	var mask_graphics_89 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_169 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_170 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_171 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_172 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_173 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_174 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_175 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_176 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_177 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_178 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:149.7,y:77.5}).wait(80).to({graphics:mask_graphics_80,x:149.7,y:77.5}).wait(1).to({graphics:mask_graphics_81,x:149.5,y:75.3}).wait(1).to({graphics:mask_graphics_82,x:149.5,y:73}).wait(1).to({graphics:mask_graphics_83,x:149.5,y:70.8}).wait(1).to({graphics:mask_graphics_84,x:149.5,y:68.6}).wait(1).to({graphics:mask_graphics_85,x:149.5,y:66.4}).wait(1).to({graphics:mask_graphics_86,x:149.5,y:64.1}).wait(1).to({graphics:mask_graphics_87,x:149.5,y:61.9}).wait(1).to({graphics:mask_graphics_88,x:149.5,y:59.7}).wait(1).to({graphics:mask_graphics_89,x:149.5,y:57.5}).wait(80).to({graphics:mask_graphics_169,x:149.5,y:57.5}).wait(1).to({graphics:mask_graphics_170,x:149.5,y:44.7}).wait(1).to({graphics:mask_graphics_171,x:149.5,y:32}).wait(1).to({graphics:mask_graphics_172,x:149.5,y:19.3}).wait(1).to({graphics:mask_graphics_173,x:149.5,y:6.6}).wait(1).to({graphics:mask_graphics_174,x:149.5,y:-6.1}).wait(1).to({graphics:mask_graphics_175,x:149.5,y:-18.8}).wait(1).to({graphics:mask_graphics_176,x:149.5,y:-31.6}).wait(1).to({graphics:mask_graphics_177,x:149.5,y:-44.3}).wait(1).to({graphics:mask_graphics_178,x:149.5,y:-57}).wait(4).to({graphics:null,x:0,y:0}).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(132,57,1,1,0,0,0,150,57);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({y:45},9).wait(80).to({regX:150.1,regY:57.1,x:132.1,y:45.1},0).to({y:-69.4},9).to({_off:true},1).wait(4));

	// shad
	this.instance_4 = new lib.HTML5rastershad_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(156,164,1,1,0,0,0,0,10);
	this.instance_4.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:124},9).wait(80).to({y:10},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(271,197,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({y:162},9).wait(80).to({y:51},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_6 = new lib.CTA();
	this.instance_6.parent = this;
	this.instance_6.setTransform(269.5,237,1,1,0,0,0,119.5,40);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({_off:false},0).wait(79).to({y:130},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,116.7,0.893,0.833,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(169).to({y:16.7},9).to({_off:true},4).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,220.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(413.6,227.7,1.225,1.225,0,0,0,215.2,63);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.parent = this;
	this.instance_10.setTransform(253.3,207.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},182).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.5,234.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(138,125,336,250);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;