(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/BigDeal336x280.jpg?1497642020988", id:"BigDeal336x280"},
		{src:"images/HTML5rastershad.png?1497642020988", id:"HTML5rastershad"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.BigDeal336x280 = function() {
	this.initialize(img.BigDeal336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,165);


(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACPAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgFAAgFgCgAAwAXQgFgFAAgGQAAgIAFgEQAGgCAJAAQAFAAAKACIAAgBQAAgNgPAAQgGAAgHAEIgDgGQAJgEAIAAQAKAAAGAFQAEAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgFgDgAAyALQAAAKAMAAQAGAAAFgEQAFgDAAgGIAAgEQgIgCgGAAQgOAAAAAJgAgjAUQgHgHAAgLQABgIAGgHQAGgHAKAAQAJAAAHAHQADAHAAAIIAAADIgjAAQABAHAFAEQAEAEAHAAQAIAAAGgGIAEAEQgHAIgLAAQgKAAgHgGgAgFAAQgBgOgNAAQgHAAgDAEQgFAEgBAGIAeAAIAAAAgAhfAUQgGgHAAgLQAAgJAGgHQAHgGAJAAQAKAAAIAKIAAgcIAHAAIAAA/IgHAAIAAgJQgHAKgLAAQgJAAgHgGgAhZgJQgFAFAAAGIAAAAQAAAIAFAFQAFAFAGAAQAHAAAFgFQAFgFAAgIIAAAAQAAgGgFgFQgFgFgHAAQgHAAgEAFgAiUAUQgHgHABgLQAAgIAFgHQAHgHAJAAQALAAAGAHQAGAHAAAIIgBADIglAAQACAPAOAAQAJAAAHgGIADAEQgHAIgMAAQgKAAgGgGgAh1AAQgCgOgOAAQgFAAgFAEQgDAEgCAGIAfAAIAAAAgAB7AZIAAg/IAHAAIAAA/gABjAZIAAg/IAIAAIAAA/gAAMAZIAAgsIAHAAIAAAMQAHgNAMAAIAAAHIAAAAQgIAAgFAGQgFAGgBAIIAAASgAi1AZIAAgmIgHAAIAAgGIAHAAIAAgEQAAgIADgEQAFgEAFAAIAIABIAAAGIgHgBQgHAAgBAKIAAAEIAPAAIAAAGIgPAAIAAAmg");
	this.shape.setTransform(-36.4,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA+AlIADgFQADABAEABQAGAAADgJIgUgsIAHAAIARAkIAPgkIAHAAIgTAtQgFANgLAAQgGAAgEgCgAE2AXQgGgFAAgHQAAgNAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAEAAAKIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAE3ALQAAAJAMAAQAGABAFgEQAEgDABgGIAAgFQgIgCgGAAQgOAAAAAKgAD7AIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgADNATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgIgHgGAAQgIABgEAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgAAPAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAIgBAGAHQAIAHgBAIIAAABQABALgIAGQgGAHgIAAQgMAAgGgKgAATgJQgEAFAAAFIAAABQAAAHAEAGQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgAhJATQgHgGAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgHgAhEgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAh+ATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAhgAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAjYAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAkNATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgACzAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAilAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgAkfAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAlXAZIAAgsIAHAAIAAAsgAlYgdIAAgIIAIAAIAAAIg");
	this.shape_1.setTransform(20.8,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSAUIAAgnIAlAAIAAAng");
	this.shape.setTransform(212.7,21.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZBJQgOgFgLgLQgLgKgGgPIgEgPIgCgRIAAAAQAAgPAGgPQAFgOAKgLQAKgLAOgGIAOgFIAOgBQAJAAAIABQAIACAHAEQAJAEAOAOQAJAKAFAQQAFAOAAAPIgBAKIhvAAQACAJAEAHQAEAIAFAEQAGAFAIADQAHADAGAAQANAAAKgFQAKgEAJgKIAVATIgMAMQgHAFgIAEQgHADgJACQgKADgKAAQgOgBgPgGgAAngJQgBgJgDgHQgDgHgFgGQgFgGgHgDQgHgDgIAAQgGAAgHADQgHADgFAFQgFAGgDAIQgEAHgBAJIBNAAIAAAAg");
	this.shape_1.setTransform(200.4,15.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrBOIAAiXIAjAAIAAAiQADgJAFgGQAEgIAGgFQAHgFAJgCQAIgDAKABIAAAlIgCAAQgMAAgJAEQgKADgHAIQgFAIgDALQgEAKAAAOIAAA7g");
	this.shape_2.setTransform(186.8,15.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZBJQgOgFgLgLQgLgKgGgPIgEgPIgCgRIAAAAQAAgPAGgPQAFgOAKgLQAKgLAOgGIAOgFIAOgBQAJAAAIABQAIACAHAEQAJAEAOAOQAJAKAFAQQAFAOAAAPIgBAKIhvAAQACAJAEAHQAEAIAFAEQAGAFAIADQAHADAGAAQANAAAKgFQAKgEAJgKIAVATIgMAMQgHAFgIAEQgHADgJACQgKADgKAAQgOgBgPgGgAAngJQgBgJgDgHQgDgHgFgGQgFgGgHgDQgHgDgIAAQgGAAgHADQgHADgFAFQgFAGgDAIQgEAHgBAJIBNAAIAAAAg");
	this.shape_3.setTransform(171.4,15.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAhBpIAAhXQAAgJgCgHQgCgEgEgFQgFgFgGgDQgGgCgIAAQgFAAgHACQgGADgEAFQgFAFgDAFQgCAHAAAJIAABWIgjAAIAAjRIAjAAIAABSQAIgNALgGQAGgEAHgCQAFgCAJAAQANAAAKAEQAKAEAHAIQAHAIAEAKQADALAAAMIAABhg");
	this.shape_4.setTransform(153.8,12.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQBpIAAjRIAhAAIAADRg");
	this.shape_5.setTransform(131.9,12.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiBLQgKgDgHgGQgIgGgEgJQgEgJAAgLIAAAAQAAgNAEgJQAFgJAIgEQAJgHALgDQALgDAPAAQAOAAAZAHIAAgEQAAgIgDgHQgCgGgFgEQgFgEgHgCQgHgDgHAAQgMAAgLADQgJACgMAFIgKgbQAOgHANgDQAPgDAPAAQAQAAANAFQANAEAIAIQAIAIAFAMQADAMAAAPIAABZIgiAAIAAgTQgIAKgMAGQgPAHgMAAQgLAAgKgEgAgNAFQgGACgFADQgEAEgDAEQgCAFAAAGIAAABQAAALAJAGQAHAGANAAQAHAAAIgDQAHgCAFgEQAGgFADgGQAEgGAAgHIAAgKQgVgGgOAAQgHAAgHABg");
	this.shape_6.setTransform(118.9,15.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZBJQgOgFgLgLQgLgKgGgPIgEgPIgCgRIAAAAQAAgPAGgPQAFgOAKgLQAKgLAOgGIAOgFIAOgBQAJAAAIABQAIACAHAEQAJAEAOAOQAJAKAFAQQAFAOAAAPIgBAKIhvAAQACAJAEAHQAEAIAFAEQAGAFAIADQAHADAGAAQANAAAKgFQAKgEAJgKIAVATIgMAMQgHAFgIAEQgHADgJACQgKADgKAAQgOgBgPgGgAAngJQgBgJgDgHQgDgHgFgGQgFgGgHgDQgHgDgIAAQgGAAgHADQgHADgFAFQgFAGgDAIQgEAHgBAJIBNAAIAAAAg");
	this.shape_7.setTransform(102,15.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AghBmQgNgGgJgKQgLgKgGgPIgEgQIgCgSIAAgBQAAgMAGgTQAGgOAKgLQAKgKANgGQANgFANAAQAIAAAIADQAHACAHADQALAHAKAMIAAhSIAjAAIAADSIgjAAIAAgaQgKAOgLAGQgHAFgHACQgIACgIAAQgNAAgNgFgAgPgRQgIADgGAHQgGAGgEAHQgDAJAAALIAAABQAAALADAKQAEAIAGAHQAGAGAIAEQAIADAHAAQAJAAAIgEQAIgDAGgHQAGgGAEgIQADgKAAgLIAAgBQAAgKgDgKQgEgHgGgGQgGgHgIgDQgIgEgJABQgHgBgIAEg");
	this.shape_8.setTransform(83.1,12.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgmBhQgRgFgPgJIANgaQANAIANAEQANAEAQAAQAJAAAJgDQAJgDAHgGQAGgGADgJQADgJAAgLIAAgMQgOAPgIAFQgHAEgIACQgHACgIAAQgOAAgMgFQgNgFgJgJQgKgJgGgNQgGgMAAgRIAAAAQAAgLAGgTQAGgNAKgKQAKgJAMgFQANgFANAAQAIAAAIACQAHACAHAEQAMAGAKAMIAAgXIAjAAIAAB4QAAATgFAPQgFAOgKAKQgFAFgGAEQgHAEgIACQgXAFgMAAQgSAAgSgEgAgQhEQgIADgGAGQgGAGgDAHQgDAIAAAKIAAAAQAAAJADAIQADAIAHAEQAGAFAHADQAIADAIAAQAIAAAJgDQAIgDAGgFQAGgEAEgIQADgIAAgJIAAAAQAAgKgDgIQgEgHgGgGQgGgFgIgDQgJgDgIAAQgIAAgIACg");
	this.shape_9.setTransform(55,17.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQBpIAAiXIAhAAIAACXgAgRhGIAAgiIAkAAIAAAig");
	this.shape_10.setTransform(41.6,12.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIBpQgHgCgHgFQgLgGgKgNIAAAZIgjAAIAAjSIAjAAIAABUQAKgNALgIQAHgDAHgCQAIgDAIAAQANAAANAFQANAGAKAKQAKALAGAOQAGATAAAMIAAABIgCASIgEAQQgGAPgKAKQgKAKgNAGQgNAFgNAAQgIAAgIgCgAgQgRQgIADgGAHQgGAHgEAGQgEAKAAAKIAAABQAAALAEAKQAEAIAGAGQAGAHAIADQAIAEAIAAQAIAAAIgDQAIgEAGgGQAGgHAEgIQADgKAAgLIAAgBQAAgKgEgKQgDgHgGgGQgGgHgIgDQgIgEgIABQgIgBgIAEg");
	this.shape_11.setTransform(28.1,12.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgiBLQgKgDgIgGQgHgGgEgJQgEgJgBgLIAAAAQABgNAEgJQAFgJAIgEQAIgHAMgDQAMgDANAAQAQAAAYAHIAAgEQAAgIgCgHQgDgGgFgEQgFgEgHgCQgHgDgHAAQgMAAgMADQgJACgLAFIgJgbQAOgHAMgDQAPgDAOAAQARAAANAFQANAEAIAIQAJAIADAMQAEAMABAPIAABZIgiAAIAAgTQgJAKgLAGQgRAHgMAAQgLAAgJgEgAgNAFQgGACgFADQgFAEgCAEQgCAFgBAGIAAABQAAALAJAGQAJAGAMAAQAHAAAHgDQAIgCAGgEQAFgFADgGQADgGABgHIAAgKQgWgGgOAAQgGAAgHABg");
	this.shape_12.setTransform(0.4,15.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaBqIAAh5IgUAAIAAgdIAUAAIAAgLQAAgNADgJQADgKAGgGQAGgGAIgDQAHgDAMAAQAOAAAOAEIAAAdQgLgDgKAAQgKAAgFAFQgFAGAAAMIAAAIIApAAIAAAdIgoAAIAAB5g");
	this.shape_13.setTransform(-21.6,12.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgQBOIgPgFQgPgGgLgLQgLgKgGgPIgFgPIgBgQIAAAAQAAgJAGgUQAGgPALgKQALgMAPgGIAQgFIAPgBQALAAAVAGQAPAGALALQALALAGAOQAGAUAAAKIAAAAIgBAQIgFAOQgGAPgLALQgLALgPAGQgVAHgLAAgAgSgsQgIAEgHAHQgGAHgDAJQgDAIAAAJIAAAAQAAAKAEAJQADAJAGAGQAHAHAIAEQAJAEAIgBQAKABAJgEQAIgEAHgGQAGgHADgJQADgJAAgKIAAAAQAAgIgDgJQgEgJgGgHQgHgHgIgDQgJgFgJAAQgJAAgJAEg");
	this.shape_14.setTransform(-36.9,15.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AghBmQgNgGgJgKQgLgKgGgPIgEgQIgCgSIAAgBQAAgMAGgTQAGgOAKgLQAKgKANgGQANgFANAAQAIAAAIADQAHACAHADQALAHAKAMIAAhSIAjAAIAADSIgjAAIAAgaQgKAOgLAGQgHAFgHACQgIACgIAAQgNAAgNgFgAgPgRQgIADgGAHQgGAGgEAHQgDAJAAALIAAABQAAALADAKQAEAIAGAHQAGAGAIAEQAIADAHAAQAJAAAIgEQAIgDAGgHQAGgGAEgIQADgKAAgLIAAgBQAAgKgDgKQgEgHgGgGQgGgHgIgDQgIgEgJABQgHgBgIAEg");
	this.shape_15.setTransform(-65.2,12.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAhBOIAAhVQAAgJgCgHQgCgHgEgFQgFgFgGgCQgGgDgIAAQgFAAgHADQgGADgEAEQgFAFgDAHQgCAIAAAIIAABVIgjAAIAAiXIAjAAIAAAXQAIgMALgHQAGgDAHgCQAFgDAJAAQANAAAKAFQAKAEAHAHQAHAIAEALQADALAAANIAABgg");
	this.shape_16.setTransform(-83.4,15.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgQBpIAAiXIAhAAIAACXgAgRhGIAAgiIAkAAIAAAig");
	this.shape_17.setTransform(-96.6,12.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAeBpIgrhCIgWAWIAAAsIgjAAIAAjRIAjAAIAAB8IA9hCIArAAIg9A8IA/Bbg");
	this.shape_18.setTransform(-108.2,12.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgZBJQgOgFgLgLQgLgKgGgPIgEgPIgCgRIAAAAQAAgPAGgPQAFgOAKgLQAKgLAOgGIAOgFIAOgBQAJAAAIABQAIACAHAEQAJAEAOAOQAJAKAFAQQAFAOAAAPIgBAKIhvAAQACAJAEAHQAEAIAFAEQAGAFAIADQAHADAGAAQANAAAKgFQAKgEAJgKIAVATIgMAMQgHAFgIAEQgHADgJACQgKADgKAAQgOgBgPgGgAAngJQgBgJgDgHQgDgHgFgGQgFgGgHgDQgHgDgIAAQgGAAgHADQgHADgFAFQgFAGgDAIQgEAHgBAJIBNAAIAAAAg");
	this.shape_19.setTransform(-135,15.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgrBOIAAiXIAjAAIAAAiQADgJAFgGQAEgIAGgFQAHgFAJgCQAIgDAKABIAAAlIgCAAQgMAAgJAEQgKADgHAIQgFAIgDALQgEAKAAAOIAAA7g");
	this.shape_20.setTransform(-148.6,15.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgXAaQANgDAHgGQAEgIgBgJIgNAAIAAgoIAlAAIAAAiQAAAKgDAJQgDAJgGAGQgFAFgHAEQgIACgLABg");
	this.shape_21.setTransform(-159.5,7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgkBJQgKgEgHgIQgHgHgDgLQgFgLAAgNIAAhgIAkAAIAABVQAAAJACAHQADAHADAFQAFAEAFADQAHACAHAAQAGAAAGgCQAHgDAEgFQAFgFACgHQADgHAAgIIAAhVIAjAAIAACXIgjAAIAAgYQgIANgLAGQgFAEgIACQgFADgJAAQgNAAgKgFg");
	this.shape_22.setTransform(-172.1,15.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgQBOIgPgFQgPgGgLgLQgLgKgGgPIgFgPIgBgQIAAAAQAAgJAGgUQAGgPALgKQALgMAPgGIAQgFIAPgBQALAAAVAGQAPAGALALQALALAGAOQAGAUAAAKIAAAAIgBAQIgFAOQgGAPgLALQgLALgPAGQgVAHgLAAgAgSgsQgIAEgHAHQgGAHgDAJQgDAIAAAJIAAAAQAAAKAEAJQADAJAGAGQAHAHAIAEQAJAEAIgBQAKABAJgEQAIgEAHgGQAGgHADgJQADgJAAgKIAAAAQAAgIgDgJQgEgJgGgHQgHgHgIgDQgJgFgJAAQgJAAgJAEg");
	this.shape_23.setTransform(-190.5,15.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQBlIAAhQIhRh5IAqAAIA3BaIA5haIApAAIhQB4IAABRg");
	this.shape_24.setTransform(-206.2,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-347.9,-2,696,33);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5169A8").s().p("EgoTAHzIAAvmMBQnAAAIAAPmg");
	this.shape.setTransform(432,50);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(174,0,516,100);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgKAMIAAgXIAVAAIAAAXg");
	this.shape.setTransform(167.5,16.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_1.setTransform(161.3,11.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_2.setTransform(155.2,10.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgQBCIAAhLIgMAAIAAgSIAMAAIAAgHQAAgIACgFQACgGAEgEQADgEAFgCQAEgCAHAAQAKAAAIADIAAASQgHgCgGAAQgGAAgDADQgDAEAAAHIAAAFIAYAAIAAASIgYAAIAABLg");
	this.shape_3.setTransform(149.5,10.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEAMAAAGIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFADgEAEQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFAAQAGAAAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_4.setTransform(140,12.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgEQACgFAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAHQgCAGAAAJIAAAkg");
	this.shape_5.setTransform(131.1,12.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgvA+IAAh8IAwAAQALAAAJAEQAIADAHAFQAGAGADAHQADAIAAAKIAAAAIAAAKIgDAIQgEAHgHAFQgHAGgJADQgJACgJAAIgZAAIAAAogAgZACIAZAAQAFAAAFgCQAFAAAEgCQADgEACgEQACgEAAgFIAAAAQAAgGgCgEQgCgEgDgDQgEgDgFgBQgFgBgFAAIgZAAg");
	this.shape_6.setTransform(121.5,11.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgEQACgFAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAHQgCAGAAAJIAAAkg");
	this.shape_7.setTransform(106.3,12.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEAMAAAGIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFADgEAEQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFAAQAGAAAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_8.setTransform(96.3,12.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgQBCIAAhLIgMAAIAAgSIAMAAIAAgHQAAgIACgFQACgGAEgEQAEgEAEgCQAEgCAHAAQAKAAAIADIAAASQgHgCgGAAQgGAAgEADQgDAEAAAHIAAAFIAaAAIAAASIgZAAIAABLg");
	this.shape_9.setTransform(87.5,10.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_10.setTransform(74.7,11.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEAMAAAGIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFADgEAEQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFAAQAGAAAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_11.setTransform(65.2,12.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAkA+IhEhXIAABXIgVAAIAAh8IAUAAIBCBWIAAhWIAVAAIAAB8g");
	this.shape_12.setTransform(52.2,11.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgLAMIAAgXIAXAAIAAAXg");
	this.shape_13.setTransform(37.3,16.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgUA/QgIgDgGgHQgHgGgDgJIgCgKIgBgLQAAgIADgLQADgJAHgHQAGgGAIgEQAIgDAJAAQADAAAFACQAFABAEACQAHAEAGAIIAAgzIAWAAIAACBIgWAAIAAgQQgGAJgHAEQgEADgFABQgFABgDAAQgJAAgIgDgAgJgKQgFACgEAEQgDAEgCAEQgDAGAAAHQAAAHADAFQACAGADAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgCAEgEQAEgEACgGQACgFAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_14.setTransform(28.7,10.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgGQgGgHgEgJIgCgJIgBgLIAAAAQgBgIAEgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAGACAIAKQAFAGAEAKQACAIAAAJIAAAGIhEAAQABAGADAFQACAEADADIAIAFQAFACADgBQAIAAAHgCQAGgDAFgGIANALIgHAIIgJAGIgKADIgNABQgIAAgJgDgAAYgFQgBgFgCgFIgEgIQgDgEgFgCQgEgBgFAAQgDAAgEABQgEACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_15.setTransform(17.5,12.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AAVAwIAAg0QAAgFgCgFIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAIIAAA7g");
	this.shape_16.setTransform(6.5,12.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AAUAwIgUg/IgUA/IgUAAIgeheIAWAAIATA/IAVhAIARAAIAVBAIATg/IAWAAIgfBeg");
	this.shape_17.setTransform(-6.8,12.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgNA/IgMgDIgLgHIgKgIIgIgJIgGgLIgDgMIgCgNIAAAAIACgLQABgHACgFIAHgMIAHgKIAKgIIALgFIANgFIAMgBIANABIAOAFIAKAFIAKAIIAIAKIAGALIADAMQACAGgBAGIAAAAQABAGgCAHIgDALIgGALIgIAKIgKAIIgLAHIgNADIgNACIgNgCgAgQgoQgHADgHAHQgFAGgDAIQgDAIAAAIIAAAAQAAAIADAJQADAIAGAGQAFAGAJAEQAHADAIAAQAJAAAIgDQAIgDAFgHQAGgGADgIQADgIAAgJIAAAAQAAgHgDgJQgDgIgGgGQgGgGgHgDQgJgFgIAAQgIAAgIAEg");
	this.shape_18.setTransform(-22.2,11.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgZAKIAAgTIAzAAIAAATg");
	this.shape_19.setTransform(-33.5,11.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgEQACgFAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAHQgCAGAAAJIAAAkg");
	this.shape_20.setTransform(-40.5,12.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AgPAuQgJgEgGgGQgHgHgEgJIgDgJIgBgLIAAAAQAAgIAEgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAKQADAIABAJIgBAGIhEAAQABAGACAFQADAEAEADIAIAFQAEACAEgBQAHAAAGgCQAGgDAHgGIAMALIgIAIIgIAGIgLADIgMABQgIAAgJgDgAAYgFQAAgFgCgFIgGgIQgDgEgDgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_21.setTransform(-50,12.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgEBBQgFgBgEgDQgHgEgGgIIAAAPIgWAAIAAiBIAWAAIAAA0QAGgIAHgFQAEgCAFgBQAEgCAFAAQAIAAAIADQAIAEAGAGQAGAHAEAJQAEALAAAIIgBALIgDAKQgDAJgHAGQgGAHgIADQgIADgIAAQgFAAgEgBgAgJgKQgFADgEAEQgEADgCAEQgCAGAAAHQAAAHACAFQACAGAEAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgCAEgEQADgEACgFQADgGAAgHQAAgHgDgGQgCgEgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_22.setTransform(-61.2,10.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AAyAwIAAg0QAAgFgBgFQgBgEgDgDIgGgFQgEgCgEAAQgFAAgDACQgEACgDADIgEAHQgBAFAAAGIAAAzIgUAAIAAg0QAAgFgCgFQgBgEgCgDQgDgDgDgCQgEgCgEAAQgFAAgEACQgDACgDADQgDADgBAFQgCAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAGgIAGgEQADgDAEgBQAFgBAFAAIAKABIAIAEQACABACAEIAFAHQAGgIAHgEIAJgEIAKgBQAHAAAHACQAGADAEAEQAEAFADAHQACAGAAAJIAAA7g");
	this.shape_23.setTransform(-76,12.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgGQgGgHgEgJIgDgJIAAgLIAAAAQAAgIADgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAGACAIAKQAGAGADAKQACAIAAAJIAAAGIhEAAQABAGADAFQACAEADADIAIAFQAGACACgBQAIAAAHgCQAFgDAGgGIANALIgHAIIgJAGIgKADIgNABQgIAAgJgDgAAYgFQAAgFgDgFIgEgIQgEgEgEgCQgEgBgFAAQgDAAgFABQgDACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_24.setTransform(-90,12.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AAnA+IAAhYIgnA6IAAAAIgng6IAABYIgVAAIAAh8IAYAAIAkA8IAmg8IAYAAIAAB8g");
	this.shape_25.setTransform(-103.2,11.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgOAQQAJgCAEgEQACgEgBgGIgIAAIAAgYIAXAAIAAAVQgBAFgBAGQgCAFgEAEQgDADgEACIgLADg");
	this.shape_26.setTransform(-119.1,17.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AgJBBIAAiBIATAAIAACBg");
	this.shape_27.setTransform(-123.8,10.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AgUAvQgHgCgFgEQgFgEgCgFQgCgGgBgHQAAgHAEgGQACgGAFgCQAFgEAIgCQAHgCAJAAQAIAAAPAEIAAgCQAAgFgCgEQgBgEgDgCQgDgDgEgBQgEgCgEAAQgIAAgHACIgMAEIgHgRQAKgEAHgBQAJgDAIAAQALAAAIADQAIADAFAFQAFAFACAIQAEAHAAAJIAAA3IgWAAIAAgMQgGAGgHAEQgJAEgHAAQgGAAgGgCgAgIADIgHADIgEAGQgBACAAAEQgBAHAGAEQAFAEAIAAQAEAAAEgCQAFgBADgDQADgCACgEQACgEAAgEIAAgHQgNgEgIAAIgIABg");
	this.shape_28.setTransform(-131.8,12.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgDAwIgKgDQgJgDgHgIQgGgGgEgJQgEgJAAgKIAAAAQAAgIAEgKQAEgIAGgHQAIgIAIgDIAKgDIAIgBIAMABIAKAEQAGACAKAKIgNAOQgHgGgFgCQgGgEgHAAQgFAAgEACQgFADgEAEQgEAEgCAFQgCAGAAAFQAAAGACAGQACAFAEAEQAEAFAFACQAEACAFAAQAIAAAHgDQAFgDAGgFIAMAMQgKAKgGADIgKAEIgMABg");
	this.shape_29.setTransform(-141.9,12.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEAMAAAGIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFADgEAEQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFAAQAGAAAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_30.setTransform(-153,12.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgrA+IAAh8IAXAAIAABoIBAAAIAAAUg");
	this.shape_31.setTransform(-163.9,11.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-215.5,1,431,22);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364.5,-45.5,729,91);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5169A8").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ax9ITIAAwlMAj7AAAIAAQlg");
	mask.setTransform(123,74.9);

	// pic
	this.instance = new lib.BigDeal336x280();
	this.instance.parent = this;
	this.instance.setTransform(-17,23,0.671,0.671);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(247.6,75.8,1,1,-90,0,0,0,10);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(7.9,-92.2,249.7,336);


// stage content:
(lib.SCU201706_BigDeal_728x90_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_179 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(179).call(this.frame_179).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(707,69,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,2.167,0.321);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},180).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.parent = this;
	this.instance.setTransform(474,80,1.11,1.11,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border728x90();
	this.instance_1.parent = this;
	this.instance_1.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},180).wait(1));

	// PIC
	this.instance_2 = new lib.pic();
	this.instance_2.parent = this;
	this.instance_2.setTransform(122,30,0.851,0.851,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(80).to({x:-76.3},9).to({_off:true},1).wait(91));

	// HEAD
	this.instance_3 = new lib.HEAD1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(564.5,39,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({x:368.5},9).wait(80).to({x:589.5},9).to({_off:true},2).wait(1));

	// CTA
	this.instance_4 = new lib.CTA();
	this.instance_4.parent = this;
	this.instance_4.setTransform(367.5,86,1,1,0,0,0,119.5,40);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(90).to({_off:false},0).wait(79).to({x:588.5},9).to({_off:true},2).wait(1));

	// shad
	this.instance_5 = new lib.HTML5rastershad_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(221,45,1,1,-90,0,0,0,10);
	this.instance_5.alpha = 0.199;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(80).to({x:-24},9).wait(80).to({x:205},9).to({_off:true},2).wait(1));

	// tag
	this.instance_7 = new lib._2016TAG();
	this.instance_7.parent = this;
	this.instance_7.setTransform(612.3,77,1.037,1.037,0,0,0,0,2.7);

	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(612.3,76.4,1.037,1.037,0,0,0,0,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_7,p:{x:612.3,y:77}}]},81).to({state:[{t:this.instance_8},{t:this.instance_7,p:{x:105.5,y:76.4}}]},88).to({state:[]},11).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(852.4,83.5,1.116,1.116,0,0,0,215.3,63.1);

	this.instance_10 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(852.4,83,1.116,1.116,0,0,0,215.3,63.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_9,p:{x:852.4,y:83.5}}]},81).to({state:[{t:this.instance_10},{t:this.instance_9,p:{x:345.6,y:83}}]},88).to({state:[]},11).wait(1));

	// logo rule
	this.instance_11 = new lib._2016_SCU_logoruleai();
	this.instance_11.parent = this;
	this.instance_11.setTransform(706,65,1.154,1.154,0,0,0,81.4,0.5);

	this.instance_12 = new lib._2016_SCU_logoruleai();
	this.instance_12.parent = this;
	this.instance_12.setTransform(706,64.5,1.154,1.154,0,0,0,81.4,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_11,p:{x:706,y:65}}]},81).to({state:[{t:this.instance_12},{t:this.instance_11,p:{x:199.3,y:64.5}}]},88).to({state:[]},11).wait(1));

	// shad
	this.instance_13 = new lib.HTML5rastershad_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(700,92,1,1,-90,0,0,0,10);
	this.instance_13.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(80).to({x:508,y:79.1},9).wait(92));

	// logo box
	this.instance_14 = new lib.box1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(324.8,29.5,2.165,0.639,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({_off:true},180).wait(1));

	// com
	this.instance_15 = new lib.comhoriz();
	this.instance_15.parent = this;
	this.instance_15.setTransform(640,82.7,0.687,0.687,0,0,0,0,4.5);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// EHO
	this.instance_16 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_16.parent = this;
	this.instance_16.setTransform(466.5,75,0.07,0.07,0,0,0,135,145);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(343.9,-52,813.1,357.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;