(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497567973350", id:"HTML5rastershad"},
		{src:"images/YourPlace336x280.jpg?1497567973350", id:"YourPlace336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.YourPlace336x280 = function() {
	this.initialize(img.YourPlace336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.YourPlace336x280();
	this.instance.parent = this;
	this.instance.setTransform(19,0,0.89,0.89);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(19,0,299,146.9);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVBfIAAglIAiAAIAAAlgAgNAjIgGgpIACgCQAMAAAIgCQAJgDAGgEQAGgDADgGQAEgFAAgHIAAAAQAAgGgDgFQgCgEgEgEQgEgDgFgCQgGgCgHAAQgLAAgLAGQgLAFgJAKIgVgVQAGgHAHgFQAHgGAIgEQAIgEAJgCQAKgCAIAAQAOAAAMAEQAMADAIAIQAJAHAEAKQAFAKAAANIAAAAQAAANgFAJQgEAJgHAHQgHAFgLAEQgJAEgMACIgCAVg");
	this.shape.setTransform(120.8,27);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaBEQgUgJgJgHIAOgWQAMAJAMAEQAMAFAJAAQAKAAAGgFQAGgEAAgHIAAAAQAAgIgKgFQgEgCgQgFQgVgHgJgFQgHgEgDgHQgEgHAAgKIAAgBQAAgKAEgIQADgIAHgGQAHgFAKgDQAJgDAIAAQAOAAAOAEQANAEAMAIIgNAXQgLgGgKgEQgLgDgIAAQgIAAgFAEQgFADAAAHIAAAAQAAAHAJAFIAVAJIAPAFQAJAEAGACQAHAFADAHQAEAHAAAJIAAABQAAALgEAIQgEAJgHAFQgHAGgKADQgKACgLAAQgNAAgQgFg");
	this.shape_1.setTransform(107.7,29.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoBIIAAiMIAhAAIAAAgQADgIAEgHQAEgGAGgFQAHgFAHgCQAIgCAJAAIAAAjIgCAAQgKAAgKADQgJAEgGAHQgEAHgEAKQgDAJAAAOIAAA2g");
	this.shape_2.setTransform(96.2,29.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghBEQgJgDgHgIQgHgHgDgKQgDgKAAgNIAAhYIAgAAIAABPQAAAIACAGQACAHAEAEQAEAFAFACQAHACAGAAQAGAAAFgCQAGgDAEgEQAFgFADgGQABgHAAgIIAAhOIAiAAIAACMIgiAAIAAgWQgHAMgKAGQgFADgHACQgFACgIAAQgMAAgJgEg");
	this.shape_3.setTransform(81.6,29.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPBIIgOgEQgOgGgKgKQgKgKgGgOIgEgNIgBgPIAAAAQAAgJAFgSQAGgNAKgLQALgKAOgGIAOgEIAOgCQALAAATAGQAOAFAKALQAKAKAGANQAGATAAAJIAAAAIgCAOIgEAOQgGANgKALQgLAKgNAGQgTAGgLAAgAgRgpQgHADgGAHQgFAGgDAJQgEAIAAAIIAAAAQAAAIAEAJQADAJAGAFQAGAHAHADQAJAEAHAAQAJAAAJgEQAHgDAHgHQAFgGADgHQADgJAAgJIAAAAQAAgIgDgIQgDgIgGgHQgGgHgIgDQgIgDgJAAQgIgBgJAEg");
	this.shape_4.setTransform(64.5,29.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgoBIIAAiMIAhAAIAAAgQADgIAEgHQAEgGAGgFQAGgFAIgCQAIgCAJAAIAAAjIgCAAQgLAAgJADQgJAEgGAHQgFAHgDAKQgDAJAAAOIAAA2g");
	this.shape_5.setTransform(42.6,29.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOBIIgPgEQgNgGgLgKQgKgKgFgOIgFgNIgCgPIAAAAQAAgJAHgSQAFgNALgLQAKgKANgGIAPgEIAOgCQALAAATAGQAOAFAKALQAKAKAGANQAFATAAAJIAAAAIgBAOIgEAOQgGANgKALQgLAKgNAGQgUAGgKAAgAgQgpQgIADgGAHQgGAGgDAJQgCAIAAAIIAAAAQAAAIACAJQAEAJAFAFQAHAHAIADQAHAEAIAAQAJAAAJgEQAIgDAFgHQAGgGADgHQADgJAAgJIAAAAQAAgIgDgIQgEgIgFgHQgGgHgIgDQgJgDgIAAQgJgBgHAEg");
	this.shape_6.setTransform(27.5,29.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBEQgNgFgKgKQgLgJgEgOIgFgOIgCgQIAAAAQABgOAFgNQAFgOAJgKQAJgKAOgGIAMgEIAOgCIAQACQAGABAHADQAIAEANANQAJAKAFAPQADANAAANIAAAKIhmAAQAAAIAEAIQAEAGAFAEQAGAFAHADQAHACAFAAQAMAAAKgEQAIgFAJgIIATARIgLALQgGAFgHADQgIAEgIACQgJACgJAAQgNAAgOgGgAAlgIQgBgJgEgHQgCgHgEgEQgFgGgHgCQgGgDgIgBQgFABgHADQgGACgFAFQgFAFgDAHQgDAHgBAJIBIAAIAAAAg");
	this.shape_7.setTransform(2.4,29.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgGBIIgOgEQgNgGgLgKQgKgKgFgOQgGgNAAgPIAAAAQAAgNAGgOQAFgNALgLQAKgKANgGIAOgEQAGgCAIAAQAKAAAIACQAIACAHADQAJAEAPANIgVAXQgIgJgIgFQgJgEgMAAQgHgBgHAEQgHADgGAHQgGAGgDAJQgDAIAAAIIAAAAQAAAJADAJQADAHAGAHQAGAGAIADQAGAEAJAAQALAAAJgFQAIgEAJgIIAUATQgPAPgJAEQgIAEgIACQgJACgKAAg");
	this.shape_8.setTransform(-12.9,29.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggBGQgJgDgHgFQgHgGgEgIQgEgIAAgLIAAAAQAAgMAEgIQAEgJAIgEQAIgFALgDQALgDANAAQAOAAAWAGIAAgEQAAgHgCgGQgDgGgEgEQgEgEgHgCQgGgCgHAAQgLAAgLADQgIACgLAEIgJgaQAOgFALgDQAOgDANAAQAQAAAMAEQAMAEAHAIQAIAHAEAMQAEALAAAOIAABSIggAAIAAgSQgIAKgLAFQgOAGgMAAQgKAAgJgDgAgMAFQgGACgEADQgFADgCAEQgCAFAAAFIAAABQAAAKAIAGQAHAFANAAQAFAAAIgCQAGgCAGgEQAFgEADgGQADgFAAgHIAAgKQgTgFgNAAQgHAAgGABg");
	this.shape_9.setTransform(-29,29.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgPBiIAAjDIAfAAIAADDg");
	this.shape_10.setTransform(-40.4,26.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhIBeIAAi4IAgAAIAAAYQAJgMALgHQAGgEAHgCQAHgCAHAAQANAAAMAFQAMAFAJAJQAJAKAGAOQAFATAAAMIAAABIgBAQIgEANQgGAOgJAJQgJAKgMAFQgMAFgNAAQgHAAgHgCQgHgCgGgEQgLgGgJgLIAABBgAgPg9QgHADgGAGQgGAGgDAJQgDAIAAAKIAAABQAAAKADAIQADAHAGAGQAGAGAHADQAIADAHAAQAIAAAHgDQAHgDAGgGQAGgGADgHQADgIAAgKIAAgBQAAgKgDgJQgDgIgGgGQgGgGgHgDQgIgDgHAAQgHAAgIADg");
	this.shape_11.setTransform(-52.9,31.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgoBIIAAiMIAgAAIAAAgQAEgIAEgHQADgGAHgFQAGgFAIgCQAIgCAJAAIAAAjIgBAAQgLAAgKADQgIAEgHAHQgEAHgDAKQgFAJAAAOIAAA2g");
	this.shape_12.setTransform(-75.4,29.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgiBEQgJgDgHgIQgGgHgDgKQgDgKAAgNIAAhYIAgAAIAABPQAAAIACAGQACAHAEAEQAEAFAFACQAGACAHAAQAFAAAGgCQAHgDADgEQAFgFACgGQACgHAAgIIAAhOIAhAAIAACMIghAAIAAgWQgHAMgJAGQgHADgGACQgFACgIAAQgMAAgKgEg");
	this.shape_13.setTransform(-90,29.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgOBIIgPgEQgNgGgLgKQgKgKgFgOIgFgNIgCgPIAAAAQAAgJAHgSQAFgNAKgLQALgKANgGIAPgEIAOgCQALAAATAGQAOAFAKALQAKAKAGANQAFATABAJIAAAAIgCAOIgEAOQgGANgKALQgLAKgNAGQgTAGgLAAgAgRgpQgHADgGAHQgGAGgDAJQgCAIAAAIIAAAAQAAAIACAJQAEAJAFAFQAGAHAJADQAHAEAIAAQAJAAAJgEQAIgDAFgHQAGgGADgHQADgJAAgJIAAAAQAAgIgDgIQgDgIgGgHQgGgHgIgDQgJgDgIAAQgIgBgJAEg");
	this.shape_14.setTransform(-107.1,29.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgPBeIAAhKIhLhxIAnAAIAzBTIA1hTIAmAAIhLBwIAABLg");
	this.shape_15.setTransform(-121.7,27.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,13,337,31);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgSAyQgQgGgHgGIAMgQQAIAGAJAEQAJADAGAAQAIAAAEgDQAFgDgBgFIAAgBQAAgFgHgEIgOgGQgQgEgHgEQgFgDgDgFQgCgFAAgIQAAgHACgGQADgGAGgFQAFgEAGgCQAIgCAFAAQAKAAAKADQAKADAJAGIgKARQgHgFgIgCQgHgDgHAAQgFAAgEADQgEADAAAEIAAABQAAAFAHAEIAPAGIALAEIALAEQAFAEACAFQAEAFAAAHIAAAAQAAAIgEAHQgCAGgGAEQgFAEgHACQgHACgJAAQgJAAgLgEg");
	this.shape.setTransform(119.3,26.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgDgEQgEgEgEgCQgGgCgFAAQgDAAgGACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_1.setTransform(108.4,26.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AAXBJIAAg8QAAgHgCgEQgBgDgDgDQgDgEgEgCQgFgBgFgBQgDABgEABQgFADgDADQgDADgCADQgCAFAAAGIAAA8IgYAAIAAiRIAYAAIAAA5QAGgIAIgFQADgDAFgBQAEgBAFAAQAKAAAHADQAGACAFAGQAFAFADAHQACAIAAAHIAABEg");
	this.shape_2.setTransform(96.2,24.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgEA2IgLgEQgJgEgIgHQgHgIgEgKQgEgKAAgLIAAAAQAAgKAEgKQAEgKAHgHQAIgIAKgEIAKgDQAEgCAGAAQAHAAAGACIALAEQAHADALAKIgPAQQgGgHgGgDQgHgDgJAAQgFAAgFACQgFADgEAFQgFAEgCAGQgCAGAAAGIAAAAQAAAHACAGQACAGAFAFQAEAEAGADQAEACAGAAQAJAAAHgDQAGgDAGgHIAOAPQgKALgHADIgMAEQgGACgIAAg");
	this.shape_3.setTransform(84.4,26.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AAXA2IAAg6QAAgHgBgEQgCgFgDgDQgDgEgEgCQgFgBgFgBQgDABgFABQgEADgDADQgDADgCAFQgCAFABAGIAAA6IgZAAIAAhoIAZAAIAAAQQAFgIAHgFQAFgDAEgBQAEgBAGAAQAIAAAHADQAHACAFAGQAFAFACAHQADAIAAAJIAABCg");
	this.shape_4.setTransform(72.4,26.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AgXA0QgHgCgFgEQgFgEgDgHQgDgGAAgHIAAgBQAAgIADgHQADgGAGgCQAGgFAIgCQAIgCAKAAQAJAAARAEIAAgCQAAgFgCgFQgBgEgEgDQgDgDgFgBQgFgCgEAAQgJAAgHACIgOAEIgHgTQAKgDAIgDQAKgCAKAAQAMAAAJADQAIADAGAGQAGAFADAJQACAIAAAKIAAA9IgXAAIAAgNQgGAHgIAEQgLAEgIAAQgHAAgHgCgAgIAEQgFABgDACQgDACgCAEQgBADAAAEIAAABQAAAHAGAFQAFADAJAAQAEAAAFgBQAFgBAEgDQAEgEACgEQACgEAAgFIAAgHQgOgFgKABQgDAAgFABg");
	this.shape_5.setTransform(60,26.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AgdA1IAAhnIAYAAIAAAXQACgGADgEQADgFAEgEQAFgDAFgCQAGgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_6.setTransform(51.3,26.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("Ag5BGIAAiLIA9AAQAMAAAJADQAKAEAGAGQAEAEADAHQACAFAAAHIAAABQAAAFgCAFQgBAGgDADQgFAHgJAEIALADIAJAIQAEAEACAFQACAGAAAGIAAABQAAAJgEAHQgDAIgHAEQgHAGgKACQgJADgMAAgAghAvIAnAAIAMgBQAFgBADgCQAEgCABgEQACgEAAgFIAAAAQAAgEgCgEQgBgDgEgDIgJgDIgNgBIglAAgAghgJIAhAAIAKgCIAIgDQAEgDACgDQABgEAAgFIAAAAQAAgEgBgDIgFgGIgIgDIgKgCIgiAAg");
	this.shape_7.setTransform(39.9,25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgCgKIgBgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgGACQgEACgDAEIgGAJQgDAFAAAGIA0AAIAAAAg");
	this.shape_8.setTransform(20.3,26.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgEA2IgLgEQgJgEgIgHQgHgIgEgKQgEgKAAgLIAAAAQAAgKAEgKQAEgKAHgHQAIgIAKgEIAKgDQAEgCAGAAQAHAAAGACIALAEQAHADALAKIgPAQQgGgHgGgDQgHgDgJAAQgFAAgFACQgFADgEAFQgFAEgCAGQgCAGAAAGIAAAAQAAAHACAGQACAGAFAFQAEAEAGADQAEACAGAAQAJAAAHgDQAGgDAGgHIAOAPQgKALgHADIgMAEQgGACgIAAg");
	this.shape_9.setTransform(9,26.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgLBIIAAhoIAXAAIAABogAgLgwIAAgXIAYAAIAAAXg");
	this.shape_10.setTransform(0.3,24.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AgJA1IgshpIAaAAIAbBMIAchMIAaAAIgrBpg");
	this.shape_11.setTransform(-8.5,26.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_12.setTransform(-18.1,26.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgRAzQgKgEgHgIQgIgHgDgKIgDgKIgCgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACQgEACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_13.setTransform(-28.7,26.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AgKBGIgPgEIgOgHIgOgKIAPgSQAHAHAOAHQAFADAGAAIAKABIALgBIAHgDQAEgDABgDQACgDAAgEIAAgBQAAgEgBgCIgFgFQgDgDgHgCIgNgEIgUgHQgJgDgGgDQgGgFgDgGQgDgHAAgKIAAAAQAAgJAEgIQADgHAGgFQAHgGAJgDQAIgCAKAAIANABIANADQAJADAPAKIgOATQgJgIgKgDQgJgDgIgBIgJABIgHAEQgGAFAAAHIAAAAIABAIIAFAFQAEACAGACIAPAGQALACAIADQAJAEAFADQAGAEADAHQADAGAAAJQAAALgEAHQgDAIgHAGQgHAFgJACQgJAEgLAAIgOgCg");
	this.shape_14.setTransform(-41.3,25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgcALIAAgVIA5AAIAAAVg");
	this.shape_15.setTransform(-51.6,25.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgLBJIAAiRIAXAAIAACRg");
	this.shape_16.setTransform(-58.5,24.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AgLBJIAAiRIAXAAIAACRg");
	this.shape_17.setTransform(-64.2,24.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgZAzQgGgDgFgGQgFgFgDgHQgCgIAAgJIAAhBIAYAAIAAA6QAAAGACAFQABAEADAEIAHAFQAFABAEAAQAEAAAEgCQAFgBADgEIAFgIQACgFAAgGIAAg5IAYAAIAABnIgYAAIAAgQQgGAIgIAFQgEADgFABQgDABgFAAQgJAAgIgCg");
	this.shape_18.setTransform(-73.3,26.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgzBGIAAiLIBnAAIAAAXIhOAAIAAAmIBFAAIAAAUIhFAAIAAA6g");
	this.shape_19.setTransform(-85.6,25);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AAPBGIAAgfIhEAAIgFgSIBMhaIAVAAIAABXIAUAAIAAAVIgUAAIAAAfgAgcASIArAAIAAg1g");
	this.shape_20.setTransform(-105.5,25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AgxBHIAAgUIAwgpQAIgIAKgKQAEgFABgEIABgIQAAgGgBgEQgCgEgEgDIgGgEQgFgBgEgBIgHACQgFABgDADQgHAFgJALIgRgPIAKgLQAFgHAGgDQAGgDAIgCQAHgCAIAAQAKAAAIACQAJADAGAGQAGAFAEAIQADAIAAAJQAAAJgCAGQgCAHgFAGQgEAFgHAGIgRAOIgaAYIBAAAIAAAWg");
	this.shape_21.setTransform(-118.4,24.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgKAxIAAgnIgmAAIAAgUIAmAAIAAgmIAVAAIAAAmIAmAAIAAAUIgmAAIAAAng");
	this.shape_22.setTransform(115.5,5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AgaBCQgMgDgKgGIAJgSQAJAFAIADQAKADALAAQAFAAAHgCQAGgCAEgEQAEgEADgGQACgGAAgIIAAgJQgKALgFADQgFADgGABQgEACgFAAQgKAAgIgDQgJgEgHgGQgGgHgEgJQgEgHAAgMQAAgIAEgNQAEgJAGgGQAIgHAIgDQAIgEAKAAQAFAAAFACIAKAEQAIAEAHAIIAAgPIAYAAIAABSQAAANgDAKQgEAKgHAGQgDAEgEADIgLAEQgPAEgIAAQgNAAgMgEgAgKguQgGACgEAEQgEAEgCAFQgDAGAAAGIAAAAQAAAHADAFQACAFAEACQAEAEAGACQAFACAFAAQAFAAAGgCQAFgCAFgEQAEgCACgFQADgFAAgHIAAAAQAAgGgDgGQgCgFgEgEIgKgGQgGgCgFAAQgFAAgFACg");
	this.shape_23.setTransform(96.2,8.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AAXA1IAAg5QAAgGgCgGQgBgEgDgDQgDgEgEgCQgFgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFQgCAFAAAGIAAA5IgYAAIAAhnIAYAAIAAAQQAGgJAIgEQADgCAFgCQAEgCAFAAQAJAAAIAEQAGACAFAGQAFAFADAHQACAIAAAJIAABBg");
	this.shape_24.setTransform(83.6,6.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgLBIIAAhoIAXAAIAABogAgMgwIAAgXIAYAAIAAAXg");
	this.shape_25.setTransform(74.5,4.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AAUBIIgcguIgQARIAAAdIgYAAIAAiQIAYAAIAABWIAqgtIAdAAIgpApIArA+g");
	this.shape_26.setTransform(66.5,4.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AAXA1IAAg5QAAgGgCgGQgBgEgDgDQgDgEgEgCQgFgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFQgCAFAAAGIAAA5IgYAAIAAhnIAYAAIAAAQQAGgJAIgEQADgCAFgCQAEgCAFAAQAJAAAIAEQAGACAFAGQAFAFADAHQACAIAAAJIAABBg");
	this.shape_27.setTransform(53.9,6.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgXA0QgHgCgFgEQgFgFgDgGQgDgFAAgJIAAAAQAAgIADgGQADgHAGgCQAGgFAIgBQAIgDAKAAQAJAAARAEIAAgCQAAgFgCgFQgBgEgEgDQgDgDgFgCQgFgBgEAAQgJAAgHACIgOAEIgHgSQAKgEAIgDQAKgCAKAAQAMAAAJADQAIADAGAGQAGAGADAIQACAIAAALIAAA8IgXAAIAAgNQgGAHgIAEQgLAEgIAAQgHAAgHgCgAgIAEQgFABgDADQgDACgCADQgBADAAAEIAAAAQAAAIAGAFQAFADAJAAQAEABAFgCQAFgBAEgEQAEgDACgEQACgEAAgFIAAgHQgOgFgKAAQgDAAgFACg");
	this.shape_28.setTransform(41.5,6.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("Ag5BFIAAiJIA9AAQAMAAAJACQAKAEAGAGQAEAFADAFQACAGAAAHIAAABQAAAGgCAFQgBAEgDAEQgFAHgJAEIALAEIAJAHQAEAEACAFQACAGAAAGIAAABQAAAJgEAIQgDAHgHAEQgHAFgKADQgJACgMAAgAghAwIAnAAIAMgBQAFgBADgDQAEgDABgDQACgEAAgEIAAgBQAAgEgCgEQgBgEgEgCIgJgDIgNgBIglAAgAghgKIAhAAIAKgBIAIgDQAEgDACgDQABgEAAgFIAAAAQAAgEgBgEIgFgFIgIgEIgKgBIgiAAg");
	this.shape_29.setTransform(29.2,5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgRAzQgKgEgHgIQgIgHgDgKIgDgKIgCgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_30.setTransform(9.6,6.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AgLBIIAAiQIAXAAIAACQg");
	this.shape_31.setTransform(0.7,4.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#002663").s().p("AgKBIIAAhoIAWAAIAABogAgMgwIAAgXIAYAAIAAAXg");
	this.shape_32.setTransform(-5,4.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#002663").s().p("AgFBIQgFgBgFgDQgHgEgHgJIAAAQIgYAAIAAiQIAYAAIAAA7QAHgKAIgFQAEgCAFgBQAFgDAFAAQAKAAAIAFQAJADAHAHQAHAHAEAKQAEANAAAIIAAABIgBANIgDAKQgEAKgHAIQgHAGgJAEQgIAEgKAAQgFAAgFgCgAgKgLQgGADgEAEQgFAEgCAFQgCAGAAAHIAAABQAAAIACAFQACAHAFAEQAEAFAGACQAFADAFgBQAGAAAFgCQAGgCAEgFQAEgEACgGQADgGAAgIIAAgBQAAgHgDgGQgCgFgEgEQgFgEgFgDQgGgCgFAAQgFAAgFACg");
	this.shape_33.setTransform(-14.3,4.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#002663").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAEQAFAFAGADQAGACAFAAQAHAAAGgCQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_34.setTransform(-27.8,6.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#002663").s().p("AAsBFIAAhiIgsBAIAAAAIgrhAIAABiIgYAAIAAiJIAaAAIApBBIAqhBIAaAAIAACJg");
	this.shape_35.setTransform(-43.1,5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#002663").s().p("AgXBGQgIgEgHgGQgHgIgEgKIgDgKIgBgNIAAgBQAAgIAEgNQAEgJAHgIQAHgHAIgDQAJgFAKAAQAEAAAGADQAFABAFACQAHAFAHAIIAAg5IAYAAIAACQIgYAAIAAgRQgHAJgHAFIgKAEQgGACgEAAQgKAAgJgEgAgKgLQgFADgFAEQgEAEgDAFQgCAGAAAHIAAABQAAAIACAGQADAGAFAEQAEAFAFACQAGACAEAAQAFABAGgDQAFgCAFgFQAEgEACgHQADgFAAgIIAAgBQAAgHgDgGQgCgFgEgEQgFgEgFgDQgGgCgFAAQgEAAgGACg");
	this.shape_36.setTransform(-64.7,4.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#002663").s().p("AAXA1IAAg5QAAgGgBgGQgCgEgDgDQgDgEgEgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFQgBAFAAAGIAAA5IgZAAIAAhnIAZAAIAAAQQAFgJAHgEQAFgCAEgCQADgCAGAAQAJAAAHAEQAHACAFAGQAFAFACAHQADAIAAAJIAABBg");
	this.shape_37.setTransform(-77.3,6.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#002663").s().p("AgZAzQgGgDgFgGQgFgFgDgHQgCgIAAgJIAAhBIAYAAIAAA6QAAAGACAFQABAEADAEIAHAFQAEABAFAAQAEAAAEgCQAFgBADgEIAFgIQABgFABgGIAAg5IAYAAIAABnIgYAAIAAgQQgGAIgIAFQgDADgGABQgCABgHAAQgIAAgIgCg");
	this.shape_38.setTransform(-89.8,6.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#002663").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAEQAFAFAGADQAGACAFAAQAHAAAGgCQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_39.setTransform(-102.5,6.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#002663").s().p("AgKBGIgPgEIgOgHIgOgKIAPgSQAHAHAOAHQAFACAGABIAKABIALgBIAHgDQAEgCABgEQACgDAAgEIAAgBQAAgDgBgDIgFgFQgDgDgHgCIgNgEIgUgHQgJgDgGgDQgGgEgDgHQgDgHAAgKIAAAAQAAgJAEgIQADgHAGgFQAHgFAJgDQAIgDAKAAIANABIANADQAJADAPAKIgOATQgJgIgKgDQgJgDgIgBIgJABIgHAEQgGAFAAAHIAAABIABAHIAFAFQAEADAGACIAPAEQALADAIADQAJAEAFADQAGAFADAGQADAGAAAKQAAAJgEAJQgDAHgHAFQgHAGgJACQgJADgLABIgOgCg");
	this.shape_40.setTransform(-115.6,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139,-6,278,44);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A3WzcMAutAAAMAAAAm5MgutAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.5,-125.5,301,251);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.parent = this;
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201706_YourPlace_300x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(280,141,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.893,0.893);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.parent = this;
	this.instance.setTransform(150,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border300x250();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_80 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_81 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_82 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_83 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_84 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_85 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_86 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_87 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_88 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_89 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_169 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_170 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_171 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_172 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_173 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_174 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_175 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_176 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_177 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_178 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:168,y:66}).wait(80).to({graphics:mask_graphics_80,x:168,y:67}).wait(1).to({graphics:mask_graphics_81,x:168,y:62.6}).wait(1).to({graphics:mask_graphics_82,x:168,y:58.1}).wait(1).to({graphics:mask_graphics_83,x:168,y:53.7}).wait(1).to({graphics:mask_graphics_84,x:168,y:49.2}).wait(1).to({graphics:mask_graphics_85,x:168,y:44.8}).wait(1).to({graphics:mask_graphics_86,x:168,y:40.3}).wait(1).to({graphics:mask_graphics_87,x:168,y:35.9}).wait(1).to({graphics:mask_graphics_88,x:168,y:31.4}).wait(1).to({graphics:mask_graphics_89,x:168,y:27}).wait(80).to({graphics:mask_graphics_169,x:168,y:27}).wait(1).to({graphics:mask_graphics_170,x:168,y:14.8}).wait(1).to({graphics:mask_graphics_171,x:168,y:2.6}).wait(1).to({graphics:mask_graphics_172,x:168,y:-9.7}).wait(1).to({graphics:mask_graphics_173,x:168,y:-21.9}).wait(1).to({graphics:mask_graphics_174,x:168,y:-34.1}).wait(1).to({graphics:mask_graphics_175,x:168,y:-46.3}).wait(1).to({graphics:mask_graphics_176,x:168,y:-58.6}).wait(1).to({graphics:mask_graphics_177,x:168,y:-70.8}).wait(1).to({graphics:mask_graphics_178,x:168,y:-83}).wait(1).to({graphics:null,x:0,y:0}).wait(4));

	// PIC
	this.instance_2 = new lib.pic();
	this.instance_2.parent = this;
	this.instance_2.setTransform(132,57,1,1,0,0,0,150,57);

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(80).to({regX:150.1,regY:57.1,x:132.1,y:34.1},9).wait(80).to({y:-88.9},9).to({_off:true},1).wait(4));

	// PIC shad
	this.instance_3 = new lib.HTML5rastershad_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(168,156,1,1,0,0,0,0,10);
	this.instance_3.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({y:119},9).wait(80).to({y:10},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(269.5,189,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:149},9).wait(80).to({y:42},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(269.5,222,1,1,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90).to({_off:false},0).wait(79).to({y:120},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,116.7,0.893,0.833,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(169).to({y:16.7},9).to({_off:true},4).wait(1));

	// tag
	this.instance_7 = new lib._2016TAG();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,220.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(413.6,227.7,1.225,1.225,0,0,0,215.2,63);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.parent = this;
	this.instance_9.setTransform(253.3,207.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_10 = new lib.box1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},182).wait(1));

	// com
	this.instance_11 = new lib.comhoriz();
	this.instance_11.parent = this;
	this.instance_11.setTransform(67,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.5,234.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(130,125,356,250);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;