(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497569040163", id:"HTML5rastershad"},
		{src:"images/Teensy160x600.jpg?1497569040163", id:"Teensy160x600"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Teensy160x600 = function() {
	this.initialize(img.Teensy160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,177);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuastackai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdAlIADgFQACABAFABQAGAAADgJIgVgsIAHAAIARAkIAOgkIAHAAIgSAuQgFANgKAAQgFAAgFgDgAFDAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAFIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAEOATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAEsAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAC0AVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAB/ATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgAh8AXQgGgFAAgHQAAgHAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAEABAKIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAh7ALQABAJALAAQAHABAFgEQAEgDAAgGIAAgFQgHgCgGAAQgOAAgBAKgAjRATQgHgGAAgLQAAgIAGgIQAHgGAJAAQAKAAAGAGQAGAIAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEADQgIAJgLAAQgKAAgGgHgAizAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAkNAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAkIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAlCATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIAAADIglAAQACAPAOAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAkkAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgADnAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgABtAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAA1AZIAAgsIAHAAIAAAsgAgyAZIAAg/IAIAAIAAA/gAhJAZIAAg/IAHAAIAAA/gAigAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIAAAAQgIAAgGAFQgFAGAAAJIAAASgAlkAZIAAgnIgGAAIAAgFIAGAAIAAgFQAAgHAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAFIgPAAIAAAngAA0gdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhwAlIACgFIAHACQAGAAAEgJIgVgsIAHAAIARAkIAPgkIAIAAIgUAtQgFANgKAAQgGAAgEgCgACFAXQgGgFAAgHQAAgNAUAAQAGAAAIACIAAgBQAAgNgNAAQgHAAgIAEIgCgGQAJgEAIAAQALAAAEAFQAFAEAAAKIAAAaIgHAAIAAgHQgFAIgLAAQgHAAgFgDgACGALQAAAJAMAAQAHABAEgEQAEgDAAgGIAAgFQgGgCgHAAQgOAAAAAKgABPAVQgEgFAAgIIAAgbIAHAAIAAAZQAAAOAMAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgFAJgLAAQgIAAgFgFgAAcATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgHgHgHAAQgHABgFAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAHgHIAEAEQgIAJgLAAQgKAAgHgHgAigAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAJgBAGAHQAHAHAAAIIAAABQAAALgHAGQgGAHgJAAQgMAAgGgKgAibgJQgGAFAAAFIAAABQAAAHAGAGQAFAFAGAAQAHAAAFgFQAFgFAAgIQAAgGgFgFQgFgFgHAAQgGAAgFAFgAACAZIAAgZQAAgOgLAAQgGAAgEAEQgEAEAAAGIAAAZIgGAAIAAgsIAGAAIAAAIQAHgJAJAAQAHAAAFAEQAEAFAAAJIAAAbg");
	this.shape_1.setTransform(0,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.3,0,72.7,18.9);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLANIAAgZIAXAAIAAAZg");
	this.shape.setTransform(51.2,58.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgJADgKQAEgJAHgIQAGgHAJgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAHADAKQADAKAAAJIAAAGIhIAAQABAHADAEIAGAIIAJAGQAEABAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAFgFADIgJAGIgLADIgMACQgJAAgKgEgAAZgFQAAgHgCgEQgCgFgEgEQgDgDgEgCQgFgCgFAAQgDAAgFACQgEABgDAEIgGAIIgDAMIAxAAIAAAAg");
	this.shape_1.setTransform(43.2,55.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKBFIAAiJIAVAAIAACJg");
	this.shape_2.setTransform(34.8,53.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWAxQgGgCgFgEQgFgEgDgFQgDgGAAgIQAAgIADgGQADgGAGgCQAFgEAIgCQAHgCAJAAQAKAAAPAEIAAgDQAAgFgBgEQgCgEgDgDQgDgDgFgBQgEgBgEAAQgIAAgIABIgNAFIgGgSQAJgEAIgCQAJgCAKAAQALAAAIADQAJACAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAGgIAEQgKAEgHAAQgIAAgGgCgAgIADIgHAEQgDACgCADQgCADAAAEQAAAIAGAEQAGAEAIAAQAEAAAFgCQAEgBAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgJAAIgIABg");
	this.shape_3.setTransform(26.2,55.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSAwQgOgGgGgGIAKgPQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgEIAAgBQAAgFgHgDQgDgCgKgEQgPgFgGgDQgFgDgDgFQgDgEAAgIIAAAAQAAgHADgFQADgGAFgFQAFgDAGgCQAHgCAFAAQAJAAAKADQAKADAIAFIgJAQQgHgEgIgDQgHgCgGAAQgFAAgEADQgDACAAAFIAAAAQAAAFAGAEIAOAFIALAEQAGACAEACQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHACQgHABgIAAQgJAAgLgDg");
	this.shape_4.setTransform(16,55.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAWAzIAAg3QgBgGgBgFQgBgEgDgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCAFQgCAEABAGIAAA3IgYAAIAAhjIAYAAIAAAQQAFgIAGgEIAJgEQADgCAFAAQAJAAAHADQAGADAFAFQAEAFADAHQACAHAAAJIAAA+g");
	this.shape_5.setTransform(-0.1,55.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKAyIgKgCQgJgFgIgHQgHgGgEgKIgDgJIgBgLIAAAAQAAgFAEgOQAEgJAHgIQAIgHAJgEIAKgDIAKgBQAHAAAOAEQAKAEAHAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAKQgEAJgHAHQgIAHgJAFQgOAEgHAAgAgLgcQgGACgEAFQgEAEgCAGQgCAFAAAGIAAAAQAAAGACAGQADAGAEAEQADAFAGACQAGACAFABQAHgBAFgCQAFgCAFgFQADgEACgGQADgGAAgGIAAAAQAAgFgDgGQgCgGgDgEQgFgFgFgCQgHgDgFAAQgGAAgFADg");
	this.shape_6.setTransform(-12.3,55.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_7.setTransform(-28.3,53.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_8.setTransform(-34.7,53.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFBEIgJgDQgHgFgGgIIAAAQIgXAAIAAiJIAXAAIAAA3QAGgJAHgEIAKgEQAEgCAFAAQAJAAAIAEQAJADAGAHQAHAHADAJQAEAMAAAIIAAABIgBAMIgDAKQgDAJgHAHQgGAHgJADQgIAEgJAAQgFAAgFgCgAgKgKQgFACgEAEQgEAEgDAEQgCAGAAAHIAAABQAAAHACAGQADAGAEAEQAEAEAFADQAGACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQACgGAAgHIAAgBQAAgHgCgGQgCgEgEgEQgEgEgGgCQgFgDgFAAQgEAAgGADg");
	this.shape_9.setTransform(-43.5,53.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AghBAIgLgFIAIgRQAHAEAHAAQAEAAAEgDQADgCADgHIgqhiIAYAAIAbBIIAahIIAYAAIgoBlIgGANQgEAGgCADQgDADgFACQgFABgGAAQgHAAgGgBg");
	this.shape_10.setTransform(34.1,35.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgSAvQgOgGgGgFIAKgPQAIAGAIADQAJADAGAAQAHAAAEgDQAEgCAAgFIAAgBQAAgFgHgDQgDgDgKgDQgPgFgGgDQgFgDgDgFQgDgEAAgHIAAgBQAAgHADgGQADgGAFgEQAFgDAGgDQAHgCAFAAQAJAAAKAEQAKADAIAFIgJAQQgHgFgIgCQgHgCgGgBQgFAAgEAEQgDACAAAEIAAABQAAAFAGADIAOAGIALAEQAGACAEACQAFAEACAEQADAFAAAGIAAABQAAAHgDAHQgCAGgFAEQgFADgHADQgHACgIAAQgJAAgLgFg");
	this.shape_11.setTransform(23.8,34.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAVAzIAAg3QAAgGgBgFQgCgEgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgEADgBAFQgCAEAAAGIAAA3IgWAAIAAhjIAWAAIAAAQQAGgIAHgEIAIgEQADgCAGAAQAIAAAHADQAHADAEAFQAFAFACAHQACAHABAJIAAA+g");
	this.shape_12.setTransform(13.4,34.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgQAwQgJgDgHgIQgHgGgEgKIgDgKIgBgLQAAgKADgJQAEgJAHgHQAGgIAJgDIAJgEIAJgBIALABIAKAEQAGACAJAJQAGAHADALQADAJAAAJIAAAHIhIAAQABAFACAFIAHAIIAJAGQAEABAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAFgFADIgJAFIgLAFIgMABQgJAAgKgEgAAZgGQAAgFgDgFQgBgFgEgEQgDgDgEgCQgFgCgFAAQgDAAgFACQgEABgDAEIgGAIIgDALIAxAAIAAAAg");
	this.shape_13.setTransform(1.8,34.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgQAwQgJgDgHgIQgIgGgDgKIgDgKIgBgLQAAgKADgJQAEgJAGgHQAIgIAIgDIAJgEIAJgBIALABIAKAEQAGACAJAJQAGAHADALQADAJAAAJIAAAHIhIAAQABAFADAFIAFAIIAJAGQAFABAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAFgFADIgJAFIgLAFIgMABQgKAAgJgEgAAZgGQAAgFgCgFQgCgFgEgEQgDgDgEgCQgEgCgGAAQgEAAgEACQgEABgEAEIgFAIIgEALIAyAAIAAAAg");
	this.shape_14.setTransform(-9.7,34.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_15.setTransform(-19.2,32.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgWAxQgGgCgFgEQgFgEgDgFQgDgGAAgIQAAgIADgGQADgGAGgCQAFgEAIgCQAHgCAJAAQAKAAAPAEIAAgDQAAgFgBgEQgCgEgDgDQgDgDgFgBQgEgBgEAAQgIAAgIABIgNAFIgGgSQAJgEAIgCQAJgCAKAAQALAAAIADQAJACAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAGgIAEQgKAEgHAAQgIAAgGgCgAgIADIgHAEQgDACgCADQgCADAAAEQAAAIAGAEQAGAEAIAAQAEAAAFgCQAEgBAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgJAAIgIABg");
	this.shape_16.setTransform(-34.5,34.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA/QgMgDgJgGIAIgRQAJAFAIADQAJACAKAAQAFAAAGgCQAGgBAEgEQAEgEACgGQADgGAAgHIAAgIQgJAKgGADQgEADgGABQgEABgFAAQgJAAgIgDQgIgDgGgGQgHgGgEgJQgDgHAAgLIAAAAQAAgHADgNQAEgIAHgHQAGgGAIgDQAIgDAJAAQAFAAAFABQAFABAEADQAIAEAGAIIAAgPIAXAAIAABOQAAAMgDAKQgDAJgGAHIgIAGIgKAEQgPADgHAAQgMAAgLgDgAgKgsQgFACgEAEIgGAIQgCAGAAAGIAAAAQAAAGACAFQACAFAEACQAEAEAFACQAFACAFAAQAFAAAGgCQAFgCAEgEQAEgCACgFQADgFAAgGIAAAAQAAgGgDgFQgCgFgEgEQgEgEgFgCQgGgCgFAAQgFAAgFACg");
	this.shape_17.setTransform(44.2,14.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAVAzIAAg3QAAgGgBgFQgCgEgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgEADgBAFQgCAEAAAGIAAA3IgWAAIAAhjIAWAAIAAAQQAGgIAHgEIAIgEQADgCAGAAQAIAAAHADQAHADAEAFQAFAFACAHQACAHABAJIAAA+g");
	this.shape_18.setTransform(32.3,13.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_19.setTransform(23.7,11.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAWBFIAAg5QgBgGgBgFQgBgCgDgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCADQgCAEABAGIAAA5IgYAAIAAiJIAYAAIAAA2QAFgIAGgEIAJgEQADgCAFAAQAJAAAHADQAGADAFAFQAEAFADAHQACAHAAAHIAABAg");
	this.shape_20.setTransform(15.2,11.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_21.setTransform(5.2,11.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghBAIgLgFIAIgRQAHAEAGAAQAFAAADgDQAEgCADgHIgqhiIAZAAIAaBIIAahIIAYAAIgoBlIgGANQgDAGgCADQgFADgEACQgFABgGAAQgHAAgGgBg");
	this.shape_22.setTransform(-4.2,14.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_23.setTransform(-13.3,13.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgJADgKQAEgKAGgGQAIgIAIgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAKQADAJAAAJIgBAHIhHAAQABAFADAGIAFAIIAJAEQAFACAEAAQAIAAAGgDQAGgDAHgGIAOAMQgEAEgFADIgJAHIgKADIgOACQgIAAgKgEgAAZgFQgBgGgBgFQgCgFgEgDQgCgEgFgCQgFgCgFAAQgDAAgFACQgFACgDADIgGAJIgDALIAyAAIAAAAg");
	this.shape_24.setTransform(-23.4,13.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgJAyIgphjIAYAAIAaBIIAbhIIAYAAIgpBjg");
	this.shape_25.setTransform(-34.2,13.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgJAEgKQADgKAGgGQAIgIAIgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAKQADAJAAAJIgBAHIhHAAQABAFACAGIAGAIIAJAEQAFACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgLADIgOACQgJAAgJgEgAAZgFQAAgGgDgFQgBgFgDgDQgDgEgFgCQgFgCgFAAQgDAAgFACQgFACgDADIgGAJIgDALIAyAAIAAAAg");
	this.shape_26.setTransform(-45.1,13.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgSAwQgOgHgGgFIAKgPQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgEIAAgBQAAgFgHgDQgDgCgKgEQgPgFgGgDQgFgDgDgFQgDgEAAgIIAAAAQAAgHADgFQADgGAFgFQAFgEAGgBQAHgCAFAAQAJAAAKADQAKADAIAFIgJAQQgHgEgIgDQgHgCgGAAQgFAAgEADQgDACAAAFIAAAAQAAAFAGAEIAOAFIALAEQAGACAEACQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHACQgHABgIAAQgJAAgLgDg");
	this.shape_27.setTransform(35.2,-7.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgJADgKQAEgJAGgIQAIgHAIgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAHADAKQADAKAAAJIgBAGIhHAAQABAHADAEIAFAIIAJAGQAFABAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAFgFADIgJAGIgKADIgOACQgIAAgKgEgAAZgFQgBgHgBgEQgCgFgEgEQgDgDgEgCQgFgCgFAAQgEAAgEACQgFABgDAEIgFAIIgEAMIAyAAIAAAAg");
	this.shape_28.setTransform(24.9,-7.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAUBFIgdgsIgNAPIAAAdIgYAAIAAiJIAYAAIAABRIAngrIAcAAIgoAnIAqA8g");
	this.shape_29.setTransform(14.7,-9.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgWAxQgGgCgFgEQgFgEgDgFQgDgGAAgIQAAgIADgGQADgGAGgCQAFgEAIgCQAHgCAJAAQAKAAAPAEIAAgDQAAgFgBgEQgCgEgDgDQgDgDgFgBQgEgBgEAAQgIAAgIABIgNAFIgGgSQAJgEAIgCQAJgCAKAAQALAAAIADQAJACAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAGgIAEQgKAEgHAAQgIAAgGgCgAgIADIgHAEQgDACgCADQgCADAAAEQAAAIAGAEQAGAEAIAAQAEAAAFgCQAEgBAEgDQAEgDACgEQACgEAAgFIAAgHQgOgEgJAAIgIABg");
	this.shape_30.setTransform(2.7,-7.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AA1AzIAAg3QAAgGgCgFQgBgEgDgDQgCgEgEgBQgEgCgFAAQgEAAgEACQgEABgDAEQgDADgBAEQgCAFAAAGIAAA3IgVAAIAAg3IgBgLQgCgEgCgDQgDgEgEgBQgEgCgEAAQgFAAgEACQgEACgDADQgDADgBAFQgCAEAAAGIAAA3IgXAAIAAhjIAXAAIAAAQQAGgIAGgEIAIgEQAFgCAGAAQAFAAAFACQAEABAEACIAFAGQADADACAEQAGgIAIgFQAEgCAFgBQAFgCAGAAQAIAAAGADQAHACAEAFQAFAFACAHQADAIAAAJIAAA+g");
	this.shape_31.setTransform(-11.6,-7.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_32.setTransform(-30.4,-9.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgKBCIAAiDIAVAAIAACDg");
	this.shape_33.setTransform(-37.1,-9.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.6,-20,121.3,86);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("EgMfAo7MAAAhR2IY/AAMAAABR2g");
	this.shape.setTransform(80,262);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E7E").s().p("AgKALIAAgVIAVAAIAAAVg");
	this.shape.setTransform(40.2,80.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E7E").s().p("AgOArQgIgDgHgHQgGgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQAEgIAFgHQAGgGAIgEIAJgCIAHgBIAKABIAJADQAFACAIAIQAFAHADAIQADAJAAAIIgBAGIhAAAIADAJQADAFADADIAIAEQAFABACAAQAIAAAFgCQAGgDAGgFIAMAKIgHAHQgEAEgFACIgKADIgLABQgHAAgJgDgAAWgFQAAgFgCgEQgBgFgEgDIgGgFQgEgCgFAAQgDAAgEACQgEACgDADIgFAHQgCAFgBAFIAsAAIAAAAg");
	this.shape_1.setTransform(33,77.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E7E").s().p("AgQArQgNgGgFgEIAJgOQAHAFAIADQAIADAEAAQAHAAAEgDQADgCAAgFQAAgFgGgDIgMgFQgNgEgGgDQgEgCgCgEQgDgFAAgGIAAAAQAAgHADgFQACgFAFgEQAEgDAGgCQAGgCAEAAQAJAAAIADQAJADAHAFIgIAOQgHgEgGgCQgHgDgFAAQgEAAgEADQgDACAAAEQAAAFAGADIAMAGIAKADIAJADQAFADACAFQACAEAAAGIAAAAQAAAHgCAFQgDAFgEAEQgFAEgGACQgGABgHAAQgIAAgKgDg");
	this.shape_2.setTransform(23.5,77.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E7E").s().p("AgTAsQgGgCgEgDQgFgEgDgFQgCgGAAgGQAAgHACgGQAEgFAFgCQAEgEAHgCQAHgBAIAAQAIAAAOADIAAgCQAAgEgCgEIgDgGIgIgEIgHgBQgHAAgGABQgGABgHAEIgFgQIAPgGQAJgCAHAAQAKAAAIACQAHADAGAFQAEAFACAHQADAHAAAJIAAAzIgUAAIAAgLQgFAGgHADQgJAEgGAAQgHAAgFgCgAgHADIgGADIgFAEQgBADAAAEIAAAAQAAAHAFADQAFAEAIAAQACAAAFgBQAFgCADgDQADgCABgEQACgDABgEIAAgGQgNgEgIAAIgHABg");
	this.shape_3.setTransform(14.2,77.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E7E").s().p("AATA+IAAg0QAAgEgBgFQgBgCgDgDQgCgDgEgBQgDgBgFAAIgGABQgEABgDADIgEAFQgBAEAAAGIAAAzIgVAAIAAh6IAVAAIAAAvQAFgGAGgEIAHgEIAIgBQAHAAAGADQAGACAEAEQAEAFADAGQACAHAAAFIAAA6g");
	this.shape_4.setTransform(4.2,75.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E7E").s().p("AgEAtIgIgCQgJgEgGgGQgGgHgDgIQgEgJAAgJQAAgIAEgJQADgIAHgGQAFgHAJgEIAJgCIAIgBIALABIAKADQAGADAJAIIgOAOQgFgGgFgCQgFgDgHAAQgFAAgEACQgEACgEAEQgDAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFADAEQADAEAFACQAEACAGAAQAHAAAFgDQAFgCAFgGIANAMQgJAKgGADIgKADIgLABg");
	this.shape_5.setTransform(-5.8,77.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E7E").s().p("AgZAtIAAhXIAVAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAGAAIAAAWIgBAAQgHAAgGACQgFACgFAEQgCAFgBAHQgDAEAAAJIAAAig");
	this.shape_6.setTransform(-13.6,77);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E7E").s().p("AgUArQgGgDgEgEQgFgFgCgGQgCgHAAgHIAAg3IAVAAIAAAwQAAAGABAEQABAEADADIAGAEQADABAEAAQADAAAEgBQAEgCACgDQADgCACgFQABgEAAgFIAAgwIAVAAIAABXIgVAAIAAgOQgFAIgGADQgDADgEABQgDABgFAAQgHAAgGgCg");
	this.shape_7.setTransform(-22.8,77.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E7E").s().p("AgtA7IAAhzIAUAAIAAAPQAGgIAHgEIAIgEIAIgBQAIAAAIADQAHADAGAGQAGAGADAJQAEAMAAAIIAAAAIgBALIgDAHQgDAIgGAGQgGAGgHAEQgIADgIAAQgEAAgEgCQgEgBgEgCQgHgEgGgHIAAApgAgJgmQgFACgDAEQgEAEgCAFQgCAFAAAHIAAAAQAAAGACAFQACAEAEAEQADAEAFACQAFACAEAAQAFAAAEgCQAFgCADgEQAEgEACgEQACgFAAgGIAAAAQAAgHgCgFQgCgFgEgEQgDgEgFgCQgEgCgFAAQgEAAgFACg");
	this.shape_8.setTransform(-33.4,78.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E7E").s().p("AgdA4QgFgBgFgDIAHgPQAGAEAGAAQAEAAAEgDQADgCACgFIgmhYIAXAAIAXBAIAXhAIAVAAIgjBaIgFALQgDAFgCADQgEADgEACIgKABQgGAAgFgCg");
	this.shape_9.setTransform(31.7,59.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E7E").s().p("AgYAtIAAhXIAUAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAGAAIAAAWIgCAAQgGAAgGACQgGACgDAEQgDAFgCAHQgCAEAAAJIAAAig");
	this.shape_10.setTransform(23.6,58);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E7E").s().p("AgOArQgIgDgHgHQgGgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQAEgIAFgHQAGgGAIgEIAJgCIAHgBIAKABIAJADQAFACAIAIQAFAHADAIQADAJAAAIIgBAGIhAAAIADAJQADAFADADIAIAEQAFABACAAQAIAAAFgCQAGgDAGgFIAMAKIgHAHQgEAEgFACIgKADIgLABQgHAAgJgDgAAWgFQAAgFgCgEQgBgFgEgDIgGgFQgEgCgFAAQgDAAgEACQgEACgDADIgFAHQgCAFgBAFIAsAAIAAAAg");
	this.shape_11.setTransform(14.6,58.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E7E").s().p("AgHAsIglhYIAVAAIAXBAIAYhAIAVAAIgkBYg");
	this.shape_12.setTransform(4.9,58.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E7E").s().p("AgOArQgJgDgFgHQgHgGgDgIIgDgJIgBgKIAAAAQAAgIADgJQADgIAHgHQAFgGAIgEIAIgCIAIgBIAKABIAIADQAGACAIAIQAGAHACAIQADAJAAAIIAAAGIhAAAIADAJQACAFAEADIAHAEQAEABADAAQAHAAAHgCQAFgDAFgFIANAKIgHAHQgEAEgEACIgKADIgMABQgHAAgJgDgAAXgFQgBgFgCgEQgBgFgDgDIgHgFQgFgCgEAAQgDAAgEACQgEACgDADIgFAHQgCAFAAAFIAsAAIAAAAg");
	this.shape_13.setTransform(-4.8,58.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E7E").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_14.setTransform(-20.3,58);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E7E").s().p("AgJAtIgJgCQgIgEgHgGQgGgHgEgIIgCgJIgBgJQAAgFADgMQAEgIAGgHQAHgGAJgEIAJgCIAIgBQAHAAAMADQAIAEAHAGQAGAHAEAIQADAMAAAFIAAAAIAAAJIgDAJQgEAIgGAGQgHAHgIAEQgNADgGAAgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQAFACAEAAQAGAAAFgCQAFgCAEgEQADgEACgFQACgFAAgGQAAgEgCgGQgCgFgEgEQgEgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_15.setTransform(-31.2,58.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E7E").s().p("AAYA6QgFgDgEgEQgEgDgCgGQgBgGAAgFIAAgBQAAgHABgFQACgGAFgEQADgEAGgCQAEgCAHAAQAGAAAFACQAFACAEAEQAEAEACAGQABAFAAAHIAAAAQAAAGgBAFQgCAGgEAEQgEAEgFADQgGADgFgBQgGABgGgDgAAaARQgDAGAAAHIAAAAQAAAHADAFQAEAGAGAAQAFAAAEgGQADgFAAgGIAAgBQAAgHgDgGQgEgEgFAAQgGAAgEAEgAgyA7IAug9IAng4IARAAIgvA+IgnA3gAgugBQgFgCgDgFQgFgEgCgFQgBgGAAgGIAAAAQAAgGABgFQACgGAFgEQADgEAGgDQAEgCAHAAQAGAAAFACQAGADADAEQAEAEACAFQACAGgBAGQABAGgCAGQgCAFgEAEQgEAFgFACQgFABgHAAQgFAAgGgBgAgsgpQgDAEAAAIQAAAIAEAEQADAGAGAAQAFAAAEgGQADgEAAgIIAAAAQAAgHgDgFQgEgFgGAAQgFAAgEAFg");
	this.shape_16.setTransform(32.9,37.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E7E").s().p("AgMA6IgLgDIgKgFIgJgIIAMgQQAIAIAHADQAIAEAHAAQAEAAAFgBIAHgFQADgDACgDQACgEgBgEIAAgBQABgEgCgEIgGgHQgDgCgEgBIgIgBIgMABIgKADIgMgGIADg6IBFAAIAAATIgzAAIgCAcIAJgDIAIgBQAJAAAHADQAIABAFAGQAGAEADAFQADAHAAAKQAAAJgDAIQgDAGgGAGQgFAGgJACQgIADgJAAQgFAAgHgCg");
	this.shape_17.setTransform(20.3,37.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E7E").s().p("AgKALIAAgVIAVAAIAAAVg");
	this.shape_18.setTransform(12.8,42.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E7E").s().p("AACA7IAAhgIgTAGIgFgRIAegLIAPAAIAAB2g");
	this.shape_19.setTransform(6.6,37.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E7E").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_20.setTransform(-6.4,39);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E7E").s().p("AgZAtIAAhXIAVAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAGAAIAAAWIgBAAQgHAAgGACQgGACgEAEQgCAFgBAHQgDAEAAAJIAAAig");
	this.shape_21.setTransform(-14.8,39);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E7E").s().p("AgTAsQgGgCgFgDQgEgEgCgFQgDgGAAgGQAAgHADgGQACgFAGgCQAEgDAHgCQAGgCAJAAQAIAAAOADIAAgBQAAgFgCgEIgDgGIgHgEIgIgBQgHAAgHACQgFAAgGADIgGgPIAPgGQAIgCAIAAQALAAAHACQAIADAEAFQAGAFABAHQADAHAAAJIAAAzIgUAAIAAgLQgFAGgGADQgJAEgHAAQgGAAgGgCgAgHADIgHADIgDAEQgCADAAAEIAAABQAAAFAFAEQAFAEAIAAQADAAAEgCQAEgBADgCQAEgDABgEQACgDAAgFIAAgFQgMgEgIAAIgHABg");
	this.shape_22.setTransform(-23.9,39.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E7E").s().p("AgrA7IAAh1IBWAAIAAATIhCAAIAAAeIA7AAIAAARIg7AAIAAAhIBDAAIAAASg");
	this.shape_23.setTransform(-34,37.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E7E").s().p("AgKALIAAgVIAVAAIAAAVg");
	this.shape_24.setTransform(21.8,17.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E7E").s().p("AgTA8QgHgEgGgGQgGgGgDgIIgDgJIgBgLIAAAAQAAgIAEgLQADgIAGgGQAGgGAHgDQAIgDAIAAIAIABIAIADQAHAFAFAGIAAgvIAVAAIAAB6IgVAAIAAgPQgFAIgHADQgEADgEABQgFABgDABQgIAAgIgDgAgIgJQgFACgEADQgDAEgCADQgCAGAAAHIAAAAQAAAGACAGQACAFAEADQADAFAFACQAEACAEAAQAFAAAEgCQAFgCAEgFQAEgEACgEQACgGAAgGIAAAAQAAgHgCgGQgCgDgEgEQgEgDgFgCQgEgDgFAAQgEABgEACg");
	this.shape_25.setTransform(13.6,12.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E7E").s().p("AgYAtIAAhXIAUAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAGAAIAAAWIgBAAQgHAAgGACQgFACgFAEQgCAFgBAHQgDAEAAAJIAAAig");
	this.shape_26.setTransform(5.3,14);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E7E").s().p("AgUAsQgFgCgFgDQgEgEgCgFQgDgGAAgGQAAgHADgGQADgFAEgCQAFgEAHgCQAHgBAIAAQAIAAAOADIAAgCQAAgEgBgEIgFgGIgGgEIgIgBQgHAAgHABQgFABgGAEIgGgQIAPgGQAIgCAJAAQAKAAAHACQAIADAEAFQAGAFACAHQACAHAAAJIAAAzIgUAAIAAgLQgFAGgGADQgJAEgHAAQgGAAgHgCgAgGADIgIADIgDAEQgCADAAAEIAAAAQAAAHAFADQAFAEAHAAQAEAAAEgBQAEgCADgDQAEgCACgEQABgDAAgEIAAgGQgMgEgIAAIgGABg");
	this.shape_27.setTransform(-3.8,14.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003E7E").s().p("AgFA8IgLgDIgLgHIgIgHQgFgEgDgFIgGgKIgDgMIgBgMIAAAAIABgLIADgLIAGgLIAHgJIAJgHQAFgEAGgCIALgEIAMgBQAIAAAGACQAHABAGACQAHADAMALIgOAPQgHgHgHgEIgJgDIgKgBQgGAAgHADQgIADgFAGQgFAGgDAIQgDAHAAAIIAAAAQAAAIADAIQADAHAFAHQAFAFAIAEQAHACAGAAIALgBIAIgCQAHgEAIgHIAOANIgKAIIgKAIIgOADQgGACgJAAIgKgBg");
	this.shape_28.setTransform(-14.6,12.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003E7E").s().p("AARA+IgZgoIgMAOIAAAaIgUAAIAAh6IAUAAIAABHIAjglIAZAAIgjAjIAlA1g");
	this.shape_29.setTransform(39.8,-6.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003E7E").s().p("AgDAtIgJgCQgIgEgHgGQgGgHgEgIQgDgJAAgJQAAgIADgJQAEgIAGgGQAHgHAIgEIAJgCIAIgBIALABIAKADQAFADAKAIIgOAOQgEgGgGgCQgFgDgHAAQgFAAgEACQgEACgEAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQADACAFAAQAIAAAFgDQAFgCAGgGIAMAMQgJAKgGADIgKADIgLABg");
	this.shape_30.setTransform(29.6,-4.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003E7E").s().p("AgUAsQgFgCgFgDQgEgEgDgFQgCgFAAgHQAAgHACgGQAEgFAEgCQAFgEAHgCQAGgBAJAAQAIAAAOADIAAgCQAAgEgBgEIgFgGIgHgEIgHgBQgHAAgGABQgGABgGAEIgGgQIAPgGQAJgCAIAAQAJAAAIACQAIADAFAFQAEAFADAHQACAHAAAJIAAAzIgUAAIAAgLQgFAGgGADQgJAEgHAAQgGAAgHgCgAgGADIgHADIgFAEQgBAEAAADIAAAAQAAAHAFADQAFAEAHAAQADAAAFgCQAEgBADgDQAEgCACgEQACgDAAgFIAAgFQgMgEgJAAIgGABg");
	this.shape_31.setTransform(19.4,-4.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003E7E").s().p("AgwA7IAAh1IAzAAQALAAAHACQAIAEAGAEQADAFACAEQACAFAAAGIgBAKIgEAHQgEAGgHAEIAJADQAEACAEADQADAEABAEQACAFAAAGIAAAAQAAAIgDAGQgDAGgGAEQgGAFgIACQgIACgKAAgAgbAoIAgAAIAKAAIAHgDQADgDACgDQABgDAAgEQAAgEgBgDQgCgDgDgCIgHgDIgMgBIgeAAgAgbgIIAbAAIAIgBQAFgBACgCQADgCABgDQACgDAAgEIAAAAQAAgEgBgCIgEgGQgDgCgEgBIgJAAIgbAAg");
	this.shape_32.setTransform(8.9,-6.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003E7E").s().p("AATA+IAAgzQAAgFgBgFQgBgCgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAGQgBADAAAGIAAAzIgVAAIAAh6IAVAAIAAAvQAFgGAGgEIAHgEIAIgBQAHAAAGADQAGACAEAEQAEAFADAGQACAHAAAFIAAA6g");
	this.shape_33.setTransform(-7.9,-6.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003E7E").s().p("AgQArQgNgGgFgEIAJgOQAHAFAIADQAIADAEAAQAHAAAEgDQADgCAAgFQAAgFgGgDIgMgFQgNgEgGgDQgEgCgCgEQgDgFAAgGIAAgBQAAgGADgFQACgFAFgEQAEgDAGgCQAGgCAEAAQAJAAAIADQAJACAHAGIgIAOQgHgEgGgCQgHgCgFgBQgEABgEACQgDACAAAEQAAAFAGADIAMAGIAKADIAJADQAFADACAEQACAFAAAGIAAAAQAAAHgCAFQgDAFgEAEQgFADgGADQgGABgHAAQgIAAgKgDg");
	this.shape_34.setTransform(-17.6,-4.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003E7E").s().p("AgTAsQgGgCgEgDQgFgEgCgFQgDgFAAgHQAAgHADgGQACgFAGgCQAEgEAHgCQAHgBAIAAQAIAAAOADIAAgCQAAgEgCgEIgDgGIgIgEIgHgBQgHAAgHABQgFABgHAEIgFgQIAPgGQAIgCAIAAQAKAAAIACQAHADAGAFQAEAFACAHQADAHAAAJIAAAzIgUAAIAAgLQgFAGgHADQgJAEgGAAQgHAAgFgCgAgHADIgHADIgEAEQgBAEAAADIAAAAQAAAHAFADQAFAEAIAAQACAAAFgCQAEgBAEgDQADgCABgEQACgDAAgFIAAgFQgLgEgJAAIgHABg");
	this.shape_35.setTransform(-26.9,-4.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003E7E").s().p("AgFA8IgMgDIgKgHIgJgHQgEgEgDgFIgFgKIgEgLIgBgNIAAAAIABgLIAEgLIAFgLIAHgJIAJgHQAFgEAFgCIAMgEIAMgBQAHAAAIACQAGAAAGADQAHADAMALIgNAPQgIgHgHgEIgJgDIgKgBQgGAAgIADQgGAEgGAFQgFAGgDAIQgDAIAAAHIAAAAQAAAIADAIQADAHAFAHQAGAFAGAEQAIACAGAAIAKgBIAJgCQAHgEAJgIIANAOIgKAJIgKAHIgOADQgHACgHAAIgLgBg");
	this.shape_36.setTransform(-37.7,-6.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003E7E").s().p("AgTA7QgHgDgGgGQgGgGgDgIIgDgJIgBgLIAAgBQAAgHAEgLQADgIAGgGQAGgGAHgDQAIgDAIAAIAIABIAIAEQAHADAFAHIAAgvIAVAAIAAB5IgVAAIAAgOQgFAHgHAEQgEADgEABQgFACgDAAQgIAAgIgEgAgIgKQgFADgEADQgDAEgCADQgCAGAAAGIAAABQAAAGACAGQACAFAEAEQADADAFACQAEADAEAAQAFAAAEgDQAFgCAEgDQAEgFACgEQACgGAAgGIAAgBQAAgGgCgGQgCgDgEgEQgEgDgFgCQgEgCgFgBQgEAAgEACg");
	this.shape_37.setTransform(39.6,-25.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003E7E").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_38.setTransform(28.9,-24);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003E7E").s().p("AgUArQgGgDgEgEQgFgFgCgGQgCgHAAgHIAAg3IAVAAIAAAwQAAAGABAEQABAEADADIAGAEQADABAEAAQADAAAEgBQAEgCACgDQADgCACgFQABgEAAgFIAAgwIAVAAIAABXIgVAAIAAgOQgFAIgGADQgDADgEABQgDABgFAAQgHAAgGgCg");
	this.shape_39.setTransform(18.3,-23.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003E7E").s().p("AgJAtIgJgCQgIgEgHgGQgGgHgEgIIgCgJIgBgJQAAgFADgMQAEgIAGgHQAHgGAJgEIAJgCIAIgBQAHAAAMADQAIAEAHAGQAGAHAEAIQADAMAAAFIAAAAIAAAJIgDAJQgEAIgGAGQgHAHgIAEQgNADgGAAgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQAFACAEAAQAGAAAFgCQAFgCAEgEQADgEACgFQACgFAAgGQAAgEgCgGQgCgFgEgEQgEgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_40.setTransform(7.5,-23.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003E7E").s().p("AgJA7IgNgDIgLgGQgHgEgFgFIANgPQAGAGAMAGIAJADIAIABIAJgBIAHgDIAEgFQABgDAAgDIgBgGIgDgFIgJgDIgMgFIgQgEQgIgDgFgCQgFgEgDgGQgCgGAAgIQAAgIADgGQADgHAFgEQAGgEAIgDQAHgCAIAAIALABQAGAAAFACQAIADAMAIIgMAQQgIgGgIgDQgHgDgHAAIgIABIgGADQgFAEAAAGIAAAAIABAHIAFAEIAIAEIAMAEIARAGQAHACAFADQAEAEADAFQADAGAAAHQAAAIgEAHQgCAHgHAEQgFAFgIADQgHABgKAAIgMgBg");
	this.shape_41.setTransform(-3.5,-25.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#003E7E").s().p("AgOArQgIgDgHgHQgGgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQAEgIAFgHQAGgGAIgEIAJgCIAHgBIAKABIAJADQAFACAIAIQAFAHADAIQADAJAAAIIAAAGIhBAAIAEAJQACAFADADIAIAEQAFABACAAQAIAAAGgCQAFgDAGgFIAMAKIgHAHQgEAEgFACIgKADIgLABQgIAAgIgDgAAWgFQAAgFgCgEQgCgFgCgDIgHgFQgFgCgEAAQgDAAgEACQgEACgDADIgFAHQgCAFgBAFIAsAAIAAAAg");
	this.shape_42.setTransform(-19.1,-23.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#003E7E").s().p("AATA9IAAgyQAAgFgBgFQgBgCgDgDQgCgCgEgCQgDgCgFAAIgGACQgEACgDACIgEAGQgBAEAAAFIAAAyIgVAAIAAh5IAVAAIAAAvQAFgHAGgDIAHgEIAIgBQAHAAAGADQAGABAEAFQAEAFADAGQACAGAAAGIAAA5g");
	this.shape_43.setTransform(-29.4,-25.6);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#003E7E").s().p("AgJA7IAAhhIgmAAIAAgUIBfAAIAAAUIgmAAIAABhg");
	this.shape_44.setTransform(-40,-25.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61,-35,122,122);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgJSguyISlAAMAAABdlIylAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-300.5,121,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Teensy160x600();
	this.instance.parent = this;
	this.instance.setTransform(4,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(168,187,1,1,0,0,0,0,10);
	this.instance_1.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,197);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201706_Teensy_120x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(101,6,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.357,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(60,586.2,0.683,0.683,0,0,0,0,0.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuastackai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(60,558.7,1.153,1.153,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border120x600();
	this.instance_2.parent = this;
	this.instance_2.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},164).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(133,57,1,1,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},164).wait(1));

	// CTA
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(827.5,469,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1,scaleY:1,x:179.5,y:257},4).to({_off:true},160).wait(1));

	// HEAD
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(838.5,695,5,5,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(71).to({_off:false},0).to({scaleX:1,scaleY:1,x:179.5,y:396},4).to({_off:true},89).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({_off:true},164).wait(1));

	// tag
	this.instance_7 = new lib._2016TAGvert();
	this.instance_7.parent = this;
	this.instance_7.setTransform(60.1,526.2,1.014,1.014,0,0,0,0,2.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(204.9,528.5,0.673,0.673,0,0,0,215.2,63.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.parent = this;
	this.instance_9.setTransform(116.8,517.3,0.696,0.696,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_10 = new lib.HTML5rastershad_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_10.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},164).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},164).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(17.1,232.1,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.9,300,640,664);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;