(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497569017476", id:"HTML5rastershad"},
		{src:"images/Teensy336x280.jpg?1497569017476", id:"Teensy336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Teensy336x280 = function() {
	this.initialize(img.Teensy336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Teensy336x280();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQASIAAgjIAiAAIAAAjg");
	this.shape.setTransform(133.4,47.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXBFQgNgGgKgKQgLgKgEgNIgFgPIgCgPIAAAAQABgOAFgOQAFgNAJgKQAKgKANgGIAMgFIANgBIARABQAGACAHADQAIAEAOANQAIALAEANQAEAOABANIgBAKIhmAAQABAJADAGQAEAHAFAEQAGAGAHABQAGADAGAAQAMAAAKgFQAIgDAJgJIATARIgLALQgGAFgHAEQgHADgJACQgIACgKAAQgNAAgOgFgAAlgJQgBgIgDgHQgDgHgEgFQgFgFgGgDQgHgCgIAAQgFAAgHACQgGADgFAFQgEAFgEAHQgDAHgBAIIBIAAIAAAAg");
	this.shape_1.setTransform(121.9,42.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgPBiIAAjDIAfAAIAADDg");
	this.shape_2.setTransform(109.9,39.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AggBGQgJgDgHgFQgHgGgEgIQgEgIAAgLIAAAAQAAgMAEgIQAFgJAIgEQAHgFALgDQAKgDAOAAQAOAAAWAGIAAgEQAAgHgCgGQgCgGgFgEQgFgEgGgCQgGgCgHAAQgMAAgKADQgIACgLAEIgJgaQANgFALgDQAOgDAOAAQAQAAAMAEQAMAEAIAIQAHAHAEAMQAEALAAAOIAABSIggAAIAAgSQgIAKgKAFQgQAGgKAAQgKAAgKgDgAgLAFQgHACgEADQgFADgCAEQgCAFAAAFIAAABQAAAKAIAGQAHAFANAAQAGAAAHgCQAGgCAGgEQAFgEADgGQADgFAAgHIAAgKQgTgFgOAAQgFAAgGABg");
	this.shape_3.setTransform(97.8,42.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaBEQgUgJgJgHIAOgWQAMAJAMAEQAMAFAJAAQAKAAAGgFQAGgEAAgHIAAAAQAAgIgKgFQgEgCgQgFQgVgHgJgFQgHgEgDgHQgEgHAAgKIAAgBQAAgKAEgIQADgIAHgGQAHgFAKgDQAJgDAIAAQAOAAAOAEQANAEAMAIIgNAXQgLgGgKgEQgLgDgIAAQgIAAgFAEQgFADAAAHIAAAAQAAAHAJAFIAVAJIAPAFQAJAEAGACQAHAFADAHQAEAHAAAJIAAABQAAALgEAIQgEAJgHAFQgHAGgKADQgKACgLAAQgNAAgQgFg");
	this.shape_4.setTransform(83.3,42.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAfBIIAAhPQAAgIgCgHQgCgGgEgEQgEgFgGgCQgFgDgHAAQgFAAgHADQgFACgFAFQgEAEgDAHQgCAHAAAIIAABOIghAAIAAiMIAhAAIAAAWQAIgMAKgGQAFgDAHgCQAFgCAHAAQAMAAAKAEQAKADAGAIQAHAHADAKQAEAKAAAMIAABZg");
	this.shape_5.setTransform(60.4,42.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOBIIgPgEQgNgGgLgKQgKgKgFgOIgFgNIgBgPIAAAAQgBgJAHgTQAFgMAKgLQALgKANgGIAPgFIAOgBQALAAATAGQAOAGAKAJQAKALAGANQAFATABAJIAAAAIgCAPIgEANQgGAOgKAKQgLAKgNAGQgTAGgLAAgAgRgpQgHAEgGAGQgFAGgDAIQgDAJAAAIIAAAAQAAAJADAIQADAIAGAHQAFAGAIAEQAIADAIAAQAKAAAIgDQAHgEAHgGQAFgHADgIQADgIAAgJIAAAAQAAgIgDgIQgDgIgGgHQgGgGgIgDQgJgFgIAAQgIABgJADg");
	this.shape_6.setTransform(43.1,42.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABaQgIgDgFgEQgGgGgDgIQgCgIAAgMIAAhIIgTAAIAAgcIATAAIAAgoIAeAAIAAAoIAmAAIAAAcIgmAAIAABEQAAAIAFAFQAEAEAIAAQALAAAKgFIAAAbQgGAEgIACQgGACgKAAQgJAAgFgCg");
	this.shape_7.setTransform(20.4,40.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgOBhIAAiMIAeAAIAACMgAgQhBIAAgfIAhAAIAAAfg");
	this.shape_8.setTransform(11.2,39.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgHBhQgHgCgGgDQgLgHgJgKIAAAVIggAAIAAjDIAgAAIAABPQAJgNALgGQAGgEAHgCQAHgCAHAAQANAAAMAFQAMAFAJAJQAJAKAGAOQAFARAAAMIAAAAIgBARIgEAPQgGANgJAKQgJAJgMAGQgMAEgNAAQgHAAgHgCgAgPgQQgHAEgGAGQgGAGgDAGQgDAJAAAKIAAAAQAAAKADAJQADAIAGAHQAGAFAHAEQAIADAHAAQAIAAAHgDQAHgDAGgGQAGgGADgJQADgIAAgLIAAAAQAAgKgDgJQgDgGgGgGQgGgGgHgEQgIgDgHAAQgHAAgIADg");
	this.shape_9.setTransform(-1.3,39.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgvBaQgIgCgIgEIALgYQAKAFAJAAQAHAAAFgDQAFgEAEgJIg8iNIAjAAIAnBoIAlhoIAiAAIg5CRQgEALgFAHQgFAIgDAFQgGAEgHADQgGACgJAAQgKAAgIgDg");
	this.shape_10.setTransform(-26.9,44.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaBEQgUgJgJgHIAOgWQAMAJAMAEQAMAFAJAAQAKAAAGgFQAGgEAAgHIAAAAQAAgIgKgFQgEgCgQgFQgVgHgJgFQgHgEgDgHQgEgHAAgKIAAgBQAAgKAEgIQADgIAHgGQAHgFAKgDQAJgDAIAAQAOAAAOAEQANAEAMAIIgNAXQgLgGgKgEQgLgDgIAAQgIAAgFAEQgFADAAAHIAAAAQAAAHAJAFIAVAJIAPAFQAJAEAGACQAHAFADAHQAEAHAAAJIAAABQAAALgEAIQgEAJgHAFQgHAGgKADQgKACgLAAQgNAAgQgFg");
	this.shape_11.setTransform(-41.4,42.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAfBIIAAhPQAAgIgCgHQgCgGgEgEQgEgFgFgCQgGgDgIAAQgEAAgGADQgHACgEAFQgEAEgCAHQgDAHAAAIIAABOIggAAIAAiMIAgAAIAAAWQAIgMAJgGQAHgDAGgCQAFgCAHAAQANAAAJAEQAKADAGAIQAHAHADAKQADAKAAAMIAABZg");
	this.shape_12.setTransform(-56.2,42.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgXBFQgNgGgKgKQgLgKgEgNIgFgPIgBgPIAAAAQAAgOAFgOQAFgNAJgKQAJgKAOgGIAMgFIAOgBIAPABQAIACAGADQAIAEANANQAJALAFANQADAOAAANIAAAKIhmAAQAAAJAEAGQAEAHAFAEQAFAGAHABQAIADAFAAQAMAAAJgFQAJgDAJgJIATARIgLALQgGAFgHAEQgIADgIACQgJACgJAAQgOAAgNgFgAAlgJQgCgIgDgHQgCgHgFgFQgEgFgHgDQgGgCgIAAQgFAAgHACQgGADgFAFQgFAFgDAHQgDAHgBAIIBIAAIAAAAg");
	this.shape_13.setTransform(-72.8,42.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgXBFQgNgGgKgKQgKgKgGgNIgEgPIgBgPIAAAAQgBgOAGgOQAFgNAJgKQAJgKANgGIAOgFIANgBIAPABQAIACAGADQAIAEANANQAJALAFANQADAOAAANIAAAKIhnAAQACAJADAGQAEAHAFAEQAFAGAHABQAHADAGAAQAMAAAJgFQAJgDAJgJIATARIgLALQgGAFgHAEQgHADgJACQgIACgKAAQgOAAgNgFgAAlgJQgCgIgDgHQgCgHgFgFQgEgFgHgDQgGgCgIAAQgFAAgHACQgGADgFAFQgEAFgDAHQgEAHgBAIIBIAAIAAAAg");
	this.shape_14.setTransform(-89.1,42.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAABaQgIgDgFgEQgGgGgDgIQgDgIAAgMIAAhIIgSAAIAAgcIASAAIAAgoIAfAAIAAAoIAmAAIAAAcIgmAAIAABEQAAAIAEAFQAFAEAJAAQAKAAAKgFIAAAbQgHAEgHACQgHACgIAAQgKAAgFgCg");
	this.shape_15.setTransform(-102.6,40.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AggBGQgJgDgHgFQgHgGgEgIQgEgIAAgLIAAAAQAAgMAEgIQAFgJAIgEQAHgFALgDQALgDANAAQAOAAAWAGIAAgEQAAgHgCgGQgDgGgEgEQgFgEgGgCQgHgCgGAAQgMAAgKADQgIACgLAEIgJgaQANgFAMgDQAOgDANAAQAQAAAMAEQAMAEAHAIQAIAHAEAMQAEALAAAOIAABSIggAAIAAgSQgIAKgLAFQgPAGgLAAQgJAAgKgDgAgMAFQgGACgEADQgFADgCAEQgCAFAAAFIAAABQAAAKAIAGQAHAFANAAQAFAAAIgCQAGgCAGgEQAFgEADgGQADgFAAgHIAAgKQgTgFgOAAQgGAAgGABg");
	this.shape_16.setTransform(-124.3,42.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjBaQgQgFgOgIIAMgZQAMAIAMAEQANAEAOAAQAJAAAIgDQAJgDAFgGQAGgFADgIQADgJAAgKIAAgLQgNAOgIAFQgGADgHACQgHACgHAAQgNAAgLgFQgMgEgJgJQgKgJgFgMQgFgLAAgPIAAAAQAAgLAFgSQAFgMAKgJQAJgIAMgFQALgEANAAQAHAAAHACQAHABAHAEQAKAGAKALIAAgVIAgAAIAABvQAAASgEANQgFAOgJAJQgEAFgHADQgGAEgHACQgVAFgLAAQgSAAgQgEgAgOg/QgIADgFAFQgGAFgDAHQgDAIAAAIIAAABQAAAJADAHQADAHAGADQAFAFAIADQAHADAHAAQAIAAAIgDQAHgDAGgFQAGgDADgHQADgHAAgJIAAgBQAAgIgDgIQgDgHgGgFQgGgFgHgDQgIgDgIAAQgHAAgHADg");
	this.shape_17.setTransform(123.4,17.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAfBIIAAhPQAAgIgCgHQgCgGgEgEQgEgFgGgCQgGgDgGAAQgGAAgGADQgGACgEAFQgEAEgCAHQgDAHAAAIIAABOIggAAIAAiMIAgAAIAAAWQAIgMAJgGQAHgDAGgCQAFgCAHAAQAMAAAKAEQAJADAHAIQAGAHAEAKQADAKABAMIAABZg");
	this.shape_18.setTransform(106.5,15.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgPBhIAAiMIAfAAIAACMgAgQhBIAAgfIAhAAIAAAfg");
	this.shape_19.setTransform(94.2,12.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAfBiIAAhRQAAgJgCgGQgCgEgEgEQgEgFgGgDQgGgCgGAAQgGAAgGACQgFADgFAFQgEAEgDAFQgCAHAAAIIAABQIggAAIAAjDIAgAAIAABMQAIgLAJgGQAHgDAGgCQAFgCAHgBQAMABAKAEQAJADAHAHQAGAIAEAJQADALABAKIAABbg");
	this.shape_20.setTransform(82.1,12.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAABaQgIgDgFgEQgGgGgCgIQgDgIAAgMIAAhIIgTAAIAAgcIATAAIAAgoIAeAAIAAAoIAmAAIAAAcIgmAAIAABEQAAAIAFAFQAEAEAIAAQALAAAJgFIAAAbQgGAEgGACQgIACgJAAQgJAAgFgCg");
	this.shape_21.setTransform(67.9,13.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgvBaQgIgCgIgEIALgYQAKAFAJAAQAHAAAFgDQAFgEAEgJIg8iNIAjAAIAnBoIAlhoIAiAAIg5CRQgEALgFAHQgFAIgDAFQgGAEgHADQgGACgJAAQgKAAgIgDg");
	this.shape_22.setTransform(54.5,17.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgoBIIAAiMIAhAAIAAAgQADgIAEgHQADgGAHgFQAGgFAIgCQAIgCAJAAIAAAjIgCAAQgKAAgJADQgKAEgGAHQgFAHgDAKQgDAJAAAOIAAA2g");
	this.shape_23.setTransform(41.6,15.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgXBFQgNgGgKgKQgKgKgGgNIgEgOIgBgQIAAAAQgBgOAGgOQAFgNAJgKQAJgKANgGIAOgFIAMgBIAQABQAIACAGADQAJAEAMANQAJALAEANQAFAOAAANIgBAKIhnAAQABAJAEAGQAEAHAGAEQAFAGAGABQAIADAGAAQALAAAJgFQAJgDAJgJIATARIgLALQgGAFgHAEQgIADgIACQgIACgKAAQgOAAgNgFgAAkgJQgBgIgCgHQgDgHgFgFQgEgFgGgDQgHgCgIAAQgFAAgGACQgHADgFAFQgEAFgDAHQgEAHgBAIIBHAAIAAAAg");
	this.shape_24.setTransform(27.2,15.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgNBHIg7iNIAjAAIAlBmIAmhmIAjAAIg7CNg");
	this.shape_25.setTransform(11.8,15.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgXBFQgNgGgKgKQgKgKgGgNIgEgOIgBgQIAAAAQgBgOAGgOQAFgNAJgKQAJgKANgGIAOgFIANgBIAPABQAIACAGADQAIAEANANQAJALAFANQADAOAAANIAAAKIhnAAQACAJADAGQAEAHAFAEQAFAGAHABQAHADAGAAQAMAAAJgFQAJgDAJgJIATARIgLALQgGAFgHAEQgHADgJACQgIACgKAAQgOAAgNgFgAAlgJQgCgIgDgHQgCgHgFgFQgEgFgHgDQgGgCgIAAQgFAAgHACQgGADgFAFQgEAFgDAHQgEAHgBAIIBIAAIAAAAg");
	this.shape_26.setTransform(-3.6,15.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBEQgUgJgJgHIAOgWQAMAJAMAEQAMAFAJAAQAKAAAGgFQAGgEAAgHIAAAAQAAgIgKgFQgEgCgQgFQgVgHgJgFQgHgEgDgHQgEgHAAgKIAAgBQAAgKAEgIQADgIAHgGQAHgFAKgDQAJgDAIAAQAOAAAOAEQANAEAMAIIgNAXQgLgGgKgEQgLgDgIAAQgIAAgFAEQgFADAAAHIAAAAQAAAHAJAFIAVAJIAPAFQAJAEAGACQAHAFADAHQAEAHAAAJIAAABQAAALgEAIQgEAJgHAFQgHAGgKADQgKACgLAAQgNAAgQgFg");
	this.shape_27.setTransform(-26.8,15.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgXBFQgNgGgKgKQgKgKgGgNIgEgOIgBgQIAAAAQgBgOAGgOQAFgNAJgKQAJgKANgGIAOgFIAMgBIAQABQAIACAGADQAJAEAMANQAJALAFANQADAOAAANIAAAKIhnAAQABAJAEAGQAEAHAGAEQAFAGAGABQAHADAHAAQALAAAJgFQAJgDAJgJIATARIgLALQgGAFgHAEQgHADgJACQgIACgKAAQgOAAgNgFgAAkgJQgBgIgDgHQgCgHgFgFQgEgFgHgDQgGgCgIAAQgFAAgGACQgHADgFAFQgEAFgDAHQgEAHgBAIIBHAAIAAAAg");
	this.shape_28.setTransform(-41.5,15.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAcBiIgog+IgVAVIAAApIggAAIAAjDIAgAAIAAB0IA6g9IAnAAIg4A3IA6BVg");
	this.shape_29.setTransform(-56,12.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgfBGQgKgDgHgFQgHgGgEgIQgEgIAAgLIAAAAQAAgMAFgIQAEgJAHgEQAIgFALgDQAKgDAOAAQAOAAAWAGIAAgEQAAgHgCgGQgDgGgEgEQgFgEgGgCQgHgCgGAAQgLAAgKADQgJACgLAEIgIgaQANgFAKgDQAOgDAPAAQAPAAAMAEQAMAEAIAIQAHAHAEAMQAEALAAAOIAABSIggAAIAAgSQgIAKgLAFQgOAGgLAAQgLAAgIgDgAgMAFQgGACgEADQgEADgDAEQgCAFAAAFIAAABQAAAKAIAGQAIAFAMAAQAGAAAHgCQAHgCAFgEQAFgEADgGQADgFAAgHIAAgKQgUgFgMAAQgHAAgGABg");
	this.shape_30.setTransform(-72.9,15.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABLBIIAAhPQAAgIgCgHQgBgGgFgFQgDgEgGgCQgFgDgHAAQgGAAgGADQgFACgEAEQgFAFgCAHQgCAGAAAJIAABOIgfAAIAAhPQAAgIgCgHQgCgGgEgFQgDgEgGgCQgFgDgHAAQgHAAgFADQgGACgEAFQgEAFgCAGQgDAHAAAIIAABOIggAAIAAiMIAgAAIAAAVQAJgLAIgGQAGgDAHgCQAGgCAIAAQAIAAAHACQAGABAFAEQAFADADAEIAHALQAJgMALgGQAGgEAHgBQAHgCAIAAQAMAAAJADQAJAEAGAHQAHAHAEAKQADAKAAANIAABZg");
	this.shape_31.setTransform(-93.2,15.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAABaQgIgDgFgEQgGgGgCgIQgEgIAAgMIAAhIIgSAAIAAgcIASAAIAAgoIAfAAIAAAoIAmAAIAAAcIgmAAIAABEQAAAIAEAFQAFAEAJAAQAKAAAJgFIAAAbQgFAEgHACQgHACgJAAQgKAAgFgCg");
	this.shape_32.setTransform(-119.9,13.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgPBeIAAi7IAfAAIAAC7g");
	this.shape_33.setTransform(-129.6,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-169,-1,337,58);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E7E").s().p("AgKAMIAAgXIAVAAIAAAXg");
	this.shape.setTransform(127.7,37.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E7E").s().p("AgPAuQgJgEgGgGQgHgHgEgJIgDgKIgBgKIAAAAQAAgJAEgIQADgJAHgIQAGgGAIgEIAJgDIAIgBIALABIAJADQAGADAIAIQAFAHADAKQADAJABAIIgBAGIhEAAQABAGACAFQADAEAEADIAIAFIAIABQAHAAAGgDQAHgDAGgFIAMALIgIAHIgIAHIgLADIgMABQgIAAgJgDgAAYgFQAAgGgCgEIgGgIQgDgEgDgBQgFgCgFAAQgDAAgFACQgEABgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_1.setTransform(120.1,33.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E7E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_2.setTransform(110,33.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E7E").s().p("AgVAvQgGgCgFgEQgEgEgDgFQgCgGgBgHQAAgHADgGQADgGAFgCQAGgEAHgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgBgEQgCgEgDgCQgDgDgEgBQgFgCgDAAQgIAAgHACIgMAEIgGgRQAJgEAHgBQAJgDAJAAQAKAAAIADQAIADAFAFQAFAFACAIQADAHABAJIAAA3IgWAAIAAgMQgGAGgGAEQgJAEgIAAQgGAAgHgCgAgHADIgIADIgEAGQgCACAAAEQAAAHAGAEQAFAEAIAAQADAAAFgCQAFgBADgDQADgCADgEQABgEAAgEIAAgHQgNgEgIAAIgHABg");
	this.shape_3.setTransform(100.2,33.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E7E").s().p("AAVBBIAAg2QAAgFgCgFIgEgFQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCADQgBAEAAAGIAAA1IgWAAIAAiBIAWAAIAAAzQAFgIAGgEIAIgDQADgCAFAAQAIAAAHADQAGACAEAFQAFAFACAHQACAGAAAHIAAA8g");
	this.shape_4.setTransform(89.6,31.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E7E").s().p("AgDAwIgKgDQgJgEgGgGQgHgHgEgJQgEgJAAgKIAAAAQAAgJAEgIQAEgJAHgIQAGgGAJgEIAKgDIAIgBIAMABIAKAEQAGADAKAIIgNAPQgGgGgGgCQgGgEgHAAQgFAAgEADQgFACgEAEQgDAEgDAGQgCAFAAAFQAAAGACAFQADAGADAEQAEAEAFADQAEACAGAAQAHAAAGgDQAGgDAGgGIAMANQgJAKgHADIgKAEIgMABg");
	this.shape_5.setTransform(79,33.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E7E").s().p("AgaAwIAAhdIAWAAIAAAVQACgFACgEQACgFAFgDQAEgDAFgBQAFgCAGAAIAAAXIgBAAQgHAAgGACQgGADgEAFQgDAEgCAHQgCAGAAAJIAAAkg");
	this.shape_6.setTransform(70.7,33.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E7E").s().p("AgWAtQgGgCgEgFQgFgFgCgGQgCgIAAgIIAAg6IAWAAIAAA0QAAAGABAEQABAEADADQADADADACQAEABAEAAQAEAAAEgBQAEgCACgDQADgDACgEQABgFAAgFIAAg0IAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIADQgDACgFAAQgIAAgHgDg");
	this.shape_7.setTransform(61,33.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E7E").s().p("AgwA/IAAh7IAWAAIAAARQAGgJAHgFQAEgCAFgBQAEgCAFABQAIAAAIACQAIAEAGAGQAGAHAEAJQAEANAAAIIgBAMIgDAHQgDAJgHAGQgGAHgIADQgIADgIABQgFgBgEgBQgFgBgEgDQgHgDgGgJIAAAtgAgJgpQgFADgEAEQgEAEgCAFQgCAGAAAHQAAAHACAFQACAEAEAEQAEAEAFADQAFACAEAAQAFAAAFgCQAFgDAEgDQADgEACgFQADgFAAgHQAAgHgDgGQgCgFgEgEQgDgEgFgDQgFgCgFABQgEgBgFACg");
	this.shape_8.setTransform(49.7,35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E7E").s().p("AgfA8IgKgEIAHgQQAHADAGAAQAFAAADgCQADgDADgGIgohdIAXAAIAZBFIAZhFIAWAAIglBgIgGAMQgDAFgCAEQgEADgEABQgFACgGAAQgGAAgGgCg");
	this.shape_9.setTransform(32.6,35.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E7E").s().p("AgaAwIAAhdIAWAAIAAAVQACgFACgEQACgFAFgDQAEgDAFgBQAFgCAGAAIAAAXIgBAAQgHAAgGACQgGADgEAFQgDAEgCAHQgCAGAAAJIAAAkg");
	this.shape_10.setTransform(24,33.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E7E").s().p("AgPAuQgJgEgGgGQgHgHgEgJIgDgKIgBgKIAAAAQABgJADgIQADgJAGgIQAHgGAIgEIAJgDIAIgBIAKABIAKADQAFADAJAIQAGAHADAKQACAJAAAIIAAAGIhEAAQABAGADAFQACAEADADIAIAFIAIABQAJAAAFgDQAGgDAGgFIANALIgHAHIgJAHIgKADIgNABQgIAAgJgDgAAYgFQgBgGgBgEIgGgIQgCgEgFgBQgEgCgFAAQgDAAgFACQgDABgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_11.setTransform(14.5,33.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E7E").s().p("AgIAvIgnhdIAXAAIAYBEIAahEIAWAAIgmBdg");
	this.shape_12.setTransform(4.2,33.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E7E").s().p("AgPAuQgJgEgHgGQgGgHgEgJIgCgKIgBgKIAAAAQgBgJAEgIQAEgJAFgIQAHgGAIgEIAJgDIAIgBIAKABIAKADQAFADAJAIQAGAHADAKQADAJAAAIIgBAGIhEAAQABAGACAFQADAEADADIAIAFIAIABQAIAAAHgDQAGgDAFgFIANALIgHAHIgJAHIgLADIgMABQgIAAgJgDgAAYgFQgBgGgCgEIgEgIQgEgEgDgBQgFgCgFAAQgDAAgEACQgFABgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_13.setTransform(-6,33.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E7E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCAEQgBAFAAAFIAAA0IgWAAIAAhdIAWAAIAAAOQAFgHAGgEIAIgDQADgCAFAAQAIAAAHADQAGACAEAFQAFAEACAIQACAGAAAIIAAA7g");
	this.shape_14.setTransform(-22.4,33.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E7E").s().p("AgJAwIgKgDQgJgEgHgGQgHgHgEgJIgCgJIgBgKIAAAAQAAgFAEgMQADgJAHgIQAHgGAJgEIAKgDIAJgBQAHAAANAEQAJAEAHAGQAHAHADAJQAEAMAAAGIgBAJIgDAKQgEAIgGAIQgHAGgKAEQgNAEgGAAgAgLgaQgFACgEAEQgDAEgCAGQgDAFAAAFQAAAGADAFQACAGAEAEQAEAEAFADQAFACAFAAQAGAAAFgCQAGgDADgEQAEgEACgGQACgFAAgGIAAAAQAAgEgCgGQgCgGgEgEQgEgEgFgCQgGgDgFAAQgFAAgGADg");
	this.shape_15.setTransform(-33.9,33.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E7E").s().p("AAZA+QgFgDgEgEQgEgFgCgFQgCgHAAgGIAAgBQAAgGACgFQACgGAEgFQAEgEAGgDQAFgCAHAAQAGAAAGACQAFADAEAEQAEAFACAFQACAGAAAGQAAAHgCAGQgCAGgEAFQgEAEgFADQgGACgGAAQgHAAgGgCgAAcATQgEAFAAAHQAAAIAEAGQAEAFAGAAQAGAAAEgFQADgGAAgHIAAgBQAAgHgDgFQgEgGgGAAQgHAAgDAGgAg1A/IAxhCIApg6IASAAIgyBAIgpA8gAgxgBQgFgDgEgEQgEgFgCgFQgCgGAAgHQAAgGACgGQACgGAEgEQAEgFAGgCQAFgDAHAAQAGAAAGADQAFACAEAFQAEAEACAGQACAFAAAHIAAAAQAAAHgCAFQgCAHgEAEQgEAEgFADQgGABgHAAQgGAAgGgBgAgvgrQgDAEAAAIIAAAAQAAAIAEAGQAEAEAGAAQAGAAAEgEQADgGAAgIQAAgHgEgFQgEgGgGAAQgGAAgEAGg");
	this.shape_16.setTransform(-52.9,32.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E7E").s().p("AgMA/IgMgFIgMgFIgJgIIAOgRQAHAIAIADQAJAFAHAAQAEAAAGgCQAEgCADgDQADgCACgFQACgDAAgGQAAgEgCgFQgBgDgFgDIgIgEQgFgCgDABQgHgBgFACIgLAEIgOgGIAEg+IBJAAIAAATIg2AAIgCAdIAJgCIAJgBQAJAAAJADQAHACAGAFQAHAFACAFQAEAIAAAJIAAABQAAAKgEAHQgDAJgGAFQgGAGgIADQgKADgJAAIgMgBg");
	this.shape_17.setTransform(-66.2,32.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E7E").s().p("AgLAMIAAgXIAWAAIAAAXg");
	this.shape_18.setTransform(-74.1,37.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E7E").s().p("AACA/IAAhmIgUAGIgFgSIAggLIAPAAIAAB9g");
	this.shape_19.setTransform(-80.7,32.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E7E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCAEQgBAFAAAFIAAA0IgWAAIAAhdIAWAAIAAAOQAFgHAGgEIAIgDQADgCAFAAQAIAAAHADQAGACAEAFQAFAEACAIQACAGAAAIIAAA7g");
	this.shape_20.setTransform(-94.5,33.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E7E").s().p("AgaAwIAAhdIAWAAIAAAVQACgFACgEQACgFAFgDQAEgDAFgBQAFgCAGAAIAAAXIgBAAQgHAAgGACQgGADgEAFQgDAEgCAHQgCAGAAAJIAAAkg");
	this.shape_21.setTransform(-103.4,33.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E7E").s().p("AgVAvQgGgCgFgEQgEgEgDgFQgCgGgBgHQAAgHADgGQADgGAFgCQAGgEAHgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgCgEQgBgEgDgCQgDgDgEgBQgFgCgDAAQgIAAgHACIgMAEIgHgRQAKgEAHgBQAJgDAIAAQALAAAIADQAIADAFAFQAFAFACAIQAEAHAAAJIAAA3IgWAAIAAgMQgGAGgGAEQgJAEgIAAQgGAAgHgCgAgHADIgIADIgEAGQgCACAAAEQAAAHAGAEQAFAEAIAAQADAAAFgCQAFgBADgDQADgCACgEQACgEAAgEIAAgHQgNgEgIAAIgHABg");
	this.shape_22.setTransform(-113,33.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E7E").s().p("AguA/IAAh8IBcAAIAAAUIhFAAIAAAgIA9AAIAAASIg9AAIAAAhIBGAAIAAAVg");
	this.shape_23.setTransform(-123.8,32.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E7E").s().p("AgLAMIAAgXIAXAAIAAAXg");
	this.shape_24.setTransform(121.9,17.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E7E").s().p("AgUA/QgIgDgGgHQgHgGgDgJIgDgKIAAgLQAAgIADgLQADgJAHgHQAGgGAIgEQAIgDAJAAQADAAAFACQAFABAEACQAHAEAGAIIAAgzIAWAAIAACBIgWAAIAAgQQgGAJgHAEQgEADgFABQgFABgDAAQgJAAgIgDgAgJgKQgFACgEAEQgDAEgCAEQgDAGAAAHQAAAHADAFQACAGADAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgCAEgEQAEgEACgGQACgFAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_25.setTransform(113.3,11.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E7E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgEQACgFAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAFgCAGQgCAGAAAJIAAAkg");
	this.shape_26.setTransform(104.4,13.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E7E").s().p("AgUAvQgHgCgEgEQgFgEgDgFQgCgGAAgHQAAgHADgGQACgGAGgCQAFgEAGgCQAIgCAJAAQAIAAAPAEIAAgCQAAgFgBgEQgCgEgDgCQgDgDgFgBQgDgCgFAAQgHAAgGACIgOAEIgGgRQAJgEAIgBQAJgDAIAAQALAAAIADQAIADAFAFQAFAFADAIQACAHAAAJIAAA3IgVAAIAAgMQgFAGgIAEQgIAEgIAAQgHAAgFgCgAgIADIgGADIgFAGQgCACABAEQAAAHAFAEQAFAEAIAAQADAAAFgCQAFgBADgDQADgCADgEQACgEAAgEIAAgHQgNgEgJAAIgIABg");
	this.shape_27.setTransform(94.8,13.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003E7E").s().p("AgFBAIgNgFIgKgGIgKgHIgIgKIgFgLQgDgGgBgGIgBgNIAAAAIABgLQABgHADgGIAFgLIAIgKIAJgIIAMgFIAMgFIAMgBQAIABAIABQAHABAGADQAIAEAMAKIgOAQQgIgHgIgEIgJgDIgKgCQgHAAgIAEQgHAEgGAGQgGAFgDAJQgDAIAAAIIAAAAQAAAIADAJQADAIAGAGQAFAHAIACQAIAEAHAAIAKgBIAKgDQAHgEAJgIIAOAOIgKAJQgGAFgGACQgGADgHACQgHACgJAAIgLgBg");
	this.shape_28.setTransform(83.3,12.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003E7E").s().p("AASBBIgagpIgNAOIAAAbIgWAAIAAiBIAWAAIAABMIAlgoIAbAAIgmAlIAnA4g");
	this.shape_29.setTransform(66.5,11.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003E7E").s().p("AgDAwIgKgDQgJgEgHgGQgGgHgEgJQgEgJAAgKIAAAAQAAgJAEgIQAEgKAGgGQAIgIAIgDIAKgDIAIgBIAMABIAKAEQAGACAKAJIgNAPQgHgGgFgCQgGgEgHAAQgFAAgEADQgFACgEAEQgEAEgCAFQgCAGAAAFQAAAGACAFQACAGAEAEQAEAFAFACQAEACAGAAQAHAAAHgDQAFgDAGgFIAMAMQgKAKgGADIgKAEIgMABg");
	this.shape_30.setTransform(55.7,13.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003E7E").s().p("AgVAvQgGgCgFgEQgEgEgDgFQgCgGgBgHQAAgHADgGQADgGAFgCQAGgEAHgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgCgEQgBgEgDgCQgDgDgEgBQgFgCgDAAQgIAAgHACIgMAEIgHgRQAKgEAHgBQAJgDAIAAQALAAAIADQAIADAFAFQAFAFACAIQAEAHAAAJIAAA3IgWAAIAAgMQgGAGgGAEQgJAEgIAAQgGAAgHgCgAgHADIgIADIgEAGQgCACAAAEQAAAHAGAEQAFAEAIAAQADAAAFgCQAFgBADgDQADgCACgEQACgEAAgEIAAgHQgNgEgIAAIgHABg");
	this.shape_31.setTransform(44.9,13.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003E7E").s().p("AgzA+IAAh8IA2AAQALABAJADQAIACAFAGQAFAEACAFQACAFAAAHIAAAAQAAAFgBAFQgBAEgEAEQgEAGgIAEIAKADQAFACADADQAEAFACAEQABAGAAAGIAAAAQAAAIgDAHQgDAGgHAEQgGAFgIACQgJACgKAAgAgdArIAjAAIAKgBIAIgDQACgCACgEQACgDAAgFIAAAAQAAgEgCgDQgBgDgDgCQgEgCgEgBIgMgCIghAAgAgdgJIAdAAIAJgBIAIgCIAEgGQACgDAAgFIAAAAQAAgDgCgDQgBgEgDgCIgHgDIgJgBIgeAAg");
	this.shape_32.setTransform(33.8,12.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003E7E").s().p("AAVBBIAAg2QAAgFgCgFIgEgFQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCADQgBAEAAAGIAAA1IgWAAIAAiBIAWAAIAAAzQAFgIAGgEIAIgDIAIgCQAIAAAHADQAGACAEAFQAFAFACAHQACAGAAAHIAAA8g");
	this.shape_33.setTransform(16,11.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003E7E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_34.setTransform(5.7,13.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003E7E").s().p("AgVAvQgGgCgFgEQgEgEgDgFQgCgGgBgHQAAgHADgGQADgGAFgCQAGgEAHgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgCgEQgBgEgDgCQgDgDgEgBQgFgCgDAAQgIAAgHACIgMAEIgHgRQAKgEAHgBQAJgDAIAAQALAAAIADQAIADAFAFQAFAFACAIQAEAHAAAJIAAA3IgWAAIAAgMQgGAGgGAEQgJAEgIAAQgGAAgHgCgAgHADIgIADIgEAGQgCACAAAEQAAAHAGAEQAFAEAIAAQADAAAFgCQAFgBADgDQADgCACgEQACgEAAgEIAAgHQgNgEgIAAIgHABg");
	this.shape_35.setTransform(-4.1,13.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003E7E").s().p("AgFBAIgNgFIgKgGIgKgHIgIgKIgFgLQgDgGgBgGIgBgNIAAAAIABgLQABgHADgGIAFgLIAIgKIAJgIIAMgFIAMgFIAMgBQAIABAIABQAHABAGADQAIAEAMAKIgOAQQgIgHgIgEIgJgDIgKgCQgHAAgIAEQgHAEgGAGQgGAFgDAJQgDAIAAAIIAAAAQAAAIADAJQADAIAGAGQAFAHAIACQAIAEAHAAIAKgBIAKgDQAHgEAJgIIAOAOIgKAJQgGAFgGACQgGADgHACQgHACgJAAIgLgBg");
	this.shape_36.setTransform(-15.6,12.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003E7E").s().p("AgUA/QgIgDgGgHQgHgGgDgJIgCgKIgBgLQgBgIAEgLQADgJAHgHQAGgGAIgEQAIgDAJAAQADAAAFACQAFABAEACQAHAEAGAIIAAgzIAWAAIAACBIgWAAIAAgQQgGAJgHAEQgEADgFABQgFABgDAAQgJAAgIgDgAgJgKQgFACgEAEQgEAEgCAEQgCAGAAAHQAAAHACAFQACAGAEAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgCAEgEQAEgEACgGQACgFAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_37.setTransform(-34.1,11.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003E7E").s().p("AAVAwIAAg0QAAgFgCgFIgEgHQgCgDgEgBQgEgDgFAAQgDAAgDADQgEABgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAOQAFgHAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAEACAIQACAGAAAIIAAA7g");
	this.shape_38.setTransform(-45.4,13.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003E7E").s().p("AgWAuQgGgDgEgFQgFgFgCgGQgCgHAAgJIAAg6IAWAAIAAA0QAAAFABAFQABAEADADQADADADACQAEABAEAAQAEAAAEgBQAEgCACgDQADgDACgFQABgEAAgGIAAgzIAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIADQgDACgFAAQgIAAgHgCg");
	this.shape_39.setTransform(-56.7,13.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003E7E").s().p("AgJAwIgKgDQgJgEgHgGQgHgHgEgJIgCgJIgBgKIAAAAQAAgFAEgMQADgKAHgGQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEAMAAAGIgBAKIgDAJQgEAIgGAIQgHAGgKAEQgNAEgGAAgAgLgaQgFABgEAFQgDAEgCAFQgDAGAAAFQAAAGADAFQACAGAEAEQAEAFAFACQAFACAFAAQAGAAAFgCQAGgCADgFQAEgEACgGQACgFAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgCQgGgDgFAAQgFAAgGADg");
	this.shape_40.setTransform(-68.1,13.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003E7E").s().p("AgJA/QgHgBgHgDQgGgCgGgEIgNgJIAOgPQAGAEANAHIAJADIAKABIAJgBIAHgDIAFgFQABgDAAgDIAAAAIgBgHQgCgCgDgDQgDgCgFgCIgMgEIgSgFQgJgEgFgCQgFgEgDgFQgCgHAAgJQAAgHADgHQADgIAGgEQAFgFAJgCQAIgEAIAAIAMACQAGABAGACQAIACANAJIgNASQgIgHgIgDQgJgDgHgBIgIACQgEABgDACQgFAEAAAGIAAAAIABAHQABADAEACIAJAEIANAEQAKADAIADQAHADAFADQAGAEACAGQACAFAAAIQABAKgEAGQgDAHgGAGQgHAEgIACQgIAEgKAAQgFAAgHgCg");
	this.shape_41.setTransform(-79.8,12.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#003E7E").s().p("AgPAuQgJgEgHgGQgGgHgEgJIgDgJIAAgLIAAAAQAAgJADgIQAEgKAFgGQAHgIAIgDIAJgDIAIgBIAKABIAKADQAGACAIAKQAGAGADAKQACAJAAAIIAAAGIhEAAQABAGADAFQACAEADADIAIAFIAIABQAIAAAHgCQAFgDAGgGIANALIgHAHIgJAHIgKADIgNABQgIAAgJgDgAAYgFQAAgFgDgFIgEgIQgEgEgEgCQgEgBgFAAQgDAAgFABQgDACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_42.setTransform(-96.3,13.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#003E7E").s().p("AAVBBIAAg2QAAgFgCgFIgEgFQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCADQgBAEAAAGIAAA1IgWAAIAAiBIAWAAIAAAzQAFgIAGgEIAIgDIAIgCQAIAAAHADQAGACAEAFQAFAFACAHQACAGAAAHIAAA8g");
	this.shape_43.setTransform(-107.3,11.8);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#003E7E").s().p("AgKA+IAAhnIgoAAIAAgVIBlAAIAAAVIgoAAIAABng");
	this.shape_44.setTransform(-118.5,12.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-162,2,324,42);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A3WzcMAutAAAMAAAAm5MgutAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.5,-125.5,301,251);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.parent = this;
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201706_Teensy_300x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(280,141,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.893,0.893);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(67,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(233,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border300x250();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A3aMGIAA4LMAu2AAAIAAYLg");
	var mask_graphics_80 = new cjs.Graphics().p("A3aMGIAA4LMAu2AAAIAAYLg");
	var mask_graphics_81 = new cjs.Graphics().p("A3aMNIAA4ZMAu2AAAIAAYZg");
	var mask_graphics_82 = new cjs.Graphics().p("A3aMTIAA4lMAu2AAAIAAYlg");
	var mask_graphics_83 = new cjs.Graphics().p("A3aMZIAA4xMAu2AAAIAAYxg");
	var mask_graphics_84 = new cjs.Graphics().p("A3aMfIAA49MAu2AAAIAAY9g");
	var mask_graphics_85 = new cjs.Graphics().p("A3aMlIAA5JMAu2AAAIAAZJg");
	var mask_graphics_86 = new cjs.Graphics().p("A3aMrIAA5VMAu2AAAIAAZVg");
	var mask_graphics_87 = new cjs.Graphics().p("A3aMxIAA5hMAu2AAAIAAZhg");
	var mask_graphics_88 = new cjs.Graphics().p("A3aM3IAA5tMAu2AAAIAAZtg");
	var mask_graphics_89 = new cjs.Graphics().p("A3aM+IAA57MAu2AAAIAAZ7g");
	var mask_graphics_169 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_170 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_171 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_172 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_173 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_174 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_175 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_176 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_177 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_178 = new cjs.Graphics().p("A6PM5IAA57MA0eAAAIAAZ7g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:150,y:77.5}).wait(80).to({graphics:mask_graphics_80,x:150,y:77.5}).wait(1).to({graphics:mask_graphics_81,x:150,y:72.6}).wait(1).to({graphics:mask_graphics_82,x:150,y:67.6}).wait(1).to({graphics:mask_graphics_83,x:150,y:62.7}).wait(1).to({graphics:mask_graphics_84,x:150,y:57.7}).wait(1).to({graphics:mask_graphics_85,x:150,y:52.8}).wait(1).to({graphics:mask_graphics_86,x:150,y:47.8}).wait(1).to({graphics:mask_graphics_87,x:150,y:42.9}).wait(1).to({graphics:mask_graphics_88,x:150,y:37.9}).wait(1).to({graphics:mask_graphics_89,x:150,y:33}).wait(80).to({graphics:mask_graphics_169,x:168,y:33}).wait(1).to({graphics:mask_graphics_170,x:168,y:20}).wait(1).to({graphics:mask_graphics_171,x:168,y:7}).wait(1).to({graphics:mask_graphics_172,x:168,y:-6}).wait(1).to({graphics:mask_graphics_173,x:168,y:-19}).wait(1).to({graphics:mask_graphics_174,x:168,y:-32}).wait(1).to({graphics:mask_graphics_175,x:168,y:-45}).wait(1).to({graphics:mask_graphics_176,x:168,y:-58}).wait(1).to({graphics:mask_graphics_177,x:168,y:-71}).wait(1).to({graphics:mask_graphics_178,x:168,y:-83.5}).wait(4).to({graphics:null,x:0,y:0}).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(132,53,1,1,0,0,0,150,57);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(169).to({y:-118},9).to({_off:true},1).wait(4));

	// PIC shad
	this.instance_4 = new lib.HTML5rastershad_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(168,165,1,1,0,0,0,0,10);
	this.instance_4.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:126},9).wait(80).to({y:1},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(269.5,195,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({y:152},9).wait(80).to({y:41},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_6 = new lib.CTA();
	this.instance_6.parent = this;
	this.instance_6.setTransform(269.5,225,1,1,0,0,0,119.5,40);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({_off:false},0).wait(79).to({y:116},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,116.7,0.893,0.833,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(169).to({y:16.7},9).to({_off:true},4).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,220.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(413.6,227.7,1.225,1.225,0,0,0,215.2,63);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.parent = this;
	this.instance_10.setTransform(253.3,207.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},182).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.5,234.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(131,125,355,250);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;