(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 250,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497572164845", id:"HTML5rastershad"},
		{src:"images/Reasons336x280.jpg?1497572164845", id:"Reasons336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Reasons336x280 = function() {
	this.initialize(img.Reasons336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,166);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Reasons336x280();
	this.instance.parent = this;
	this.instance.setTransform(-35,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35,0,336,166);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape.setTransform(79.4,47.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgIgHgEgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIAEALQACAKAAAJIAAAHIhMAAQABAGADAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgEgCQgGgCgFAAQgEAAgFACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_1.setTransform(71,43.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgDgEQgEgEgEgCQgGgCgFAAQgDAAgGACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_2.setTransform(58.9,43.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgHADQgGACgFAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_3.setTransform(49.6,43.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSBJIAAhTIgNAAIAAgUIANAAIAAgIQAAgIADgHQACgGAEgFQAEgEAFgCQAFgCAIAAQAKAAAJADIAAAUQgHgDgHABQgHAAgDADQgEAEAAAJIAAAFIAcAAIAAAUIgbAAIAABTg");
	this.shape_4.setTransform(41.4,41.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAXA1IAAg5QAAgHgBgEQgCgFgDgDQgDgEgEgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFQgBAFAAAGIAAA5IgZAAIAAhnIAZAAIAAAQQAFgJAHgEQAFgDAEgBQADgCAGAAQAJABAHADQAHACAFAGQAFAFACAHQADAIAAAJIAABBg");
	this.shape_5.setTransform(25.3,43.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgFgFgDgGQgDgFAAgIIAAgBQAAgIADgGQADgHAGgCQAGgFAIgCQAIgCAKAAQAJAAARAEIAAgCQAAgFgCgFQgBgEgEgDQgDgDgFgBQgFgCgEAAQgJAAgHACIgOAEIgHgTQAKgEAIgCQAKgCAKAAQAMAAAJADQAIADAGAGQAGAFADAJQACAIAAAKIAAA9IgXAAIAAgNQgGAHgIAEQgLAEgIAAQgHAAgHgCgAgIAEQgFABgDACQgDADgCADQgBADAAAEIAAAAQAAAIAGAFQAFADAJAAQAEABAFgCQAFgCAEgCQAEgDACgFQACgEAAgFIAAgHQgOgFgKAAQgDAAgFACg");
	this.shape_6.setTransform(12.9,43.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAXBIIAAg7QAAgHgBgEQgCgDgDgDQgDgEgEgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCADQgCAFABAGIAAA7IgZAAIAAiQIAZAAIAAA5QAFgJAHgEQAFgDAEgBQAEgCAFAAQAKABAGADQAHACAFAGQAFAFACAHQADAIAAAHIAABDg");
	this.shape_7.setTransform(1.2,41.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgCgGgBgIIAAg2IgMAAIAAgVIAMAAIAAgdIAXAAIAAAdIAdAAIAAAVIgdAAIAAAyQAAAHADADQADADAHAAQAHAAAIgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_8.setTransform(-9.2,42.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgHADQgGACgFAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_9.setTransform(-22.9,43.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgEgKIgEgKIgBgMIAAAAQABgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIADALQADAKAAAJIAAAHIhLAAQAAAGADAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgFgCQgEgCgGAAQgDAAgFACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_10.setTransform(-33.5,43.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgCgGgBgIIAAg2IgMAAIAAgVIAMAAIAAgdIAXAAIAAAdIAdAAIAAAVIgdAAIAAAyQAAAHADADQADADAHAAQAHAAAIgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_11.setTransform(-43.4,42.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgDgGABgIIAAg2IgOAAIAAgVIAOAAIAAgdIAWAAIAAAdIAdAAIAAAVIgdAAIAAAyQAAAHADADQADADAHAAQAIAAAHgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_12.setTransform(-51.6,42.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgIgHgDgKIgEgKIgBgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgEgCgGAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_13.setTransform(-61.6,43.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgFBIQgFgBgFgDQgHgFgHgIIAAAQIgYAAIAAiQIAYAAIAAA7QAHgKAIgFQAEgCAFgBQAFgCAFgBQAKABAIAEQAJADAHAHQAHAHAEAKQAEANAAAJIAAAAIgBANIgDAKQgEAKgHAHQgHAIgJADQgIAEgKAAQgFAAgFgCgAgKgLQgGADgEAEQgFAEgCAEQgCAHAAAIIAAAAQAAAIACAFQACAHAFAEQAEAFAGACQAFACAFAAQAGAAAFgCQAGgCAEgFQAEgEACgGQADgGAAgIIAAAAQAAgIgDgHQgCgEgEgEQgFgEgFgDQgGgDgFABQgFgBgFADg");
	this.shape_14.setTransform(-74.1,41.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgSAyQgQgGgHgGIAMgQQAIAGAJAEQAJADAGAAQAIAAAEgDQAFgDgBgFIAAgBQAAgFgHgEIgOgGQgQgEgHgEQgFgDgDgFQgCgFAAgIQAAgHACgGQADgGAGgFQAFgEAGgCQAIgCAFAAQAKAAAKADQAKADAJAGIgKARQgHgFgIgCQgHgDgHAAQgFAAgEADQgEADAAAEIAAABQAAAFAHAEIAPAGIALAEIALAEQAFAEACAFQAEAFAAAHIAAAAQAAAIgEAHQgCAGgGAEQgFAEgHACQgHACgJAAQgJAAgLgEg");
	this.shape_15.setTransform(48.6,23.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgPASQAJgCAFgFQABgFAAgGIgIAAIAAgbIAYAAIAAAYQAAAGgBAGQgDAGgDAEQgEAEgFACQgFACgIABg");
	this.shape_16.setTransform(40.9,17.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgCgGgBgIIAAg2IgMAAIAAgVIAMAAIAAgdIAXAAIAAAdIAcAAIAAAVIgcAAIAAAyQAAAHADADQADADAHAAQAHAAAIgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_17.setTransform(34.1,22.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgKBIIAAhoIAWAAIAABogAgLgwIAAgXIAYAAIAAAXg");
	this.shape_18.setTransform(27.2,21.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgTAyQgPgGgGgGIAKgQQAJAGAJAEQAJADAGAAQAIAAAEgDQAEgDABgFIAAgBQgBgFgHgEIgOgGQgQgEgGgEQgGgDgCgFQgDgFAAgIQAAgHADgGQADgGAFgFQAFgEAGgCQAIgCAGAAQAJAAALADQAKADAIAGIgKARQgHgFgIgCQgHgDgHAAQgFAAgEADQgEADAAAEIAAABQAAAFAHAEIAPAGIAMAEIAKAEQAFAEADAFQACAFAAAHIAAAAQAAAIgCAHQgEAGgFAEQgFAEgHACQgHACgIAAQgKAAgMgEg");
	this.shape_19.setTransform(13.2,23.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAXA1IAAg5QAAgGgBgGQgCgEgDgEQgDgDgEgBQgFgCgFAAQgDAAgFACQgEABgDADQgDAEgCAFQgCAFABAGIAAA5IgZAAIAAhnIAZAAIAAAQQAFgJAHgDQAFgDAEgCQAEgBAGgBQAIAAAHAEQAHADAFAEQAFAGACAIQADAHAAAJIAABBg");
	this.shape_20.setTransform(2.2,23.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAEQAFAFAGADQAGACAFAAQAHAAAGgCQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_21.setTransform(-10.6,23.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgTAyQgPgGgGgGIALgQQAIAGAJAEQAJADAGAAQAIAAAEgDQAFgDgBgFIAAgBQABgFgIgEIgOgGQgQgEgHgEQgEgDgEgFQgCgFAAgIQAAgHACgGQADgGAGgFQAFgEAHgCQAHgCAFAAQAKAAALADQAJADAJAGIgJARQgIgFgIgCQgIgDgGAAQgFAAgEADQgEADAAAEIAAABQAAAFAHAEIAPAGIAMAEIAKAEQAFAEADAFQADAFAAAHIAAAAQAAAIgDAHQgEAGgEAEQgGAEgHACQgHACgIAAQgKAAgMgEg");
	this.shape_22.setTransform(-22.3,23.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgFgFgDgFQgDgHAAgIIAAAAQAAgIADgGQADgHAGgDQAGgDAIgCQAIgDAKAAQAJAAARAEIAAgCQAAgGgCgEQgBgEgEgDQgDgDgFgCQgFgBgEAAQgJAAgHACIgOAFIgHgTQAKgFAIgCQAKgCAKAAQAMAAAJADQAIADAGAGQAGAGADAIQACAIAAALIAAA8IgXAAIAAgNQgGAHgIAEQgLAEgIAAQgHAAgHgCgAgIAEQgFABgDADQgDACgCADQgBADAAAEIAAAAQAAAIAGAFQAFADAJAAQAEAAAFgBQAFgBAEgEQAEgDACgEQACgEAAgFIAAgHQgOgEgKgBQgDABgFABg");
	this.shape_23.setTransform(-33.3,23.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgHgHgFgKIgDgKIgBgMIAAAAQABgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIADALQADAKAAAJIAAAHIhLAAQAAAGADAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgFACQgFACgDAEIgHAJQgCAFAAAGIA0AAIAAAAg");
	this.shape_24.setTransform(-44.8,23.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQACgFAFgEQAFgDAGgCQAGgCAGABIAAAZIgBAAQgIAAgHADQgGACgFAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_25.setTransform(-54.2,23.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgMBGIgMgDIgKgHQgFgEgEgFIgHgKIgGgNIgDgNIgBgPIAAAAIABgNIAEgOIAFgMQADgGAEgEIAJgJQAFgEAFgDQAGgDAGgCIAMgBQAGAAAGABIANAFIAKAHIAJAIIAHALIAFAMQAFASAAAJIAAAAIgCAOIgDANQgCAHgEAGQgDAGgDAFIgJAJQgFADgFADIgNAEQgGACgGAAIgMgCgAgOgtQgGAEgEAGQgFAHgDAJQgCAKAAAJIAAAAQAAAKACAJQADAJAFAHQAEAHAHAEQAGADAHABQAHgBAHgDQAHgEAFgHQAEgGACgKQADgJAAgKIAAAAQAAgJgDgJQgCgJgFgHQgFgHgGgEQgHgDgHAAQgGgBgIAEg");
	this.shape_26.setTransform(81.7,2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgMBGIgMgDIgKgHQgFgEgEgFIgHgKIgFgNIgDgNIgCgPIAAAAIACgNIADgOIAFgMQADgGAEgEIAJgJQAFgEAFgDQAGgDAHgCIALgBQAGAAAHABIAMAFIAKAHIAIAIIAIALIAFAMQAEASAAAJIAAAAIAAAOIgEANQgCAHgDAGQgEAGgEAFIgJAJQgEADgFADIgMAEQgHACgGAAIgMgCgAgNgtQgHAEgFAGQgEAHgCAJQgDAKAAAJIAAAAQAAAKADAJQACAJAEAHQAGAHAGAEQAHADAGABQAHgBAIgDQAGgEAEgHQAFgGADgKQACgJAAgKIAAAAQAAgJgCgJQgDgJgFgHQgFgHgGgEQgHgDgHAAQgHgBgGAEg");
	this.shape_27.setTransform(67.3,2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AACBGIAAhyIgWAHIgGgUIAkgMIARAAIAACLg");
	this.shape_28.setTransform(55.4,2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgYAzQgIgDgEgGQgFgFgCgHQgDgIAAgJIAAhBIAYAAIAAA6QAAAGABAFQACAEADAEIAHAFQAEABAFAAQAEAAAFgCQAEgBADgEIAFgIQABgFAAgGIAAg5IAZAAIAABnIgZAAIAAgQQgFAIgHAFQgEADgFABQgDABgGAAQgJAAgHgCg");
	this.shape_29.setTransform(39.9,3.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAEQAFAFAGADQAGACAFAAQAHAAAGgCQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_30.setTransform(27.2,3.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgiBDQgGgCgGgDIAIgSQAIAEAGAAQAGAAADgCQAEgDACgHIgshnIAaAAIAcBMIAchMIAZAAIgqBqQgDAIgEAFQgDAHgCADQgEADgGACQgEACgHgBQgHABgGgCg");
	this.shape_31.setTransform(15.2,5.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgIgHgDgKIgEgKIgBgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAbgGQgBgGgCgFQgCgFgEgEQgDgEgFgCQgEgCgGAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA1AAIAAAAg");
	this.shape_32.setTransform(-2.7,3.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgJA1IgshpIAaAAIAbBMIAchMIAaAAIgrBpg");
	this.shape_33.setTransform(-14.1,3.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgLBIIAAhnIAXAAIAABngAgMgwIAAgXIAYAAIAAAXg");
	this.shape_34.setTransform(-22.9,1.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgaBCQgMgDgKgGIAJgSQAJAFAIADQAKADAKAAQAHAAAGgCQAGgCAEgEQAEgEADgGQACgGAAgIIAAgJQgJALgHADQgEADgGABQgEACgFAAQgJAAgJgDQgJgEgHgGQgGgHgEgJQgEgHAAgMQAAgIAEgNQAEgJAGgGQAIgHAIgDQAJgEAJAAQAFAAAFACIAKAEQAIAEAHAIIAAgPIAYAAIAABSQAAANgEAKQgDAKgHAGQgDAEgFADIgKAEQgPAEgIAAQgNAAgMgEgAgLguQgFACgEAEQgEAEgCAFQgDAGAAAGIAAAAQAAAHADAFQACAFAEACQAEAEAFACQAGACAFAAQAGAAAFgCQAFgCAFgEQAFgCACgFQACgFAAgHIAAAAQAAgGgCgGQgCgFgFgEIgKgGQgFgCgGAAQgFAAgGACg");
	this.shape_35.setTransform(-32.7,5.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgLBJIAAiQIAXAAIAACQg");
	this.shape_36.setTransform(-48,1.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgLBJIAAiQIAXAAIAACQg");
	this.shape_37.setTransform(-53.7,1.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgPASQAJgCAEgFQACgFAAgGIgJAAIAAgbIAZAAIAAAYQAAAGgCAGQgBAGgFAEQgDAEgFACQgFACgHABg");
	this.shape_38.setTransform(-59.4,-2.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgDgKIAAgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgGACQgEACgDAEIgGAJQgDAFAAAGIA0AAIAAAAg");
	this.shape_39.setTransform(-67.9,3.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAiBGIgihiIghBiIgVAAIgxiLIAbAAIAhBmIAjhmIASAAIAjBmIAhhmIAaAAIgxCLg");
	this.shape_40.setTransform(-82.8,2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-127,-9,249,64);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgPAoQgMgFgFgEIAIgNQAHAFAIACQAGADAFAAQAGAAAEgCQADgDAAgEQAAgFgGgDIgKgEQgNgEgFgDQgFgCgCgEQgCgEAAgGQAAgGACgFQACgFAFgDQAEgEAFgBQAGgCAEAAQAIAAAIACQAJADAGAEIgHAOQgHgEgGgCQgHgCgEAAQgEAAgDADQgEACABADIAAABQAAAEAFADQAEACAIADIAJADIAJADQADADACAEQADAEAAAFIAAABQAAAGgDAFQgCAFgEAEQgEADgGACQgFABgIAAQgGAAgKgDg");
	this.shape.setTransform(99,26.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgTAoQgFgCgEgEQgFgFgCgGQgBgGAAgHIAAg0IATAAIAAAuQAAAFABAEQABAEADACQACADADABQAEACADAAQADAAAEgCIAGgEQACgCACgEIABgJIAAguIATAAIAABTIgTAAIAAgNQgFAHgFADIgIADQgCACgEAAQgHAAgGgDg");
	this.shape_1.setTransform(90.1,26.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AASAqIAAgtIgBgJQgBgEgCgDIgGgEIgIgBQgCAAgEACQgDABgCACQgDADgCAEQgBAEAAAFIAAAtIgTAAIAAhSIATAAIAAANQAFgHAFgEIAHgCIAHgBQAIAAAFACQAFACAFAEQADAEACAHQACAGAAAGIAAA0g");
	this.shape_2.setTransform(80.3,26.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgIAqIgJgCQgHgEgHgGQgGgFgDgJIgDgHIgBgJQAAgFAEgKQADgIAHgHQAGgGAHgDIAJgDIAIAAQAGAAALACQAJAEAGAGQAGAGADAIQAEALgBAFIAAAAIgBAIIgCAIQgDAJgGAFQgGAGgJAEQgLADgGAAgAgJgXQgFACgDADQgDAEgCAEQgCAGAAAEIAAAAQAAAFACAFQACAFADAEQAEADAEACQAFACAEABQAFgBAGgCQAEgCADgDQAEgEABgFQACgFAAgFQAAgEgCgFQgCgFgDgEQgEgEgEgBQgFgDgFAAQgEAAgFADg");
	this.shape_3.setTransform(70.1,26.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AgtA3IAAhtIAwAAQAKgBAHADQAIADAEAFQAEADACAFQACAFAAAFIAAAAIgBAJQgBAEgDADQgEAFgHAFIAJABQAEACADAEQADADABAFQACAEAAAGIAAAAQAAAHgDAGQgDAFgFAEQgGAFgHACQgIABgJAAgAgaAmIAfAAIAJgBIAHgDIAEgFQABgDAAgDQAAgEgBgDQgBgDgDgCIgIgCIgJgBIgeAAgAgagIIAaAAIAIAAIAGgDQADgCACgDQACgDAAgEIAAAAQgBgDgBgCQgBgEgDgBIgGgDIgIgBIgbAAg");
	this.shape_4.setTransform(59.4,25.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AAAA0QgEgBgDgCQgEgDgBgFQgCgFAAgHIAAgqIgLAAIAAgRIALAAIAAgXIARAAIAAAXIAXAAIAAARIgXAAIAAAnQAAAFADADQADACAFAAQAGAAAGgCIAAAQIgIADIgKABQgFAAgDgCg");
	this.shape_5.setTransform(45.1,25.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AASAqIAAgtIgBgJQgBgEgCgDIgGgEIgIgBQgCAAgEACQgDABgCACQgDADgCAEQgBAEAAAFIAAAtIgTAAIAAhSIATAAIAAANQAFgHAFgEIAHgCIAHgBQAHAAAGACQAFACAEAEQAFAEABAHQACAGAAAGIAAA0g");
	this.shape_6.setTransform(37,26.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AgTAoQgFgCgEgEQgFgFgCgGQgBgGAAgHIAAg0IATAAIAAAuQAAAFABAEQACAEACACQACADADABQAEACADAAQAEAAADgCIAGgEQACgCACgEIABgJIAAguIATAAIAABTIgTAAIAAgNQgFAHgFADIgIADQgBACgFAAQgHAAgGgDg");
	this.shape_7.setTransform(27,26.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgIAqIgJgCQgHgEgHgGQgGgFgDgJIgDgHIgBgJQABgFADgKQADgIAHgHQAGgGAHgDIAJgDIAIAAQAGAAALACQAJAEAGAGQAGAGADAIQAEALgBAFIAAAAIgBAIIgCAIQgDAJgGAFQgGAGgJAEQgLADgGAAgAgJgXQgFACgDADQgEAEgBAEQgCAGAAAEIAAAAQAAAFACAFQABAFAEAEQAEADAEACQAFACAEABQAGgBAEgCQAFgCADgDQAEgEACgFQABgFAAgFQAAgEgBgFQgCgFgEgEQgDgEgFgBQgFgDgFAAQgEAAgFADg");
	this.shape_8.setTransform(16.9,26.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgDAqIgIgCQgIgEgGgGQgGgFgDgJQgEgIAAgIQAAgIAEgHQADgIAGgHQAGgGAIgDIAIgDIAHAAIALABIAJACQAGADAIAIIgMANQgFgFgFgDQgFgDgHAAQgEAAgEADQgEACgDADQgEAEgBAEQgCAGAAAEIAAAAQAAAFACAFQABAFAEAEQADADAFACQADACAFABQAGgBAGgDQAFgCAFgFIAMAMQgJAIgGADIgJADIgLABg");
	this.shape_9.setTransform(7.4,26.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgDAqIgIgCQgIgEgGgGQgGgFgDgJQgEgIAAgIQAAgIAEgHQADgIAGgHQAGgGAIgDIAIgDIAHAAIALABIAJACQAGADAIAIIgMANQgFgFgFgDQgFgDgHAAQgEAAgEADQgEACgDADQgEAEgBAEQgCAGAAAEIAAAAQAAAFACAFQABAFAEAEQADADAFACQADACAFABQAGgBAGgDQAFgCAFgFIAMAMQgJAIgGADIgJADIgLABg");
	this.shape_10.setTransform(-1.4,26.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AAlA4IgLgbIgzAAIgMAbIgUAAIAxhvIARAAIAxBvgAATAMIgTgrIgSArIAlAAg");
	this.shape_11.setTransform(-12,25.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AASAqIgSg3IgSA3IgRAAIgchTIAUAAIARA4IATg4IAPAAIASA4IASg4IATAAIgcBTg");
	this.shape_12.setTransform(-29.9,26.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgNAoQgIgDgGgGQgGgFgDgIIgDgJIgBgJIAAAAQAAgIADgIQADgIAGgGQAFgGAIgDIAIgDIAHAAIAKAAIAIADQAEACAIAIQAFAGADAJQACAHAAAIIAAAFIg8AAQABAFACAEIAFAHQAEADADABQAEACADAAQAHAAAFgDQAGgCAFgFIAMAKIgHAGIgIAFIgKADIgKABQgHAAgIgDgAAVgEIgCgJQgBgEgEgEQgCgDgEgBQgDgCgFAAQgDAAgDACQgEABgDADIgFAIIgDAJIAqAAIAAAAg");
	this.shape_13.setTransform(-41.2,26.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AAgA3Ig8hNIAABNIgTAAIAAhtIASAAIA6BLIAAhLIATAAIAABtg");
	this.shape_14.setTransform(-52.4,25.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgJA4IgKgDIgIgGIgHgGQgDgEgDgFIgEgJIgCgMIgBgLIAAAAIABgKIACgLIAFgKIAFgJIAHgGIAJgGIAJgDQAFgBAEAAQAFAAAFABIAKADQAEACAEAEIAHAGIAGAJIAEAJQADAPAAAHIAAAAIAAALIgDALIgEAKIgGAJIgHAGIgIAGIgKADIgKABIgJgBgAgKgjQgFADgEAFQgEAGgCAGQgCAIAAAHIAAAAQAAAIACAHQACAHAEAGQAEAFAFADQAFADAFAAQAGAAAGgDQAFgDAEgFQADgGACgGQACgIAAgIIAAAAQAAgHgCgHQgCgHgEgGQgEgFgFgDQgFgDgGAAQgFAAgFADg");
	this.shape_15.setTransform(-69.3,25.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgJA4IgKgDIgIgGIgHgGQgDgEgDgFIgEgJIgCgMIgBgLIAAAAIABgKIACgLIAFgKIAFgJIAHgGIAJgGIAJgDQAFgBAEAAQAFAAAFABIAKADQAEACAEAEIAHAGIAGAJIAEAJQADAPAAAHIAAAAIAAALIgDALIgEAKIgGAJIgHAGIgIAGIgKADIgKABIgJgBgAgKgjQgFADgEAFQgEAGgCAGQgCAIAAAHIAAAAQAAAIACAHQACAHAEAGQAEAFAFADQAFADAFAAQAGAAAGgDQAFgDAEgFQADgGACgGQACgIAAgIIAAAAQAAgHgCgHQgCgHgEgGQgEgFgFgDQgFgDgGAAQgFAAgFADg");
	this.shape_16.setTransform(-80.8,25.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AACA4IAAhbIgSAGIgFgQIAdgKIANAAIAABvg");
	this.shape_17.setTransform(-90.3,25.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgEBEIAAgQQgNgDgHgCQgJgEgIgHIAKgPQAHAGAGAEQAHADAIABIAAgfQgJgCgGgCQgHgCgEgEQgEgEgCgFQgCgFAAgHIAAAAQAAgGACgGQADgFAEgEQAFgEAGgDQAGgCAHgBIAAgJIAMAAIAAAKQAJABAHADQAHADAHAFIgJAPIgKgHIgLgEIAAAfQAJACAGADQAHADAEACQAEAEACAFQACAFAAAHIAAAAQAAAHgCAFQgCAGgFAEQgFAEgGACQgGADgIAAIAAAQgAAIAkQAHgBAEgDQAEgEAAgGQAAgFgDgEQgDgDgJgDgAgPglQgDADAAAGQAAAFADADQADAEAJADIAAgdQgHABgFAEg");
	this.shape_18.setTransform(-98.1,25.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgIAnIAAgfIgeAAIAAgQIAeAAIAAgeIARAAIAAAeIAeAAIAAAQIgeAAIAAAfg");
	this.shape_19.setTransform(60.3,7.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AgUA1QgKgDgIgFIAHgOIAOAGQAIACAIAAQAFAAAFgBQAFgCADgDQADgDACgFQACgFAAgGIAAgHQgIAJgEACIgIADQgEACgDAAQgIAAgHgDQgHgDgFgFQgGgFgDgHQgDgFAAgKIAAAAQAAgHADgKQADgHAGgFQAFgFAHgDQAHgCAIAAIAHABIAIACQAGAEAGAGIAAgMIATAAIAABBQAAALgCAIQgDAHgGAGIgGAFIgIAEQgNACgFAAQgLABgJgDgAgIglQgFACgDADQgDADgCAEQgBAEAAAGQAAAFABAEQACAFADABQADADAFABQAEADAEAAQAFAAAEgDQAFgBADgDQADgCACgEQACgEAAgFQAAgGgCgEQgCgEgDgDQgDgDgFgBQgEgCgFgBQgEAAgEACg");
	this.shape_20.setTransform(44.9,9.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AASAqIAAgtIgBgJQgBgEgDgDIgFgEIgIgBQgCAAgDACQgEABgDACQgCADgBAEQgCAEAAAFIAAAtIgUAAIAAhSIAUAAIAAANQAEgHAHgEIAGgCIAIgBQAGAAAGACQAGACADAEQAFAEACAHQACAGAAAGIAAA0g");
	this.shape_21.setTransform(34.8,8.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgIA5IAAhSIARAAIAABSgAgJgmIAAgTIATAAIAAATg");
	this.shape_22.setTransform(27.6,7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AAQA6IgWgkIgNAMIAAAYIgTAAIAAhzIATAAIAABEIAhgkIAYAAIghAhIAiAyg");
	this.shape_23.setTransform(21.1,7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AgDAqIgIgCQgIgEgGgGQgGgFgDgJQgEgIAAgIQAAgIAEgHQADgIAGgHQAGgGAIgDIAIgDIAHAAIALABIAJACQAGADAIAIIgMANQgFgFgFgDQgFgDgHAAQgEAAgEADQgEACgDADQgEAEgBAEQgCAGAAAEIAAAAQAAAFACAFQABAFAEAEQADADAFACQADACAFABQAGgBAGgDQAFgCAFgFIAMAMQgJAIgGADIgJADIgLABg");
	this.shape_24.setTransform(11.5,8.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgNAoQgIgDgGgGQgGgFgDgIIgDgJIgBgJIAAAAQAAgIAEgIQADgIAFgGQAFgGAIgDIAIgDIAHAAIAKAAIAIADQAEACAIAIQAFAGACAJQADAHAAAIIAAAFIg8AAQABAFACAEIAFAHQAEADADABQAEACADAAQAHAAAFgDQAGgCAFgFIAMAKIgHAGIgIAFIgKADIgKABQgHAAgIgDgAAVgEIgCgJQgBgEgEgEQgCgDgEgBQgEgCgEAAQgDAAgDACQgEABgDADIgFAIIgDAJIAqAAIAAAAg");
	this.shape_25.setTransform(2.1,8.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AASA6IAAgwIgBgJQgBgCgDgCIgFgFIgIgBQgCABgDABQgEABgDADQgCACgBACQgCAFAAAEIAAAwIgUAAIAAhzIAUAAIAAAuQAEgIAHgDIAGgDIAHgBQAIAAAFACQAFADAFADQADAFACAGQADAGAAAFIAAA2g");
	this.shape_26.setTransform(-7.7,7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AgFA4IgKgDQgGgCgEgEIgJgGIgGgJIgFgJIgEgMIgBgLIAAAAIABgKIADgLIAGgKIAGgJIAJgGIAKgGIALgDIAKgBQAHAAAHABQAGABAGACQAHADALAKIgNAOQgHgGgHgEIgIgCIgJgBQgGAAgHADQgHADgFAFQgFAGgCAHQgDAHAAAHIAAAAQAAAIADAHQACAHAFAFQAFAGAHADQAHADAGAAIAJgBIAIgCQAHgEAIgHIANAMIgKAJIgKAGIgMAEQgGABgIAAIgKgBg");
	this.shape_27.setTransform(-18.4,7.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgNAoQgIgDgGgGQgGgFgDgIIgCgJIgBgJIAAAAQAAgIADgIQADgIAFgGQAGgGAHgDIAIgDIAHAAIAJAAIAIADQAFACAIAIQAFAGACAJQAEAHAAAIIgBAFIg8AAQAAAFADAEIAFAHQADADAEABQAFACACAAQAHAAAGgDQAFgCAFgFIALAKIgGAGIgIAFIgJADIgLABQgHAAgIgDgAAVgEIgCgJQgBgEgDgEQgDgDgEgBQgEgCgEAAQgCAAgFACQgDABgDADIgFAIIgCAJIApAAIAAAAg");
	this.shape_28.setTransform(-34.1,8.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("AgNAoQgIgDgGgGQgGgFgDgIIgDgJIgBgJIAAAAQAAgIAEgIQADgIAFgGQAGgGAHgDIAIgDIAHAAIAJAAIAJADQAEACAIAIQAFAGACAJQADAHAAAIIAAAFIg8AAQAAAFADAEIAFAHQADADAEABQAFACACAAQAHAAAGgDQAFgCAFgFIALAKIgGAGIgIAFIgKADIgKABQgHAAgIgDgAAVgEIgCgJQgCgEgCgEQgDgDgEgBQgEgCgEAAQgCAAgFACQgDABgDADIgFAIIgDAJIAqAAIAAAAg");
	this.shape_29.setTransform(-43.7,8.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_30.setTransform(-51.2,8.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AgoA3IAAhtIBRAAIAAASIg9AAIAAAeIA2AAIAAAQIg2AAIAAAtg");
	this.shape_31.setTransform(-59.7,7.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139,-2,278,38);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border250x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("AzczcMAm5AAAMAAAAm5Mgm5AAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.5,-125.5,251,251);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.parent = this;
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201706_Reasons_250x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(229,142,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.744,0.893);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(61,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(187,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border250x250();
	this.instance_2.parent = this;
	this.instance_2.setTransform(125,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AzXMEIAA4HMAmvAAAIAAYHg");
	var mask_graphics_80 = new cjs.Graphics().p("AzXMEIAA4HMAmvAAAIAAYHg");
	var mask_graphics_81 = new cjs.Graphics().p("AzVLwIAA3bMAmvAAAIAAXbg");
	var mask_graphics_82 = new cjs.Graphics().p("AzVLaIAA2uMAmvAAAIAAWug");
	var mask_graphics_83 = new cjs.Graphics().p("AzVLEIAA2CMAmvAAAIAAWCg");
	var mask_graphics_84 = new cjs.Graphics().p("AzVKtIAA1VMAmvAAAIAAVVg");
	var mask_graphics_85 = new cjs.Graphics().p("AzVKXIAA0pMAmvAAAIAAUpg");
	var mask_graphics_86 = new cjs.Graphics().p("AzVKBIAAz9MAmvAAAIAAT9g");
	var mask_graphics_87 = new cjs.Graphics().p("AzVJrIAAzQMAmvAAAIAATQg");
	var mask_graphics_88 = new cjs.Graphics().p("AzVJVIAAykMAmvAAAIAASkg");
	var mask_graphics_89 = new cjs.Graphics().p("AzVI+IAAx3MAmvAAAIAAR3g");
	var mask_graphics_169 = new cjs.Graphics().p("AzVI+IAAx3MAmvAAAIAAR3g");
	var mask_graphics_170 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_171 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_172 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_173 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_174 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_175 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_176 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_177 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");
	var mask_graphics_178 = new cjs.Graphics().p("AzVI8IAAx3MAmvAAAIAAR3g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:124.5,y:77.7}).wait(80).to({graphics:mask_graphics_80,x:124.5,y:77.7}).wait(1).to({graphics:mask_graphics_81,x:124.3,y:75.3}).wait(1).to({graphics:mask_graphics_82,x:124.3,y:73}).wait(1).to({graphics:mask_graphics_83,x:124.3,y:70.8}).wait(1).to({graphics:mask_graphics_84,x:124.3,y:68.6}).wait(1).to({graphics:mask_graphics_85,x:124.3,y:66.4}).wait(1).to({graphics:mask_graphics_86,x:124.3,y:64.2}).wait(1).to({graphics:mask_graphics_87,x:124.3,y:61.9}).wait(1).to({graphics:mask_graphics_88,x:124.3,y:59.7}).wait(1).to({graphics:mask_graphics_89,x:124.3,y:57.5}).wait(80).to({graphics:mask_graphics_169,x:124.3,y:57.5}).wait(1).to({graphics:mask_graphics_170,x:124.3,y:44.9}).wait(1).to({graphics:mask_graphics_171,x:124.3,y:32.1}).wait(1).to({graphics:mask_graphics_172,x:124.3,y:19.4}).wait(1).to({graphics:mask_graphics_173,x:124.3,y:6.6}).wait(1).to({graphics:mask_graphics_174,x:124.3,y:-6.2}).wait(1).to({graphics:mask_graphics_175,x:124.3,y:-19}).wait(1).to({graphics:mask_graphics_176,x:124.3,y:-31.7}).wait(1).to({graphics:mask_graphics_177,x:124.3,y:-44.5}).wait(1).to({graphics:mask_graphics_178,x:124.3,y:-57.3}).wait(4).to({graphics:null,x:0,y:0}).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(174,57,1,1,0,0,0,150,57);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({y:42},9).wait(80).to({regX:150.1,regY:57.1,x:174.1,y:42.1},0).to({y:-57.5},9).to({_off:true},1).wait(4));

	// shad
	this.instance_4 = new lib.HTML5rastershad_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(118,164,1,1,0,0,0,0,10);
	this.instance_4.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:124},9).wait(80).to({y:10},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(246,199,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({y:163},9).wait(80).to({y:51},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_6 = new lib.CTA();
	this.instance_6.parent = this;
	this.instance_6.setTransform(244.5,235,1,1,0,0,0,119.5,40);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({_off:false},0).wait(79).to({y:127},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,116.7,0.893,0.833,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(169).to({y:16.7},9).to({_off:true},4).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(125,220.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(388.6,227.7,1.225,1.225,0,0,0,215.2,63);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.parent = this;
	this.instance_10.setTransform(228.3,207.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},182).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.5,234.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(75,125,350,250);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;