(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 336,
	height: 280,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497648022503", id:"HTML5rastershad"},
		{src:"images/Neighbor336x280.jpg?1497648022503", id:"Neighbor336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Neighbor336x280 = function() {
	this.initialize(img.Neighbor336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Neighbor336x280();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTAUIAAgnIAnAAIAAAng");
	this.shape.setTransform(105.6,53.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgiBpQgNgGgKgKQgLgLgGgPIgFgQIgCgTIAAAAQABgNAGgUQAGgPAKgLQALgKANgGQANgFAOAAQAHAAAJACQAIACAHAEQAMAHAJANIAAhWIAkAAIAADZIgkAAIAAgaQgJAOgMAHQgIAEgHACQgJADgHAAQgOAAgNgGgAgQgRQgIADgGAHQgHAGgDAHQgDAKgBAMIAAAAQABAMADAJQADAJAHAHQAGAHAIADQAJAEAHAAQAJAAAIgEQAJgDAGgHQAHgHADgJQAEgKAAgLIAAAAQAAgLgEgKQgDgHgHgHQgGgHgJgDQgIgEgJAAQgIAAgIAEg");
	this.shape_1.setTransform(91.1,45.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQBQIgQgEQgPgHgMgLQgMgLgFgPIgGgQIgBgQIAAAAQAAgJAHgVQAFgPAMgMQAMgLAPgHIAQgFIAQgBQAMAAAVAGQAPAHAMALQAMALAFAPQAHAVAAAKIAAAAIgBAQIgGAPQgFAPgMAMQgMALgPAHQgWAGgLAAgAgTguQgIAFgGAGQgHAIgDAIQgDAKgBAJIAAAAQABAKADAJQADAKAHAGQAHAHAIAFQAKADAIAAQAKAAAKgDQAIgFAGgHQAHgHAEgIQADgJAAgLIAAAAQgBgJgDgJQgEgJgGgIQgHgGgIgFQgJgDgKAAQgKAAgJADg");
	this.shape_2.setTransform(71.6,48.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgQBQIgQgEQgPgHgMgLQgLgLgHgPIgFgQIgBgQIAAAAQAAgJAGgVQAHgPALgMQAMgLAPgHIAQgFIAQgBQAMAAAVAGQAQAHALALQAMALAFAPQAHAVAAAKIAAAAIgBAQIgGAPQgFAPgMAMQgMALgPAHQgWAGgLAAgAgTguQgIAFgGAGQgHAIgDAIQgEAKAAAJIAAAAQAAAKAEAJQADAKAHAGQAGAHAJAFQAKADAIAAQAKAAAKgDQAJgFAGgHQAGgHAEgIQACgJABgLIAAAAQgBgJgDgJQgEgJgGgIQgGgGgJgFQgJgDgKAAQgKAAgJADg");
	this.shape_3.setTransform(51.9,48.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAjBtIAAhaQgBgJgCgHQgDgGgDgEQgFgGgGgCQgGgDgJAAQgFAAgHADQgGACgGAGQgEAFgDAFQgCAHgBAKIAABZIgkAAIAAjZIAkAAIAABVQAKgNAKgGQAGgFAIgCQAFgBAJAAQANAAALADQALAFAGAIQAIAIADALQAFALAAAMIAABlg");
	this.shape_4.setTransform(32.9,45.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgsBQIAAicIAkAAIAAAjQAEgJAEgHQAEgHAHgFQAHgFAIgDQAJgDAKABIAAAmIgBAAQgMAAgKAEQgKAEgHAIQgFAIgFAMQgDAKAAAPIAAA8g");
	this.shape_5.setTransform(18,47.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQBQIgRgEQgOgHgMgLQgLgLgHgPIgEgQIgCgQIAAAAQAAgJAGgVQAHgPALgMQAMgLAPgHIAQgFIAQgBQAMAAAWAGQAOAHAMALQALALAHAPQAGAVAAAKIAAAAIgCAQIgEAPQgHAPgLAMQgMALgPAHQgVAGgMAAgAgSguQgKAFgGAGQgGAIgDAIQgDAKAAAJIAAAAQAAAKADAJQAEAKAGAGQAHAHAIAFQAJADAJAAQAKAAAJgDQAJgFAHgHQAGgHAEgIQACgJAAgLIAAAAQABgJgEgJQgDgJgHgIQgGgGgJgFQgKgDgJAAQgJAAgJADg");
	this.shape_6.setTransform(1.3,48.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgIBsQgIgCgHgEQgMgHgJgMIAAAYIgkAAIAAjZIAkAAIAABXQAKgOAMgHQAGgEAIgCQAIgCAIAAQAOAAANAFQANAGALAKQAKALAGAPQAGAUAAANIAAAAIgBATIgFAQQgGAPgKALQgKAKgOAGQgNAGgOAAQgIAAgIgDgAgQgRQgJADgGAHQgHAHgDAHQgEAKAAALIAAAAQAAALAEAKQADAJAHAHQAGAHAJADQAIAEAIAAQAIAAAJgEQAIgDAGgHQAGgGAEgKQADgJAAgMIAAAAQAAgLgDgKQgEgHgGgHQgGgHgIgDQgJgEgIAAQgIAAgIAEg");
	this.shape_7.setTransform(-18.2,45.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAjBtIAAhaQgBgJgCgHQgCgGgEgEQgFgGgGgCQgGgDgJAAQgGAAgGADQgHACgFAGQgEAFgDAFQgCAHgBAKIAABZIgkAAIAAjZIAkAAIAABVQAKgNAKgGQAGgFAIgCQAFgBAJAAQANAAALADQAKAFAHAIQAIAIADALQAFALAAAMIAABlg");
	this.shape_8.setTransform(-37.9,45.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgnBkQgSgFgQgJIAOgcQAOAJANAEQAOAEAQAAQAKAAAJgDQAJgDAGgGQAHgHADgIQADgKAAgMIAAgMQgNAQgJAFQgIAEgIACQgHACgJAAQgNAAgNgEQgNgGgKgJQgLgKgFgNQgHgNAAgRIAAgBQABgLAGgTQAFgOALgKQAKgJANgGQANgEANAAQAJAAAIABQAIACAHAFQALAGALAMIAAgYIAkAAIAAB8QAAAVgEAOQgFAQgLAJQgFAGgHAEIgPAHQgYAEgMAAQgTAAgSgEgAgRhGQgHADgGAGQgHAGgDAIQgEAIAAAJIAAABQAAAJAEAIQADAJAHAEQAFAFAJAEQAIADAIAAQAIAAAJgDQAJgEAGgFQAGgEAEgJQAEgIAAgJIAAgBQAAgJgEgIQgEgIgGgGQgGgGgJgDQgJgDgIAAQgIAAgJADg");
	this.shape_9.setTransform(-57.7,50.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQBsIAAidIAiAAIAACdgAgShJIAAgiIAlAAIAAAig");
	this.shape_10.setTransform(-71.6,45.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaBMQgPgFgLgMQgLgLgGgPIgFgQIgBgRIAAAAQAAgQAGgOQAFgPAKgMQALgLAOgHIAPgFIAOgBQAKAAAIABIAPAFQAKAFAOAOQAKAMAEAPQAFAPAAAQIAAAKIhzAAQACAJAEAJQAEAHAGAFQAGAFAHADQAIACAHAAQANAAAKgEQAKgFAKgKIAVATQgGAHgGAGQgHAFgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogKQgBgIgDgIQgDgIgFgFQgFgGgHgDQgHgDgJAAQgGAAgHADQgHADgGAFQgFAGgDAHQgEAIgBAJIBPAAIAAAAg");
	this.shape_11.setTransform(-85,48.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAjBQIAAhYQAAgJgDgHQgCgHgEgFQgFgFgGgDQgHgDgHAAQgHAAgGADQgHADgFAFQgEAFgDAHQgDAIABAJIAABXIgkAAIAAicIAkAAIAAAYQAJgNAKgGQAGgEAIgCQAFgCAJAAQAOAAAKAEQAKAEAHAIQAIAIADALQAFALAAAOIAABjg");
	this.shape_12.setTransform(-103.2,47.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaBMQgPgFgLgLQgLgMgGgOIgFgRIgBgRIAAAAQAAgPAGgPQAFgQAKgLQALgMAOgFIAPgGIAOgBQAKAAAIABIAPAGQAKAEAOAPQAKALAEAQQAFAPAAAPIAAAKIhzAAQACAKAEAHQAEAIAGAFQAGAFAHADQAIACAHAAQANABAKgGQAKgEAKgJIAVASQgGAIgGAEQgHAGgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogJQgBgKgDgHQgDgIgFgFQgFgGgHgDQgHgEgJAAQgGAAgHAEQgHADgGAFQgFAFgDAJQgEAHgBAKIBPAAIAAAAg");
	this.shape_13.setTransform(131.2,18.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAjBtIAAhaQgBgJgCgHQgDgFgDgGQgFgEgGgDQgGgDgJAAQgFAAgHADQgGACgGAGQgEAFgDAFQgCAIgBAIIAABaIgkAAIAAjZIAkAAIAABVQAKgNAKgHQAGgDAIgCQAFgCAJgBQANABALAEQALAEAGAIQAIAIADALQAFALAAAMIAABlg");
	this.shape_14.setTransform(113,15.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgBBkQgIgDgGgFQgGgGgEgJQgDgJAAgNIAAhRIgUAAIAAgfIAUAAIAAgsIAiAAIAAAsIArAAIAAAfIgrAAIAABMQAAAKAGAFQAEAFAKAAQAMAAAKgGIAAAeQgHAEgHACQgIACgKAAQgLAAgGgCg");
	this.shape_15.setTransform(97.2,16);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgiBpQgNgGgLgKQgKgLgGgPIgEgQIgCgTIAAAAQgBgNAHgUQAFgPALgLQAKgKAOgGQANgFAOAAQAIAAAIACQAIACAGAEQANAHAJANIAAhWIAlAAIAADZIglAAIAAgaQgJAOgNAHQgGAEgIACQgIADgIAAQgOAAgNgGgAgQgRQgIADgHAHQgFAGgEAHQgEAKABAMIAAAAQgBAMAEAJQADAJAHAHQAGAHAJADQAHAEAIAAQAJAAAJgEQAHgDAHgHQAGgHAEgJQAEgKAAgLIAAAAQAAgLgEgKQgEgHgGgHQgHgHgHgDQgJgEgJAAQgHAAgJAEg");
	this.shape_16.setTransform(71.8,15.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAiBQIAAhYQABgJgDgHQgCgHgFgFQgEgFgGgDQgHgDgIAAQgFAAgHADQgGADgFAFQgFAFgDAHQgDAIAAAJIAABXIgkAAIAAicIAkAAIAAAYQAJgNALgGQAHgEAGgCQAHgCAIAAQANAAALAEQAKAEAIAIQAHAIAEALQADALAAAOIAABjg");
	this.shape_17.setTransform(53,17.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AglBMQgLgFgHgHQgHgIgEgLQgEgMAAgNIAAhjIAlAAIAABYQAAAJACAHQACAHAEAFQAFAFAGADQAGACAIAAQAGAAAHgCQAGgDAFgFQAFgFACgHQADgIAAgJIAAhXIAlAAIAACcIglAAIAAgYQgJANgKAGQgHAEgHACQgFACgJABQgOgBgKgEg");
	this.shape_18.setTransform(34.2,18.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgQBQIgRgEQgPgHgLgLQgLgMgHgOIgEgQIgCgQIAAAAQAAgKAGgUQAHgQALgLQAMgMAPgFIAQgGIAQgBQAMAAAWAGQAPAHALALQAMALAFAPQAHAVAAAKIAAAAIgCAQIgFAQQgFAPgMALQgMALgPAHQgWAGgLAAgAgSgtQgKAEgFAGQgHAIgDAJQgEAJAAAJIAAAAQAAAKAEAJQAEAJAGAHQAGAIAJADQAKAEAIAAQAKAAAKgEQAIgDAHgIQAGgGAEgKQACgJAAgKIAAAAQAAgJgDgJQgDgJgHgIQgGgGgJgEQgJgEgKgBQgKABgIAEg");
	this.shape_19.setTransform(15.1,18.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgtBQIAAicIAkAAIAAAjQAFgJAEgHQAEgHAHgFQAHgFAIgDQAKgDAJABIAAAmIgCAAQgMAAgJAEQgKAEgHAIQgGAIgDAMQgFAKAAAPIAAA8g");
	this.shape_20.setTransform(0.3,17.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgYAbQAOgDAHgHQAEgHgBgKIgNAAIAAgpIAmAAIAAAjQAAALgDAIQgDAKgGAFQgGAGgHAEQgIADgMABg");
	this.shape_21.setTransform(-11,9.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AglBMQgLgFgHgHQgHgIgEgLQgEgMAAgNIAAhjIAlAAIAABYQAAAJACAHQACAHAEAFQAFAFAGADQAGACAIAAQAGAAAHgCQAGgDAFgFQAFgFACgHQADgIAAgJIAAhXIAlAAIAACcIglAAIAAgYQgJANgKAGQgHAEgHACQgFACgJABQgOgBgKgEg");
	this.shape_22.setTransform(-33,18.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgRBQIgQgEQgOgHgMgLQgLgMgHgOIgEgQIgCgQIAAAAQAAgKAGgUQAHgQALgLQAMgMAPgFIAQgGIAQgBQAMAAAWAGQAOAHAMALQALALAHAPQAGAVAAAKIAAAAIgCAQIgEAQQgHAPgLALQgMALgPAHQgWAGgLAAgAgSgtQgJAEgHAGQgGAIgDAJQgEAJABAJIAAAAQgBAKAEAJQADAJAHAHQAGAIAJADQAJAEAJAAQALAAAIgEQAKgDAFgIQAHgGADgKQADgJAAgKIAAAAQAAgJgDgJQgEgJgGgIQgHgGgIgEQgKgEgJgBQgJABgJAEg");
	this.shape_23.setTransform(-52.1,18.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag1BlQgIgDgJgEIAMgbQALAGALAAQAHAAAFgEQAGgEAEgKIhCidIAnAAIArBzIAphzIAmAAIg/ChQgFAMgFAIQgFAJgFAFQgGAFgHADQgIACgKAAQgKAAgKgCg");
	this.shape_24.setTransform(-70,20.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgaBMQgPgFgLgLQgLgMgGgOIgFgRIgBgRIAAAAQAAgPAGgPQAFgQAKgLQALgMAOgFIAPgGIAOgBQAKAAAIABIAPAGQAKAEAOAPQAKALAEAQQAFAPAAAPIAAAKIhzAAQACAKAEAHQAEAIAGAFQAGAFAHADQAIACAHAAQANABAKgGQAKgEAKgJIAVASQgGAIgGAEQgHAGgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogJQgBgKgDgHQgDgIgFgFQgFgGgHgDQgHgEgJAAQgGAAgHAEQgHADgGAFQgFAFgDAJQgEAHgBAKIBPAAIAAAAg");
	this.shape_25.setTransform(-96.9,18.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgaBMQgPgFgLgLQgLgMgGgOIgFgRIgBgRIAAAAQAAgPAGgPQAFgQAKgLQALgMAOgFIAPgGIAOgBQAKAAAIABIAPAGQAKAEAOAPQAKALAEAQQAFAPAAAPIAAAKIhzAAQACAKAEAHQAEAIAGAFQAGAFAHADQAIACAHAAQANABAKgGQAKgEAKgJIAVASQgGAIgGAEQgHAGgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogJQgBgKgDgHQgDgIgFgFQgFgGgHgDQgHgEgJAAQgGAAgHAEQgHADgGAFQgFAFgDAJQgEAHgBAKIBPAAIAAAAg");
	this.shape_26.setTransform(-115,18.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgQBqQgMgDgLgEQgLgEgKgHQgKgGgKgIIAWgaQAKAIAVAMIARAFQAJACAIAAQAIAAAHgCQAHgCAFgDQAFgEACgFQADgFAAgFIAAgBQAAgGgCgFQgCgEgFgDQgGgFgJgCIgVgHQgTgEgLgFQgOgFgIgFQgJgHgFgKQgFgLAAgOIAAAAQAAgOAGgMQAFgLAKgIQAJgHANgFQAOgEAPgBQAKAAAKACQAKACAKAEQAMAEAWAPIgTAcQgPgLgOgGQgOgFgMAAQgIAAgHACQgGACgFAEQgJAGAAALIAAABQAAAGADAFQACAEAFAEQAGADAKAEIAXAHQARAEAMAFQANAFAIAGQAIAHAEAKQAFAJAAANIAAAAQAAAPgGAMQgFAMgKAIQgKAIgOAEQgOAFgQgBQgKAAgMgBg");
	this.shape_27.setTransform(-133.9,15.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,0,337,64);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgPAQIAAgfIAfAAIAAAfg");
	this.shape.setTransform(84.2,45.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_1.setTransform(75.8,39.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgNBWIAAh8IAbAAIAAB8gAgOg6IAAgcIAdAAIAAAcg");
	this.shape_2.setTransform(67.7,38.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgWBYIAAhkIgQAAIAAgYIAQAAIAAgKQAAgKADgIQADgIAFgFQAFgFAGgCQAGgDAJAAQANAAALADIAAAZQgJgDgIAAQgIAAgFAEQgEAFAAAKIAAAHIAiAAIAAAYIghAAIAABkg");
	this.shape_3.setTransform(60,38.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAJgJAMgFIAOgEIAMgCQAJAAARAGQAMAFAKAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgJAJgMAFQgSAGgIAAgAgPgkQgHADgFAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAHQAEAIAEAFQAGAGAHADQAHADAHAAQAIAAAIgDQAGgDAFgGQAFgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgGgDQgIgDgHAAQgIAAgHADg");
	this.shape_4.setTransform(47.4,40.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_5.setTransform(35.5,40.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AhABTIAAilIBBAAQAOAAANADQALAFAIAHQAJAIAEAJQAEALABANIAAAAIgBAOIgFALQgEAJgKAHQgJAHgNAEQgMADgMAAIghAAIAAA2gAgiADIAiAAQAHAAAGgDQAHAAAFgDQAFgFACgFQADgFAAgHIAAgBQAAgHgDgFQgCgGgFgEQgFgDgHgDQgGgBgHAAIgiAAg");
	this.shape_6.setTransform(22.7,38.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_7.setTransform(2.4,40.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAJgJAMgFIAOgEIAMgCQAJAAARAGQANAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgBANIgEAMQgFAMgJAJQgJAJgNAFQgSAGgIAAgAgPgkQgGADgGAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAHQAEAIAEAFQAGAGAHADQAHADAHAAQAIAAAHgDQAIgDAEgGQAGgFACgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgHgDQgHgDgHAAQgHAAgIADg");
	this.shape_8.setTransform(-10.9,40.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgWBYIAAhkIgQAAIAAgYIAQAAIAAgKQAAgKADgIQADgIAFgFQAFgFAGgCQAGgDAJAAQANAAALADIAAAZQgJgDgIAAQgIAAgFAEQgEAFAAAKIAAAHIAiAAIAAAYIghAAIAABkg");
	this.shape_9.setTransform(-22.8,38.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_10.setTransform(-39.9,39.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAJgJANgFIAMgEIANgCQAJAAASAGQAMAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgJAJgMAFQgRAGgJAAgAgPgkQgHADgFAGQgFAFgCAIQgDAHAAAHIAAAAQAAAIADAHQACAIAGAFQAFAGAHADQAHADAHAAQAIAAAHgDQAHgDAGgGQAEgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgFgGgIgDQgGgDgIAAQgIAAgHADg");
	this.shape_11.setTransform(-52.5,40.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAwBTIhbh1IAAB1IgdAAIAAilIAcAAIBYByIAAhyIAdAAIAAClg");
	this.shape_12.setTransform(-69.9,38.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgOAQIAAgfIAeAAIAAAfg");
	this.shape_13.setTransform(140.7,19.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgbBUQgLgEgIgJQgIgIgFgMIgEgOIgBgOIAAgBQAAgKAFgQQAFgMAIgJQAIgIALgEQAKgFAMAAQAFAAAHACQAGACAGADQAJAGAIAKIAAhEIAdAAIAACtIgdAAIAAgVQgIALgJAFQgGAEgGACQgHABgFAAQgLAAgLgEgAgMgOQgHADgFAFQgFAGgDAFQgDAIAAAJIAAABQAAAJADAHQADAIAFAFQAFAFAHADQAGADAGAAQAHAAAHgDQAGgDAFgFQAGgGACgHQAEgIAAgIIAAgBQAAgJgEgIQgCgFgGgFQgFgGgGgCQgHgDgHAAQgGAAgGACg");
	this.shape_14.setTransform(129,12.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_15.setTransform(114.1,14.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAIQADAJAAALIAABPg");
	this.shape_16.setTransform(99.5,14.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AAcBAIgchVIgbBVIgaAAIgph+IAeAAIAZBUIAchVIAXAAIAcBVIAahUIAdAAIgpB+g");
	this.shape_17.setTransform(81.7,14.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgSBVQgIgCgIgEIgPgIQgHgEgGgGIgLgNQgEgHgDgIIgEgQQgCgIAAgJIAAAAQAAgHACgJQABgIADgIIAIgPIAKgNIANgLIAPgIQAJgDAIgBQAJgCAIAAQAJAAAKACQAIABAIADQAIAEAHAEQAHAFAGAGIALANIAHAOQADAIABAJQACAIAAAIIAAAAQAAAJgCAIIgEAQIgIAPQgEAHgHAFQgFAGgHAFIgPAIQgIAEgJACQgJACgJAAQgJAAgJgCgAgVg2QgLAFgHAIQgIAJgEAKQgEALgBALIAAAAQABALAEAMQAEALAIAIQAHAIALAEQALAFAKAAQAMAAALgFQAKgEAHgIQAIgIAEgLQAEgLABgMIAAAAQgBgLgEgKQgEgMgIgHQgIgJgJgFQgMgEgLAAQgLAAgKAEg");
	this.shape_18.setTransform(61.2,12.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgiAOIAAgbIBFAAIAAAbg");
	this.shape_19.setTransform(46.1,13.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_20.setTransform(36.8,14.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_21.setTransform(24.1,14.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgGBXIgMgFQgKgGgHgKIAAAUIgdAAIAAitIAdAAIAABFQAHgLAKgGIAMgFQAGgCAGAAQALAAALAFQAKAEAJAIQAIAJAFAMQAFAQAAAKIAAABIgBAOIgEAOQgFAMgIAIQgJAJgKAEQgKAEgMAAQgGAAgGgBgAgNgNQgGACgGAGQgFAFgDAGQgDAHAAAJIAAABQAAAIADAIQADAHAFAGQAGAFAGADQAHADAGAAQAHAAAGgDQAGgCAFgGQAGgFACgIQAEgHAAgJIAAgBQAAgJgEgIQgCgFgGgFQgFgGgGgCQgGgDgHAAQgGAAgHADg");
	this.shape_22.setTransform(9.2,12.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("ABDBAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFACgDAEQgEAEgCAGQgCAGAAAIIAABFIgbAAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFADgDAEQgEAEgCAGQgCAGAAAHIAABFIgdAAIAAh8IAdAAIAAATQAHgKAIgFQAFgEAGgBQAGgCAHAAQAGAAAGACIALAEQAEADACAEQAEAEADAFQAIgLAKgFIALgEQAGgCAHAAQALAAAIADQAIADAGAHQAGAGADAJQADAJAAALIAABPg");
	this.shape_23.setTransform(-10.6,14.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_24.setTransform(-29.2,14.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AA1BUIAAh3Ig1BOIAAAAIg0hOIAAB3IgdAAIAAimIAfAAIAyBPIAzhPIAfAAIAACmg");
	this.shape_25.setTransform(-46.9,12.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgTAVQALgCAGgGQADgGgBgHIgKAAIAAggIAeAAIAAAbQAAAIgDAIQgCAHgFAEQgFAFgFADQgGACgJABg");
	this.shape_26.setTransform(-68.1,21.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AgNBXIAAitIAbAAIAACtg");
	this.shape_27.setTransform(-74.3,12.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AgcA/QgIgDgGgFQgHgFgDgHQgEgIAAgJIAAgBQAAgJAEgJQAEgHAHgDQAHgFAJgDQAKgCALAAQANAAATAFIAAgDQAAgHgCgFQgCgFgEgDQgEgEgFgCQgGgBgGgBQgKAAgJACQgIACgJAEIgIgXQAMgFAKgCQAMgDAMAAQAOAAALAEQAKADAHAHQAHAHADAKQAEAJAAANIAABKIgdAAIAAgQQgHAIgJAFQgNAFgKAAQgJAAgIgCgAgKAEQgGACgEADQgEACgCAEQgCAFAAAEIAAABQAAAJAIAFQAGAFALAAQAFAAAHgCQAGgCAEgDQAFgEACgFQADgFAAgGIAAgJQgRgFgMAAQgFAAgFABg");
	this.shape_28.setTransform(-85.1,14.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgGBAIgMgEQgMgFgIgJQgKgJgFgMQgEgMAAgNIAAAAQAAgMAEgMQAFgMAKgJQAIgJANgFIAMgEQAFgCAHAAQAIAAAIACIANAEQAIAEANAMIgSAUQgHgIgHgEQgIgEgKAAQgHAAgGADQgGADgGAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAIQAEAHAFAFQAFAGAGADQAGADAIAAQAKAAAIgEQAHgEAIgHIARARQgNANgIAEQgGADgIACQgIACgIAAg");
	this.shape_29.setTransform(-98.5,14.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAKgJALgFIANgEIANgCQAJAAARAGQAMAFAKAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgIAJgNAFQgSAGgIAAgAgPgkQgGADgGAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAHQAEAIAFAFQAFAGAHADQAHADAHAAQAIAAAIgDQAGgDAFgGQAFgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgGgDQgIgDgHAAQgIAAgHADg");
	this.shape_30.setTransform(-113.4,14.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("Ag5BUIAAimIAdAAIAACLIBWAAIAAAbg");
	this.shape_31.setTransform(-127.8,12.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158,0,324,54);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A6K1yMA0VAAAMAAAArlMg0VAAAg");
	this.shape.setTransform(-0.5,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-169,-141,337,281);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.parent = this;
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201706_Neighbor_336x280_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(316,145,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.parent = this;
	this.instance.setTransform(168,265.4,1.03,1.03,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border336x280();
	this.instance_1.parent = this;
	this.instance_1.setTransform(168.6,140.5,1,1,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_80 = new cjs.Graphics().p("A6PM9IAA56MA0eAAAIAAZ6g");
	var mask_graphics_81 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_82 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_83 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_84 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_85 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_86 = new cjs.Graphics().p("A6PM9IAA55MA0eAAAIAAZ5g");
	var mask_graphics_87 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_88 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_89 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_169 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_170 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_171 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_172 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_173 = new cjs.Graphics().p("A6PM+IAA57MA0eAAAIAAZ7g");
	var mask_graphics_174 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_175 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_176 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_177 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");
	var mask_graphics_178 = new cjs.Graphics().p("A6PM+IAA56MA0eAAAIAAZ6g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(80).to({graphics:mask_graphics_80,x:168,y:83}).wait(1).to({graphics:mask_graphics_81,x:168,y:77.4}).wait(1).to({graphics:mask_graphics_82,x:168,y:71.9}).wait(1).to({graphics:mask_graphics_83,x:168,y:66.3}).wait(1).to({graphics:mask_graphics_84,x:168,y:60.8}).wait(1).to({graphics:mask_graphics_85,x:168,y:55.2}).wait(1).to({graphics:mask_graphics_86,x:168,y:49.7}).wait(1).to({graphics:mask_graphics_87,x:168,y:44.1}).wait(1).to({graphics:mask_graphics_88,x:168,y:38.6}).wait(1).to({graphics:mask_graphics_89,x:168,y:33}).wait(80).to({graphics:mask_graphics_169,x:168,y:33}).wait(1).to({graphics:mask_graphics_170,x:168,y:20.1}).wait(1).to({graphics:mask_graphics_171,x:168,y:7.2}).wait(1).to({graphics:mask_graphics_172,x:168,y:-5.7}).wait(1).to({graphics:mask_graphics_173,x:168,y:-18.6}).wait(1).to({graphics:mask_graphics_174,x:168,y:-31.4}).wait(1).to({graphics:mask_graphics_175,x:168,y:-44.3}).wait(1).to({graphics:mask_graphics_176,x:168,y:-57.2}).wait(1).to({graphics:mask_graphics_177,x:168,y:-70.1}).wait(1).to({graphics:mask_graphics_178,x:168,y:-83}).wait(1).to({graphics:null,x:0,y:0}).wait(4));

	// PIC
	this.instance_2 = new lib.pic();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,57,1,1,0,0,0,150,57);

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(80).to({regX:150.2,regY:56.9,x:150.2,y:47.9},9).wait(80).to({y:-62.1},9).to({_off:true},1).wait(4));

	// PIC shad
	this.instance_3 = new lib.HTML5rastershad_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(168,176,1,1,0,0,0,0,10);
	this.instance_3.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({y:126},9).wait(80).to({y:10},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(288.5,204,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:152},9).wait(80).to({y:39},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(287.5,231,1,1,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90).to({_off:false},0).wait(79).to({y:118},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(169).to({scaleY:1,y:-2},9).to({_off:true},4).wait(1));

	// tag
	this.instance_7 = new lib._2016TAG();
	this.instance_7.parent = this;
	this.instance_7.setTransform(168,244.1,1.5,1.5,0,0,0,0,2.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(484.3,253,1.47,1.47,0,0,0,215.2,63.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.parent = this;
	this.instance_9.setTransform(291.9,228.5,1.52,1.52,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_10 = new lib.box1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(150,92.2,1,2,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},182).wait(1));

	// com
	this.instance_11 = new lib.comhoriz();
	this.instance_11.parent = this;
	this.instance_11.setTransform(67,267.2,0.687,0.687,0,0,0,0,4.5);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(166.5,266.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(167,140,337.1,280);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;