(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1497906917274", id:"HTML5rastershad"},
		{src:"images/Teensy160x600.jpg?1497906917274", id:"Teensy160x600"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Teensy160x600 = function() {
	this.initialize(img.Teensy160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,177);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPARIAAghIAfAAIAAAhg");
	this.shape.setTransform(44.3,73.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgVA/QgMgFgKgIQgJgJgFgNIgEgNIgCgPIAAAAQAAgNAGgMQAEgMAJgKQAIgKANgFIAMgEIALgCQAIAAAHACQAHACAGACQAIAEAMAMQAHAJAEANQAEAOAAAMIAAAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgFQAJgDAIgIIASAQIgLAKQgFAFgHADQgHADgHABQgJADgIAAQgMgBgNgFgAAhgIQAAgHgDgHQgDgGgEgFQgEgEgFgDQgHgCgHgBQgFABgGACQgFACgFAFQgFAFgCAGQgDAGgBAIIBBAAIAAAAg");
	this.shape_1.setTransform(33.6,68.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOBbIAAi1IAdAAIAAC1g");
	this.shape_2.setTransform(22.5,65.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgdBBQgJgDgGgFQgHgFgDgHQgEgIAAgKIAAAAQAAgLAEgIQAEgIAHgEQAHgEAKgEQAKgCAMAAQANAAAUAFIAAgDQAAgHgCgFQgBgGgFgDQgEgEgGgCQgGgBgGAAQgLgBgJADQgIACgJAEIgJgYQAMgGAKgCQAOgDAMAAQAPAAALAEQALAEAHAHQAHAHADALQAEAJAAAOIAABMIgeAAIAAgRQgHAKgKAEQgOAGgJAAQgKAAgIgDgAgLAEIgJAFQgFADgBAEQgCAEAAAFIAAAAQAAAKAGAFQAIAFALABQAGAAAGgDQAGgBAFgEQAFgEACgFQADgFAAgGIAAgJQgRgGgNAAQgFAAgGABg");
	this.shape_3.setTransform(11.3,68.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYA/QgTgIgIgHIANgUQALAIALAEQAMAEAIAAQAJAAAFgEQAGgDAAgIIAAAAQAAgHgJgEQgEgDgOgFQgVgGgIgEQgGgEgDgGQgDgHgBgJIAAAAQABgJADgIQAEgHAGgGQAGgFAJgDQAIgDAIAAQAMAAANAFQANADALAHIgMAVQgKgFgKgEQgKgDgHAAQgHABgFADQgFAEAAAFIAAABQAAAGAJAFIATAIIAOAEIANAGQAHAFADAGQAEAGAAAJIAAAAQAAAKgEAJQgDAIgIAEQgGAGgJACQgJADgLAAQgMAAgOgFg");
	this.shape_4.setTransform(-2.1,68.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAdBDIAAhJQAAgIgCgFQgCgGgEgFQgEgEgFgCQgFgDgHABQgEgBgGADQgFACgEAFQgEAEgCAGQgDAGAAAIIAABIIgeAAIAAiCIAeAAIAAAUQAIgKAJgGIALgFQAEgCAIAAQALAAAJAEQAIADAGAHQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_5.setTransform(-23.4,68.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOBDIgMgEQgNgFgKgKQgJgJgGgNIgEgMIgBgOIAAAAQAAgIAFgRQAFgMAKgKQAKgKANgFIANgEIANgCQAKAAASAGQAMAFAKAKQAJAKAGALQAFASAAAIIAAAAIgCAOIgDAMQgGAMgJAKQgKAKgMAFQgTAGgJAAgAgPglQgIACgFAHQgFAFgCAIQgEAIAAAHIAAAAQAAAIAEAIQADAIAFAFQAFAHAIACQAHAEAHAAQAJAAAIgEQAGgCAGgHQAFgFADgHQADgJgBgIIAAAAQABgHgDgIQgDgHgFgGQgGgGgIgDQgHgEgIAAQgHAAgIAEg");
	this.shape_6.setTransform(-39.4,68.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgHAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEAEAIAAQAJAAAJgFIAAAZQgGAEgGABQgHACgIAAQgJgBgEgCg");
	this.shape_7.setTransform(67.9,39.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_8.setTransform(59.4,39);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgHBaIgMgFQgJgGgJgKIAAAUIgeAAIAAi0IAeAAIAABIQAJgLAKgGQAFgEAHgCQAGgCAGAAQAMAAALAFQALAFAJAIQAJAJAFANQAFAQAAALIAAAAIgCAQIgDAOQgFAMgJAJQgJAJgLAEQgLAFgMAAQgGAAgHgCgAgNgOQgHADgGAFQgFAGgDAGQgDAIAAAJIAAAAQAAAKADAIQADAHAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgFADgIQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgFgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_9.setTransform(47.8,39);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgsBTQgHgBgHgFIAKgWQAJAFAJABQAGAAAFgEQAEgEAEgIIg3iCIAgAAIAkBgIAihgIAfAAIg0CGIgIARQgFAHgDAEQgFAEgGADQgHACgIAAQgJAAgIgDg");
	this.shape_10.setTransform(24.1,43.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgYA/QgTgIgIgHIANgUQALAHALAFQALAEAIAAQAKAAAGgEQAFgDAAgIIAAAAQAAgHgJgEQgFgDgOgFQgTgGgJgEQgGgEgDgGQgEgHABgJIAAAAQgBgJAEgJQADgGAHgGQAHgFAIgDQAIgDAJAAQAMAAANAFQAMADAKAHIgLAVQgKgFgJgEQgLgDgHAAQgHABgFADQgFAEAAAFIAAABQAAAGAJAFIATAIIAPAEIAMAGQAHAFADAGQAEAGAAAJIAAAAQAAAKgEAIQgEAJgHAEQgGAGgJACQgJADgLAAQgLAAgPgFg");
	this.shape_11.setTransform(10.6,41.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAdBDIAAhJQAAgIgCgGQgCgFgEgFQgEgEgFgCQgFgDgHABQgEgBgGADQgFACgEAFQgEAEgCAFQgDAHAAAIIAABIIgeAAIAAiCIAeAAIAAAUQAIgKAJgGIALgFQAEgCAIAAQALAAAJAEQAIADAGAHQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_12.setTransform(-3.2,41.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgWA/QgMgFgJgIQgJgJgFgNIgEgNIgBgPIAAAAQAAgNAEgMQAFgMAJgKQAIgKAMgFIAMgEIAMgCQAIAAAHACQAHACAGACQAHAEAMAMQAIAJAFANQADAOAAAMIAAAIIhfAAQABAIAEAHQADAFAFAFQAFAFAHACQAFACAGAAQALAAAJgFQAIgDAHgIIASAQIgKAKQgGAFgGADQgHADgIABQgHADgKAAQgMgBgNgFgAAigHQgBgIgDgHQgCgGgEgFQgFgEgGgDQgFgCgIgBQgFABgGACQgFACgFAFQgEAFgDAGQgEAGgBAJIBDAAIAAAAg");
	this.shape_13.setTransform(-18.5,41.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgVA/QgMgFgKgIQgJgJgFgNIgEgNIgCgPIAAAAQAAgNAGgMQAEgMAJgKQAIgKAMgFIANgEIALgCQAIAAAHACQAHACAGACQAIAEALAMQAIAJAFANQADAOAAAMIAAAIIhfAAQABAIAEAHQADAFAFAFQAFAFAGACQAHACAFAAQAKAAAKgFQAHgDAJgIIASAQIgLAKQgGAFgGADQgHADgIABQgIADgIAAQgMgBgNgFgAAigHQgBgIgDgHQgCgGgEgFQgFgEgFgDQgHgCgHgBQgFABgGACQgGACgEAFQgEAFgDAGQgDAGgCAJIBDAAIAAAAg");
	this.shape_14.setTransform(-33.6,41.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgHAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEAEAIAAQAJAAAJgFIAAAZQgGAEgGABQgHACgIAAQgJgBgEgCg");
	this.shape_15.setTransform(-46.1,39.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgdBBQgJgDgGgFQgHgFgDgHQgEgIAAgKIAAAAQAAgLAEgIQADgIAIgDQAHgFAKgEQAKgCAMAAQANAAAUAFIAAgDQAAgHgCgFQgBgGgFgDQgEgEgGgCQgGgBgGAAQgKgBgKADQgIACgKAEIgIgYQAMgGAKgCQANgDANAAQAPAAALAEQALAEAHAHQAHAHADALQAEAJAAAOIAABMIgeAAIAAgRQgHAKgKAEQgOAGgKAAQgJAAgIgDgAgLAEIgKAFQgEADgBAEQgCAEAAAFIAAAAQAAAKAGAFQAIAFALABQAFAAAHgDQAGgBAFgEQAFgEACgFQADgFAAgGIAAgJQgSgGgMAAQgFAAgGABg");
	this.shape_16.setTransform(-66.2,41.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AghBTQgPgEgMgHIALgXQAMAHAKADQAMAEANAAQAIAAAIgDQAHgCAGgGQAGgFACgHQADgIAAgKIAAgKQgMANgHAEQgGAEgHABQgGACgGAAQgMAAgLgEQgLgEgJgIQgIgIgFgMQgFgJAAgPIAAAAQAAgKAGgQQAEgLAJgJQAIgIALgEQALgEAMAAQAGAAAHACQAGABAGAEQAJAFAJAKIAAgTIAfAAIAABnQAAAQgEANQgEAMgJAIIgKAIQgGAEgGACQgUAEgKAAQgQAAgQgEgAgOg6QgGADgFAFQgGAEgCAHQgDAHAAAIIAAAAQAAAIADAHQACAHAGACQAFAFAGADQAIACAGAAQAHAAAHgCQAHgDAGgFQAFgDADgGQADgHAAgIIAAAAQAAgIgDgHQgDgGgFgFQgGgFgHgDQgHgDgHAAQgGAAgIADg");
	this.shape_17.setTransform(58.3,16.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAdBDIAAhJQAAgIgCgGQgCgFgEgFQgEgEgFgCQgFgDgHABQgEgBgGADQgFACgEAFQgEAEgCAFQgDAHAAAIIAABIIgeAAIAAiCIAeAAIAAAUQAIgKAJgGIALgFQAEgCAIAAQALAAAJAEQAIADAGAHQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_18.setTransform(42.6,14.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_19.setTransform(31.2,12);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAdBbIAAhLQAAgIgCgGQgCgEgEgEQgEgEgFgCQgFgDgHAAQgEAAgGADQgFACgEAEQgEAFgCADQgDAHAAAHIAABLIgeAAIAAi1IAeAAIAABHQAIgLAJgFIALgFQAEgCAIAAQALAAAJAEQAIADAGAHQAGAGAEAKQADAJAAAKIAABUg");
	this.shape_20.setTransform(19.9,11.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgHAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEAEAIAAQAJAAAJgFIAAAZQgGAEgGABQgHACgIAAQgJgBgEgCg");
	this.shape_21.setTransform(6.8,12.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgsBTQgHgBgHgFIAKgWQAJAFAJABQAGAAAFgEQAEgEAEgIIg3iCIAgAAIAkBgIAihgIAfAAIg0CGIgIARQgFAHgDAEQgFAEgGADQgHACgIAAQgJAAgIgDg");
	this.shape_22.setTransform(-5.6,16.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AglBDIAAiCIAeAAIAAAdQAEgHADgGQAEgGAFgEQAGgFAHgCQAIgCAIAAIAAAgIgCAAQgKAAgIAEQgJADgFAGQgEAHgDAKQgEAIAAAMIAAAzg");
	this.shape_23.setTransform(-17.6,14.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgWA/QgMgFgIgIQgKgJgFgNIgEgNIgBgPIAAAAQAAgNAEgMQAFgMAJgKQAJgKAMgFIALgEIANgCQAHAAAHACQAHACAGACQAIAEALAMQAJAJADANQAFAOAAAMIgBAIIhfAAQABAIADAHQAEAFAFAFQAFAFAHACQAFACAGAAQAKAAAJgFQAJgDAHgIIASAQIgKAKQgFAFgHADQgHADgIABQgIADgJAAQgMgBgNgFgAAhgIQAAgHgDgHQgDgGgEgFQgEgEgGgDQgFgCgIgBQgFABgGACQgGACgEAFQgEAFgEAGQgDAGAAAIIBBAAIAAAAg");
	this.shape_24.setTransform(-30.9,14.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgMBCIg2iDIAgAAIAiBfIAjhfIAgAAIg2CDg");
	this.shape_25.setTransform(-45.1,14.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgVA/QgNgFgIgIQgKgJgFgNIgEgNIgCgPIAAAAQABgNAFgMQAEgMAJgKQAJgKAMgFIALgEIANgCQAHAAAHACQAHACAGACQAIAEAMAMQAHAJAEANQAEAOABAMIgBAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgFQAIgDAJgIIASAQIgLAKQgGAFgGADQgHADgHABQgIADgJAAQgMgBgNgFgAAhgIQAAgHgDgHQgDgGgEgFQgEgEgGgDQgFgCgIgBQgFABgGACQgFACgFAFQgFAFgDAGQgCAGgBAIIBBAAIAAAAg");
	this.shape_26.setTransform(-59.4,14.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYA/QgTgIgIgHIANgUQALAHALAFQALAEAIAAQAKAAAFgEQAGgDAAgIIAAAAQAAgHgJgEQgEgDgPgFQgTgGgJgEQgGgEgDgGQgDgHAAgJIAAAAQAAgJADgJQADgGAHgGQAGgFAJgDQAIgDAIAAQANAAANAFQAMADAKAHIgLAVQgKgFgKgEQgJgDgIAAQgHABgFADQgFAEAAAFIAAABQAAAGAJAFIATAIIAPAEIAMAGQAHAFADAGQAEAGAAAJIAAAAQAAAKgEAIQgDAJgIAEQgGAGgJACQgJADgLAAQgMAAgOgFg");
	this.shape_27.setTransform(46.4,-12.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgVA/QgMgFgKgIQgJgJgFgNIgEgNIgCgPIAAAAQAAgNAGgMQAEgMAJgKQAIgKANgFIAMgEIALgCQAIAAAHACQAHACAGACQAIAEAMAMQAHAJAFANQADAOAAAMIAAAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgFQAJgDAIgIIASAQIgLAKQgGAFgGADQgHADgHABQgJADgIAAQgMgBgNgFgAAhgIQAAgHgDgHQgDgGgEgFQgEgEgFgDQgHgCgHgBQgFABgGACQgFACgFAFQgFAFgDAGQgCAGgBAIIBBAAIAAAAg");
	this.shape_28.setTransform(32.7,-12.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAaBbIglg6IgTAUIAAAmIgeAAIAAi1IAeAAIAABrIA1g4IAkAAIg0A0IA2BOg");
	this.shape_29.setTransform(19.3,-15.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgdBBQgJgDgGgFQgHgFgDgHQgEgIAAgKIAAAAQAAgLAEgIQAEgIAHgEQAHgEAKgEQAKgCAMAAQANAAAUAFIAAgDQAAgHgCgFQgBgGgFgDQgEgEgGgCQgGgBgGAAQgLgBgJADQgIACgJAEIgJgYQAMgGAKgCQAOgDAMAAQAPAAALAEQALAEAGAHQAIAHADALQAEAJAAAOIAABMIgeAAIAAgRQgHAKgKAEQgOAGgJAAQgKAAgIgDgAgLAEIgJAFQgFADgBAEQgCAEAAAFIAAAAQAAAKAGAFQAIAFALABQAGAAAGgDQAGgBAFgEQAFgEACgFQADgFAAgGIAAgJQgRgGgNAAQgFAAgGABg");
	this.shape_30.setTransform(3.6,-12.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABGBDIAAhJQAAgIgCgGQgCgGgDgEQgEgEgFgCQgFgDgGABQgGgBgFADQgGACgDAEQgEAFgCAFQgCAGAAAJIAABIIgdAAIAAhJQAAgIgBgGQgCgGgEgEQgDgEgFgCQgFgDgGABQgGgBgGADQgFACgEAFQgDAEgCAGQgDAGAAAIIAABIIgeAAIAAiCIAeAAIAAAUQAIgKAIgGIALgFQAHgCAHAAQAHAAAGACQAGABAFAEIAHAHQAEAEACAFQAJgKAKgGIAMgFQAGgCAIAAQAKAAAJADQAJAEAGAGQAGAHADAJQADAKAAAMIAABSg");
	this.shape_31.setTransform(-15.2,-12.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgHAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEAEAIAAQAJAAAJgFIAAAZQgGAEgGABQgHACgIAAQgJgBgEgCg");
	this.shape_32.setTransform(-39.9,-14.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgOBXIAAitIAdAAIAACtg");
	this.shape_33.setTransform(-48.8,-14.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-82.5,-28,165,110);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("EgMfAsOMAAAhYbIY/AAMAAABYbg");
	this.shape.setTransform(80,262,1,0.926);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E7E").s().p("AgLAMIAAgYIAXAAIAAAYg");
	this.shape.setTransform(44.2,109.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E7E").s().p("AgQAvQgJgDgHgHQgHgHgEgJIgCgKIgBgLIAAAAQAAgJADgKQAEgJAGgHQAHgHAIgEIAKgDIAIgBIALABIAKADQAFADAJAJQAGAHADAKQADAJAAAJIAAAGIhHAAQABAGADAFQACAFAEADQAEADAEACQAFABAEAAQAIAAAGgDQAGgCAGgGIAOALIgIAIQgEAEgFACIgLAEQgGABgHAAQgIAAgKgEgAAZgGQgBgFgCgFQgCgFgDgDQgDgEgEgCQgFgCgFAAQgDAAgFACQgEACgEAEIgFAIQgCAFgBAFIAxAAIAAAAg");
	this.shape_1.setTransform(36.2,105.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E7E").s().p("AgRAvQgOgGgHgFIALgQQAHAGAJAEQAIADAFAAQAIAAAEgDQAEgDAAgFQAAgGgHgDIgNgFQgPgFgGgDQgEgDgDgEQgDgGAAgGIAAgBQAAgHADgFQACgGAFgEQAFgEAHgCQAGgCAFAAQAKAAAJADQAJADAIAFIgJARQgGgFgIgCQgHgDgGAAQgFAAgEADQgDADAAAEIAAAAQAAAFAGAEIAOAFIALAEIAKAEQAEADADAFQADAFAAAGIAAABQAAAHgDAGQgDAGgFAEQgFAEgHACQgGACgIAAQgIAAgLgEg");
	this.shape_2.setTransform(25.8,105.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E7E").s().p("AgVAwQgHgBgFgFQgEgEgDgFQgDgGAAgHIAAAAQAAgIADgHQADgFAFgDQAGgDAHgCQAIgCAJAAQAJAAAPAEIAAgCQAAgGgBgEQgCgEgDgCIgIgFQgEgBgEAAIgPABIgNAFIgGgRQAIgEAIgDQAKgCAJAAQALABAIACQAIADAGAFQAFAGADAIQACAHAAAKIAAA4IgWAAIAAgMQgFAHgIAEQgJADgIAAQgHAAgGgCgAgHADIgIADQgDADgBADQgCADAAAEIAAAAQAAAHAGAEQAFAEAIAAQAEAAAFgCQAFgBADgDQAEgDACgEQACgDAAgFIAAgHQgOgEgJAAQgDAAgEABg");
	this.shape_3.setTransform(15.5,105.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E7E").s().p("AAVBEIAAg4QAAgGgBgFQgCgCgCgDQgDgDgEgCQgEgCgFAAQgDAAgEACQgEACgDADQgDADgCADQgBAEAAAGIAAA4IgXAAIAAiHIAXAAIAAA1QAFgIAHgEIAIgEQADgBAGAAQAIAAAGADQAHACAEAFQAFAFACAHQADAHAAAHIAAA/g");
	this.shape_4.setTransform(4.5,104);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E7E").s().p("AgEAyIgKgDQgJgEgHgHQgHgHgEgJQgDgKAAgKIAAAAQAAgJADgJQAEgKAHgHQAHgHAJgEIAKgDIAJgBQAHAAAGABQAFABAFADQAHADAKAJIgPAPQgFgGgGgDQgGgDgIAAQgFAAgFACQgFADgEAEIgGAKQgCAGAAAFQAAAGACAGQADAGADAEQAEAEAGADQAEACAGAAQAHAAAHgDQAGgDAFgGIAOANQgKALgGADIgLAEQgGABgHAAg");
	this.shape_5.setTransform(-6.5,105.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E7E").s().p("AgbAyIAAhhIAWAAIAAAWQACgFADgEQACgFAEgEQAFgDAFgBQAGgCAGAAIAAAYIgBAAQgIAAgGACQgGADgEAFQgDAFgCAHQgDAGAAAJIAAAmg");
	this.shape_6.setTransform(-15,105.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E7E").s().p("AgXAwQgGgEgFgEQgEgGgDgHQgCgGAAgJIAAg9IAXAAIAAA3IABAJQABAFADADQADADAEABQAEACAEABQAEgBAEgCQAEgBADgDQADgDABgFQACgEAAgGIAAg2IAXAAIAABhIgXAAIAAgPQgFAHgHAFQgEADgFABQgCABgGAAQgIAAgHgCg");
	this.shape_7.setTransform(-25.2,106);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E7E").s().p("AgxBBIAAh/IAWAAIAAAQQAGgIAIgFIAJgDQAEgCAEAAQAJAAAJAEQAIADAGAHQAHAGAEAKQADANAAAIIgBAMIgCAJQgEAJgGAGQgHAHgIADQgJAEgJAAQgEAAgEgBQgFgBgFgDQgHgFgGgHIAAAtgAgKgqQgFADgEAEQgEAEgDAGQgCAGAAAGQAAAIACAFQADAEAEAFQAEAEAFACQAFADAFAAQAFAAAFgDQAGgCADgEQAEgEACgFQACgFABgIQAAgGgDgGQgCgHgEgDQgEgFgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_8.setTransform(-36.9,107.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E7E").s().p("AggA/IgLgFIAHgRQAHAEAHAAQAFAAADgCQADgDADgGIgphhIAYAAIAaBHIAahHIAXAAIgnBkIgGAMQgEAGgBADQgEADgFACQgFABgGAAQgHAAgFgBg");
	this.shape_9.setTransform(35,86.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E7E").s().p("AgbAyIAAhhIAWAAIAAAWQACgGADgEQACgFAEgDQAFgDAFgBQAGgCAGAAIAAAYIgBAAQgIAAgGACQgGADgEAFQgDAFgCAHQgDAGAAAKIAAAlg");
	this.shape_10.setTransform(26,84.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E7E").s().p("AgQAvQgJgDgHgHQgHgHgEgJIgCgKIgBgLIAAAAQAAgJADgKQAEgJAGgHQAHgHAIgEIAKgDIAIgBIALABIAKADQAFADAJAJQAGAHADAKQADAJAAAJIAAAGIhHAAQABAGADAFQACAFAEADQAEADAEACQAFABAEAAQAIAAAGgDQAGgCAGgGIAOALIgIAIQgEAEgFACIgLAEQgGABgHAAQgIAAgKgEgAAZgGQgBgFgCgFQgCgFgDgDQgDgEgEgCQgFgCgFAAQgDAAgFACQgEACgEAEIgFAIQgCAFgBAFIAxAAIAAAAg");
	this.shape_11.setTransform(16,84.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E7E").s().p("AgJAxIgohhIAYAAIAZBHIAahHIAYAAIgoBhg");
	this.shape_12.setTransform(5.4,84.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E7E").s().p("AgQAvQgJgDgHgHQgHgHgEgJIgCgKIgBgLIAAAAQAAgJADgKQAEgJAGgHQAHgHAIgEIAKgDIAIgBIALABIAKADQAFADAJAJQAGAHADAKQADAJAAAJIAAAGIhHAAQABAGADAFQACAFAEADQAEADAEACQAFABAEAAQAIAAAGgDQAGgCAGgGIAOALIgIAIQgEAEgFACIgLAEQgGABgHAAQgIAAgKgEgAAZgGQgBgFgCgFQgCgFgDgDQgDgEgEgCQgFgCgFAAQgDAAgFACQgEACgEAEIgFAIQgCAFgBAFIAxAAIAAAAg");
	this.shape_13.setTransform(-5.3,84.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E7E").s().p("AAVAyIAAg2QAAgGgBgFQgCgEgCgDQgDgDgEgBQgEgCgFAAQgDAAgEACQgEABgDADQgDAEgCAEQgBAFAAAFIAAA2IgXAAIAAhhIAXAAIAAAPQAFgIAHgEIAIgDQADgCAGAAQAIAAAGADQAHADAEAFQAFAEACAIQADAHAAAIIAAA9g");
	this.shape_14.setTransform(-22.3,84.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E7E").s().p("AgKAyIgKgDQgJgEgIgHQgGgHgEgJIgDgKIgBgKIAAAAQAAgGAEgMQAEgKAHgHQAHgHAJgEIAKgDIAKgBQAHAAAOAEQAJAEAIAHQAGAHAFAJQADANAAAGIgBAKIgCAJQgFAKgHAHQgHAHgJAEQgOAEgHAAgAgLgcQgGACgDAFQgEAEgDAGQgCAGAAAFQAAAGACAGQADAFAEAFQAEAEAFADQAGACAFAAQAHAAAFgCQAFgDAFgEQADgEACgGQADgGAAgGIAAAAQAAgFgDgGQgCgGgEgEQgEgEgFgDQgGgCgGAAQgFAAgGACg");
	this.shape_15.setTransform(-34.3,84.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E7E").s().p("AAaBAQgFgDgFgFQgDgEgDgGQgCgGAAgGIAAgBQAAgHACgGQADgGAEgFQAEgEAFgDQAHgCAHAAQAGAAAGACQAGADADAEQAEAFADAGQACAGAAAHIAAAAQAAAHgCAGQgDAGgEAEQgEAFgGADQgFACgHAAQgHAAgGgCgAAcATQgDAGAAAIIAAAAQAAAIAEAFQAEAGAHAAQAFAAAFgGQADgFAAgHIAAgBQAAgIgDgGQgFgFgGAAQgGAAgFAFgAg3BBIAzhDIAqg+IATAAIg0BDIgqA+gAgzgBQgGgDgEgEQgEgFgCgGQgCgGAAgHIAAAAQAAgHACgGQACgGAEgEQAFgFAFgDQAHgCAGAAQAHAAAFACQAGADAEAFQAFAEABAGQADAGAAAGIAAABQAAAGgDAHQgBAGgFAFQgEAEgGADQgGABgGAAQgHAAgGgBgAgwgtQgFAFAAAHIAAABQAAAIAFAGQAEAFAGAAQAHAAADgFQAEgGAAgIIAAAAQAAgIgEgFQgEgGgGAAQgHAAgDAGg");
	this.shape_16.setTransform(36.2,62.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E7E").s().p("AgNBBQgHgCgGgDIgLgGIgKgIIAOgRQAJAIAHAEQAJAEAIAAQAFAAAFgCQAEgBAEgDQADgDACgEQACgFAAgFIAAAAQAAgFgCgEQgCgEgEgDQgDgDgFgBQgFgCgEAAIgNACIgLAEIgOgHIAEhAIBMAAIAAAUIg5AAIgCAfIAKgDIAJgBQAKAAAIADQAIACAHAFQAGAGADAFQAEAIAAAKIAAABQAAAKgEAIQgDAIgHAGQgGAGgJADQgJADgKAAQgGAAgHgBg");
	this.shape_17.setTransform(22.4,62.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E7E").s().p("AgLANIAAgYIAXAAIAAAYg");
	this.shape_18.setTransform(14.1,67.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E7E").s().p("AADBCIAAhrIgXAGIgEgTIAhgLIAQAAIAACDg");
	this.shape_19.setTransform(7.3,62.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E7E").s().p("AAVAyIAAg2QAAgGgBgEQgCgFgCgDQgDgDgEgBQgEgDgFAAQgDAAgEADQgEABgDADQgDAEgCAEQgBAFAAAFIAAA2IgXAAIAAhhIAXAAIAAAPQAFgIAHgDIAIgFQADgBAGAAQAIAAAGADQAHADAEAEQAFAGACAHQADAGAAAJIAAA9g");
	this.shape_20.setTransform(-7.1,63.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E7E").s().p("AgbAyIAAhhIAWAAIAAAXQACgHADgDQACgGAEgCQAFgEAFgCQAGgBAGAAIAAAYIgBAAQgIAAgGADQgGACgEAFQgDAFgCAHQgDAFAAAKIAAAmg");
	this.shape_21.setTransform(-16.4,63.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E7E").s().p("AgVAxQgHgDgFgEQgEgDgDgGQgDgFAAgIIAAAAQAAgIADgHQADgFAFgCQAGgEAHgCQAIgCAJAAQAJAAAPAEIAAgDQAAgFgBgEQgCgEgDgDIgIgEQgEgBgEAAIgPABIgNAFIgGgRQAIgFAIgBQAKgCAJAAQALAAAIACQAIADAGAGQAFAFADAHQACAIAAAKIAAA5IgWAAIAAgNQgFAGgIAFQgJADgIAAQgHABgGgCgAgHAEIgIACQgDACgBAEQgCADAAADIAAABQAAAHAGAEQAFAEAIAAQAEAAAFgCQAFgBADgDQAEgCACgEQACgFAAgEIAAgHQgOgEgJAAQgDAAgEACg");
	this.shape_22.setTransform(-26.4,63.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E7E").s().p("AgvBBIAAiBIBfAAIAAAUIhJAAIAAAjIBAAAIAAASIhAAAIAAAjIBKAAIAAAVg");
	this.shape_23.setTransform(-37.6,62.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E7E").s().p("AgLANIAAgYIAXAAIAAAYg");
	this.shape_24.setTransform(24,39.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E7E").s().p("AgVBBQgIgDgGgHQgHgGgEgKIgDgKIgBgMQAAgIAEgMQAEgJAGgHQAHgGAIgEQAIgDAJAAQAEAAAFABIAKAEQAHAEAGAIIAAg1IAXAAIAACHIgXAAIAAgRQgGAJgHAEQgFADgFABQgFACgEAAQgIAAgJgEgAgJgKQgFACgEAEQgEAEgCAEQgDAGAAAHQAAAIADAGQACAFAEAFQAEAEAFACQAFACAEAAQAFAAAGgCQAFgCAEgFQAEgEACgGQACgGAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgGgDgFAAQgEAAgFADg");
	this.shape_25.setTransform(15,33.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E7E").s().p("AgbAyIAAhhIAWAAIAAAXQACgGADgFQACgEAEgDQAFgEAFgBQAGgCAGAAIAAAYIgBAAQgIAAgGADQgGACgEAFQgDAFgCAHQgDAFAAALIAAAlg");
	this.shape_26.setTransform(5.9,35.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E7E").s().p("AgVAxQgHgDgFgDQgEgEgDgGQgDgGAAgHIAAgBQAAgHADgGQADgGAFgCQAGgEAHgCQAIgCAJAAQAJAAAPAEIAAgDQAAgFgBgEQgCgEgDgDIgIgDQgEgCgEAAIgPACIgNAEIgGgSQAIgDAIgCQAKgCAJgBQALAAAIADQAIADAGAGQAFAFADAHQACAIAAAKIAAA5IgWAAIAAgNQgFAGgIAEQgJAFgIAAQgHAAgGgCgAgHAEIgIADQgDACgBADQgCADAAADIAAABQAAAHAGAEQAFAEAIAAQAEAAAFgBQAFgCADgDQAEgCACgEQACgFAAgEIAAgHQgOgEgJAAQgDAAgEACg");
	this.shape_27.setTransform(-4.2,35.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003E7E").s().p("AgFBCIgOgEIgLgGIgKgJIgIgKQgDgEgDgHQgCgGgBgHQgCgGABgHIAAAAQgBgGACgGQABgHACgGIAGgLIAIgLIAKgHQAGgEAGgDIANgEIAMgCQAJABAHABQAIACAGADQAJADAMALIgPARQgIgIgIgEQgEgCgFgBIgLgBQgHAAgJADQgHAEgGAGQgGAHgDAIQgDAJAAAIIAAAAQAAAJADAJQADAIAGAGQAGAHAHADQAIAEAIAAQAGAAAFgBIAKgEQAHgEAKgIIAOAPIgLAKQgFAEgGADQgHADgHABQgIACgJAAQgGAAgFgBg");
	this.shape_28.setTransform(-16.1,34);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003E7E").s().p("AATBEIgbgrIgOAOIAAAdIgWAAIAAiHIAWAAIAABQIAngqIAcAAIgoAmIApA7g");
	this.shape_29.setTransform(43.8,12.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003E7E").s().p("AgEAyIgKgDQgJgEgHgHQgHgHgEgJQgDgKAAgKIAAAAQAAgJADgJQAEgKAHgHQAHgHAJgEIAKgDIAJgBQAHAAAGABQAFABAFADQAHADAKAJIgPAPQgFgGgGgDQgGgDgIAAQgFAAgFACQgFADgEAEIgGAKQgCAGAAAFQAAAGACAGQADAGADAEQAEAEAGADQAEACAGAAQAHAAAHgDQAGgDAFgGIAOANQgKALgGADIgLAEQgGABgHAAg");
	this.shape_30.setTransform(32.6,14.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003E7E").s().p("AgVAxQgHgCgFgFQgEgDgDgGQgDgFAAgIIAAgBQAAgHADgGQADgGAFgCQAGgEAHgCQAIgCAJAAQAJAAAPAEIAAgDQAAgFgBgEQgCgEgDgDIgIgDQgEgCgEAAIgPACIgNAEIgGgSQAIgEAIgBQAKgCAJAAQALAAAIACQAIADAGAGQAFAFADAHQACAIAAAKIAAA5IgWAAIAAgNQgFAGgIAEQgJAFgIAAQgHAAgGgCgAgHAEIgIADQgDACgBADQgCADAAADIAAABQAAAHAGAEQAFAEAIAAQAEAAAFgBQAFgCADgDQAEgCACgEQACgEAAgFIAAgHQgOgEgJAAQgDAAgEACg");
	this.shape_31.setTransform(21.4,14.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003E7E").s().p("Ag1BBIAAiBIA4AAQAMAAAJADQAIADAGAGQAFAEACAGQABAEAAAHQABAHgCAEQgBAEgDAEQgEAHgJAEIAKACIAJAHQADAEACAFQACAFAAAGIAAABQAAAIgDAIQgEAGgHAFQgGAFgIACQgKACgKAAgAgfAtIAlAAIALgBQAEgBAEgDQADgCABgDQACgEAAgEIAAgBQAAgEgCgDQgBgDgDgDQgEgCgFgBQgFgCgHABIgjAAgAgfgJIAfAAIAJgBQAFgBADgDQADgCACgDQACgDAAgEIAAgBQAAgEgCgDQgBgDgDgCQgDgCgFgBIgKgBIgfAAg");
	this.shape_32.setTransform(9.8,13);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003E7E").s().p("AAVBEIAAg4QAAgGgBgFQgCgCgCgDQgDgDgEgCQgEgCgFAAQgDAAgEACQgEACgDADQgDADgCADQgBAEAAAGIAAA4IgXAAIAAiHIAXAAIAAA1QAFgIAHgEIAIgEQADgBAGAAQAIAAAGADQAHACAEAFQAFAFACAHQADAHAAAHIAAA/g");
	this.shape_33.setTransform(-8.7,12.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003E7E").s().p("AgSAvQgOgGgGgFIAKgQQAIAGAIAEQAJADAGAAQAHAAAEgDQAEgDAAgFQAAgGgGgDIgOgFQgPgFgGgDQgEgDgDgEQgDgGAAgGIAAgBQAAgHADgFQADgGAFgEQAEgEAGgCQAHgCAGAAQAIAAAKADQAKADAIAFIgJARQgIgFgHgCQgHgDgGAAQgFAAgEADQgDADAAAEIAAAAQAAAFAHAEIANAFIALAEIAKAEQAFADACAFQADAFAAAGIAAABQAAAHgDAGQgCAGgGAEQgEAEgIACQgGACgIAAQgJAAgLgEg");
	this.shape_34.setTransform(-19.4,14.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003E7E").s().p("AgVAxQgHgCgFgFQgEgDgDgGQgDgFAAgIIAAgBQAAgHADgGQADgGAFgCQAGgEAHgCQAIgCAJAAQAJAAAPAEIAAgDQAAgFgBgEQgCgEgDgDIgIgDQgEgCgEAAIgPACIgNAEIgGgSQAIgEAIgBQAKgCAJAAQALAAAIACQAIADAGAGQAFAFADAHQACAIAAAKIAAA5IgWAAIAAgNQgFAGgIAEQgJAFgIAAQgHAAgGgCgAgHAEIgIADQgDACgBADQgCADAAADIAAABQAAAHAGAEQAFAEAIAAQAEAAAFgBQAFgCADgDQAEgCACgEQACgEAAgFIAAgHQgOgEgJAAQgDAAgEACg");
	this.shape_35.setTransform(-29.6,14.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003E7E").s().p("AgGBCIgMgEIgMgGIgKgJIgIgKQgDgEgCgHQgDgGgBgHQgBgGgBgHIAAAAQABgGABgGQABgHADgGIAFgLIAIgKIAKgIQAGgEAGgDIANgEIAMgCQAJAAAHACQAIACAGADQAIADANALIgOARQgJgIgIgEQgFgCgEgBIgLgBQgHAAgIADQgIAEgGAGQgGAHgDAIQgEAJABAIIAAAAQgBAJAEAJQADAIAGAHQAGAGAIADQAHAEAIAAQAGAAAFgBIAKgDQAHgFAKgIIAOAPIgLAKQgFAEgGADQgHADgHABQgIACgJAAQgGAAgGgBg");
	this.shape_36.setTransform(-41.6,13);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003E7E").s().p("AgVBBQgIgDgGgHQgHgGgEgKIgDgKIgBgMQAAgIAEgMQAEgJAGgHQAHgGAIgEQAIgDAJAAQAEAAAFABIAKAEQAHAEAGAIIAAg1IAXAAIAACHIgXAAIAAgRQgGAJgHAEQgFADgFABQgFACgEAAQgIAAgJgEgAgJgKQgFACgEAEQgEAEgCAEQgDAGAAAHQAAAIADAGQACAFAEAFQAEAEAFACQAFACAEAAQAFAAAGgCQAFgCAEgFQAEgEACgGQACgGAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgGgDgFAAQgEAAgFADg");
	this.shape_37.setTransform(43.7,-8.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003E7E").s().p("AAVAyIAAg2QAAgGgBgFQgCgEgCgDQgDgDgEgCQgEgBgFAAQgDAAgEABQgEACgDADQgDADgCAFQgBAEAAAGIAAA2IgXAAIAAhhIAXAAIAAAQQAFgIAHgFIAIgDQADgCAGAAQAIAAAGADQAHADAEAFQAFAFACAGQADAIAAAIIAAA9g");
	this.shape_38.setTransform(31.9,-6.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003E7E").s().p("AgWAwQgHgDgEgFQgFgFgCgHQgDgIAAgIIAAg9IAXAAIAAA2IABAKQABAFAEADQACADAEACQAEACAEAAQAEAAAEgCQAEgCADgDQADgEACgEQABgFAAgFIAAg2IAXAAIAABhIgXAAIAAgQQgFAJgHAEQgEACgEACQgDABgGAAQgIAAgGgCg");
	this.shape_39.setTransform(20.2,-6.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003E7E").s().p("AgKAyIgJgDQgKgEgIgHQgHgHgDgJIgDgKIgBgKIAAAAQAAgGAEgMQAEgKAHgHQAHgHAKgEIAJgDIAKgBQAHAAAOAEQAJAEAHAHQAHAHAFAJQADANAAAGIgBAKIgCAJQgFAKgHAHQgHAHgJAEQgOAEgHAAgAgLgcQgFACgEAFQgFAEgCAGQgBAGAAAFQAAAGABAGQADAFAEAFQAEAEAGADQAFACAFAAQAHAAAFgCQAGgDAEgEQADgEACgGQACgGABgGIAAAAQgBgFgCgGQgCgGgEgEQgEgEgFgDQgGgCgGAAQgFAAgGACg");
	this.shape_40.setTransform(8.3,-6.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003E7E").s().p("AgJBCQgIgBgHgEIgNgGIgMgJIAOgQQAGAFANAHIALAEIAJABQAFgBAFgBIAHgDIAFgFQABgEAAgDIAAAAIgBgHIgEgFIgJgEIgNgEQgMgDgHgDQgIgDgGgDQgFgEgDgGQgDgHAAgJIAAAAQAAgIADgHQAEgHAGgGQAGgEAIgDQAIgDAJAAIAMABQAHABAGADQAIACANAKIgMARQgJgHgJgDQgJgEgHAAIgJABIgGAEQgGAFAAAGIAAAAIABAHQACADADACQAEADAGACIANAEQALACAIAEQAIADAFADQAFAEADAGQACAGAAAJQAAAIgDAIQgDAIgHAFQgGAEgJADQgIADgLAAQgFAAgHgBg");
	this.shape_41.setTransform(-3.9,-8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#003E7E").s().p("AgQAvQgJgDgHgHQgHgHgEgJIgCgKIgBgLIAAAAQAAgJADgKQAEgJAGgHQAHgHAIgEIAKgDIAIgBIALABIAKADQAFADAJAJQAGAHADAKQADAJAAAJIAAAGIhHAAQABAGADAFQACAFAEADQAEADAEACQAFABAEAAQAIAAAGgDQAGgCAGgGIAOALIgIAIQgEAEgFACIgLAEQgGABgHAAQgIAAgKgEgAAZgGQgBgFgCgFQgCgFgDgDQgDgEgEgCQgFgCgFAAQgDAAgFACQgEACgEAEIgFAIQgCAFgBAFIAxAAIAAAAg");
	this.shape_42.setTransform(-21,-6.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#003E7E").s().p("AAVBEIAAg4QAAgGgBgFQgCgCgCgDQgDgDgEgCQgEgCgFAAQgDAAgEACQgEACgDADQgDADgCADQgBAEAAAGIAAA4IgXAAIAAiHIAXAAIAAA1QAFgIAHgEIAIgEQADgBAGAAQAIAAAGADQAHACAEAFQAFAFACAHQADAHAAAHIAAA/g");
	this.shape_43.setTransform(-32.4,-8.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#003E7E").s().p("AgKBBIAAhrIgqAAIAAgWIBpAAIAAAWIgqAAIAABrg");
	this.shape_44.setTransform(-44.1,-8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89.2,-18.8,178.5,135.8);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.5,-300.5,161,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6EB340").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Teensy160x600();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(168,187,1,1,0,0,0,0,10);
	this.instance_1.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,197);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201706_Teensy_160x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(7,7,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.476,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(80.1,585.7,0.8,0.8,0,0,0,0.1,0.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(80,572.8,1.2,1.2,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border160x600();
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},164).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,57,1,1,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},164).wait(1));

	// CTA
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(889.5,503,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1,scaleY:1,x:199.5,y:254},4).to({_off:true},160).wait(1));

	// HEAD
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(815.5,577,5,5,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(71).to({_off:false},0).to({scaleX:1,scaleY:1,x:198.5,y:379},4).to({_off:true},89).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({_off:true},164).wait(1));

	// tag
	this.instance_7 = new lib._2016TAGvert();
	this.instance_7.parent = this;
	this.instance_7.setTransform(80.1,536.9,1.35,1.35,0,0,0,0,2.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(272.9,540.1,0.897,0.897,0,0,0,215.2,63.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.parent = this;
	this.instance_9.setTransform(155.6,525.1,0.927,0.927,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_10 = new lib.HTML5rastershad_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_10.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},164).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},164).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(17.1,232.1,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.5,300,825,778);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;