(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 336,
	height: 280,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Freeer336x280.jpg?1504144252568", id:"Freeer336x280"},
		{src:"images/HTML5rastershad.png?1504144252568", id:"HTML5rastershad"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.Freeer336x280 = function() {
	this.initialize(img.Freeer336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,409,165);


(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Freeer336x280();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,409,165);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAPIAAgdIAdAAIAAAdg");
	this.shape.setTransform(72.2,63.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA6QgLgFgIgHQgJgJgFgMIgDgMIgBgNIAAAAQAAgMAEgLQAEgMAIgJQAIgIALgFIALgDIALgCQAHAAAHACQAGABAFACQAIADALAMQAHAIADANQAEALAAAMIAAAHIhYAAQACAIADAFQADAGAEAEQAFAEAGACQAGACAEAAQAKAAAIgDQAIgEAHgIIARAPIgKAJIgLAIQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_1.setTransform(62.2,59.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQADgGADgGIAIgJQAGgFAGgCQAHgBAIAAIAAAdIgCAAQgJAAgHADQgIADgGAGQgDAGgDAJQgDAHAAAMIAAAvg");
	this.shape_2.setTransform(51.1,59.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA8QgIgDgGgEQgGgFgDgHQgEgHAAgJIAAgBQAAgKAEgHQAEgHAGgDQAHgFAJgDQAJgCALAAQAMAAATAFIAAgDQAAgFgCgFQgCgFgDgEQgEgDgGgCQgFgCgGAAQgJAAgJACIgQAGIgIgWQALgFAKgCQALgDAMgBQAOAAAKAEQAKAEAGAGQAHAHADAKQAEAJAAAMIAABGIgcAAIAAgPQgHAIgJAFQgMAEgJAAQgJAAgIgCgAgKAFQgFACgEADQgDACgCADQgCAEAAAEIAAAAQAAAJAHAFQAGAEALAAQAEABAGgCQAGgCAEgEQAFgDACgFQADgFAAgFIAAgHQgRgEgLgBIgKABg");
	this.shape_3.setTransform(38.7,59.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUA6QgLgFgIgHQgJgJgFgMIgDgMIgBgNIAAAAQAAgMAEgLQAEgMAIgJQAIgIALgFIALgDIALgCQAHAAAHACQAGABAFACQAIADALAMQAHAIADANQAEALAAAMIAAAHIhYAAQACAIADAFQADAGAEAEQAFAEAGACQAGACAEAAQAKAAAIgDQAIgEAHgIIARAPIgKAJIgLAIQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_4.setTransform(18.5,59.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAaA9IgahRIgaBRIgZAAIgnh4IAcAAIAZBRIAahSIAXAAIAbBSIAYhRIAcAAIgoB4g");
	this.shape_5.setTransform(1.7,59.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSAUQALgCAEgGQADgFAAgHIgKAAIAAgfIAdAAIAAAaQAAAIgDAHQgCAHgEAEQgFAFgFADQgGACgJABg");
	this.shape_6.setTransform(-18.6,65.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABMQgHgBgEgEQgFgFgCgHQgDgHAAgKIAAg+IgPAAIAAgXIAPAAIAAgiIAaAAIAAAiIAgAAIAAAXIggAAIAAA6QAAAIAEADQADAEAIAAQAJAAAIgEIAAAXQgFADgGABQgHACgHAAQgIAAgEgCg");
	this.shape_7.setTransform(-26.1,57.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBTIAAh4IAaAAIAAB4gAgOg3IAAgbIAcAAIAAAbg");
	this.shape_8.setTransform(-33.9,57.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA8QgIgDgGgEQgGgFgDgHQgEgHAAgJIAAgBQAAgKAEgHQAEgHAGgDQAHgFAJgDQAJgCALAAQAMAAATAFIAAgDQAAgFgCgFQgCgFgDgEQgEgDgGgCQgFgCgGAAQgJAAgJACIgQAGIgIgWQALgFAKgCQALgDAMgBQAOAAAKAEQAKAEAGAGQAHAHADAKQAEAJAAAMIAABGIgcAAIAAgPQgHAIgJAFQgMAEgJAAQgJAAgIgCgAgKAFQgFACgEADQgDACgCADQgCAEAAAEIAAAAQAAAJAHAFQAGAEALAAQAEABAGgCQAGgCAEgEQAFgDACgFQADgFAAgFIAAgHQgRgEgLgBIgKABg");
	this.shape_9.setTransform(-44.3,59.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAnBRIgnhyIgmByIgZAAIg3igIAeAAIAmB1IAoh2IAVAAIApB2IAmh1IAdAAIg4Cgg");
	this.shape_10.setTransform(-61.5,57.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOAPIAAgdIAdAAIAAAdg");
	this.shape_11.setTransform(114,40.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcA6QgIgDgFgGQgGgGgDgJQgDgIAAgLIAAhMIAcAAIAABEQAAAGACAGQACAFADAEQADAFAFACQAFABAFAAQAFAAAFgCQAFgCAEgEQAEgEABgFQADgGAAgHIAAhDIAbAAIAAB4IgbAAIAAgTQgHAKgJAFIgKAFQgEABgHABQgKgBgIgDg");
	this.shape_12.setTransform(103.7,36.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgMA+IgNgEQgLgFgJgIQgJgKgFgKIgDgNIgBgMIAAAAQAAgHAEgQQAFgLAJgJQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAJQAIAIAFALQAFARAAAHIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgiQgHADgFAFQgEAFgDAHQgDAHAAAHIAAAAQAAAHADAIQADAGAFAGQAFAGAHADQAGACAHAAQAIAAAHgCQAGgDAFgGQAFgFADgHQACgHAAgIIAAAAQAAgHgDgHQgCgGgFgGQgFgFgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_13.setTransform(89.1,36.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgoBNQgGgCgHgEIAJgUQAJAFAIAAQAGAAADgEQAEgDAEgIIgzh3IAeAAIAgBYIAghYIAdAAIgwB7IgIAPQgEAIgDADQgEAEgGACQgGACgHAAQgJAAgHgCg");
	this.shape_14.setTransform(74.6,38.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgeBMQgOgDgLgHIAKgVQAKAGALADQALADALAAQAHAAAIgCQAHgCAFgFQAEgFADgHQADgHAAgJIAAgJQgLAMgHAEQgFADgHABQgFACgGAAQgLAAgJgEQgLgEgHgHQgIgHgFgLQgEgJAAgNIAAAAQAAgJAEgPQAFgLAIgHQAIgHAKgEQAJgEALAAQAGAAAGABQAGACAGADQAIAFAJAJIAAgSIAcAAIAABfQAAAPgFAMQgEALgHAIQgEAEgFADQgFADgHACQgSAEgJAAQgPAAgOgEgAgMg1QgHACgEAEQgFAFgDAGQgCAGAAAIIAAAAQAAAHACAHQADAGAFACQAEAFAHACQAGADAGAAQAGAAAHgDQAGgCAGgFQAFgCACgGQADgHAAgHIAAAAQAAgHgDgHQgCgGgFgEQgGgFgGgCQgHgDgGAAQgGAAgGADg");
	this.shape_15.setTransform(52.9,38.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAaA9IAAhDQAAgGgBgGQgCgGgEgEQgDgDgEgCQgGgCgGAAQgEAAgFACQgFACgEAEQgDAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAGgKAJgFQAEgDAGgBQAEgDAGAAQALAAAIAEQAIADAFAHQAGAFADAJQADAJAAAKIAABLg");
	this.shape_16.setTransform(38.5,36.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgMBTIAAh4IAaAAIAAB4gAgOg3IAAgbIAdAAIAAAbg");
	this.shape_17.setTransform(28,34.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgoBNQgGgCgHgEIAJgUQAJAFAIAAQAGAAADgEQAEgDAEgIIgzh3IAeAAIAgBYIAghYIAdAAIgwB7IgIAPQgEAIgDADQgEAEgGACQgGACgHAAQgJAAgHgCg");
	this.shape_18.setTransform(17.8,38.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbA8QgIgCgGgFQgGgFgDgHQgEgHAAgJIAAAAQAAgKAEgIQAEgHAGgEQAHgFAJgCQAJgCALAAQAMAAATAFIAAgCQAAgGgCgGQgCgFgDgDQgEgDgGgBQgFgCgGAAQgJAAgJACIgQAFIgIgWQALgFAKgDQALgCAMAAQAOAAAKADQAKADAGAHQAHAHADAJQAEAKAAAMIAABGIgcAAIAAgPQgHAIgJAEQgMAGgJAAQgJgBgIgCgAgKAGQgFABgEACQgDADgCAEQgCADAAAEIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAEgDQAFgEACgEQADgFAAgGIAAgHQgRgFgLAAIgKACg");
	this.shape_19.setTransform(3.9,36.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag9BQIAAidIAcAAIAAAVQAHgLAJgFQAFgEAGgBQAGgCAGAAQALAAAKAEQAKAEAIAJQAIAIAEALQAFARAAAKIAAABIgBANIgEAMQgEALgIAIQgIAIgKAEQgKAFgLAAQgGgBgGgBIgLgFQgJgFgHgKIAAA4gAgMg0QgHADgEAFQgGAFgCAHQgDAIAAAIIAAABQAAAIADAHQACAFAGAGQAEAFAHADQAGACAGAAQAGAAAHgCQAGgDAFgFQAFgGACgFQADgHAAgIIAAgBQAAgIgDgIQgCgHgFgFQgFgFgGgDQgHgDgGAAQgGAAgGADg");
	this.shape_20.setTransform(-9.9,38.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgIQgJgJgFgLIgDgNIgBgNIAAAAQAAgLAEgMQAEgLAIgJQAIgJALgFIALgEIALgBQAHAAAHABQAGABAFADQAIAEALALQAHAJADALQAEAMAAALIAAAIIhYAAQACAIADAFQADAGAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgHIARAOIgKAJIgLAHQgGADgIACQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgEgFgCQgGgDgGAAQgFAAgFACQgFACgFAEQgEAFgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_21.setTransform(-31.7,36.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBTIgLgFQgJgFgHgKIAAATIgcAAIAAimIAcAAIAABDQAHgKAJgGQAFgDAGgCQAGgCAGAAQALAAAKAEQAKAFAIAIQAIAIAEALQAFAPAAAKIAAABIgBAOIgEANQgEALgIAIQgIAIgKAFQgKAEgLAAQgGAAgGgCgAgMgNQgHADgEAFQgGAFgCAFQgDAIAAAIIAAABQAAAIADAIQACAHAGAFQAEAFAHADQAGADAGAAQAGAAAHgDQAGgDAFgFQAFgFACgHQADgIAAgIIAAgBQAAgIgDgIQgCgFgFgFQgFgFgGgDQgHgDgGAAQgGAAgGADg");
	this.shape_22.setTransform(-46,34.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgZBRQgLgFgHgIQgJgIgFgLIgDgNIgBgOIAAgBQAAgKAEgPQAFgLAIgIQAIgIAKgFQAKgEALAAQAFAAAHACQAGACAFADQAJAFAIAKIAAhCIAcAAIAACmIgcAAIAAgUQgIALgJAFIgLAFQgHACgFAAQgKAAgKgEgAgMgNQgGADgFAFQgFAFgDAFQgCAIAAAIIAAABQAAAIACAIQAEAHAEAFQAFAFAGADQAHADAFAAQAGAAAHgDQAGgDAGgFQAFgFACgHQADgIAAgIIAAgBQAAgIgDgIQgCgFgFgFQgGgFgGgDQgGgDgHAAQgGAAgGADg");
	this.shape_23.setTransform(-68.9,34.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgSAUQALgBAFgGQADgFgBgIIgKAAIAAgfIAdAAIAAAbQAAAHgDAIQgCAGgEAFQgFAFgFACQgGACgJABg");
	this.shape_24.setTransform(-79.7,29.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgIQgJgJgFgLIgDgNIgBgNIAAAAQAAgLAEgMQAEgLAIgJQAIgJALgFIALgEIALgBQAHAAAHABQAGABAFADQAIAEALALQAHAJADALQAEAMAAALIAAAIIhYAAQACAIADAFQADAGAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgHIARAOIgKAJIgLAHQgGADgIACQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgEgFgCQgGgDgGAAQgFAAgFACQgFACgFAEQgEAFgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_25.setTransform(-89.4,36.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAaA9IgahRIgaBRIgZAAIgnh5IAcAAIAZBSIAahSIAXAAIAbBSIAZhSIAbAAIgoB5g");
	this.shape_26.setTransform(-106.2,36.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBRQgKgFgIgIQgIgIgEgLIgEgNIgCgOIAAgBQAAgKAGgPQAEgLAIgIQAIgIAKgFQAKgEALAAQAGAAAGACQAGACAFADQAJAFAHAKIAAhCIAcAAIAACmIgcAAIAAgUQgHALgJAFIgLAFQgGACgGAAQgLAAgKgEgAgLgNQgHADgFAFQgFAFgCAFQgDAIAAAIIAAABQAAAIADAIQACAHAGAFQAEAFAHADQAGADAFAAQAHAAAGgDQAHgDAEgFQAFgFADgHQADgIAAgIIAAgBQAAgIgDgIQgDgFgFgFQgEgFgHgDQgGgDgHAAQgFAAgGADg");
	this.shape_27.setTransform(81.2,11.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAaA+IAAhDQAAgIgCgFQgCgFgCgFQgEgDgFgCQgEgCgHAAQgEAAgFACQgFACgDAEQgEAEgCAGQgCAFAAAHIAABDIgcAAIAAh4IAcAAIAAATQAHgKAHgFQAGgDAFgCQAEgBAHAAQAKgBAIAEQAIADAFAGQAGAHADAIQADAJAAAKIAABMg");
	this.shape_28.setTransform(66.8,13.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgbA8QgIgDgGgEQgGgFgDgHQgEgHAAgJIAAgBQAAgKAEgHQAEgHAGgDQAHgFAJgDQAJgCALAAQAMAAATAFIAAgDQAAgFgCgFQgCgFgDgEQgEgDgGgCQgFgCgGAAQgJAAgJACIgQAGIgIgWQALgFAKgCQALgEAMAAQAOAAAKAEQAKADAGAHQAHAHADAKQAEAJAAAMIAABGIgcAAIAAgPQgHAIgJAFQgMAEgJAAQgJAAgIgCgAgKAFQgFACgEACQgDADgCADQgCAEAAAEIAAABQAAAIAHAFQAGAEALAAQAEAAAGgBQAGgCAEgEQAFgDACgFQADgFAAgFIAAgHQgRgEgLAAIgKAAg");
	this.shape_29.setTransform(52.5,13.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQACgGAEgGIAIgJQAGgFAGgCQAHgBAIAAIAAAdIgCAAQgJAAgHADQgIADgGAGQgDAGgDAJQgDAHAAAMIAAAvg");
	this.shape_30.setTransform(35,13.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgMAIgJQAIgIALgFIALgEIALgBQAHAAAHABQAGACAFADQAIADALAKQAHAKADAMQAEALAAAMIAAAHIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFACgFAFQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_31.setTransform(22.8,13.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AggANIAAgZIBBAAIAAAZg");
	this.shape_32.setTransform(11.2,12.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgMAIgJQAIgIALgFIALgEIALgBQAHAAAHABQAGACAFADQAIADALAKQAHAKADAMQAEALAAAMIAAAHIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFACgFAFQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_33.setTransform(-0.4,13.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgMIgDgMIgBgNIAAAAQAAgLAEgMQAEgMAIgJQAIgIALgFIALgEIALgBQAHAAAHABQAGACAFADQAIADALAKQAHAKADAMQAEALAAAMIAAAHIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFACgFAFQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_34.setTransform(-14.2,13.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQACgGAEgGIAIgJQAGgFAGgCQAHgBAIAAIAAAdIgCAAQgJAAgIADQgHADgFAGQgEAGgDAJQgDAHAAAMIAAAvg");
	this.shape_35.setTransform(-25.3,13.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgVBUIAAhgIgPAAIAAgWIAPAAIAAgJQAAgKADgIQADgIAEgFQAFgFAGgCQAFgCAKAAQALAAALADIAAAXQgJgCgIAAQgHAAgFAEQgDAFAAAJIAAAHIAfAAIAAAWIgfAAIAABgg");
	this.shape_36.setTransform(-34.6,11);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgoBNQgGgCgHgDIAJgVQAJAEAIAAQAGAAADgCQAEgEAEgHIgzh4IAeAAIAgBYIAghYIAdAAIgwB7IgIAQQgEAHgDAEQgEADgGACQgGACgHAAQgJAAgHgCg");
	this.shape_37.setTransform(-53,15.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAaA+IAAhDQAAgIgCgFQgCgFgCgFQgEgDgFgCQgEgCgHAAQgEAAgFACQgFACgDAEQgEAEgCAGQgCAFAAAHIAABDIgcAAIAAh4IAcAAIAAATQAHgKAHgFQAGgDAFgCQAEgBAHAAQAKgBAIAEQAIADAFAGQAGAHADAIQADAJAAAKIAABMg");
	this.shape_38.setTransform(-66.9,13.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AA2BRIgRgoIhKAAIgQAoIgdAAIBGigIAZAAIBGCggAAbAQIgbg+IgaA+IA1AAg");
	this.shape_39.setTransform(-83.2,11.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,-1,337,73);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgUA1QgPgHgIgGIAMgRQAIAHAKADQAJAEAHAAQAIAAAFgEQAFgDgBgFIAAgBQAAgFgHgEIgQgGQgQgFgHgEQgFgDgDgFQgDgGAAgIIAAAAQAAgIADgGQADgHAGgEQAEgEAIgDQAHgCAGAAQALAAAKAEQALADAJAGIgKASQgIgFgIgDQgJgDgGAAQgFABgEADQgFACAAAGIAAAAQAAAFAIAEIAPAGIAMAFQAHADAFABQAFAEACAFQAEAGAAAHIAAAAQAAAJgEAHQgDAGgFAEQgGAEgHADQgIACgJAAQgKAAgMgEg");
	this.shape.setTransform(130.9,25.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgZA1QgIgDgFgGQgFgFgCgIQgDgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHIAAg8IAZAAIAABtIgZAAIAAgRQgGAJgHAEQgFADgFABQgDACgHAAQgJAAgHgDg");
	this.shape_1.setTransform(119.2,25.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AAYA4IAAg9QAAgGgCgGQgBgFgDgDQgDgDgFgCQgEgCgGAAQgDAAgFACQgFACgDAEQgDADgCAFQgCAFAAAHIAAA8IgZAAIAAhtIAZAAIAAARQAGgIAIgFIAJgFQAEgBAGAAQAJAAAHADQAIACAFAGQAFAGADAIQACAIAAAKIAABEg");
	this.shape_2.setTransform(106.3,25.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgLA4IgLgDQgLgFgIgIQgIgIgEgKIgDgLIgBgLIAAAAQgBgGAFgPQAEgKAJgIQAHgIALgFIAMgDIAKgBQAIAAAPAEQALAEAIAIQAIAIAEALQAEAOABAHIgBALIgEALQgEAKgIAIQgIAIgLAFQgQAEgHAAgAgMgfQgHACgEAFQgFAFgCAGQgCAHAAAGQAAAHADAGQACAHAFAFQAEAFAGACQAHADAFAAQAHAAAHgDQAFgCAFgFQAFgFACgGQACgHAAgHIAAAAQAAgGgCgGQgDgHgEgFQgFgFgGgCQgGgDgHAAQgHAAgFADg");
	this.shape_3.setTransform(92.9,25.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("Ag8BJIAAiRIBAAAQANAAAJAEQAKADAHAGQAEAFADAGQACAGAAAIIAAAAQAAAGgBAGQgCAFgDAEQgFAGgKAFIAMAEQAGADADAEQAEAEACAGQADAGAAAHQAAAKgEAIQgEAHgHAGQgHAFgKACQgKADgNAAgAgiAyIAoAAIAMgBQAGgCADgCQAEgDACgDQACgEAAgFIAAAAQAAgFgCgEQgCgEgEgCQgEgCgFgCIgOgBIgmAAgAgigKIAiAAIAKgBQAFgCAEgCQAEgCACgEQACgEAAgFIAAgBQAAgDgCgEQgCgEgDgCQgDgCgFgCIgLgBIgjAAg");
	this.shape_4.setTransform(78.9,23.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AAABFQgGgBgEgEQgEgEgDgGQgCgGAAgJIAAg5IgOAAIAAgWIAOAAIAAgeIAXAAIAAAeIAeAAIAAAWIgeAAIAAA1QAAAHAEADQADADAHAAQAIAAAIgDIAAAUQgFADgGACQgFABgHAAQgHAAgEgCg");
	this.shape_5.setTransform(60.1,23.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AAYA4IAAg9QAAgGgCgGQgBgFgDgDQgDgDgFgCQgEgCgGAAQgDAAgFACQgFACgDAEQgDADgCAFQgCAFAAAHIAAA8IgZAAIAAhtIAZAAIAAARQAGgIAIgFIAJgFQAEgBAGAAQAJAAAHADQAIACAFAGQAFAGADAIQACAIAAAKIAABEg");
	this.shape_6.setTransform(49.5,25.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AgZA1QgIgDgFgGQgFgFgCgIQgDgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHIAAg8IAZAAIAABtIgZAAIAAgRQgGAJgHAEQgFADgFABQgDACgHAAQgJAAgHgDg");
	this.shape_7.setTransform(36.4,25.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgLA4IgMgDQgKgFgIgIQgIgIgEgKIgEgLIgBgLIAAAAQABgGAEgPQAEgKAIgIQAJgIAKgFIALgDIALgBQAIAAAPAEQALAEAIAIQAIAIAEALQAFAOgBAHIgBALIgDALQgEAKgIAIQgIAIgLAFQgPAEgIAAgAgNgfQgFACgFAFQgEAFgDAGQgCAHAAAGQAAAHACAGQADAHAEAFQAFAFAGACQAGADAGAAQAHAAAGgDQAHgCAEgFQAEgFADgGQACgHAAgHIAAAAQAAgGgDgGQgCgHgFgFQgEgFgGgCQgGgDgHAAQgGAAgHADg");
	this.shape_8.setTransform(23.1,25.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgEA4IgLgDQgLgFgIgIQgHgIgFgKQgEgKAAgMIAAAAQAAgKAEgLQAFgKAHgIQAIgIALgFIALgDIAKgBIAOABIAMAEQAHADALALIgQARQgGgHgGgDQgIgEgJAAQgFAAgFADQgGACgEAFQgFAFgCAGQgCAHAAAGQAAAHACAGQACAHAFAFQAEAFAGACQAFADAHAAQAIAAAIgEQAGgDAGgHIAQAPQgMAMgHADQgFADgHACQgHABgIAAg");
	this.shape_9.setTransform(10.4,25.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgEA4IgLgDQgLgFgIgIQgHgIgFgKQgEgKAAgMIAAAAQAAgKAEgLQAFgKAHgIQAIgIALgFIALgDIAKgBIAOABIAMAEQAHADALALIgQARQgGgHgGgDQgIgEgJAAQgFAAgFADQgGACgEAFQgFAFgCAGQgCAHAAAGQAAAHACAGQACAHAFAFQAEAFAGACQAFADAHAAQAIAAAIgEQAGgDAGgHIAQAPQgMAMgHADQgFADgHACQgHABgIAAg");
	this.shape_10.setTransform(-1.6,25.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AAxBJIgPgjIhDAAIgQAjIgaAAIBAiRIAWAAIBBCRgAAZAPIgZg5IgYA5IAxAAg");
	this.shape_11.setTransform(-15.9,23.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AAYA4IgYhKIgXBKIgYAAIgjhuIAZAAIAXBKIAYhLIAUAAIAZBLIAWhKIAaAAIgkBug");
	this.shape_12.setTransform(-39.5,25.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgRA1QgLgEgHgIQgJgHgDgLIgEgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAHgJAKgEIALgDIAJgBIAMABIAMADQAGADAKAKQAGAIAEALQADALAAAKIAAAHIhPAAQABAHACAFQADAGAEADQAFAEAEACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgKgEgAAcgGQAAgHgDgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgFACgDADQgEAEgDAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_13.setTransform(-54.9,25.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AAqBJIhPhnIAABnIgZAAIAAiRIAXAAIBNBkIAAhkIAaAAIAACRg");
	this.shape_14.setTransform(-69.5,23.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgMBKQgHgBgGgEIgLgGIgJgJQgFgFgDgHIgFgMIgEgPIgBgPIAAAAIABgOIAEgOIAFgNIAIgLIAJgJIALgHQAHgDAGgCQAHgBAFgBQAHABAHABQAGACAGADQAFACAGAFIAJAJIAHALIAGAMQAFAUgBAJIAAAAIgBAPIgDAOIgGANIgHALIgKAKIgLAGQgFAEgHABQgGABgHAAQgGAAgGgBgAgOgvQgHAEgFAHQgFAHgDAJQgCAKAAAKIAAAAQAAAKADAKQADAJAEAIQAFAHAHAEQAIAEAGAAQAIAAAHgEQAHgEAFgHQAFgHACgJQADgKAAgLIAAAAQAAgKgDgJQgDgJgFgIQgEgHgHgEQgHgEgIAAQgHAAgHAEg");
	this.shape_15.setTransform(-91.7,23.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgMBKQgHgBgGgEIgLgGIgJgJQgFgFgDgHIgFgMIgEgPIgBgPIAAAAIABgOIAEgOIAFgNIAIgLIAJgJIALgHQAHgDAGgCQAHgBAFgBQAHABAHABQAGACAGADQAFACAGAFIAJAJIAHALIAGAMQAFAUgBAJIAAAAIgBAPIgDAOIgGANIgHALIgKAKIgLAGQgFAEgHABQgGABgHAAQgGAAgGgBgAgOgvQgHAEgFAHQgEAHgEAJQgCAKAAAKIAAAAQAAAKADAKQADAJAEAIQAGAHAGAEQAIAEAGAAQAIAAAHgEQAHgEAFgHQAFgHACgJQADgKAAgLIAAAAQAAgKgDgJQgDgJgFgIQgEgHgHgEQgHgEgIAAQgHAAgHAEg");
	this.shape_16.setTransform(-106.9,23.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AADBJIAAh3IgZAHIgFgVIAlgMIASAAIAACRg");
	this.shape_17.setTransform(-119.4,23.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgFBZIAAgVQgSgDgJgEQgMgFgLgIIANgUQAKAIAIAEQAKAFAJABIAAgpIgUgFQgIgDgFgFQgGgGgDgGQgCgHAAgJIAAAAQAAgJADgHQADgHAGgFQAGgFAIgDQAIgDAKgBIAAgMIAQAAIAAAMQALACAKAEQAJAEAJAGIgLAUIgOgJIgPgFIAAAoQAMADAJAEQAIAEAGAEQAFAFADAGQADAHAAAJIAAAAQAAAIgEAIQgDAHgGAFQgGAFgIADQgIAEgKABIAAAUgAAKAvQAKgBAFgEQAGgFAAgIQAAgHgEgEQgFgFgMgEgAgUgxQgFAEAAAHIAAABQAAAHAEAEQAFAEALAEIAAglQgJABgGAFg");
	this.shape_18.setTransform(-129.6,23.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgKAzIAAgoIgpAAIAAgVIApAAIAAgoIAVAAIAAAoIApAAIAAAVIgpAAIAAAog");
	this.shape_19.setTransform(79.3,0.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AgbBGQgNgEgKgGIAJgUQAJAHAJACQAKAEALAAQAHAAAHgDQAGgCAEgEQAFgFACgGQADgHAAgHIAAgJQgKALgHAEQgEADgGABQgFABgGAAQgJAAgJgDQgKgEgHgGQgHgIgEgJQgEgIAAgMIAAAAQAAgJAEgNQAEgJAIgIQAHgGAJgEQAJgDAJAAQAGAAAFACQAGABAFACQAIAFAHAJIAAgRIAaAAIAABXQAAAOgEAJQgDALgHAHQgEAEgFACIgKAGQgRADgIAAQgOAAgMgDgAgLgxQgGADgEAEQgFADgCAGQgCAGAAAGIAAABQAAAHACAGQACAFAFACQAEAEAGADQAGACAFAAQAGAAAGgCQAGgDAEgEQAFgCACgFQADgGAAgHIAAAAQAAgHgDgGQgCgFgFgEQgEgEgGgDQgGgCgGAAQgFAAgGACg");
	this.shape_20.setTransform(59,3.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AAYA4IAAg9QAAgHgCgEQgBgFgDgEQgDgEgFgCQgEgBgGAAQgDAAgFACQgFACgDADQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAASQAGgJAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAGQAFAFADAIQACAIAAAJIAABFg");
	this.shape_21.setTransform(45.8,2.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgLBMIAAhuIAXAAIAABugAgMgzIAAgXIAZAAIAAAXg");
	this.shape_22.setTransform(36.3,0.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AAWBMIgfgwIgQARIAAAfIgZAAIAAiXIAZAAIAABaIAsgwIAfAAIgsAsIAtBBg");
	this.shape_23.setTransform(27.8,0.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AgEA4IgLgDQgLgFgIgIQgHgIgFgKQgEgKAAgMIAAAAQAAgKAEgLQAFgKAHgIQAIgIALgFIALgDIAKgBIAOABIAMAEQAHADALALIgQARQgGgHgGgDQgIgEgJAAQgFAAgFADQgGACgEAFQgFAFgCAGQgCAHAAAGQAAAHACAGQACAHAFAFQAEAFAGACQAFADAHAAQAIAAAIgEQAGgDAGgHIAQAPQgMAMgHADQgFADgHACQgHABgIAAg");
	this.shape_24.setTransform(15.2,2.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgSA1QgKgEgIgIQgIgHgDgLIgEgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIANABIALADQAGADAKAKQAHAIADALQADALAAAKIAAAHIhQAAQACAHACAFQADAGAEADQAFAEAEACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQAAgHgDgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgFACgEADQgEAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_25.setTransform(2.8,2.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AAYBMIAAg/QAAgGgCgFQgBgDgDgEQgDgDgFgCQgEgCgGAAQgDAAgFACQgFACgDAEQgDADgCADQgCAFAAAHIAAA+IgZAAIAAiXIAZAAIAAA8QAGgJAIgFIAJgEQAEgCAGAAQAJAAAHADQAIADAFAGQAFAFADAIQACAIAAAIIAABGg");
	this.shape_26.setTransform(-10,0.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AgHBKIgOgEQgHgDgGgEIgLgKIgJgKIgGgOIgEgNQgCgIAAgIIAAAAQAAgHACgHIAEgOQACgHAEgGIAJgLQAFgGAGgEIANgHQAHgDAIgBIAOgBQAKAAAIABIAQAFQAJAEAOAMIgQATQgKgIgJgFQgFgDgFgBIgMgBQgJAAgJAFQgIADgHAIQgHAHgDAJQgEAKAAAJIAAAAQAAAKAEAKQADAJAHAHQAHAIAIADQAJAFAJAAQAGAAAGgBIALgFQAJgEAKgJIARARIgMALIgOAIQgHADgIABQgJACgKAAIgOgBg");
	this.shape_27.setTransform(-24,0.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgSA1QgKgEgIgIQgHgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAHgJAKgEIAKgDIAKgBIANABIAKADQAHADAKAKQAGAIAEALQADALAAAKIAAAHIhQAAQABAHADAFQADAGAEADQAEAEAGACQAFABAEAAQAJAAAIgDQAGgDAHgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQgBgHgCgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgEAAgFADQgFACgEADQgDAEgCAGQgDAFgBAHIA3AAIAAAAg");
	this.shape_28.setTransform(-44.6,2.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("AgRA1QgLgEgHgIQgIgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIAMABIAMADQAGADAKAKQAGAIAEALQADALAAAKIAAAHIhPAAQAAAHADAFQADAGAEADQAFAEAEACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgKgEgAAcgGQgBgHgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgEACgEADQgFAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_29.setTransform(-57.2,2.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgfA4IAAhtIAaAAIAAAZQACgGADgFQADgFAFgEQAFgDAGgCQAGgCAHAAIAAAbIgCAAQgIAAgHADQgHADgFAFQgDAGgDAIQgCAGAAALIAAAqg");
	this.shape_30.setTransform(-67.4,2.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("Ag1BJIAAiRIBrAAIAAAXIhSAAIAAApIBJAAIAAAVIhJAAIAAA8g");
	this.shape_31.setTransform(-78.6,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-172,-11,344,48);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A6K1yMA0VAAAMAAAArlMg0VAAAg");
	this.shape.setTransform(-0.5,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-169,-141,337,281);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.parent = this;
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201708_Freeer_336x280_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(316,145,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(67,267.2,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(267,265.4,1.03,1.03,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border336x280();
	this.instance_2.parent = this;
	this.instance_2.setTransform(168.6,140.5,1,1,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A6MM2IAA5mMA0eAAAIAAZmg");
	var mask_graphics_80 = new cjs.Graphics().p("A6MM2IAA5mMA0eAAAIAAZmg");
	var mask_graphics_81 = new cjs.Graphics().p("A6MMbIAA4wMA0eAAAIAAYwg");
	var mask_graphics_82 = new cjs.Graphics().p("A6MMAIAA37MA0eAAAIAAX7g");
	var mask_graphics_83 = new cjs.Graphics().p("A6MLmIAA3GMA0eAAAIAAXGg");
	var mask_graphics_84 = new cjs.Graphics().p("A6MLLIAA2QMA0eAAAIAAWQg");
	var mask_graphics_85 = new cjs.Graphics().p("A6MKwIAA1bMA0eAAAIAAVbg");
	var mask_graphics_86 = new cjs.Graphics().p("A6MKWIAA0mMA0eAAAIAAUmg");
	var mask_graphics_87 = new cjs.Graphics().p("A6MJ7IAAzwMA0eAAAIAATwg");
	var mask_graphics_88 = new cjs.Graphics().p("A6MJgIAAy7MA0eAAAIAAS7g");
	var mask_graphics_89 = new cjs.Graphics().p("A6OJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_169 = new cjs.Graphics().p("A6OJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_170 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_171 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_172 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_173 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_174 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_175 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_176 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_177 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");
	var mask_graphics_178 = new cjs.Graphics().p("A6MJDIAAyFMA0eAAAIAASFg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:168.3,y:82.2}).wait(80).to({graphics:mask_graphics_80,x:168.3,y:82.2}).wait(1).to({graphics:mask_graphics_81,x:168.3,y:79.5}).wait(1).to({graphics:mask_graphics_82,x:168.3,y:76.9}).wait(1).to({graphics:mask_graphics_83,x:168.3,y:74.2}).wait(1).to({graphics:mask_graphics_84,x:168.3,y:71.5}).wait(1).to({graphics:mask_graphics_85,x:168.3,y:68.9}).wait(1).to({graphics:mask_graphics_86,x:168.3,y:66.2}).wait(1).to({graphics:mask_graphics_87,x:168.3,y:63.5}).wait(1).to({graphics:mask_graphics_88,x:168.3,y:60.9}).wait(1).to({graphics:mask_graphics_89,x:168.5,y:58.5}).wait(80).to({graphics:mask_graphics_169,x:168.5,y:58.5}).wait(1).to({graphics:mask_graphics_170,x:168.3,y:45.6}).wait(1).to({graphics:mask_graphics_171,x:168.3,y:32.8}).wait(1).to({graphics:mask_graphics_172,x:168.3,y:20}).wait(1).to({graphics:mask_graphics_173,x:168.3,y:7.2}).wait(1).to({graphics:mask_graphics_174,x:168.3,y:-5.7}).wait(1).to({graphics:mask_graphics_175,x:168.3,y:-18.5}).wait(1).to({graphics:mask_graphics_176,x:168.3,y:-31.3}).wait(1).to({graphics:mask_graphics_177,x:168.3,y:-44.1}).wait(1).to({graphics:mask_graphics_178,x:168.3,y:-57}).wait(4).to({graphics:null,x:0,y:0}).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,57,1,1,0,0,0,150,57);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(80).to({scaleX:0.86,scaleY:0.86,x:128.4,y:36.8},9).wait(80).to({regX:150.1,regY:57.1,x:128.5,y:36.9},0).to({y:-91.1},9).to({_off:true},1).wait(4));

	// shad
	this.instance_4 = new lib.HTML5rastershad_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(168.5,174,1,1,0,0,0,0,10);
	this.instance_4.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:125.5},9).wait(80).to({y:10},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(288.5,201,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({y:154},9).wait(80).to({y:37},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_6 = new lib.CTA();
	this.instance_6.parent = this;
	this.instance_6.setTransform(287.5,251,1,1,0,0,0,119.5,40);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({_off:false},0).wait(79).to({y:136},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(169).to({scaleY:1,y:-2},9).to({_off:true},4).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(168,244.1,1.5,1.5,0,0,0,0,2.6);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(484.3,253,1.47,1.47,0,0,0,215.2,63.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.parent = this;
	this.instance_10.setTransform(291.9,228.5,1.52,1.52,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(150,92.2,1,2,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},182).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(166.5,266.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(167,140,337.5,280);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;