(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Freeer160x600.jpg?1504144713968", id:"Freeer160x600"},
		{src:"images/HTML5rastershad.png?1504144713968", id:"HTML5rastershad"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.Freeer160x600 = function() {
	this.initialize(img.Freeer160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,267,177);


(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Freeer160x600();
	this.instance.parent = this;
	this.instance.setTransform(-129,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-129,0,267,177);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQARIAAghIAhAAIAAAhg");
	this.shape.setTransform(45.9,164.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWBCQgNgFgJgJQgKgKgGgNIgDgOIgCgPIAAAAQAAgNAFgNQAFgOAJgJQAJgKANgFIAMgFIAMgBQAJAAAHABQAGACAHADQAIADAMANQAJAKAEAOQAEANAAAMIgBAJIhjAAQACAIAEAIQADAGAFAEQAFAFAHACQAGACAGAAQAMAAAJgEQAIgEAJgIIASAQQgFAGgGAFQgGAFgGADQgIAEgIACQgIABgKAAQgMAAgNgFgAAjgIQgBgIgDgHQgCgGgEgFQgFgFgGgDQgGgCgIAAQgFAAgGACQgGADgFAFQgFAEgDAHQgDAHgBAIIBFAAIAAAAg");
	this.shape_1.setTransform(34.6,159.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBGIAAiHIAfAAIAAAeQAEgIAEgGQADgGAGgEQAGgFAIgCQAHgDAKABIAAAhIgCAAQgLAAgIAEQgJADgGAHQgEAHgEAKQgEAIAAANIAAA1g");
	this.shape_2.setTransform(22,159.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfBEQgJgDgGgFQgHgGgEgIQgEgIAAgKIAAAAQAAgLAEgJQAEgIAIgEQAHgGALgDQAKgCAMAAQAOAAAWAFIAAgCQAAgHgCgGQgDgFgEgEQgEgEgHgCQgGgCgGAAQgLAAgKADQgIACgKAEIgJgZQANgGAKgCQAOgEANAAQAPAAAMAEQALAEAIAIQAHAHAEALQAEALAAANIAABQIggAAIAAgRQgHAJgKAFQgPAGgKAAQgKAAgJgDgAgLAGQgGACgEACQgEADgCAEQgDAEAAAFIAAABQAAAJAIAGQAHAFAMAAQAGAAAGgCQAHgCAFgEQAFgEADgFQACgGAAgGIAAgIQgTgFgMAAQgFAAgGABg");
	this.shape_3.setTransform(8,159.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWBCQgNgFgKgJQgJgKgFgNIgFgOIgBgPIAAAAQAAgNAFgNQAFgOAJgJQAJgKANgFIAMgFIANgBQAIAAAGABQAIACAGADQAIADAMANQAJAKAEAOQAEANAAAMIAAAJIhjAAQABAIADAIQAEAGAFAEQAFAFAHACQAGACAGAAQAMAAAIgEQAJgEAIgIIATAQQgFAGgGAFQgGAFgGADQgIAEgHACQgJABgJAAQgNAAgNgFgAAjgIQgBgIgDgHQgCgGgFgFQgEgFgGgDQgGgCgIAAQgFAAgGACQgGADgFAFQgFAEgDAHQgCAHgBAIIBEAAIAAAAg");
	this.shape_4.setTransform(-14.9,159.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAeBFIgehcIgdBcIgcAAIgtiIIAgAAIAbBcIAfhdIAZAAIAeBdIAchcIAgAAIgtCIg");
	this.shape_5.setTransform(-33.9,159.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUAXQAMgCAFgHQAEgGgBgIIgMAAIAAgjIAhAAIAAAeQAAAJgDAHQgCAIgFAGQgFAEgGADQgHAEgKAAg");
	this.shape_6.setTransform(29.7,140.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABWQgIgCgFgFQgFgFgDgHQgDgIAAgLIAAhGIgRAAIAAgbIARAAIAAgmIAeAAIAAAmIAkAAIAAAbIgkAAIAABBQAAAJAEAEQAEAEAIAAQALAAAJgFIAAAaIgNAFQgHACgIAAQgKAAgEgCg");
	this.shape_7.setTransform(21.2,131.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgOBeIAAiHIAdAAIAACHgAgPg/IAAgeIAfAAIAAAeg");
	this.shape_8.setTransform(12.3,131.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfBEQgJgDgGgFQgHgGgEgIQgEgIAAgKIAAAAQAAgLAEgJQAEgIAIgEQAHgGALgDQAKgCAMAAQAOAAAWAFIAAgCQAAgHgCgGQgDgFgEgEQgEgEgHgCQgGgCgGAAQgLAAgKADQgIACgKAEIgJgZQANgGAKgCQAOgEANAAQAPAAAMAEQALAEAIAIQAHAHAEALQAEALAAANIAABQIggAAIAAgRQgHAJgKAFQgPAGgKAAQgKAAgJgDgAgLAGQgGACgEACQgEADgCAEQgDAEAAAFIAAABQAAAJAIAGQAHAFAMAAQAGAAAGgCQAHgCAFgEQAFgEADgFQACgGAAgGIAAgIQgTgFgMAAQgFAAgGABg");
	this.shape_9.setTransform(0.6,133.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAsBbIgsiAIgrCAIgcAAIg/i1IAiAAIAsCFIAsiFIAZAAIAtCFIAsiFIAhAAIg/C1g");
	this.shape_10.setTransform(-19.1,131.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgQARIAAghIAhAAIAAAhg");
	this.shape_11.setTransform(27.2,98.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AggBCQgJgEgGgHQgGgHgEgJQgDgLAAgMIAAhUIAfAAIAABLQAAAIACAHQACAFAEAFQAEAFAFACQAGACAGAAQAGAAAFgCQAGgDAEgEQAEgEACgHQADgGAAgJIAAhKIAfAAIAACHIgfAAIAAgWQgIALgJAGQgGAEgGACQgEABgIAAQgMAAgJgDg");
	this.shape_12.setTransform(15.6,93.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOBFIgOgEQgNgFgKgKQgKgJgFgNIgEgOIgCgOIAAAAQAAgIAGgSQAFgNAKgKQAKgKAOgGIAOgDIANgCQAKAAATAFQANAGAKAKQAKAJAFAOQAGARAAAJIAAAAIgCAOIgEANQgFANgKAKQgKAKgNAFQgTAGgKAAgAgQgnQgHADgGAGQgFAHgDAHQgDAIAAAIIAAAAQAAAIADAJQADAIAGAFQAFAHAIADQAIAEAHAAQAJAAAIgEQAIgDAFgGQAGgGACgIQADgIAAgJIAAAAQAAgIgDgHQgDgIgFgHQgGgGgIgDQgIgEgIABQgIgBgIAEg");
	this.shape_13.setTransform(-0.9,93.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgtBXQgIgCgHgEIAKgYQAKAGAJAAQAGAAAFgEQAEgDAEgJIg5iHIAiAAIAlBjIAjhjIAhAAIg2CLQgEAKgFAHQgEAIgEAEQgFAFgHACQgHACgHAAQgKAAgIgCg");
	this.shape_14.setTransform(-17.2,95.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgiBXQgPgFgOgIIAMgXQALAHAMAEQAMADAOAAQAIAAAJgDQAIgCAFgGQAGgFACgHQADgJAAgKIAAgLQgMAOgIAEQgGAEgHABQgGACgHAAQgMAAgLgDQgMgFgIgJQgJgIgFgMQgGgKAAgPIAAAAQAAgLAGgRQAFgLAJgIQAIgJAMgEQALgEAMAAQAHgBAHACQAHACAGAEQAKAFAJAKIAAgUIAgAAIAABrQAAASgFANQgEANgJAIQgFAFgGADQgGAEgHACQgUAEgKAAQgRAAgQgDgAgOg9QgHADgGAFQgFAFgDAHQgDAHAAAIIAAABQAAAIADAIQADAGAGADQAFAFAHAEQAHACAHAAQAHAAAIgCQAHgEAGgFQAFgDADgGQAEgHAAgJIAAAAQAAgIgEgIQgDgHgFgFQgGgEgHgEQgIgCgHAAQgHAAgHACg");
	this.shape_15.setTransform(55.9,69.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAdBFIAAhLQAAgJgCgGQgCgGgDgEQgEgFgGgCQgFgCgHAAQgFAAgFACQgGACgEAFQgEAFgCAFQgDAHAAAIIAABLIgfAAIAAiHIAfAAIAAAWQAIgMAJgFQAFgEAHgCQAEgBAIAAQAMAAAJADQAJADAGAIQAGAHADAJQAEAKAAAMIAABVg");
	this.shape_16.setTransform(39.6,67.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgOBeIAAiHIAdAAIAACHgAgPg/IAAgeIAfAAIAAAeg");
	this.shape_17.setTransform(27.8,65.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgtBXQgIgCgHgEIAKgYQAKAGAJAAQAGAAAFgEQAFgDAEgJIg6iHIAhAAIAmBjIAjhjIAhAAIg2CLQgEAKgFAHQgEAIgEAEQgFAFgHACQgHACgHAAQgKAAgIgCg");
	this.shape_18.setTransform(16.3,69.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgfBEQgJgDgGgFQgHgGgEgIQgEgIAAgKIAAAAQAAgLAEgJQAEgIAIgEQAHgGALgDQAKgCAMAAQAOAAAWAFIAAgCQAAgHgCgGQgDgFgEgEQgEgEgHgCQgGgCgGAAQgLAAgKADQgIACgKAEIgJgZQANgGAKgCQAOgEANAAQAPAAAMAEQALAEAIAIQAHAHAEALQAEALAAANIAABQIggAAIAAgRQgHAJgKAFQgPAGgKAAQgKAAgJgDgAgLAGQgGACgEACQgEADgCAEQgDAEAAAFIAAABQAAAJAIAGQAHAFAMAAQAGAAAGgCQAHgCAFgEQAFgEADgFQACgGAAgGIAAgIQgTgFgMAAQgFAAgGABg");
	this.shape_19.setTransform(0.6,67.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhFBaIAAiwIAfAAIAAAWQAIgMALgGQAGgDAGgCQAHgCAHAAQAMAAALAEQAMAFAJAJQAJAKAFAMQAFAUAAALIAAAAIgBAQIgEANQgFANgJAJQgJAJgMAFQgLAFgMAAQgHAAgHgCQgHgCgGgEQgKgGgIgLIAAA/gAgOg7QgHADgGAGQgGAGgDAIQgDAIAAAKIAAAAQAAAKADAIQADAGAGAGQAGAGAHADQAHADAHAAQAHAAAIgDQAHgDAFgGQAFgFADgHQADgIAAgKIAAAAQAAgKgDgIQgDgIgFgGQgGgGgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_20.setTransform(-15,69.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgWBCQgNgFgJgKQgKgJgGgNIgDgOIgCgPIAAAAQAAgOAFgNQAFgNAJgJQAJgKAMgFIANgEIAMgCQAJAAAHACQAGABAHADQAIADAMANQAJAKAEANQAEANAAAOIgBAJIhjAAQACAIAEAGQADAHAFAEQAFAFAHACQAGACAGAAQAMABAJgFQAIgDAJgJIASAQQgFAHgGAEQgGAFgHADQgHADgIACQgIACgKAAQgMAAgNgFgAAjgIQgBgIgDgGQgCgHgEgFQgFgFgGgCQgGgEgIAAQgFAAgGAEQgGACgFAEQgFAGgDAGQgDAHgBAIIBFAAIAAAAg");
	this.shape_21.setTransform(-39.7,67.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgHBeQgHgCgGgEQgKgGgIgKIAAAVIgfAAIAAi8IAfAAIAABLQAIgLALgHQAGgDAGgCQAHgCAHAAQAMAAALAFQAMAFAJAIQAJAKAFANQAFARAAALIAAAAIgBAQIgEAPQgFANgJAJQgJAKgMAEQgLAFgMAAQgHAAgHgCgAgOgOQgHACgGAHQgGAFgDAGQgDAIAAAKIAAAAQAAALADAHQADAIAGAHQAGAFAHAEQAHACAHAAQAHAAAIgCQAHgEAFgFQAFgGADgIQADgJAAgKIAAAAQAAgKgDgIQgDgGgFgGQgGgFgHgDQgHgEgHAAQgHAAgHAEg");
	this.shape_22.setTransform(-55.9,65.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgdBbQgMgEgJgJQgJgKgFgNIgEgOIgCgRIAAAAQAAgLAGgRQAFgNAJgKQAJgJALgEQAMgFAMAAQAGAAAIACQAGACAGADQALAGAIALIAAhKIAgAAIAAC8IggAAIAAgXQgIAMgLAGQgGAEgGACQgIACgGAAQgMAAgLgFgAgOgPQgHADgFAGQgGAGgDAGQgDAIAAAKIAAAAQAAAKADAIQADAJAGAGQAFAFAIAEQAHADAGAAQAIAAAHgDQAHgEAFgFQAGgGADgJQAEgIAAgKIAAAAQAAgJgEgJQgDgGgGgGQgFgGgHgDQgHgDgIAAQgGAAgIADg");
	this.shape_23.setTransform(50.4,39.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUAXQAMgCAFgGQAEgHgBgIIgLAAIAAgjIAgAAIAAAeQAAAJgCAIQgDAIgFAFQgFAFgGADQgHADgKAAg");
	this.shape_24.setTransform(38.3,34.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgWBCQgNgFgJgJQgKgKgGgNIgDgOIgCgPIAAAAQAAgNAFgNQAFgNAJgKQAJgKANgFIAMgFIANgBQAHAAAIABQAGACAHADQAIADAMANQAJAKAEANQAEANAAANIgBAJIhiAAQABAIADAIQAEAGAFAEQAGAFAGACQAHADAFgBQAMAAAJgEQAIgEAIgIIATAQQgFAGgGAFQgGAFgGADQgIAEgIACQgIABgKAAQgMAAgNgFgAAjgIQgBgIgDgHQgCgGgEgFQgFgFgGgDQgHgCgHAAQgFAAgGACQgGADgFAEQgEAFgEAHQgDAHAAAIIBEAAIAAAAg");
	this.shape_25.setTransform(27.3,41.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAeBFIgehcIgeBcIgcAAIgsiIIAgAAIAcBcIAehdIAZAAIAfBdIAchcIAfAAIgtCIg");
	this.shape_26.setTransform(8.3,41.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgdBbQgMgEgJgJQgJgKgFgNIgEgOIgCgRIAAAAQAAgLAGgRQAFgNAJgKQAJgJALgEQAMgFAMAAQAGAAAIACQAGACAGADQALAGAIALIAAhKIAgAAIAAC8IggAAIAAgXQgIAMgLAGQgGAEgGACQgIACgGAAQgMAAgLgFgAgOgPQgHADgFAGQgGAGgDAGQgDAIAAAKIAAAAQAAAKADAIQADAJAGAGQAFAFAIAEQAHADAGAAQAIAAAHgDQAHgEAFgFQAGgGADgJQAEgIAAgKIAAAAQAAgJgEgJQgDgGgGgGQgFgGgHgDQgHgDgIAAQgGAAgIADg");
	this.shape_27.setTransform(-19.8,39.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAdBFIAAhMQAAgHgCgHQgCgGgDgEQgEgEgGgDQgFgCgHAAQgEAAgGACQgGADgEAEQgEAFgCAGQgDAGAAAIIAABLIgfAAIAAiGIAfAAIAAAUQAIgLAJgGQAFgDAHgBQAEgCAIAAQALAAAKADQAJAEAGAHQAGAGADAKQAEAKAAAMIAABVg");
	this.shape_28.setTransform(-36.1,41.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgfBEQgJgDgGgFQgHgGgEgIQgEgIAAgKIAAAAQAAgLAEgJQAEgIAIgEQAHgGALgDQAKgCAMAAQAOAAAWAFIAAgCQAAgHgCgGQgDgFgEgEQgEgEgHgCQgGgCgGAAQgLAAgKADQgIACgKAEIgJgZQANgGAKgCQAOgEANAAQAPAAAMAEQALAEAIAIQAHAHAEALQAEALAAANIAABQIggAAIAAgRQgHAJgKAFQgPAGgKAAQgKAAgJgDgAgLAGQgGACgEACQgEADgCAEQgDAEAAAFIAAABQAAAJAIAGQAHAFAMAAQAGAAAGgCQAHgCAFgEQAFgEADgFQACgGAAgGIAAgIQgTgFgMAAQgFAAgGABg");
	this.shape_29.setTransform(-52.2,41.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgnBGIAAiHIAgAAIAAAeQADgIAEgGQADgGAGgEQAGgFAIgCQAIgDAIABIAAAhIgCAAQgKAAgJAEQgIADgHAHQgDAHgEAKQgDAIAAANIAAA1g");
	this.shape_30.setTransform(69.7,15.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgWBCQgNgFgJgKQgKgJgGgNIgDgOIgCgPIAAAAQAAgNAFgNQAFgOAJgJQAJgKAMgGIANgDIAMgCQAIAAAIACQAGABAHADQAIADANANQAHAKAFAOQAEANAAANIgBAJIhjAAQACAHAEAIQADAGAFAFQAGAEAGACQAGACAGABQALgBAKgEQAIgDAJgJIASARQgFAFgGAFQgGAFgHADQgGAEgJABQgIACgKAAQgMAAgNgFgAAjgIQgBgIgCgHQgDgGgEgFQgFgFgGgCQgGgDgIAAQgFAAgGADQgGACgFAFQgEAFgDAGQgEAHgBAIIBFAAIAAAAg");
	this.shape_31.setTransform(55.8,15.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AglAPIAAgdIBLAAIAAAdg");
	this.shape_32.setTransform(42.7,14.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgWBCQgNgFgJgKQgKgJgGgNIgDgOIgCgPIAAAAQAAgNAFgNQAFgOAJgJQAJgKANgGIAMgDIANgCQAHAAAIACQAGABAHADQAIADAMANQAJAKAEAOQAEANAAANIgBAJIhiAAQABAHADAIQAEAGAFAFQAGAEAGACQAHACAFABQAMgBAJgEQAIgDAIgJIATARQgFAFgGAFQgGAFgGADQgIAEgIABQgIACgKAAQgMAAgNgFgAAjgIQgBgIgDgHQgCgGgEgFQgFgFgGgCQgHgDgHAAQgFAAgGADQgGACgFAFQgEAFgEAGQgDAHAAAIIBEAAIAAAAg");
	this.shape_33.setTransform(29.5,15.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgWBCQgNgFgKgKQgJgJgFgNIgFgOIgBgPIAAAAQAAgNAFgNQAFgOAJgJQAJgKAMgGIANgDIAMgCQAJAAAGACQAIABAGADQAIADANANQAHAKAFAOQAEANAAANIAAAJIhkAAQACAHAEAIQADAGAFAFQAFAEAHACQAHACAFABQALgBAJgEQAJgDAIgJIATARQgFAFgGAFQgGAFgHADQgHAEgHABQgJACgJAAQgNAAgNgFgAAjgIQgBgIgCgHQgDgGgFgFQgEgFgGgCQgHgDgHAAQgFAAgGADQgGACgFAFQgEAFgDAGQgDAHgCAIIBFAAIAAAAg");
	this.shape_34.setTransform(13.8,15.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgnBGIAAiHIAgAAIAAAeQADgIAEgGQADgGAGgEQAGgFAIgCQAIgDAIABIAAAhIgCAAQgKAAgJAEQgIADgHAHQgDAHgEAKQgDAIAAANIAAA1g");
	this.shape_35.setTransform(1.3,15.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgXBfIAAhsIgSAAIAAgaIASAAIAAgKQgBgMADgIQADgJAFgFQAGgGAHgCQAGgDALAAQANAAAMADIAAAbQgKgDgJAAQgIAAgFAFQgFAFAAAKIAAAIIAkAAIAAAaIgjAAIAABsg");
	this.shape_36.setTransform(-9.3,13.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgtBXQgIgCgHgEIAKgYQAKAGAJAAQAGAAAFgEQAFgDAEgJIg6iHIAhAAIAmBjIAjhjIAhAAIg2CLQgEAKgFAHQgEAIgEAEQgFAFgHACQgHACgHAAQgKAAgIgCg");
	this.shape_37.setTransform(-30,18);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAeBGIAAhNQgBgHgCgHQgCgGgDgEQgEgEgFgDQgGgCgHAAQgFAAgFADQgGACgEAEQgFAEgCAHQgCAGAAAIIAABMIgfAAIAAiHIAfAAIAAAVQAIgMAJgGQAGgDAFgCQAGgCAHAAQAMABAJADQAJAEAGAHQAGAHAEAKQADAJAAAMIAABWg");
	this.shape_38.setTransform(-45.7,15.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AA9BbIgSgsIhVAAIgSAsIgiAAIBRi1IAbAAIBQC1gAAeATIgehHIgeBHIA8AAg");
	this.shape_39.setTransform(-64.1,13.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78,0,156,173.7);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("EgMfAsOMAAAhYbIY/AAMAAABYbg");
	this.shape.setTransform(80,262,1,0.926);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape.setTransform(23.4,109.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AgWAuQgGgDgEgFQgFgEgCgIQgCgHAAgHIAAg7IAWAAIAAA0QAAAFABAFQABAEADADQADADADABQAEACAEAAQAEAAAEgCQAEgBACgDQADgDACgFQABgEAAgFIAAg0IAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIAEQgDABgFAAQgIAAgHgCg");
	this.shape_1.setTransform(13.4,109.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFABQgDgBgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAIAAAIIAAA6g");
	this.shape_2.setTransform(2.3,109.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgIQAHgGAJgEIAKgDIAJgBQAHAAANAEQAJAEAHAGQAHAHADAJQAEANAAAFIgBAJIgDAKQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFABQAGgBAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgEgCgGQgCgFgEgFQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_3.setTransform(-9.2,109.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AgzA+IAAh8IA3AAQALAAAIADQAIAEAGAEQAEAFACAFQACAFAAAHIAAAAQAAAGgCAEQgBAEgCAEQgFAGgIAEIALACQAEADADAEQADAEACAEQACAFAAAGIAAABQAAAIgDAHQgEAGgFAEQgHAFgJADQgIABgLAAgAgdArIAiAAIALgBIAHgEQAEgBACgEQABgDAAgFIAAAAQAAgEgBgDQgCgDgEgCQgCgDgGgBIgLgBIghAAgAgdgJIAdAAIAJAAIAHgDIAGgGQABgEAAgEIAAAAQAAgDgBgEQgCgDgDgBIgGgEIgKgBIgeAAg");
	this.shape_4.setTransform(-21.2,108.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_5.setTransform(57.2,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgBgFAAQgDAAgDABQgEACgDADQgDADgCAEQgBAFAAAFIAAA0IgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgDIAIgCQAIAAAHADQAGACAEAFQAFAFACAGQACAIAAAIIAAA6g");
	this.shape_6.setTransform(48.1,89.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AgWAtQgGgCgEgFQgFgEgCgIQgCgGAAgIIAAg7IAWAAIAAA0QAAAGABAEQABAEADADQADADADABQAEACAEAAQAEAAAEgCQAEgBACgDQADgDACgEQABgFAAgFIAAg0IAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIADQgDACgFAAQgIAAgHgDg");
	this.shape_7.setTransform(36.9,89.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgJAwIgKgDQgJgEgHgGQgHgHgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgJAHgHQAHgGAJgEIAKgDIAJgBQAHAAANAEQAJAEAHAGQAHAHADAJQAEANAAAFIgBAJIgDAKQgEAIgGAIQgHAGgKAEQgNAEgGAAgAgLgbQgFADgEAEQgDAEgCAGQgDAFAAAFQAAAGADAFQACAGAEAEQAEAFAFACQAFADAFAAQAGAAAFgDQAGgCADgFQAEgEACgGQACgFAAgGIAAAAQAAgEgCgGQgCgFgEgFQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_8.setTransform(25.5,89.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgEAwIgJgDQgJgEgHgGQgGgHgEgJQgEgJABgKIAAAAQgBgJAEgJQAEgJAGgHQAHgGAJgEIAJgDIAIgBIANABIAKADQAHAEAJAIIgOAPQgFgGgFgDQgHgDgIAAQgEAAgFACQgEADgEAEQgDAEgDAGQgCAFAAAFQAAAGACAFQADAGADAFQAEAEAFACQAEADAFAAQAIAAAHgEQAFgDAFgGIAOAOQgLAJgFADIgLAEIgNABg");
	this.shape_9.setTransform(14.6,89.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AgEAwIgJgDQgJgEgHgGQgGgHgEgJQgDgJAAgKIAAAAQAAgJADgJQAEgJAGgHQAHgGAJgEIAJgDIAIgBIANABIAKADQAGAEAKAIIgOAPQgFgGgFgDQgHgDgIAAQgEAAgFACQgEADgEAEQgEAEgBAGQgDAFAAAFQAAAGADAFQABAGAEAFQAEAEAFACQAEADAFAAQAIAAAGgEQAGgDAFgGIAOAOQgLAJgFADIgLAEIgNABg");
	this.shape_10.setTransform(4.3,89.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AAqA/IgNgfIg6AAIgNAfIgWAAIA3h9IATAAIA3B9gAAVANIgVgxIgVAxIAqAAg");
	this.shape_11.setTransform(-8,88.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AAUAvIgUg+IgUA+IgTAAIgfhdIAWAAIATA/IAVg/IAQAAIAWA/IAUg/IAVAAIgfBdg");
	this.shape_12.setTransform(-28.2,89.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgPAtQgJgDgHgHQgGgGgEgJIgDgKIAAgKIAAAAQAAgJADgJQAEgJAFgHQAHgGAIgEIAJgDIAIgBIAKABIAKADQAGADAIAIQAGAHADAJQACAKAAAIIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIACQAIAAAHgEQAFgDAGgFIANAMIgHAGIgJAGIgKAEIgNABQgIAAgJgEgAAYgFQAAgGgDgEIgEgIQgEgDgEgCQgEgCgFAAQgDAAgFACQgDACgEADQgDADgCAEIgDALIAvAAIAAAAg");
	this.shape_13.setTransform(-41.4,89.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("AAkA/IhDhYIAABYIgXAAIAAh8IAVAAIBBBVIAAhVIAXAAIAAB8g");
	this.shape_14.setTransform(-53.9,88.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgLBAIgKgFIgKgFIgIgIIgGgKIgFgLIgCgMIgBgNIAAAAIABgMIACgMIAFgLIAHgJIAIgIIAJgHIALgDIAKgCIALACIALADIAJAHIAIAIIAHAJIAEALQAEAQAAAIIAAAAIgBAMIgDANIgEALIgHAKIgIAIIgJAFIgLAFIgLABIgLgBgAgMgoQgGADgEAGQgEAHgCAIQgDAIAAAIIAAAAQAAAJADAIQACAIAEAGQAEAHAGADQAGAEAGAAQAHAAAGgEQAGgDAEgHQAEgGACgHQACgJAAgJIAAAAQAAgHgCgJQgCgIgEgHQgFgFgGgEQgGgEgGABQgGgBgGAEg");
	this.shape_15.setTransform(15.8,68.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AgLBAIgKgFIgKgFIgIgIIgGgKIgFgLIgCgMIgBgNIAAAAIABgMIACgMIAFgLIAHgJIAIgIIAJgHIALgDIAKgCIALACIALADIAJAHIAIAIIAHAJIAEALQAEAQAAAIIAAAAIgBAMIgDANIgEALIgHAKIgIAIIgJAFIgLAFIgLABIgLgBgAgMgoQgGADgEAGQgEAHgCAIQgDAIAAAIIAAAAQAAAJADAIQACAIAEAGQAEAHAGADQAGAEAGAAQAHAAAGgEQAGgDAEgHQAEgGACgHQACgJAAgJIAAAAQAAgHgCgJQgCgIgEgHQgFgFgGgEQgGgEgGABQgGgBgGAEg");
	this.shape_16.setTransform(2.8,68.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AACA/IAAhmIgUAGIgFgSIAggLIAPAAIAAB9g");
	this.shape_17.setTransform(-7.9,68.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgEBMIAAgSQgQgCgHgEQgLgEgJgHIAMgRQAIAHAHADQAIAEAIACIAAgkIgRgEQgHgDgFgEQgFgEgCgGQgCgGAAgHIAAgBQAAgHADgGQACgGAFgFQAFgEAHgCQAHgEAJAAIAAgLIANAAIAAALQAKABAIAEQAIADAIAGIgKARQgGgEgGgDIgMgFIAAAiQAKADAHAEQAIADAEADQAFAEACAGQADAFAAAIQAAAHgDAHQgDAFgFAFQgFAFgHADQgHACgJABIAAARgAAJAoQAIAAAFgEQAEgEAAgHIAAAAQAAgHgDgDQgEgEgKgDgAgRgqQgEAEAAAGIAAABQAAAFADAEQAEAEAKADIAAggQgIABgFAEg");
	this.shape_18.setTransform(-16.6,68.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgIAsIAAgjIgkAAIAAgSIAkAAIAAgiIASAAIAAAiIAjAAIAAASIgjAAIAAAjg");
	this.shape_19.setTransform(0,49.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002663").s().p("AgXA8QgLgDgJgGIAIgQQAIAFAIACQAIADAKAAQAGAAAFgCQAFgCAFgDQADgEACgFQACgGAAgHIAAgHQgIAJgGADQgEACgEABQgFACgEAAQgJAAgHgDQgJgDgGgGQgFgGgEgIQgDgHAAgJIAAgBQAAgHADgLQAEgJAFgGQAGgGAJgDQAHgCAJAAQAEAAAFABIAJADQAGAEAHAHIAAgNIAWAAIAABJQAAAMgEAJQgCAJgHAGIgHAGIgJADQgOAEgHAAQgLAAgLgDgAgKgpQgEACgEADQgEAEgBAEQgDAFAAAGIAAABQAAAFADAFQABAFAEACQAEADAFABQAEACAFABQAFgBAFgCQAFgBAEgDQAEgDACgEQACgFAAgFIAAgBQAAgFgCgGQgCgFgEgDQgEgDgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_20.setTransform(35.9,33);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002663").s().p("AAVAwIAAg0QAAgFgCgFIgEgHQgCgDgEgBQgEgDgFAAQgDAAgDADQgEABgDADQgDADgCAFQgBAEAAAFIAAA0IgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAEACAIQACAHAAAHIAAA7g");
	this.shape_21.setTransform(24.5,31.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002663").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_22.setTransform(16.4,29.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002663").s().p("AATBBIgagpIgOAOIAAAbIgWAAIAAiBIAWAAIAABMIAmgoIAaAAIgmAlIAnA4g");
	this.shape_23.setTransform(9.2,29.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002663").s().p("AgEAwIgJgDQgJgEgHgGQgGgHgEgJQgEgJABgKIAAAAQgBgJAEgIQAEgKAGgGQAHgIAJgDIAJgDIAIgBIANABIAKAEQAHACAJAKIgNAOQgGgGgFgCQgHgEgIAAQgEAAgFADQgEACgEAEQgDAEgDAFQgCAGAAAFQAAAGACAFQADAGADAEQAEAEAFADQAEADAFgBQAIAAAHgDQAFgDAFgFIAOAMQgLAKgFADIgLAEIgNABg");
	this.shape_24.setTransform(-1.6,31.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002663").s().p("AgPAuQgJgEgGgGQgHgHgEgJIgDgJIgBgLIAAAAQABgJADgIQADgKAHgGQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAKQADAJAAAIIAAAGIhEAAQABAGACAFQADAEAEADIAIAFIAIABQAHAAAGgCQAHgDAGgGIAMALIgIAHIgIAHIgLADIgMABQgIAAgJgDgAAYgFQAAgFgCgFIgGgIQgCgEgFgCQgEgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_25.setTransform(-12.3,31.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002663").s().p("AAVBBIAAg2QAAgFgCgFIgEgFQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCADQgBAEAAAGIAAA1IgWAAIAAiBIAWAAIAAAzQAFgIAGgEIAIgDIAIgCQAIAAAHADQAGACAEAFQAFAFACAHQACAHAAAGIAAA8g");
	this.shape_26.setTransform(-23.3,29.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002663").s().p("AgFBAIgNgFIgKgGIgKgHIgIgKIgFgLQgDgGgBgGIgBgNIAAAAIABgMQABgGADgGIAFgLIAIgKIAJgIIAMgFIAMgFIAMgBQAIABAIABQAHABAGADQAIAEAMAKIgOAQQgIgHgIgEIgJgDIgKgCQgHAAgIAEQgIAEgFAGQgGAFgDAJQgDAIAAAIIAAAAQAAAIADAJQADAIAGAGQAFAGAIAEQAIADAHAAQAFAAAFgBIAKgDQAHgEAJgIIAOAOIgKAJQgGAFgGACQgGADgHACQgHACgJAAIgLgBg");
	this.shape_27.setTransform(-35.3,30.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002663").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQABgIADgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIAKABIAKADQAFACAJAKQAGAGADAJQACAJAAAJIAAAGIhEAAQABAGADAEQACAFAEADIAHAFIAJABQAIAAAFgCQAHgEAFgFIANALIgIAIIgIAFIgKAEIgNABQgIAAgJgDgAAYgFQgBgGgBgEIgGgIQgCgEgFgCQgEgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_28.setTransform(15.1,11.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002663").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgCgJIgBgLIAAAAQAAgIADgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIALABIAJADQAFACAJAKQAFAGADAJQAEAJAAAJIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAHABQAJAAAGgCQAFgEAHgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQgBgGgCgEIgEgIQgEgEgDgCQgFgBgFAAQgDAAgEABQgEACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_29.setTransform(4.2,11.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002663").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_30.setTransform(-4.5,11.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002663").s().p("AgtA+IAAh8IBbAAIAAAUIhFAAIAAAjIA9AAIAAASIg9AAIAAAzg");
	this.shape_31.setTransform(-14.1,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-86,0,172,120);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.5,-300.5,161,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43C0FF").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201708_Freeer_160x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(142,448,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.476,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(80,585.8,0.68,0.68,0,0,0,0.1,1.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(80,572.9,1.13,1.13,0,0,0,0.1,3.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border160x600();
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},164).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AsfN6IAA7zIY/AAIAAbzg");
	var mask_graphics_66 = new cjs.Graphics().p("AsfN6IAA7zIY/AAIAAbzg");
	var mask_graphics_67 = new cjs.Graphics().p("AsfN6IAA7yIY/AAIAAbyg");
	var mask_graphics_68 = new cjs.Graphics().p("AsfN5IAA7xIY/AAIAAbxg");
	var mask_graphics_69 = new cjs.Graphics().p("AsfN5IAA7yIY/AAIAAbyg");
	var mask_graphics_70 = new cjs.Graphics().p("AsfN6IAA7zIY/AAIAAbzg");
	var mask_graphics_71 = new cjs.Graphics().p("AsfN6IAA7yIY/AAIAAbyg");
	var mask_graphics_72 = new cjs.Graphics().p("AsfN5IAA7xIY/AAIAAbxg");
	var mask_graphics_73 = new cjs.Graphics().p("AsfN5IAA7yIY/AAIAAbyg");
	var mask_graphics_74 = new cjs.Graphics().p("AsfN6IAA7zIY/AAIAAbzg");
	var mask_graphics_75 = new cjs.Graphics().p("AsfN6IAA7yIY/AAIAAbyg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:80,y:89}).wait(66).to({graphics:mask_graphics_66,x:80,y:89}).wait(1).to({graphics:mask_graphics_67,x:80,y:85.8}).wait(1).to({graphics:mask_graphics_68,x:80,y:82.6}).wait(1).to({graphics:mask_graphics_69,x:80,y:79.3}).wait(1).to({graphics:mask_graphics_70,x:80,y:76.1}).wait(1).to({graphics:mask_graphics_71,x:80,y:72.9}).wait(1).to({graphics:mask_graphics_72,x:80,y:69.7}).wait(1).to({graphics:mask_graphics_73,x:80,y:66.4}).wait(1).to({graphics:mask_graphics_74,x:80,y:63.2}).wait(1).to({graphics:mask_graphics_75,x:80,y:60}).wait(90));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(230,57,1,1,0,0,0,150,57);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},164).wait(1));

	// pic shad
	this.instance_4 = new lib.HTML5rastershad_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(90,187,1,1,0,0,0,0,10);
	this.instance_4.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(66).to({x:92},0).to({x:90,y:158},9).to({_off:true},89).wait(1));

	// CTA
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(743.5,553,5,5,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(71).to({_off:false},0).to({scaleX:1,scaleY:1,x:199.5,y:381},4).to({_off:true},89).wait(1));

	// HEAD
	this.instance_6 = new lib.HEAD1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(988,434,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:1,scaleY:1,x:198.5,y:220},4).wait(62).to({y:190},9).to({_off:true},89).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},164).wait(1));

	// tag
	this.instance_8 = new lib._2016TAGvert();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80.1,536.9,1.35,1.35,0,0,0,0,2.6);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(272.9,540.1,0.897,0.897,0,0,0,215.2,63.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.parent = this;
	this.instance_10.setTransform(155.6,525.1,0.927,0.927,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_11 = new lib.HTML5rastershad_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_11.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},164).wait(1));

	// logo box
	this.instance_12 = new lib.box1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({_off:true},164).wait(1));

	// EHO
	this.instance_13 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_13.parent = this;
	this.instance_13.setTransform(17.1,232.1,0.07,0.07,0,0,0,135,145);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.9,300,887.5,1167.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;