(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1499282522529", id:"HTML5rastershad"},
		{src:"images/Takeout336x280.jpg?1499282522529", id:"Takeout336x280"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Takeout336x280 = function() {
	this.initialize(img.Takeout336x280);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,165);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// pic
	this.instance = new lib.Takeout336x280();
	this.instance.parent = this;
	this.instance.setTransform(-18,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,0,336,165);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAPIAAgdIAdAAIAAAdg");
	this.shape.setTransform(131.4,41.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgoBNQgGgBgHgEIAJgVQAJAEAIABQAGAAADgEQAEgCAEgJIgzh3IAeAAIAgBYIAghYIAdAAIgwB7IgIAPQgEAHgDAFQgEAEgGABQgGACgHAAQgJAAgHgCg");
	this.shape_1.setTransform(123.3,39.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbA8QgHgDgGgEQgGgFgEgHQgDgHAAgJIAAgBQAAgJADgIQAEgHAHgDQAGgFAJgCQAKgDALAAQALAAATAFIAAgDQAAgGgBgFQgCgFgEgDQgEgEgGgBQgFgCgGAAQgJAAgJACIgQAFIgIgVQALgFAKgDQALgCAMAAQAOAAAKADQAKAEAGAGQAHAHADAJQADAKAAAMIAABGIgbAAIAAgPQgHAIgJAEQgMAFgJAAQgJAAgIgCgAgKAEIgJAEQgDADgCAEQgCADAAAFIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAFgDQAEgEACgEQADgFAAgGIAAgIQgRgFgLAAQgEAAgGABg");
	this.shape_2.setTransform(109.9,37.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaBRQgKgFgIgIQgIgIgEgLIgEgNIgCgOIAAgBQAAgKAGgPQAEgLAIgIQAIgIAKgFQAKgEALAAQAFAAAHACQAGACAFADQAJAFAIAKIAAhCIAbAAIAACmIgbAAIAAgUQgIALgJAFIgLAFQgHACgFAAQgKAAgLgEgAgLgNQgHADgFAFQgFAFgCAFQgDAIAAAIIAAABQAAAIADAIQADAHAEAFQAFAFAHADQAGADAFAAQAHAAAGgDQAHgDAFgFQAEgFADgHQADgIAAgIIAAgBQAAgIgDgIQgDgFgEgFQgFgFgHgDQgGgDgHAAQgFAAgGADg");
	this.shape_3.setTransform(95.5,35.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdBMQgPgDgLgHIAKgVQAKAGAKADQALADANAAQAHAAAHgCQAHgCAFgFQAEgFADgHQADgHAAgJIAAgJQgLAMgHAEQgFADgHABQgFACgGAAQgLAAgKgEQgKgEgIgHQgHgHgEgLQgFgJgBgNIAAAAQABgJAFgPQADgLAJgHQAHgHAKgEQAKgEALAAQAGAAAGABQAGACAFADQAKAFAHAJIAAgSIAcAAIAABfQAAAPgDAMQgEALgIAIQgEAEgFADQgGADgGACQgSAEgJAAQgPAAgNgEgAgMg1QgHACgEAEQgFAFgCAGQgDAGAAAIIAAAAQAAAHADAHQACAGAFACQAEAFAHACQAGACAGAAQAHAAAGgCQAHgCAEgFQAFgCADgGQADgHAAgHIAAAAQAAgIgDgGQgDgGgFgFQgEgEgHgCQgGgDgHAAQgGAAgGADg");
	this.shape_4.setTransform(73.2,39.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAaA9IAAhCQAAgIgBgFQgDgGgCgEQgEgDgFgCQgEgCgHAAQgEAAgFACQgFACgDAEQgEAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAHgKAHgFIALgFQAEgCAGAAQALAAAIAEQAIADAGAGQAFAGADAJQADAJAAAKIAABLg");
	this.shape_5.setTransform(58.8,37.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBTIAAh4IAaAAIAAB4gAgOg3IAAgbIAcAAIAAAbg");
	this.shape_6.setTransform(48.3,35.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLA9Igyh5IAeAAIAfBYIAhhYIAdAAIgyB5g");
	this.shape_7.setTransform(38.2,37.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMA+IgNgEQgLgFgJgJQgJgJgFgKIgDgNIgBgMIAAAAQAAgHAEgQQAFgMAJgIQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFALQAFAQAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAHQADAGAFAGQAFAGAHADQAGACAHAAQAIAAAHgCQAGgDAFgGQAFgFADgHQACgHAAgIIAAAAQAAgHgDgHQgCgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgHACg");
	this.shape_8.setTransform(24.5,37.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABAA9IAAhCQAAgHgCgHQgBgFgDgEQgDgDgFgCQgFgCgGAAQgFAAgFACQgFACgDADQgEAEgCAGQgBAGAAAHIAABCIgaAAIAAhCQAAgIgCgGQgCgFgDgEQgDgDgFgCQgEgCgGAAQgGAAgEACQgFACgEAEQgDAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAHgKAHgFIAKgEQAGgCAHgBQAHAAAFACQAGABAEADIAHAHIAFAJQAIgKAKgGQAFgDAGgBQAGgCAGAAQAKABAIADQAIACAGAHQAFAFADAJQADAJAAALIAABLg");
	this.shape_9.setTransform(6.1,37.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaA9IAAhCQAAgIgCgFQgCgGgCgEQgEgDgEgCQgFgCgHAAQgEAAgFACQgFACgEAEQgDAEgCAFQgCAGAAAHIAABCIgcAAIAAh3IAcAAIAAATQAHgKAHgFIALgFQAEgCAHAAQAKAAAIAEQAIADAFAGQAGAGADAJQADAJAAAKIAABLg");
	this.shape_10.setTransform(-18.8,37.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgMA+IgNgEQgLgFgJgJQgJgJgFgKIgDgNIgBgMIAAAAQAAgHAEgQQAFgMAJgIQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFALQAFAQAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAHQADAGAFAGQAFAGAHADQAGACAHAAQAIAAAHgCQAGgDAFgGQAFgFADgHQACgHAAgIIAAAAQAAgHgDgHQgCgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgHACg");
	this.shape_11.setTransform(-33.6,37.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAABMQgHgCgEgEQgFgEgCgGQgDgIAAgKIAAg9IgPAAIAAgZIAPAAIAAghIAaAAIAAAhIAgAAIAAAZIggAAIAAA5QAAAIAEAEQADADAIAAQAJAAAIgEIAAAXQgFADgGACQgGABgIAAQgIAAgEgCg");
	this.shape_12.setTransform(-52.9,35.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgcA6QgIgDgGgGQgFgGgDgJQgDgIAAgLIAAhMIAcAAIAABEQAAAGABAGQACAFAEAEQADAEAFACQAFACAFAAQAFAAAFgCQAFgCADgEQAEgEACgGQACgFAAgHIAAhDIAcAAIAAB4IgcAAIAAgTQgHAKgIAFIgKAFQgEABgHAAQgKAAgIgDg");
	this.shape_13.setTransform(-64.7,37.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgMA+IgNgEQgLgFgJgJQgJgJgFgKIgDgNIgBgMIAAAAQAAgHAEgQQAFgMAJgIQAJgJAMgFIAMgEIAMgBQAJAAAQAFQAMAFAJAIQAIAJAFALQAFAQAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAHQADAGAFAGQAFAGAHADQAGACAHAAQAIAAAHgCQAGgDAFgGQAFgFADgHQACgHAAgIIAAAAQAAgHgDgHQgCgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgHACg");
	this.shape_14.setTransform(-79.3,37.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUA6QgLgEgIgJQgJgIgFgLIgDgNIgBgNIAAAAQAAgLAEgMQAEgLAIgKQAIgIALgFIALgEIALgBQAHAAAHABQAGABAFAEQAIACALALQAHAKADALQAEAMAAALIAAAIIhYAAQACAHADAHQADAFAEAEQAFAEAGACQAGACAEAAQAKAAAIgEQAIgDAHgHIARAOIgKAKIgLAGQgGAEgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgGgEgEQgEgEgFgCQgGgDgGAAQgFAAgFACQgFACgFAEQgEAFgCAGQgDAGgBAHIA8AAIAAAAg");
	this.shape_15.setTransform(-93.7,37.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAYBTIgig0IgRASIAAAiIgcAAIAAilIAcAAIAABiIAwg0IAiAAIgxAvIAyBIg");
	this.shape_16.setTransform(-106.1,35);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgbA8QgHgDgGgEQgGgFgEgHQgDgHAAgJIAAgBQAAgJADgIQAEgHAHgDQAGgFAJgCQAKgDALAAQALAAATAFIAAgDQAAgGgBgFQgCgFgEgDQgEgEgGgBQgFgCgGAAQgJAAgJACIgQAFIgIgVQALgFAKgDQALgCAMAAQAOAAAKADQAKAEAGAGQAHAHADAJQADAKAAAMIAABGIgbAAIAAgPQgHAIgJAEQgMAFgJAAQgJAAgIgCgAgKAEIgJAEQgDADgCAEQgCADAAAFIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAFgDQAEgEACgEQADgFAAgGIAAgIQgRgFgLAAQgEAAgGABg");
	this.shape_17.setTransform(-120.6,37.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAABMQgHgCgEgEQgFgEgCgGQgDgIAAgKIAAg9IgPAAIAAgZIAPAAIAAghIAaAAIAAAhIAgAAIAAAZIggAAIAAA5QAAAIAEAEQADADAIAAQAJAAAIgEIAAAXQgFADgGACQgGABgIAAQgIAAgEgCg");
	this.shape_18.setTransform(-131.9,35.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgaBRQgKgFgIgIQgIgIgEgLIgEgNIgCgOIAAgBQAAgKAGgPQAEgLAIgIQAIgIAKgFQAKgEALAAQAFAAAHACQAGACAFADQAJAFAHAKIAAhCIAcAAIAACmIgcAAIAAgUQgHALgJAFIgLAFQgHACgFAAQgKAAgLgEgAgLgNQgHADgFAFQgFAFgCAFQgDAIAAAIIAAABQAAAIADAIQADAHAEAFQAFAFAHADQAGADAFAAQAHAAAGgDQAHgDAFgFQAEgFADgHQADgIAAgIIAAgBQAAgIgDgIQgDgFgEgFQgFgFgHgDQgGgDgHAAQgFAAgGADg");
	this.shape_19.setTransform(93.7,12.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgMA9IgNgDQgLgFgJgJQgJgIgFgMIgDgLIgBgNIAAAAQAAgHAEgQQAFgLAJgJQAJgJAMgFIAMgDIAMgCQAJAAAQAFQAMAFAJAIQAIAJAFAMQAFAPAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAGQADAIAFAFQAFAFAHADQAGAEAHAAQAIAAAHgEQAGgDAFgFQAFgFADgHQACgHAAgIIAAAAQAAgHgDgGQgCgIgFgFQgFgGgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_20.setTransform(78.8,14.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgMA9IgNgDQgLgFgJgJQgJgIgFgMIgDgLIgBgNIAAAAQAAgHAEgQQAFgLAJgJQAJgJAMgFIAMgDIAMgCQAJAAAQAFQAMAFAJAIQAIAJAFAMQAFAPAAAIIAAAAIgBAMIgEAMQgFAMgIAIQgJAJgMAFQgRAFgIAAgAgOgjQgHADgFAGQgEAFgDAHQgDAHAAAHIAAAAQAAAIADAGQADAIAFAFQAFAFAHADQAGAEAHAAQAIAAAHgEQAGgDAFgFQAFgFADgHQACgHAAgIIAAAAQAAgHgDgGQgCgIgFgFQgFgGgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_21.setTransform(63.7,14.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgdBMQgOgDgMgHIAKgVQALAGAKADQAKADAMAAQAIAAAHgCQAHgCAFgFQAEgFADgHQADgHAAgJIAAgJQgLAMgHAEQgFADgHABQgFACgGAAQgLAAgKgEQgJgEgJgHQgHgHgFgLQgEgJgBgNIAAAAQABgJAEgPQAEgLAJgHQAIgHAJgEQAKgEALAAQAGAAAGABQAGACAFADQAKAFAHAJIAAgSIAcAAIAABfQAAAPgDAMQgEALgIAIQgEAEgFADQgGADgGACQgSAEgJAAQgPAAgNgEgAgMg1QgGACgFAEQgFAFgCAGQgDAGAAAIIAAAAQAAAHADAHQACAGAFACQAFAFAGACQAGACAGAAQAHAAAGgCQAHgCAEgFQAFgCADgGQADgHAAgHIAAAAQAAgIgDgGQgDgGgFgFQgEgEgHgCQgGgDgHAAQgGAAgGADg");
	this.shape_22.setTransform(48.1,16.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgoBNQgGgCgHgEIAJgUQAJAFAIgBQAGAAADgCQAEgEAEgHIgzh4IAeAAIAgBYIAghYIAdAAIgwB7IgIAQQgEAGgDAEQgEAEgGACQgGACgHAAQgJAAgHgCg");
	this.shape_23.setTransform(26.9,16.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgMBUIAAinIAaAAIAACng");
	this.shape_24.setTransform(16.9,12);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgMBUIAAinIAZAAIAACng");
	this.shape_25.setTransform(10.3,12);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgbA8QgHgDgGgEQgGgFgEgHQgDgHAAgJIAAgBQAAgJADgIQAEgHAHgDQAGgFAJgCQAKgDALAAQALAAATAFIAAgDQAAgGgBgFQgCgFgEgDQgEgEgGgBQgFgCgGAAQgJAAgJACIgQAFIgIgVQALgFAKgDQALgCAMAAQAOAAAKADQAKAEAGAGQAHAHADAJQADAKAAAMIAABGIgbAAIAAgPQgHAIgJAEQgMAFgJAAQgJAAgIgCgAgKAEIgJAEQgDADgCAEQgCADAAAFIAAABQAAAIAHAFQAGAFALAAQAEAAAGgCQAGgCAFgDQAEgEACgEQADgFAAgGIAAgIQgRgFgLAAQgEAAgGABg");
	this.shape_26.setTransform(-0.1,14.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgUA6QgLgFgIgHQgJgJgFgMIgDgMIgBgNIAAAAQAAgMAEgLQAEgMAIgJQAIgIALgFIALgDIALgCQAHAAAHACQAGABAFADQAIACALAMQAHAIADANQAEALAAAMIAAAHIhYAAQACAIADAFQADAGAEAEQAFAEAGACQAGACAEAAQAKAAAIgDQAIgEAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_27.setTransform(-13.4,14.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQADgGADgGIAIgJQAGgFAGgCQAHgBAIAAIAAAdIgCAAQgJAAgIADQgHADgFAGQgEAGgDAJQgDAHAAAMIAAAvg");
	this.shape_28.setTransform(-24.1,14.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQACgGAEgGIAIgJQAFgFAHgCQAHgBAIAAIAAAdIgCAAQgJAAgIADQgHADgGAGQgDAGgDAJQgDAHAAAMIAAAvg");
	this.shape_29.setTransform(-40.4,14.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgUA6QgLgFgIgHQgJgJgFgMIgDgMIgBgNIAAAAQAAgMAEgLQAEgMAIgJQAIgIALgFIALgDIALgCQAHAAAHACQAGABAFADQAIACALAMQAHAIADANQAEALAAAMIAAAHIhYAAQACAIADAFQADAGAEAEQAFAEAGACQAGACAEAAQAKAAAIgDQAIgEAHgIIARAPIgKAKIgLAHQgGADgIABQgHACgIAAQgLAAgMgFgAAegHQAAgHgDgGQgCgFgEgFQgEgFgFgCQgGgCgGAAQgFAAgFACQgFADgFAEQgEAEgCAGQgDAFgBAIIA8AAIAAAAg");
	this.shape_30.setTransform(-52.6,14.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgZBRQgLgFgHgIQgJgIgFgLIgDgNIgBgOIAAgBQAAgKAEgPQAFgLAIgIQAIgIAKgFQAKgEALAAQAFAAAHACQAGACAFADQAJAFAIAKIAAhCIAcAAIAACmIgcAAIAAgUQgIALgJAFIgLAFQgHACgFAAQgKAAgKgEgAgMgNQgGADgFAFQgFAFgDAFQgCAIAAAIIAAABQAAAIACAIQAEAHAEAFQAFAFAGADQAHADAFAAQAGAAAHgDQAGgDAGgFQAFgFACgHQADgIAAgIIAAgBQAAgIgDgIQgCgFgFgFQgGgFgGgDQgGgDgHAAQgGAAgGADg");
	this.shape_31.setTransform(-67.6,12.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgiA+IAAh4IAcAAIAAAbQACgGAEgGIAIgJQAGgFAGgCQAHgBAIAAIAAAdIgCAAQgJAAgHADQgIADgGAGQgDAGgDAJQgDAHAAAMIAAAvg");
	this.shape_32.setTransform(-78.8,14.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgRBRQgIgCgIgDQgHgDgHgFIgMgKIgKgMQgFgHgCgHQgEgIgBgIQgCgIAAgIIAAAAQAAgHACgIQABgIAEgIQADgHAEgHQAEgHAGgFQAGgGAGgFQAHgEAIgDQAIgEAIgBIAQgCIASACQAIABAIAEQAHADAHAEQAHAFAFAFQAGAGAEAHIAIAOQADAHABAIQACAIAAAIIAAAAQAAAIgCAIQgBAIgEAHQgDAIgEAGQgEAHgGAGQgGAGgGAEQgHAFgIADQgHADgJACQgJACgIAAQgIAAgJgCgAgVg0QgKAFgHAIQgHAHgEALQgEAKAAALIAAAAQAAALAEAKQAEALAHAIQAIAHAKAFQAKAEAKAAQALAAALgEQAJgEAIgIQAHgIAEgKQAEgLAAgLIAAAAQAAgKgEgLQgEgKgHgIQgIgIgKgEQgKgFgLAAQgKAAgLAEg");
	this.shape_33.setTransform(-93.9,12.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-149.5,0,297,50);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgLAMIAAgXIAWAAIAAAXg");
	this.shape.setTransform(61.5,24.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_1.setTransform(54.4,20.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_2.setTransform(46.3,19.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_3.setTransform(38.3,20.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEANAAAFIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAEAFADQAFACAFAAQAGAAAFgCQAGgDADgEQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_4.setTransform(28,20.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgFA/IgNgDIgKgHIgKgHIgIgKIgFgLQgDgFgBgHIgBgNIAAAAIABgLQABgHADgGIAFgLIAIgKIAJgIIAMgFIAMgFIAMgBQAIABAIABQAHABAGADQAIADAMALIgOAQQgIgIgIgDIgJgDIgKgCQgHABgIADQgHADgGAHQgGAFgDAJQgDAIAAAIIAAAAQAAAJADAIQADAIAGAGQAFAHAIADQAIADAHAAIAKgBIAKgDQAHgEAJgIIAOAOIgKAJQgGAFgGADQgGADgHABQgHABgJAAIgLgBg");
	this.shape_5.setTransform(15.8,19.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgXA8QgLgDgJgGIAIgQQAIAFAIACQAIADAKAAQAFAAAGgCQAFgBAFgEQADgEACgFQACgGAAgHIAAgIQgJAKgFADQgEADgFAAIgIACQgJAAgIgDQgHgDgGgGQgHgFgDgJQgDgHgBgKIAAAAQABgHADgMQADgIAHgGQAGgFAHgDQAIgDAJgBQAEAAAEACIAJADQAIAEAGAHIAAgNIAWAAIAABJQAAAMgDAJQgEAJgFAGIgIAGIgJADQgOADgHAAQgLAAgLgCgAgKgpQgEACgEADQgDADgCAFQgCAFAAAGIAAAAQAAAGACAFQACAEADACQAEADAFACQAFACAEAAQAFAAAFgCQAFgCAEgDQAEgCACgEQACgFAAgGIAAAAQAAgGgCgFQgCgEgEgEQgEgDgFgCQgFgCgFAAQgEAAgGACg");
	this.shape_6.setTransform(-2.6,22);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAJIAAA6g");
	this.shape_7.setTransform(-14,20.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_8.setTransform(-22.1,18.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_9.setTransform(-29.3,20.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEANAAAFIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAEAFADQAFACAFAAQAGAAAFgCQAGgDADgEQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_10.setTransform(-39.6,20.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgJBBIAAiBIATAAIAACBg");
	this.shape_11.setTransform(-48,18.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AgFA/IgNgDIgKgHIgKgHIgIgKIgFgLQgDgFgBgHIgBgNIAAAAIABgLQABgHADgGIAFgLIAIgKIAJgIIAMgFIAMgFIAMgBQAIABAIABQAHABAGADQAIADAMALIgOAQQgIgIgIgDIgJgDIgKgCQgHABgIADQgHADgGAHQgGAFgDAJQgDAIAAAIIAAAAQAAAJADAIQADAIAGAGQAFAHAIADQAIADAHAAIAKgBIAKgDQAHgEAJgIIAOAOIgKAJQgGAFgGADQgGADgHABQgHABgJAAIgLgBg");
	this.shape_12.setTransform(-57,19.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgPAtQgJgDgGgHQgHgGgEgJIgDgKIgBgKIAAAAQABgJADgJQADgJAGgHQAHgGAIgEIAJgDIAIgBIAKABIAKADQAFADAJAIQAGAHADAJQACAKAAAIIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIACQAJAAAFgEQAGgDAGgFIANAMIgHAHIgJAFIgKAEIgNABQgIAAgJgEgAAYgFQgBgFgBgFIgGgIQgCgDgFgCQgEgCgFAAQgDAAgFACQgDACgEADQgDADgCAEIgDALIAvAAIAAAAg");
	this.shape_13.setTransform(105.4,0.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgXA8QgLgDgJgGIAIgQQAIAFAIACQAJADAJAAQAFAAAGgCQAFgCAEgEQAEgDACgGQACgFAAgHIAAgIQgIAKgGADQgEACgEABIgKACQgIAAgHgDQgIgDgHgGQgFgGgEgIQgEgHABgKIAAAAQgBgHAEgMQAEgIAFgGQAHgFAIgDQAHgEAIAAQAFABAFABIAJAEQAGADAHAHIAAgOIAWAAIAABKQgBAMgDAJQgCAJgHAGIgHAFIgJAFQgOACgGAAQgMABgLgDgAgJgqQgFADgEADQgEAEgCAEQgCAFAAAGIAAAAQAAAGACAFQACAFAEABQAEAEAFACQAFABAEAAQAFAAAFgBQAFgCAEgEQAEgBACgFQACgFAAgGIAAAAQAAgGgCgFQgCgEgEgEQgEgEgFgBQgFgCgFAAQgFAAgEABg");
	this.shape_14.setTransform(93.7,2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgVAvQgGgCgEgEQgFgEgDgFQgDgGABgHQAAgHACgGQADgGAFgCQAFgEAHgCQAIgCAIAAQAJAAAPAEIAAgCQAAgFgBgEQgCgEgDgCQgDgDgFgBQgDgCgFAAQgHAAgGACIgOAEIgFgRQAIgEAIgBQAJgDAJAAQAKAAAIADQAIADAFAFQAFAFADAIQACAHAAAJIAAA3IgVAAIAAgMQgGAGgGAEQgJAEgIAAQgGAAgHgCgAgHADIgHADIgFAGQgBACgBAEQABAHAFAEQAFAEAIAAQADAAAFgCQAFgBADgDQAEgCACgEQACgEgBgEIAAgHQgMgEgJAAIgHABg");
	this.shape_15.setTransform(82.4,0.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgXA8QgLgDgJgGIAIgQQAIAFAIACQAJADAJAAQAFAAAGgCQAFgCAEgEQAEgDACgGQACgFAAgHIAAgIQgJAKgFADQgEACgEABIgKACQgIAAgHgDQgJgDgFgGQgGgGgEgIQgDgHAAgKIAAAAQAAgHADgMQAEgIAGgGQAFgFAJgDQAHgEAIAAQAFABAFABIAJAEQAGADAHAHIAAgOIAVAAIAABKQAAAMgDAJQgCAJgHAGIgHAFIgJAFQgOACgGAAQgMABgLgDgAgJgqQgFADgEADQgEAEgCAEQgCAFABAGIAAAAQgBAGACAFQACAFAEABQAEAEAFACQAFABAEAAQAFAAAFgBQAFgCAEgEQAEgBACgFQACgFAAgGIAAAAQAAgGgCgFQgCgEgEgEQgEgEgFgBQgFgCgFAAQgFAAgEABg");
	this.shape_16.setTransform(71.1,2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_17.setTransform(61.8,-0.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAVQACgFACgFQACgEAFgDQAEgDAFgBQAFgCAGAAIAAAXIgBAAQgHAAgGADQgGACgEAEQgDAGgCAHQgCAEAAAKIAAAkg");
	this.shape_18.setTransform(54.9,0.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgJAHgHQAHgGAJgEIAKgDIAJgBQAHAAANAEQAJAEAHAGQAHAHADAJQAEAMAAAGIgBAJIgDAKQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAGQgDAFAAAFQAAAGADAGQACAFAEAEQAEAEAFACQAFADAFAAQAGAAAFgDQAGgCADgEQAEgEACgFQACgGAAgGIAAAAQAAgEgCgGQgCgFgEgFQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_19.setTransform(44.9,0.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AAnA/IAAhZIgnA6IAAAAIgng6IAABZIgVAAIAAh9IAXAAIAlA8IAmg8IAYAAIAAB9g");
	this.shape_20.setTransform(31.2,-0.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_21.setTransform(14.2,-0.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_22.setTransform(6.2,0.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAVQACgFACgFQACgEAFgDQAEgDAFgBQAFgCAGAAIAAAXIgBAAQgHAAgGADQgGACgEAEQgDAGgCAHQgCAEAAAKIAAAkg");
	this.shape_23.setTransform(-1.4,0.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_24.setTransform(-8.1,-1.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AguA/IAAh9IBdAAIAAAUIhGAAIAAAjIA+AAIAAASIg+AAIAAA0g");
	this.shape_25.setTransform(-16.1,-0.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgQBCIAAhLIgMAAIAAgSIAMAAIAAgHQAAgIACgFQACgGAEgEQAEgEAEgCQAEgCAHAAQAKAAAIADIAAASQgHgCgGAAQgGAAgEADQgDAEAAAHIAAAFIAaAAIAAASIgZAAIAABLg");
	this.shape_26.setTransform(-31,-1.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AgQBCIAAhLIgMAAIAAgSIAMAAIAAgHQAAgIACgFQACgGAEgEQAEgEAEgCQAEgCAHAAQAKAAAIADIAAASQgHgCgGAAQgGAAgEADQgDAEAAAHIAAAFIAaAAIAAASIgZAAIAABLg");
	this.shape_27.setTransform(-37.7,-1.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AgNA/IgMgDIgMgGIgJgJIgIgJIgFgLIgEgMIgCgNIAAAAIACgLQABgHADgGIAFgLIAIgJIAKgJIALgGIANgDIAMgBIANABIAOADIALAGIAJAJIAIAJIAFALIAEAMIACAMIAAAAIgCAMIgEANIgFALIgIAJIgJAJIgMAGIgNADIgNABIgNgBgAgQgoQgHAEgHAGQgFAGgDAIQgDAIAAAIIAAAAQAAAJADAIQADAIAGAGQAFAGAJAEQAHADAIAAQAJAAAIgDQAIgEAFgGQAGgGADgIQADgIAAgJIAAAAQAAgIgDgIQgDgIgGgGQgFgGgJgEQgIgEgIAAQgIABgIADg");
	this.shape_28.setTransform(-49,-0.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgLA/IgKgDIgKgGIgIgIIgGgKIgFgLIgCgMIgBgNIAAAAIABgLIACgNIAFgLIAHgJIAIgJIAJgGIALgDIAKgBIALABIALADIAJAGIAIAJIAHAJIAEALQAEAQAAAIIAAAAIgBAMIgDANIgEALIgHAJIgIAJIgJAGIgLADIgLABIgLgBgAgMgoQgGADgEAGQgEAGgCAIQgDAJAAAIIAAAAQAAAJADAIQACAIAEAHQAEAGAGADQAGADAGAAQAHAAAGgDQAGgDAEgGQAEgHACgIQACgIAAgJIAAAAQAAgIgCgIQgCgIgEgHQgFgGgGgDQgGgDgGgBQgGABgGADg");
	this.shape_29.setTransform(-68.5,-0.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgLA/IgKgDIgKgGIgIgIIgGgKIgFgLIgCgMIgBgNIAAAAIABgLIACgNIAFgLIAHgJIAIgJIAJgGIALgDIAKgBIALABIALADIAJAGIAIAJIAHAJIAEALQAEAQAAAIIAAAAIgBAMIgDANIgEALIgHAJIgIAJIgJAGIgLADIgLABIgLgBgAgMgoQgGADgEAGQgEAGgCAIQgDAJAAAIIAAAAQAAAJADAIQACAIAEAHQAEAGAGADQAGADAGAAQAHAAAGgDQAGgDAEgGQAEgHACgIQACgIAAgJIAAAAQAAgIgCgIQgCgIgEgHQgFgGgGgDQgGgDgGgBQgGABgGADg");
	this.shape_30.setTransform(-81.5,-0.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgMA+IgNgDIgLgGIgJgJIAOgQQAHAHAIAFQAJADAHAAQAEAAAFgBQAFgBADgEQAEgDACgDQABgFAAgEQAAgGgCgDQgBgEgFgDIgIgEQgFgBgDgBQgHABgFABIgLAEIgOgGIAEg/IBKAAIAAAUIg3AAIgCAdIAJgCIAJgBQAKAAAIACQAIADAFAFQAHAFACAFQAEAIAAAJIAAABQAAAKgEAHQgDAJgGAFQgGAGgJADQgIACgKAAIgMgBg");
	this.shape_31.setTransform(-93.7,-0.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F78E1E").s().p("AgEBMIAAgSQgQgDgHgCQgLgFgJgHIAMgQQAIAGAHAEQAIAEAIABIAAgkIgRgEQgHgCgFgFQgFgEgCgGQgCgGAAgHIAAgBQAAgGADgHQACgFAFgFQAFgFAHgCQAHgDAJgBIAAgLIANAAIAAAMQAKAAAIAEQAIADAIAGIgKARIgMgIQgGgCgGgBIAAAiIARAFQAIAEAEACQAFAFACAFQADAHAAAHQAAAIgDAFQgDAGgFAFQgFAEgHADQgHADgJABIAAARgAAJApQAIgBAFgEQAEgEAAgGIAAgBQAAgGgDgEQgEgEgKgDgAgRgqQgEAEAAAGIAAAAQAAAHADADQAEAEAKADIAAggQgIABgFAEg");
	this.shape_32.setTransform(-105.1,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139,-11,278,42);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A3WzcMAutAAAMAAAAm5MgutAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.5,-125.5,301,251);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.parent = this;
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201706_Takeout_300x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(280,141,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.893,0.893);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(67,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(233,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border300x250();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A3TMGIAA4MMAunAAAIAAYMg");
	var mask_graphics_80 = new cjs.Graphics().p("A3TMGIAA4MMAunAAAIAAYMg");
	var mask_graphics_81 = new cjs.Graphics().p("A3QLwIAA3fMAumAAAIAAXfg");
	var mask_graphics_82 = new cjs.Graphics().p("A3QLaIAA2zMAumAAAIAAWzg");
	var mask_graphics_83 = new cjs.Graphics().p("A3QLEIAA2HMAumAAAIAAWHg");
	var mask_graphics_84 = new cjs.Graphics().p("A3QKuIAA1bMAumAAAIAAVbg");
	var mask_graphics_85 = new cjs.Graphics().p("A3QKXIAA0tMAumAAAIAAUtg");
	var mask_graphics_86 = new cjs.Graphics().p("A3QKBIAA0BMAumAAAIAAUBg");
	var mask_graphics_87 = new cjs.Graphics().p("A3QJrIAAzVMAumAAAIAATVg");
	var mask_graphics_88 = new cjs.Graphics().p("A3QJVIAAypMAumAAAIAASpg");
	var mask_graphics_89 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_169 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_170 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_171 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_172 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_173 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_174 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_175 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_176 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_177 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");
	var mask_graphics_178 = new cjs.Graphics().p("A3QI+IAAx7MAumAAAIAAR7g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:149.7,y:77.5}).wait(80).to({graphics:mask_graphics_80,x:149.7,y:77.5}).wait(1).to({graphics:mask_graphics_81,x:149.5,y:75.3}).wait(1).to({graphics:mask_graphics_82,x:149.5,y:73}).wait(1).to({graphics:mask_graphics_83,x:149.5,y:70.8}).wait(1).to({graphics:mask_graphics_84,x:149.5,y:68.6}).wait(1).to({graphics:mask_graphics_85,x:149.5,y:66.4}).wait(1).to({graphics:mask_graphics_86,x:149.5,y:64.1}).wait(1).to({graphics:mask_graphics_87,x:149.5,y:61.9}).wait(1).to({graphics:mask_graphics_88,x:149.5,y:59.7}).wait(1).to({graphics:mask_graphics_89,x:149.5,y:57.5}).wait(80).to({graphics:mask_graphics_169,x:149.5,y:57.5}).wait(1).to({graphics:mask_graphics_170,x:149.5,y:44.7}).wait(1).to({graphics:mask_graphics_171,x:149.5,y:32}).wait(1).to({graphics:mask_graphics_172,x:149.5,y:19.3}).wait(1).to({graphics:mask_graphics_173,x:149.5,y:6.6}).wait(1).to({graphics:mask_graphics_174,x:149.5,y:-6.1}).wait(1).to({graphics:mask_graphics_175,x:149.5,y:-18.8}).wait(1).to({graphics:mask_graphics_176,x:149.5,y:-31.6}).wait(1).to({graphics:mask_graphics_177,x:149.5,y:-44.3}).wait(1).to({graphics:mask_graphics_178,x:149.5,y:-57}).wait(4).to({graphics:null,x:0,y:0}).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(132,57,1,1,0,0,0,150,57);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(169).to({regX:150.1,regY:57.1,x:132.1,y:57.1},0).to({y:-69.4},9).to({_off:true},1).wait(4));

	// shad
	this.instance_4 = new lib.HTML5rastershad_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(156,164,1,1,0,0,0,0,10);
	this.instance_4.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({y:124},9).wait(80).to({y:10},9).to({_off:true},1).wait(4));

	// HEAD
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(271,197,1,1,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({y:156},9).wait(80).to({y:45},9).to({_off:true},4).wait(1));

	// CTA
	this.instance_6 = new lib.CTA();
	this.instance_6.parent = this;
	this.instance_6.setTransform(269.5,237,1,1,0,0,0,119.5,40);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({_off:false},0).wait(79).to({y:130},9).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_7 = new lib.headbkgd();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,116.7,0.893,0.833,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(169).to({y:16.7},9).to({_off:true},4).wait(1));

	// tag
	this.instance_8 = new lib._2016TAG();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,220.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_9 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(413.6,227.7,1.225,1.225,0,0,0,215.2,63);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo rule
	this.instance_10 = new lib._2016_SCU_logoruleai();
	this.instance_10.parent = this;
	this.instance_10.setTransform(253.3,207.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({_off:true},13).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},182).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.5,234.2,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(138,125,336,250);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;